### ISSUE TITLE
out of date docs

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1007]
## Summary of Bug

This page was highlighted as being out of date:
https://github.com/cosmos/gaia/blob/main/docs/validators/kms/kms_ledger.md

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dcwalk** [comment]
Just flagging this related issue: #662 with some links to relevant resources for updating kms docs
