### ISSUE TITLE
Hub roadmap 2.0: More specificity about IBC

### ISSUE THREAD

**Issue by adizere** [cosmos/gaia#1008]
## Summary

I enjoyed reading the [hub roadmap 2.0](https://github.com/cosmos/gaia/blob/main/docs/roadmap/cosmos-hub-roadmap-2.0.md). Great work putting this together! It helps relayer teams anticipate some features better and gain an overarching insight with respect to the Hub's direction.

One suggestion I have is: it could be useful to try to be more specific about IBC-related features. Two concerns come to mind, but there may be others:

1. IBC-go is starting to experiment with [pre-releases of v2.0](https://github.com/cosmos/ibc-go/releases/tag/v2.0.0-beta1), but the hub roadmap only mentions v1.2.
2. One specific (much-awaited) feature of IBC-go is the fee middleware. I'm curious if that's slated to land in a certain hub upgrade.

## Problem Definition

> Why do we need this feature? 

It would help IBC-related teams (e.g., relayers) plan and align their roadmap better with the hub.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Smellycat2666** [comment]
Good summary

**Comment by nooomski** [comment]
IBC 2.0 has been added to the Vega upgrade. @okwme do we want to include fee middleware on the roadmap already?

**Comment by okwme** [comment]
added more info about IBC 3.0 but fee middlewrae still missing. Will add it :+1:
