### ISSUE TITLE
quicksync cannot start

### ISSUE THREAD

**Issue by appop** [cosmos/gaia#1017]
## Summary of Bug
gaiad cannot start 

8:39PM INF starting ABCI with Tendermint

8:39PM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:39PM INF Starting localClient service connection=query impl=localClient module=abci-client
8:39PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:39PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:39PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:39PM INF Starting EventBus service impl=EventBus module=events
8:39PM INF Starting PubSub service impl=PubSub module=pubsub
8:39PM INF Starting IndexerService service impl=IndexerService module=txindex
8:39PM INF ABCI Handshake App Info hash="y%0HO\r\x0f��Κ��Xlf�$_�\vʜ�ޛm��n��" height=7952471 module=consensus protocol-version=0 software-version=
8:39PM INF ABCI Replay Blocks appHeight=7952471 module=consensus stateHeight=7952471 storeHeight=7952472
8:39PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 792530484F0D0F959DCE9A83F1586C66D9245FAA0BCA9CF8DE9B6DFCAA6EB8F6, got 356A8ABDFF281926077B42AFEFAADDC2B1CB9A6FDB4FA963D6174462C7183A45

## Steps to Reproduce

download from https://get.quicksync.io/cosmoshub-4-default.20211011.0310.tar.lz4

cannot start on 4.2.1 5.0.5 5.0.7 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
true.

Sort of.  I got it working a few tries out of a hundred recently --let's try something :D

**Comment by faddat** [comment]
```bash

#!/bin/bash
# microtick and bitcanna contributed significantly here.
set -uxe

# set environment variables
export GOPATH=~/go
export PATH=$PATH:~/go/bin


# Install Gaia
go install ./...


# MAKE HOME FOLDER AND GET GENESIS
gaiad init test 
wget -O ~/.gaia/config/genesis.json https://cloudflare-ipfs.com/ipfs/Qmc54DreioPpPDUdJW6bBTYUKepmcPsscfqsfFcFmTaVig

INTERVAL=1000

# GET TRUST HASH AND TRUST HEIGHT

LATEST_HEIGHT=$(curl -s 162.55.132.230:2011/block | jq -r .result.block.header.height);
BLOCK_HEIGHT=$(($LATEST_HEIGHT-$INTERVAL)) 
TRUST_HASH=$(curl -s "162.55.132.230:2011/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)


# TELL USER WHAT WE ARE DOING
echo "TRUST HEIGHT: $BLOCK_HEIGHT"
echo "TRUST HASH: $TRUST_HASH"


# export state sync vars
export GAIAD_STATESYNC_ENABLE=true
export GAIAD_P2P_MAX_NUM_OUTBOUND_PEERS=200
export GAIAD_STATESYNC_RPC_SERVERS="162.55.132.230:2011,162.55.132.230:2011"
export GAIAD_STATESYNC_TRUST_HEIGHT=$BLOCK_HEIGHT
export GAIAD_STATESYNC_TRUST_HASH=$TRUST_HASH
export GAIAD_P2P_PERSISTENT_PEERS="2bb31c07148a689f0b2dd363e17631993eca1020@162.55.132.230:2010"

gaiad start --x-crisis-skip-assert-invariants
```

**Comment by appop** [comment]
Thanks

**Comment by yaruwangway** [comment]
Hi @appop , please let us know if you still have some issues here , otherwise, we will close this issue. Thank you!

**Comment by appop** [comment]
@yaruwangway We solved this, thanks.
