### ISSUE TITLE
Note to Validators

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1018]
Hi,

I'm operating a relayer. If you are operating a validator, it is very important that you:

`systemctl enable systemd-timesyncd`

please.

If you do not, there are time drift errors, and well, the Hermes default of five seconds is really pretty generous. We should be less than five seconds apart.

**Comment by faddat** [comment]
Oct 12 08:48:38 archive hermes[741991]:    0: GRPC call return error status status: InvalidArgument, message: "failed to execute message; message index: 0: cannot update client with ID 07-tendermint-395: failed to verify header: invalid header: new header has a time from the future 2021-10-12 06:48:25.271016402 +0000 UTC (now: 2021-10-12 06:48:18.406124437 +0000 UTC; max clock drift: 5s): invalid request", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

It causes stuff like the above message.

**Comment by uditvira** [comment]
@faddat is this an issue if running ntp?

**Comment by yaruwangway** [comment]
@nooomski, maybe it's better to add this to an instruction doc, do you know where would be a proper place to add it ?

**Comment by nooomski** [comment]
Would like to get more input on whether this should be best practice for all validators or if this is specific to running a particular setup. @faddat ?

@yaruwangway if this is indeed considered best practice, this should probably be amended in the [validator instructions doc](https://hub.cosmos.network/main/validators/validator-setup.html). But also, if this is an SDK wide issue and not just part of Gaia, we should consider amending the [running in production doc](https://docs.tendermint.com/v0.35/nodes/running-in-production.html) on the Tendermint site.

However, let's first establish if this would indeed solve a lot of problems. I'm not too familiar with the technical details, but wondering if [proposer based timestamps ](https://github.com/tendermint/spec/tree/master/spec/consensus/proposer-based-timestamp)might resolve this time drift?

**Comment by faddat** [comment]
@nooomski -- this ended up being a more complex issue than initially thought.  These errors were lining up with sequence errors on various chains, and what that's actually an indicator of is the node falling behind the tip because the relayer is querying it so often. 

Still, I reckon it is good practice for validators to keep their clocks set.
