### ISSUE TITLE
Option to disable proprietary date/time log prefixing

### ISSUE THREAD

**Issue by mdyring** [cosmos/gaia#102]
It would be great to have an option to disable the date/log prefixing of the log output. 

This is useful when running gaia as a systemd service, which by default logs to the journal (which already records the date/time info).

journal output looks like this, which is a bit messy:

Jan 09 08:53:50 ip-10-0-0-46 gaia[21256]: I[01-09|08:53:50.999] Executed block                               module=state height=8330 validTxs=0 invalidTxs=0

The part I'd like removed is "[01-09|08:53:50.999]" in the above.. Not sure if anything else than info level is logged (the first "I" I guess), if so it makes sense to keep that around.

**Comment by zramsay** [comment]
gaia imports the tendermint source code, so this would have to come from upstream, see https://github.com/tendermint/tendermint/issues/1096
