### ISSUE TITLE
request: add codefest label and label issues for October Codefest 

### ISSUE THREAD

**Issue by barriebyron** [cosmos/gaia#1020]
## Summary

helloooo gaia CODEOWNERS  @alessio @alexanderbez @jgimeno @shahankhatch @zmanian @yaruwangway 

## Problem Definition

We are almost halfway through [October Codefest](https://blog.cosmos.network/october-codefest-call-for-contributors-42ade37f4913)!  Let's be open, welcoming, and encouraging for contributors. This repo is a participating open source project in the Cosmos ecosystem.

## Proposal

Please create the codefest label and add the labels to suitable issues. see [Projects Call for Action: Let There Be Labels](https://docs.google.com/document/d/1lraKhXQNijWUscxV7yxl77tctYiPD5lV-78ryvGEKZs/edit).

I'm up for doing this work if you want to add me to the repo with the appropriate permissions. Seems like I don't have permissions to create labels. 

We're getting excellent traction in other repos, let's embrace the open source community and invite them in. Questions? Please ask. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @barriebyron, as it's November, is there anything else to follow up on or that we can do before closing this out?

**Comment by yaruwangway** [comment]
@glnro I have added the codefest label, now we can go through and label the issues.

**Comment by barriebyron** [comment]
Hi all! October Codefest 2021 is over. Please retain the codefest label in
the repo and we can use it in 2022.

Happy November, friends!

**Comment by dcwalk** [comment]
There is a label! closing because codefest 2021 is over :night_with_stars:
