### ISSUE TITLE
Rest Api[/query/stake/delegator_candidates]

### ISSUE THREAD

**Issue by zhiqiang-bianjie** [cosmos/gaia#103]

**Comment by zhiqiang-bianjie** [comment]
Why is the result returned by this API inconsistent with the number of delegator_candidates returned by the command line [gaia client query delegator-candidates --delegator-address]?

**Comment by jolesbi** [comment]
maybe related to https://github.com/cosmos/cosmos-sdk/issues/324

**Comment by faboweb** [comment]
The rewrite has not yet begone so I don't think it is about cosmos/cosmos-sdk#324

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/585
