### ISSUE TITLE
spike: what happens when you rename the repo from gaia to something else

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1032]
## Summary

if we were to rename the gaia repo to something else, what would break? Does github handle updates paths gracefully? is that still the case if for instance there was another gaia repo in the cosmos org? how does it impact go dependencies?

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
check if go cobra allows aliases so that you could use both `gaiad` and something like `cosmosd`

**Comment by glnro** [comment]
> ## Summary
> if we were to rename the gaia repo to something else, what would break? Does github handle updates paths gracefully? is that still the case if for instance there was another gaia repo in the cosmos org? how does it impact go dependencies?
> 

@okwme per a similar question posted [here](https://github.community/t/how-long-does-github-forward-renamed-moved-repos/582)

```
We keep redirects for moved and renamed repos indefinitely, but new repos take priority over redirects. That means if a new repo is created at an old location, the redirects will break in favor of displaying the new repo, for as long as that new repo exists.
```

We might only run into an issue if a future project were to assume the `gaia` name, then anything presumed to be pointing to the old repo would point to the new repo.

With respect to dependencies, this should not be a problem, but we would want to indicate that the path is deprecated and to update to the new location.

As for running gaiad and cosmosd, this would be separate from cobra...from my understanding of cobra, aliasing is limited to the commands, but the name of the binary would be something specified at the project level. I think the next course of action will be to speak to a validator for additional perspective.

**Comment by glnro** [comment]
Spike Conclusion

At present, the team has a few options available. Should we want to rename/rebrand Gaia to the Cosmos Hub, we’d first want to change the repo to either `cosmos/hub` or `cosmos/cosmos-hub`. There would be minimal downstream effects with a rename outside of a basic knowledge campaign as GitHub gracefully handles redirects. Should a future project be named Gaia however, redirect links would break and instead point to the new project. On this proposal, we recommend next steps to include a conversation with the larger interchain team to come to consensus on renaming and of course the name itself.

Additionally, there is the issue of the binary. Changing the binary name from a technical perspective to something like `hubd` would be low overhead for the team, but require some measure of outreach to node operators and coordination on upgrades. The best way to implement this would simply offer a new upgraded binary with no added functionality while supporting the old binary name with subsequent upgrades until sufficient notice of the switch has been given. Pain points will include updating downstream docs/tutorials, and updating any existing automation scripts that node operators/gaia partners may currently be employing. 

The repository rename could be implemented without the binary rename, both at the same time, or in subsequent updates. If there is sufficient interest in renaming both, doing so at the same time alleviates any extra outreach that would have to be done amongst node operators and Gaia partners/consumers (tutorials/documentation/etc). There is certainly a case for doing this earlier in the ecosystem’s development than later down the road when it may become too cumbersome to manage efficient outreach. That being said, the easiest course of action would be to simply rename the repo to be consistent with rebranding, and leave the binary for now.
