### ISSUE TITLE
deduplicate previous proposals file

### ISSUE THREAD

**Issue by hxrts** [cosmos/gaia#1035]
@uditvira added all past proposals in https://github.com/cosmos/governance/pull/43 but this includes duplicates of proposals that had PRs made to this repo. we should dedup these so there is only one copy of each.

we may also want to consider consistent formatting for all proposals, including previous proposals. so one file per proposal.

**Comment by dcwalk** [comment]
WIP here: https://github.com/hyphacoop/cosmos-gaia/tree/docs-proposals-dedupe

doing:
- flatten to a single readme for section
- reference draft materials for proposals that have it
- make folder titles + weighting nicer so nav in that section is a little easier

but actually thinking it would be cool to have this section maybe reflect params change approach with aims to reduce manual updating requirements.

**Comment by hxrts** [comment]
ooh. I like that. you said we're missing the IPFS links for a couple proposals as well. can we enumerate those?

**Comment by dcwalk** [comment]
There are 28 ipfs links (with some duplicates) in the content description of the results from querying gov proposals:
```
/ipfs/QmXqEBr56xeUzFpgjsmDKMSit3iqnKaDEL4tabxPXoz9xc
/ipfs/QmaUaMjXPE6i4gJR1NakQc15TZpSqjSrXNmrS1vA5veF9W
/ipfs/Qmam1PU39qmLBzKv3eYA3kMmSJdgR6nursGwWVjnmovpSy
/ipfs/QmS13GPNs1cRKSojete5y9RgW7wyf1sZ1BGqX3zjTGs7sX
/ipfs/QmNsVCsyRmEiep8rTQLxVNdMHm2uiZkmaSHCR6S72Y1sL1
/ipfs/QmbXnLfx9iSDH1rVSkW5zYC8ErRZHUK4qUPfaGs4ZdHdc7
/ipfs/Qmf54mwb8cSRf316jS4by96dL91fPCabvB9V5i2Sa1hxdz
/ipfs/QmPbSLvAgY8m7zAgSLHzKHfDtV4wx5XaGt1S1cDzqvXqJg
/ipfs/QmfJyd64srJSX824WoNnF6BbvF4wvPGqVBynZeN98C7ygq
/ipfs/QmSMGEoY2dfxADPfgoAsJxjjC6hwpSNx1dXAqePiCEMCbY
/ipfs/QmbD3bMajQCFmtDmkuRVWhmMWVdN2sK8QP2FoFCz9cjPiC
/ipfs/QmbD3bMajQCFmtDmkuRVWhmMWVdN2sK8QP2FoFCz9cjPiC
/ipfs/QmUYDQt9tqLQJwxnUck7dQY3XmZA3tDtpFh3Hchkg7oH46
/ipfs/Qmbo3fF54tX3JdoHZNVLcSBrdkXLie56Vh2u29wLfs4PnW
/ipfs/QmV6pBgDppN7X3BdVW197EUe7dpcmcdLMivPa6xxtPj3aW
/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmTZ3R4W2odBsx6hpt7awfRTfZA67x5eQaoL6ctxBr6NyN
/ipfs/QmWAxtxf7fUprPVWx1jWyxSKjBNqkcbA3FG6hRps7QTu3k
/ipfs/QmPww2PSmkmuLLu12GGwRdu5ur1Etf9u3Nt3Z6NqB7BQP1
/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmYn2SxCMYk5SWs5GMcXdbXR8wMCCXRmCyW19SFyzSeZp1 
/ipfs/QmYn2SxCMYk5SWs5GMcXdbXR8wMCCXRmCyW19SFyzSeZp1
/ipfs/QmZpgkYLoCBnXM1S7TEdQunMmur9bAw5VTNgFQCyrqgKDd
/ipfs/QmYFYySsUPdtECuUmPCX7Dkt3cKBs423qwmofpYd5NXcJu
/ipfs/QmWwJ63V4TuZkDfWoH66vxd6NK82g6rgPVnypESXBFRbws
/ipfs/QmTFxNA6punVox7JXvgp7eUFkC9GxRu26unCUwRwyvsiHz
/ipfs/QmQtZKFXp1RFrSjkrvXahY3u9eHZbrgM5M6boNUcumBWyY
/ipfs/QmWtAN412H5bzoxv5hkybdRxawFu1sgaz78AWSseiS45Av
```
... could script to extract those from the description tho they don't follow a single pattern.
I tried to `ipfs get` and don't find anything for most, also spot-checked a few in an ipfs viewer and I can access a couple but not most.

**Comment by nooomski** [comment]
Closed by bot, opening again.

**Comment by okwme** [comment]
governance repo is archived in favor of docs.cosmos.network
