### ISSUE TITLE
Add documentation on using cosmosvisor for governance

### ISSUE THREAD

**Issue by dcwalk** [cosmos/gaia#1037]
See SDK docs: https://docs.cosmos.network/master/run-node/cosmovisor.html in particular this section: "Submit a software upgrade proposal"

**Comment by nooomski** [comment]
Hey @dcwalk, this issue was closed by a bot. Not quite sure what you meant exactly? Generally Cosmovisor would not be used for governance itself, but of course, you can replace `./build/simd` with `cosmovisor` if Cosmosvisor is setup.

If you can be a bit more specific I can open the issue again.
