### ISSUE TITLE
Deduplicate information and update cli commands in submitting.md

### ISSUE THREAD

**Issue by uditvira** [cosmos/gaia#1038]
[submitting.md](https://github.com/cosmos/governance/blob/7190753eb5c547302235964563a9951bb95879ad/submitting.md) is out of date. Additionally, there is repetition with the resource in [hub.cosmos.network](https://hub.cosmos.network/main/resources/gaiad.html#governance). This issue tracks:
- [ ] deduplication of information, to make this repo more maintainable
- [ ] fixing broken links
- [x] updating cli references to `gaiad` from `gaiacli`

**Comment by nooomski** [comment]
Bot closed by accident. Opening again.

**Comment by mmulji-ic** [comment]
@uditvira are you still busy with this?

**Comment by okwme** [comment]
this repo is archived, please see up to date gov docs in hub.cosmos.network
