### ISSUE TITLE
Add signalling proposal best practices

### ISSUE THREAD

**Issue by hxrts** [cosmos/gaia#1040]
Part of @gavinly's SOW. He'll be using past signalling proposals to guide his write-up and reaching out to a few people who made those proposals, @zmanian @sunnya97, to incorporate learnings.

**Comment by dcwalk** [comment]
Just confirming this is a lingering issue, we have documented best practices but nothing specific to text proposals as of yet: https://github.com/cosmos/governance/tree/master/text

**Comment by hxrts** [comment]
Yep, this can be closed now.
