### ISSUE TITLE
add example commands for how to make a proposal deposit

### ISSUE THREAD

**Issue by hxrts** [cosmos/gaia#1041]
description of deposits are there, but instructions on how to deposit seem to be absent

**Comment by nooomski** [comment]
Hey @hxrts, this was closed by accident. Happy to look into this. Do you mean adding a small section to ["Submitting a gov proposal"](https://hub.cosmos.network/main/governance/submitting.html#)?

@dcwalk not sure if you were already on this btw?

**Comment by hxrts** [comment]
Yes exactly. The instructions show how to make a deposit with proposal submission, but not how to add a deposit to an existing submission (which is typically required to meet the deposit threshold).

**Comment by nooomski** [comment]
Cool, done in PR #1142
