### ISSUE TITLE
Update ParamChange proposals with more details about where to find keys

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#1042]
There are some subtleties in how to format ParamChange proposals that could be better clarified https://github.com/cosmos/governance/blob/master/params-change/formatting.md

**Comment by dcwalk** [comment]
As part of merging to gov->gaia we created a script to query on-chain params: https://github.com/cosmos/gaia/blob/main/docs/governance/scripts/extract_onchain_params.py , however the process has changed so an update to how those are queried and displayed within docs is required.

**Comment by dcwalk** [comment]
We are working on a schema+using validator approach for this, WIP here: https://github.com/hyphacoop/cosmos-organizing/pull/21      I think once we bring that in we can mark this as clooooosed! Going to self-assign to take this on next week.

**Comment by okwme** [comment]
just updating, looks like this PR is still open: https://github.com/hyphacoop/cosmos-organizing/pull/21

**Comment by uditvira** [comment]
Added a guide on the forum including some tips on verifying the proposal json against the schema https://forum.cosmos.network/t/about-the-parameter-change-category/5950#how-to-submit-a-param-change-proposal-9

closing this issue
