### ISSUE TITLE
Support A-Gaia-B crosschain?

### ISSUE THREAD

**Issue by luleigreat** [cosmos/gaia#1056]
## Summary

Does ibc-protocol support the crosschain mode of A-GaiaHub-B? Or only support A-B?

## Proposal

Hello everyone, I am studying cosmos ibc protocol, and I am puzzling about the ability of ibc-protocol. 

The problem is I can't find a document about how to cross chain through the cosmos hub. All the docs I can find is about how to cross chain between two chains. For example,the ibc-helloworld example. 
But I think IBC is not just only a protocol about crosschain between two chains,because there is a hub.

Can any one tell me what's the truth and  is there any document about how to cross chain through a hub instead of  just cross chain from A to B?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
Hi @crodriguezvega, can you help here ? Many thanks!

**Comment by crodriguezvega** [comment]
At the moment the [IBC protocol](https://github.com/cosmos/ibc) specifies only single-hop transactions and that is what's supported by [ibc-go](https://github.com/cosmos/ibc-go), the golang implementation of the protocol. Luckily the protocol has been designed to accommodate in the future multi-hop transactions, but this has been neither specified nor implemented yet.

However, the use-case is compelling enough that [Strangelove Ventures](https://www.strangelove.ventures)
has kindly developed a [middleware solution](https://github.com/strangelove-ventures/packet-forward-middleware) to tackle this problem and help accelerate the realization of the vision of the Cosmos Hub as a packet router in the Cosmos ecosystem. This middleware is a Cosmos SDK module that will go live on the Cosmos Hub as part of the [Vega upgrade](https://github.com/cosmos/gaia/blob/main/docs/roadmap/cosmos-hub-roadmap-2.0.md#vega-upgrade-expected-q4-2021). 

If you're interested to learn more about this middleware solution, check out the [repo](https://github.com/strangelove-ventures/packet-forward-middleware). However, This solution doesn't mean that there will not be a native multi-hop IBC protocol in the future, but it is not the immediate priority.

**Comment by luleigreat** [comment]
Thanks very muth, it helps me a lot! @crodriguezvega
