### ISSUE TITLE
gaia v0.5.0 creates block every second (ignoring config)

### ISSUE THREAD

**Issue by mdyring** [cosmos/gaia#106]
This happens on gaia-2 testnet, I imagine same will be the case for gaia-1 as the settings are the same in config.toml:

create_empty_blocks_interval = 60

Used to work but seems b0rken.

**Comment by melekes** [comment]
I think we just forgot to set no_empty_blocks. Sorry. It will be turned off for next version (gaia-3)

**Comment by mdyring** [comment]
Is this a config setting or compile time thing? 

Because gaia-1 testnet doesn't have this option in config.toml, which was the original source of my confusion.

**Comment by melekes** [comment]
It can be set via runtime setting (`--consensus.create_...`) or config.

**Comment by zmanian** [comment]
Does "no empty blocks" only affect the node when it is the proposer?

**Comment by melekes** [comment]
Yeah, but if other nodes produce blocks, this node will get them too, so 1 node without no_empty_blocks forces the whole network to produce blocks!

**Comment by zmanian** [comment]
I would expect the validator to only produce empty blocks during it's turn as proposer.

**Comment by ebuchman** [comment]
That's right. If most of the network has create_empty_blocks=true, but one validator has create_empty_blocks=false, blocks will be created roughly every second, and that one validator will likely be skipped when its her turn to propose if she doesnt have any txs

**Comment by mdyring** [comment]
Mmm, I think there was an issue open for this before. But IMHO the consensus-specific settings (empty blocks, interval) should be part of the genesis state and immutable (maybe immutable at some later time if needed).

Otherwise we'll get strange behaviour as outlined above depending on individual node settings.

**Comment by ebuchman** [comment]
Don't think we really want to enforce this at consensus level yet

**Comment by mdyring** [comment]
Perhaps not enforce, but at least include it in genesis config (and in hash) so that at least everybody will be running with the same params.

I understand it doesn't solve any malicious behavior. Enforcement can be added later on if it turns out to be a problem (say, proposing empty block when genesis config states that is not allowed).

Seems an easy way to avoid misconfigurations down the line as validator count increases?

**Comment by alexanderbez** [comment]
@tuckermint I recall there were issues with the tutorial not initializing/using the supply module correctly. I think it's since been solved. Correct me if I'm wrong @marbar3778.
