### ISSUE TITLE
panic: stored supply should not have been nil

### ISSUE THREAD

**Issue by jtomtan** [cosmos/gaia#106]
Followed the instructions in: https://hub.cosmos.network/docs/installation.html to setup a new node with the latest v1.0.0 code, when running: 

# ./gaiad start
[2019-08-16|08:34:43.865] Starting ABCI with Tendermint                module=main 
panic: stored supply should not have been nil

Check with the installation guide, seems no mis-follow. Don't know whether it's a bug or something I have missing.

**Comment by alexanderbez** [comment]
The installation guide you've posted is correct in that it describes how to install Gaia. However, you're most likely running into your own errors from a previous testnet. I would recommend either starting a fresh new node or attempting a `gaiad unsafe-reset-all`.

I was able to successfully launch a fresh new node using the testnet [genesis](https://raw.githubusercontent.com/cosmos/testnets/master/gaia-13k/genesis.json) with gaia v1.0.0

**Comment by jtomtan** [comment]
> The installation guide you've posted is correct in that it describes how to install Gaia. However, you're most likely running into your own errors from a previous testnet. I would recommend either starting a fresh new node or attempting a `gaiad unsafe-reset-all`.
> 
> I was able to successfully launch a fresh new node using the testnet [genesis](https://raw.githubusercontent.com/cosmos/testnets/master/gaia-13k/genesis.json) with gaia v1.0.0

Now i switched back to use cosmos SDK v0.34.7, ant it works. But for Gaia, with mainnet, i never succeed.

**Comment by alexanderbez** [comment]
You're using this for mainnet?? If so, you're using the wrong version. Please read the [launch info](https://github.com/cosmos/launch)

**Comment by msaikat** [comment]
Hi @jtomtan did you manage to run the mainnet?

**Comment by song-liu** [comment]
I have the same problem. 
"panic: stored supply should not have been nil".
unsafe-reset-all does not do the trick. I will try cosmos SDK v0.34.7 as jtomtan mentioned.

**Comment by alexanderbez** [comment]
The README states that the mainnet runs on version v0.34.7 of the SDK. The upcoming major upgrade will support v2.0.0

**Comment by ksemaev** [comment]
same for me with gaiad v2.0.1 (SDK version v0.37.1)

**Comment by tuckermint** [comment]
I'm getting the same issue with v0.37.3 for sdk-application-tutorial

Any ideas?

**Comment by soc1c** [comment]
Getting the same with gaiad v2.0.2. Is this still not supposed to work with mainnet?

## Summary of Bug

```
~/.opt/gaia tags/v2.0.2
❯ gaiad start
I[2019-10-23|09:03:24.269] starting ABCI with Tendermint                module=main 
panic: stored supply should not have been nil

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/supply/internal/keeper.Keeper.GetSupply(0xc00013c2a0, 0x15712c0, 0xc00094d100, 0x1581300, 0xc00013cfc0, 0x7f483cd9f3e8, 0xc00139c0e0, 0xc0008758c0, 0x1580400, 0xc0000be030, ...)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/x/supply/internal/keeper/keeper.go:50 +0x18f
github.com/cosmos/cosmos-sdk/x/supply/internal/keeper.TotalSupply.func1(0x1580400, 0xc0000be030, 0x1590f40, 0xc0009c5480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/x/supply/internal/keeper/invariants.go:27 +0xe7
github.com/cosmos/cosmos-sdk/x/crisis/internal/keeper.Keeper.AssertInvariants(0xc00013bb80, 0xb, 0x10, 0xc00013c2a0, 0x15712c0, 0xc00094d150, 0x1571300, 0xc00094d170, 0xc0009516c0, 0x6, ...)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/x/crisis/internal/keeper/keeper.go:74 +0x36d
github.com/cosmos/cosmos-sdk/x/crisis.AppModule.InitGenesis(0xc000139328, 0x1580400, 0xc0000be030, 0x1590f40, 0xc0009c5480, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/x/crisis/module.go:113 +0x2dd
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc00013d3b0, 0x1580400, 0xc0000be030, 0x1590f40, 0xc0009c5480, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/types/module/module.go:258 +0x278
github.com/cosmos/gaia/app.(*GaiaApp).InitChainer(0xc000138f00, 0x1580400, 0xc0000be030, 0x1590f40, 0xc0009c5480, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/.opt/gaia/app/app.go:247 +0x11d
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0001625a0, 0x0, 0xed44fea10, 0x0, 0xc00094e2b0, 0xb, 0xc0009c53c0, 0xc000a9f000, 0x63, 0x63, ...)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/baseapp/baseapp.go:400 +0x2c7
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000083e00, 0x0, 0xed44fea10, 0x0, 0xc00094e2b0, 0xb, 0xc0009c53c0, 0xc000a9f000, 0x63, 0x63, ...)
	/home/user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/abci/client/local_client.go:223 +0x101
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc00094d920, 0x0, 0xed44fea10, 0x0, 0xc00094e2b0, 0xb, 0xc0009c53c0, 0xc000a9f000, 0x63, 0x63, ...)
	/home/user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/proxy/app_conn.go:65 +0x6b
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc001d990c0, 0xa, 0x0, 0xc00094fec0, 0x6, 0xc00094fef0, 0xb, 0x0, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/consensus/replay.go:311 +0x666
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001d990c0, 0x15937c0, 0xc00013dce0, 0x80, 0x1021e20)
	/home/user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/consensus/replay.go:269 +0x485
github.com/tendermint/tendermint/node.doHandshake(0x1592d40, 0xc00006a208, 0xa, 0x0, 0xc00094fec0, 0x6, 0xc00094fef0, 0xb, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/node/node.go:275 +0x199
github.com/tendermint/tendermint/node.NewNode(0xc00015a780, 0x157b100, 0xc000879360, 0xc00094d4c0, 0x1561860, 0xc0009536c0, 0xc00094d730, 0x13aa960, 0xc00094d740, 0x1580dc0, ...)
	/home/user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/node/node.go:582 +0x334
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00049cf40, 0x13ab180, 0x1d, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/server/start.go:152 +0x4c1
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc0009bf680, 0x1dda908, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.3/server/start.go:65 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc0009bf680, 0x1dda908, 0x0, 0x0, 0xc0009bf680, 0x1dda908)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013a000, 0x11d3040, 0xc000af9ea0, 0x59e172)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00013a000, 0x13ab5a0, 0x11b871b, 0x10)
	/home/user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.6/libs/cli/setup.go:89 +0x3c
main.main()
	/home/user/.opt/gaia/cmd/gaiad/main.go:68 +0x875
```

## Version

```
~/.opt/gaia tags/v2.0.2
❯ gaiad version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.2
commit: aa91fa08505ea072acd81fbe36845adad7f6177f
build_tags: netgo,ledger
go: go version go1.13.1 linux/amd64
```

**Comment by alexanderbez** [comment]
Again, no. There has not been a successful upgrade yet. You'll know when the network upgrades. Any block explorer will show you. Also, the `launch` repo will state the current version as well.

**Comment by soc1c** [comment]
Thanks. I'm new to cosmos and the migration seems to send users through loops in the documentation. I managed to compile 0.34.9 and it works with mainnet.

**Comment by DZDomi** [comment]
Also stumbled onto the same error, you have to use the latest version of cosmos sdk 0.34.x in order to get a running node connected to the mainnet. Would be nice if this would be stated more clearly in the documentation

**Comment by alexanderbez** [comment]
> Also stumbled onto the same error, you have to use the latest version of cosmos sdk 0.34.x in order to get a running node connected to the mainnet. Would be nice if this would be stated more clearly in the documentation

It's stated in **multiple** places:

- This repo's README
- [Launch](https://github.com/cosmos/launch) repo

**Comment by ChainCoderX** [comment]
same for me,   Gaia.  v2.0.3.  github.com/cosmos/cosmos-sdk v0.37.4


how to fix it ?
