### ISSUE TITLE
Versioning Issues

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1064]
https://github.com/cosmos/gaia/blob/ad20b3f37db8de87dc27f64310a01ba6ddede35d/go.sum#L1002-L1005

**Comment by faddat** [comment]
https://github.com/crypto-org-chain/chain-main/pull/682

**Comment by tac0turtle** [comment]
we talked about this issue and concluded its not relevant. the concurrency bug is present in master and 6.0.0, already mentioned to billy and team.
