### ISSUE TITLE
Archive IPFS links in old governance proposals

### ISSUE THREAD

**Issue by dcwalk** [cosmos/gaia#1067]
## Summary

On-chain proposals often include a link to supplementary material or the final proposal text. The recommendation is to add those to ipfs and share a link. However not all of that old content appears available on ipfs. We should think about how to better archive them as part of the record of governance decisions.

## Problem Definition

Old ipfs content from governance proposals not remaining available.

## Proposal

- [x] Review the current state of links, discuss (initially mentioned in #1035)
- [ ] Agree how to preserve those old links
- [ ] Update docs with better practices for sharing supplementary materials

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dcwalk** [comment]
@hxrts pulling this discussion out of #1035 because it's distinct, with a final note on steps I've taken (cc @uditvira):

- made a small script to query all proposals and store json
- (manually) pulled these links and dumped into .txt   (28 links, 24 unique)
- ran small bash script to while read in; do ipfs get "$in"; done < ipfs-links.txt on these.... got less than 10
- spot-tested getting these ipfs hashes using a gateway/viewer (cloudflares: https://cloudflare-ipfs.com/)
- made a new small bash script to wget old proposals trying the http://gateway.ipfs.io gateway. ran it, stored the output too
- reviewed against the list: the gateway can resolve **11 out of 24** (unique) CIDs

i didn't get fancy rn in extracting the ipfs links tho that pattern is pretty straightforward.

For historic proposals:
- maybe what I've done to recover is enough?
- We should use whatever way forward we've discussed to pin the CIDs above :point_up: 
- I think we just want to know that we've archived what we can in whatever way we want to archive going forward

For new proposals:
- I think we should focus here
- Make some amendments to the docs to propose more robust ipfs pinning practices?
- Have a service listen + pin any ipfs link that shows up on gov proposals? <-- run by ICF? backed on filecoin? using web3.storage?

**Comment by nooomski** [comment]
Bot accidentally closed this. Opening again.

**Comment by nooomski** [comment]
Hey @uditvira , do you know if anyone is working on this rn?

**Comment by uditvira** [comment]
- in the forum templates @LexaMichaelides has added instructions on pining proposals to IPFS using pinata
- also pinned a number of existing proposals in the forum to IPFS that weren't pinned before 

closing for now and we can create new issues for specific tasks as they come up
