### ISSUE TITLE
gaia v0.5.0 process dies on peer "connection refused"

### ISSUE THREAD

**Issue by mdyring** [cosmos/gaia#107]
This is on gaia-2 testnet:

20:27:43 I[01-14|20:27:43.196] Committed state module=state height=370132 txs=0 appHash=0EB26105FCA443FDCF61079BB51C3442BAAD1F6C

20:27:43 E[01-14|20:27:53.267] Failed to dial peer module=p2p address=73.92.247.82:46656 err="Error creating peer: dial tcp 73.92.247.82:46656: getsockopt: connection refused"

*mic drop*

**Comment by mdyring** [comment]
Might be related to #108 - could be a coincidence it was last entry in log.

**Comment by mdyring** [comment]
Seems related to memory leak. After memory is exhausted, swapping slows everything to a halt causing the timeouts in the log.

E[01-15|14:29:23.916] Failed to dial peer                          module=p2p address=52.26.219.159:46656 err="Error creating peer: dial tcp 52.26.219.159:46656: i/o timeout"
E[01-15|14:29:23.916] Failed to dial peer                          module=p2p address=52.201.174.124:46656 err="Error creating peer: dial tcp 52.201.174.124:46656: i/o timeout"
E[01-15|14:29:53.916] Failed to dial peer                          module=p2p address=52.201.174.124:46656 err="Error creating peer: dial tcp 52.201.174.124:46656: i/o timeout"
E[01-15|14:29:53.916] Failed to dial peer                          module=p2p address=35.169.214.238:46656 err="Error creating peer: dial tcp 35.169.214.238:46656: i/o timeout"
E[01-15|14:29:53.916] Failed to dial peer                          module=p2p address=73.92.247.82:46656 err="Error creating peer: dial tcp 73.92.247.82:46656: i/o timeout"
E[01-15|14:30:23.916] Failed to dial peer                          module=p2p address=52.201.174.124:46656 err="Error creating peer: dial tcp 52.201.174.124:46656: i/o timeout"
E[01-15|14:30:23.916] Failed to dial peer                          module=p2p address=52.26.219.159:46656 err="Error creating peer: dial tcp 52.26.219.159:46656: i/o timeout"
E[01-15|14:30:23.916] Failed to dial peer                          module=p2p address=35.169.214.238:46656 err="Error creating peer: dial tcp 35.169.214.238:46656: i/o timeout"
E[01-15|14:30:52.266] Failed to dial peer                          module=p2p address=73.92.247.82:46656 err="Error creating peer: dial tcp 73.92.247.82:46656: getsockopt: no route to host"
E[01-15|14:30:53.916] Failed to dial peer                          module=p2p address=52.201.174.124:46656 err="Error creating peer: dial tcp 52.201.174.124:46656: i/o timeout"
E[01-15|14:31:23.916] Failed to dial peer                          module=p2p address=52.201.174.124:46656 err="Error creating peer: dial tcp 52.201.174.124:46656: i/o timeout"
E[01-15|14:31:23.916] Failed to dial peer                          module=p2p address=35.169.214.238:46656 err="Error creating peer: dial tcp 35.169.214.238:46656: i/o timeout"

**Comment by zramsay** [comment]
i started running into this this morning ...
