### ISSUE TITLE
Docker container doesn't show the version

### ISSUE THREAD

**Issue by kenorb** [cosmos/gaia#1072]
## Summary of Bug

When trying to run `gaiad version` in Docker container, it doesn't show the version. 

## Version

I don't know, that's the issue.

## Steps to Reproduce

```
$ docker run tendermint/gaia gaiad version
-
$ docker run tendermint/gaia:v4.2.1 gaiad version
-
```

Is this expected?
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
closing this as there is no docker for current versions.
