### ISSUE TITLE
Output of 'status' command returned on stderr, not stdout

### ISSUE THREAD

**Issue by kenorb** [cosmos/gaia#1073]
## Summary of Bug

When run `gaiad status` it prints JSON (without errors, rc=0), however it is still printed to stderr, not stdout.
Not sure if this is expected, it doesn't make sense much to print a regular JSON to stderr. And also makes an additional effort to format or parse JSON (e.g. `gaiad status 2>&1 | jq`).

Related: <https://github.com/FunctionX/fx-core/issues/12>.

## Version

Latest.

## Steps to Reproduce

```
docker run tendermint/gaia gaiad status | jq
docker run tendermint/gaia gaiad status  >/dev/null; echo $?
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
Hi! Thanks for letting us know about this issue. This seems to be something that isn't Gaia specific but is caused by the [Cosmos SDK](https://github.com/cosmos/cosmos-sdk). We're moving this issue to the SDK repo, but please let us know if we misunderstood. Thanks!

**Comment by tac0turtle** [comment]
hey, thanks for opening the issue, like Noam mentioned this would need to be opened on there sdk. We had an issue for it, but can't remember where it is now. Needless to say many people have asked for this. Closing this for now

**Comment by alessio** [comment]
`status` is meant to exit with 0 if no errors are encountered. Either way, the diagnostic output is always printed to stderr.
