### ISSUE TITLE
cmd/gaiad/cmd/testnet.go:387:15: badCall: suspicious Join on 1 argument (gocritic)

### ISSUE THREAD

**Issue by kenorb** [cosmos/gaia#1074]
## Summary of Bug

Cannot compile via `make` due to error.

## Version

- `main` branch

## Steps to Reproduce

```
gaia$ make
...
golangci-lint run
WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'. 
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref. 
cmd/gaiad/cmd/testnet.go:387:15: badCall: suspicious Join on 1 argument (gocritic)
	writePath := filepath.Join(dir)
	             ^
make: *** [Makefile:195: lint] Error 1
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
hello, please use `make install` if you're trying to install the binary. By running just `make` you run all sorts of lints and tests. When i run myself i don't get any errors, so i'm not sure if you have local configurations that make your lint more strict. But if you're just trying to build the binary you don't need to run all the other stuff.
