### ISSUE TITLE
Replacing Cosmos SDK with 43.2

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1084]
Is there a reason for this?

https://github.com/cosmos/gaia/blob/4533e8a604a91a5db0758a69e351c85047f658d4/go.mod#L124

**Comment by okwme** [comment]
oh strange, very good question.  
luckily it's just a patch release which means we could do gaia v6.0.1 rather painlessly.  
I'm inclined to wait until after the upgrade to avoid confusion unless there are critical updates between v0.44.2 and v0.44.3 that we should prioritize.

**Comment by okwme** [comment]
Actually we'll be able to include v0.44.4

**Comment by jhernandezb** [comment]
There is one critical bug in v0.44.2 fixed in v0.44.3 about expired authorizations that will prevent new nodes to sync

**Comment by faddat** [comment]
I think this can be safely closed, but #1099 does get into explaining and understanding it.
