### ISSUE TITLE
'make all' error

### ISSUE THREAD

**Issue by alexjipark** [cosmos/gaia#109]
Hi, Has anyone come up with this error when running 'make all' in gaia ?

Plz help me out..

go install ./cmd/gaia
#github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/rpc/grpc
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:171: cannot use handler (type func("context".Context, interface {}) (interface {}, error)) as type grpc.UnaryHandler in argument to interceptor
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:189: cannot use handler (type func("context".Context, interface {}) (interface {}, error)) as type grpc.UnaryHandler in argument to interceptor
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:198: cannot use _BroadcastAPI_Ping_Handler (type func(interface {}, "context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:202: cannot use _BroadcastAPI_BroadcastTx_Handler (type func(interface {}, "context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value
make: *** [install] Error 2

**Comment by melekes** [comment]
What is your `go version`? gaia may require at least 1.9

**Comment by zramsay** [comment]
closing for now. @alexjipark please re-open if updating to go1.9 doesn't help
