### ISSUE TITLE
Cannot run node via gaiad start. Get a panic: StoreBlockHeight (5200791) > StateBlockHeight + 1 (1) error

### ISSUE THREAD

**Issue by schnetzlerjoe** [cosmos/gaia#1091]
## Summary of Bug

When I run "gaiad start --p2p.seeds bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656 --x-crisis-skip-assert-invariants" the start fails with the output:

panic: StoreBlockHeight (5200791) > StateBlockHeight + 1 (1)

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc00023e020, 0x7}}, {0xc00023e040, 0xb}, 0x4f5b97, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.8/consensus/replay.go:382 +0xadf
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc023d98520, {0x1ccfe20, 0xc0000f21a0})
        github.com/tendermint/tendermint@v0.34.8/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc00023e020, 0x7}}, {0xc00023e040, 0xb}, 0x4f5b97, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.8/node/node.go:277 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000dd83c0, {0x1c89510, 0xc000dd7b80}, 0xc000fd2f10, {0x1c6e6e0, 0xc00000f470}, 0x4137f4, 0x93dc0, 0xc000fd3080, {0x1ca8318, ...}, ...)
        github.com/tendermint/tendermint@v0.34.8/node/node.go:685 +0x558
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x1caf7b0, 0xc000d0e750}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:244 +0x625
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000d3fb80, {0xc000da7920, 0x0, 0x1})
        github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:120 +0x168
github.com/spf13/cobra.(*Command).execute(0xc000d3fb80, {0xc000da7910, 0x1, 0x1})
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000cecc80)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000cf1890, 0xb})
        github.com/cosmos/cosmos-sdk@v0.42.3/server/cmd/execute.go:36 +0x1d0
main.main()
        github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x2c

I have also tried by adding the seeds here https://hackmd.io/@KFEZk8oMTz6vBlwADz0M4A/BkKEUOsZu# in the config.toml doc

## Version

gaiacli version: command not found

gaiad version: v4.2.0

## Steps to Reproduce

Following the same instructions in quickstart here https://github.com/cosmos/mainnet
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
Hi @schnetzlerjoe , it seems you already have some data stores before you use quick start ?

**Comment by tac0turtle** [comment]
what was your process to setting up your node? I know this error, but unclear how you got there. was the node syncing?

**Comment by tac0turtle** [comment]
closing this, but feel free to tag marbar in discord to discuss the issue you ran into
