### ISSUE TITLE
Should Validator Tokens Be a coin?

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#11]
Right now they are not a coin at all. BUT they are perfect to structure as a coin for an account - would maybe even make the code structure simpler/more-comprehensible I believe (but then by default they would be tradeable unless we halt trading on any coins with a prefix of say "bond" or something) Just an idea to not forget about

**Comment by adrianbrink** [comment]
Do you mean that bonded atoms should be of type coin?

**Comment by rigelrozanski** [comment]
@adrianbrink No, I mean, right now each account holds a a series of coins (denom/amount)... One of the "coins" that each account could hold is a coin which is called "bondedTokenFromAdrianValidator/1000" or something like that. When you bond coins to a validator you always lose control of those coins, but in exchange you get "bond tokens" which can be used to unbond your bonded coins (plus hopefully more if you have validator rewards)

**Comment by rigelrozanski** [comment]
Too complicated - maybe reopen one day
