### ISSUE TITLE
Proposer Reward: Which Proposer?

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#110]
@ebuchman 

The proposer reward is intended to:
 a) Inventive no empty blocks 
 b) Disincentivize censorship (sliding reward 1->5% based on precommits collected)

proposer rewards need to go to the proposer which created the block ?AND? the proposer which 
broadcasted the block (which is ideally the same but not always)?

Unless there is a way to enforce that the validator which broadcasts the next block must broadcast the existing locked block - in which case it may be fine to only provide rewards to the proposer of which originally created the block.

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/588
