### ISSUE TITLE
Cosmos Hub 2 Upgrade procedure

### ISSUE THREAD

**Issue by wimel** [cosmos/gaia#111]
After reading the [Cosmos Hub 2 Upgrade](https://github.com/cosmos/gaia/wiki/Cosmos-Hub-2-Upgrade#upgrade-procedure) I miss a very important step, file with the name `gaiad.toml`  is now  `app.toml` in `.gaiad/config/`

**Comment by alexanderbez** [comment]
Thanks @wimel!
