### ISSUE TITLE
Sync error for new installation of Gaia V6.0.0

### ISSUE THREAD

**Issue by m-not** [cosmos/gaia#1121]
The installation is assembled in docker, in old assemblies I replaced the binary and the update to 6.0.0 went fine.
I put the assembly 6.0.0 to sync from scratch and within a minute after successful initialization the error shown below pops up.

atom    | 2:15PM INF starting ABCI with Tendermint
atom    | 2:15PM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.
atom    | 2:15PM INF Starting multiAppConn service impl=multiAppConn module=proxy
atom    | 2:15PM INF Starting localClient service connection=query impl=localClient module=abci-client
atom    | 2:15PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
atom    | 2:15PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
atom    | 2:15PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
atom    | 2:15PM INF Starting EventBus service impl=EventBus module=events
atom    | 2:15PM INF Starting PubSub service impl=PubSub module=pubsub
atom    | 2:15PM INF Starting IndexerService service impl=IndexerService module=txindex
atom    | 2:15PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v6.0.0
atom    | 2:15PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
atom    | 2:15PM INF asserting crisis invariants inv=0/12 module=x/crisis name=staking/module-accounts
atom    | 2:15PM INF asserting crisis invariants inv=1/12 module=x/crisis name=staking/nonnegative-power
atom    | 2:15PM INF asserting crisis invariants inv=2/12 module=x/crisis name=staking/positive-delegation
atom    | 2:15PM INF asserting crisis invariants inv=3/12 module=x/crisis name=staking/delegator-shares
atom    | 2:16PM INF asserting crisis invariants inv=4/12 module=x/crisis name=distribution/nonnegative-outstanding
atom    | 2:16PM INF asserting crisis invariants inv=5/12 module=x/crisis name=distribution/can-withdraw
atom    | 2:25PM INF asserting crisis invariants inv=6/12 module=x/crisis name=distribution/reference-count
atom    | 2:25PM INF asserting crisis invariants inv=7/12 module=x/crisis name=distribution/module-account
atom    | 2:25PM INF asserting crisis invariants inv=8/12 module=x/crisis name=gov/module-account
atom    | 2:25PM INF asserting crisis invariants inv=9/12 module=x/crisis name=liquidity/escrow-amount
atom    | 2:25PM INF asserting crisis invariants inv=10/12 module=x/crisis name=bank/nonnegative-outstanding
atom    | 2:25PM INF asserting crisis invariants inv=11/12 module=x/crisis name=bank/total-supply
atom    | 2:25PM INF asserted all invariants duration=603540.755923 height=5200791 module=x/crisis
atom    | 2:25PM INF created new capability module=ibc name=ports/transfer
atom    | 2:25PM INF port binded module=x/ibc/port port=transfer
atom    | 2:25PM INF claimed capability capability=1 module=transfer name=ports/transfer
atom    | 2:25PM INF Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=consensus
atom    | 2:25PM INF Version info block=11 p2p=8 tendermint_version=v0.34.14
atom    | 2:25PM INF This node is not a validator addr=1C7C5FA32BEA6AD4BF32318E20CFA22D0C19283E module=consensus pubKey=IPPz1kQ489yxeudYWBcNBnS3zdPFj9pcDuWg0Pa/YmA=
atom    | 2:25PM INF P2P Node ID ID=81349da37fe95df56d38f1271a3ddbb3e68a9f77 file=/coin/config/node_key.json module=p2p
atom    | 2:25PM INF Adding persistent peers addrs=["bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656","366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656","cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656","ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656","3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656","ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656","538ebe0086f0f5e9ca922dae0462cc87e22f0a50@34.122.34.67:26656","d3209b9f88eec64f10555a11ecbf797bb0fa29f4@34.125.169.233:26656","bdc2c3d410ca7731411b7e46a252012323fbbf37@34.83.209.166:26656","585794737e6b318957088e645e17c0669f3b11fc@54.160.123.34:26656","df57f70cd3a104dcbd14d1aac9eb260c99a620e0@121.78.247.247:26656","11dfe200894f38e411beca77928e9dd118e66813@94.130.98.157:26656","5b4ed476e01c49b23851258d867cc0cfc0c10e58@206.189.4.227:26656","654f47a762c8f9257aef4a44c1fb5014916d8b20@99.79.60.15:26656","547bfac343b9b4bd54ce9cb891c4bca3db2a0922@157.230.116.241:26656","d6318b3bd51a5e2b8ed08f2e520d50289ed32bf1@52.79.43.100:26656","1bfda3d59e70290a3dada9bb809dd954371850d3@54.180.225.240:26656","6ee94c2093505e8790442c054e6e1e0211d36583@44.239.140.195:26656","ec779a2741da6dd2ccdaa6dfc0bebb10e595dfa4@50.18.113.67:26656","047f723806ee702b211e7227f89eacd829aabd86@52.9.212.125:26656","b0e746acb6fbed7a0311fe21cfb2ee94581ca3bc@51.79.21.187:26656","82772547c4575c18dfe6e75aafe521cf7d4dc8de@142.93.157.186:26656"] module=p2p
atom    | 2:25PM INF Adding unconditional peer ids ids=[] module=p2p
atom    | 2:25PM INF Add our address to book addr={"id":"81349da37fe95df56d38f1271a3ddbb3e68a9f77","ip":"0.0.0.0","port":26656} book=/coin/config/addrbook.json module=p2p
atom    | 2:25PM INF Starting Node service impl=Node
atom    | 2:25PM INF Starting pprof server laddr=localhost:6060
atom    | 2:25PM INF Starting P2P Switch service impl="P2P Switch" module=p2p
atom    | 2:25PM INF Starting Mempool service impl=Mempool module=mempool
atom    | 2:25PM INF Starting BlockchainReactor service impl=BlockchainReactor module=blockchain
atom    | 2:25PM INF Starting BlockPool service impl=BlockPool module=blockchain
atom    | 2:25PM INF Starting RPC HTTP server on [::]:26657 module=rpc-server
atom    | 2:25PM INF Starting Consensus service impl=ConsensusReactor module=consensus
atom    | 2:25PM INF Reactor  module=consensus waitSync=true
atom    | 2:25PM INF Starting Evidence service impl=Evidence module=evidence
atom    | 2:25PM INF Starting StateSync service impl=StateSync module=statesync
atom    | 2:25PM INF Starting PEX service impl=PEX module=pex
atom    | 2:25PM INF Starting AddrBook service book=/coin/config/addrbook.json impl=AddrBook module=p2p
atom    | 2:25PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
atom    | 2:25PM INF No addresses to dial. Falling back to seeds module=pex
atom    | 2:25PM INF Dialing peer address={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656} module=p2p
atom    | 2:25PM INF Starting Peer service impl="Peer{MConn{34.141.15.99:26656} ba3bacc714817218562f743178228f23678b2873 out}" module=p2p peer={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Starting MConnection service impl=MConn{34.141.15.99:26656} module=p2p peer={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
atom    | 2:25PM INF Saving AddrBook to file book=/coin/config/addrbook.json module=p2p size=22
atom    | 2:25PM INF Will dial address, which came from seed addr={"id":"b7c7803f2ca9b45cb20d1c2bcf18a347716dad04","ip":"3.36.130.83","port":26656} module=pex seed={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Will dial address, which came from seed addr={"id":"5b92e9ac5fa6b79e2babc325bfd4f36ae155d64b","ip":"34.237.158.233","port":50974} module=pex seed={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Will dial address, which came from seed addr={"id":"60e307a8e726482c1413980094501fdb42d78cda","ip":"35.231.202.123","port":26656} module=pex seed={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Will dial address, which came from seed addr={"id":"43ba8ef7cae88be71e63b54d4e8a91f294449c6e","ip":"123.56.250.241","port":57596} module=pex seed={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Will dial address, which came from seed addr={"id":"7425ea63de7a73323b8c009a02cd3aa7e1e3d31f","ip":"34.243.131.170","port":26656} module=pex seed={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Dialing peer address={"id":"b7c7803f2ca9b45cb20d1c2bcf18a347716dad04","ip":"3.36.130.83","port":26656} module=p2p
atom    | 2:25PM INF Will dial address, which came from seed addr={"id":"35ca51aba3924dd0a3451bd2e963fb50aa8ad4bb","ip":"34.234.223.46","port":26656} module=pex seed={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
atom    | 2:25PM INF Dialing peer address={"id":"5b92e9ac5fa6b79e2babc325bfd4f36ae155d64b","ip":"34.237.158.233","port":50974} module=p2p
atom    | 2:25PM INF Will dial address, which came from seed addr={"id":"8543e83daba200fd9155365d81afedf7e6b0002a","ip":"100.96.2.168","port":26656} module=pex seed={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
............................................................
atom    | 2:25PM INF Starting MConnection service impl=MConn{45.79.249.253:26656} module=p2p peer={"id":"ee27245d88c632a556cf72cc7f3587380c09b469","ip":"45.79.249.253","port":26656}
atom    | 2:25PM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
atom    | 2:25PM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"ee27245d88c632a556cf72cc7f3587380c09b469","ip":"45.79.249.253","port":26656}
atom    | 2:25PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"ee27245d88c632a556cf72cc7f3587380c09b469","ip":"45.79.249.253","port":26656}
atom    | 2:25PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
atom    | 2:25PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"ee27245d88c632a556cf72cc7f3587380c09b469","ip":"45.79.249.253","port":26656}
atom    | 2:25PM INF Reconnecting to peer addr={"id":"ee27245d88c632a556cf72cc7f3587380c09b469","ip":"45.79.249.253","port":26656} module=p2p
atom    | 2:25PM INF Dialing peer address={"id":"ee27245d88c632a556cf72cc7f3587380c09b469","ip":"45.79.249.253","port":26656} module=p2p
atom    | panic: UnmarshalJSON cannot decode empty bytes
atom    | 
atom    | goroutine 299759 [running]:
atom    | github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get(0x23f5f40, 0xc0011b1b90, 0xc000011520, 0x23b9ea0, 0xc000fa3bd0, 0x23b9f20, 0xc000fa3c90, 0xc001532540, 0x9, 0x1f, ...)
atom    | 	github.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:109 +0x32a
atom    | github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet(0x23f5f40, 0xc0011b1b90, 0xc000011520, 0x23b9ea0, 0xc000fa3bd0, 0x23b9f20, 0xc000fa3c90, 0xc001532540, 0x9, 0x1f, ...)
atom    | 	github.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:222 +0x1a8
atom    | github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.GetParams(...)
atom    | 	github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/keeper/keeper.go:56
atom    | github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.ExecutePoolBatches(0x23f5f40, 0xc0011b1b90, 0x23b9ea0, 0xc000fa3c20, 0x7f908819ccd8, 0xc0000fd340, 0x23bcd20, 0xc00001c750, 0x2399c60, 0xc000046480, ...)
atom    | 	github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/keeper/batch.go:83 +0x18f
atom    | github.com/gravity-devs/liquidity/x/liquidity.EndBlocker(0x23de320, 0xc000044018, 0x23f8ec0, 0xc00064c840, 0xb, 0x0, 0xc00a85cae0, 0xb, 0x4f5b97, 0x0, ...)
atom    | 	github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/abci.go:24 +0x1b8
atom    | github.com/gravity-devs/liquidity/x/liquidity.AppModule.EndBlock(...)
atom    | 	github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/module.go:173
atom    | github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(0xc000028e70, 0x23de320, 0xc000044018, 0x23f8ec0, 0xc00064c840, 0xb, 0x0, 0xc00a85cae0, 0xb, 0x4f5b97, ...)
atom    | 	github.com/cosmos/cosmos-sdk@v0.44.3/types/module/module.go:466 +0x227
atom    | github.com/cosmos/gaia/v6/app.(*GaiaApp).EndBlocker(...)
atom    | 	github.com/cosmos/gaia/v6/app/app.go:633
atom    | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc0000ce000, 0x4f5b97, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
atom    | 	github.com/cosmos/cosmos-sdk@v0.44.3/baseapp/abci.go:210 +0x314
atom    | github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000f7c5a0, 0x4f5b97, 0x0, 0x0, 0x0)
atom    | 	github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:288 +0xdb
atom    | github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0012aa600, 0x4f5b97, 0x20, 0x20, 0xb)
atom    | 	github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:89 +0x42
atom    | github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x23df220, 0xc025b04b40, 0x23ec6c0, 0xc0012aa600, 0xc00cad4960, 0x23f5ac0, 0xc0012aa650, 0x4f5b97, 0x0, 0x0, ...)
atom    | 	github.com/tendermint/tendermint@v0.34.14/state/execution.go:327 +0x654
atom    | github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc005a9d2d0, 0xb, 0x0, 0xc02fc64600, 0x8, 0xc02fc64610, 0xb, 0x4f5b97, 0x0, 0x0, ...)
atom    | 	github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x165
atom    | github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000532380, 0x0)
atom    | 	github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:398 +0xa28
atom    | created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
atom    | 	github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x8c

**Comment by suggalla** [comment]
I'm having the same issue of `panic: UnmarshalJSON cannot decode empty bytes`. This causes the node to keep crashing with the following stacktrace:

```
cosmos_1  | 5:29PM INF Error reconnecting to peer. Trying again addr={"id":"df57f70cd3a104dcbd14d1aac9eb260c99a620e0","ip":"121.78.247.247","port":26656} err="dial tcp 121.78.247.247:26656: i/o timeout" module=p2p tries=0
cosmos_1  | panic: UnmarshalJSON cannot decode empty bytes
cosmos_1  | 
cosmos_1  | goroutine 298721 [running]:
cosmos_1  | github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x203ec38, 0xc0010ebf30}, 0xc000027068, {0x1fe5530, 0xc0010ea5f0}, {0x1fe5580, 0xc0010ea700}, {0xc000116d00, 0x9, 0x1f}, ...}, ...)
cosmos_1  |     github.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:109 +0x319
cosmos_1  | github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x203ec38, 0xc0010ebf30}, 0xc000027068, {0x1fe5530, 0xc0010ea5f0}, {0x1fe5580, 0xc0010ea700}, {0xc000116d00, 0x9, 0x1f}, ...}, ...)
cosmos_1  |     github.com/cosmos/cosmos-sdk@v0.44.3/x/params/types/subspace.go:222 +0x145
cosmos_1  | github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.GetParams(...)
cosmos_1  |     github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/keeper/keeper.go:56
cosmos_1  | github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.ExecutePoolBatches({{0x203ec38, 0xc0010ebf30}, {0x1fe5530, 0xc0010ea690}, {0x7f03cb854158, 0xc001129b80}, {0x1fe7128, 0xc0001be750}, {0x1fd8ec0, 0xc0001fe3c0}, ...}, ...)
cosmos_1  |     github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/keeper/batch.go:83 +0x125
cosmos_1  | github.com/gravity-devs/liquidity/x/liquidity.EndBlocker({{0x2017728, 0xc000046068}, {0x2043e60, 0xc00016a600}, {{0xb, 0x0}, {0xc00ee15fa4, 0xb}, 0x4f5b97, {0x0, ...}, ...}, ...}, ...)
cosmos_1  |     github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/abci.go:24 +0x158
cosmos_1  | github.com/gravity-devs/liquidity/x/liquidity.AppModule.EndBlock(...)
cosmos_1  |     github.com/gravity-devs/liquidity@v1.4.2/x/liquidity/module.go:173
cosmos_1  | github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x2017728, 0xc000046068}, {0x2043e60, 0xc00016a600}, {{0xb, 0x0}, {0xc00ee15fa4, 0xb}, 0x4f5b97, ...}, ...}, ...)
cosmos_1  |     github.com/cosmos/cosmos-sdk@v0.44.3/types/module/module.go:466 +0x33d
cosmos_1  | github.com/cosmos/gaia/v6/app.(*GaiaApp).EndBlocker(...)
cosmos_1  |     github.com/cosmos/gaia/v6/app/app.go:633
cosmos_1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000551380, {0x100000000000000})
cosmos_1  |     github.com/cosmos/cosmos-sdk@v0.44.3/baseapp/abci.go:210 +0x25d
cosmos_1  | github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0001f7da0, {0xc0001f7da0})
cosmos_1  |     github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:288 +0xdf
cosmos_1  | github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc02a5d1660, {0x20})
cosmos_1  |     github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:89 +0x24
cosmos_1  | github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2018480, 0xc01f8c5aa0}, {0x202d270, 0xc00055cc30}, 0xc00f4ff2c0, {0x203c6e8, 0xc0011315f0}, 0x0)
cosmos_1  |     github.com/tendermint/tendermint@v0.34.14/state/execution.go:327 +0x54e
cosmos_1  | github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc010268bd0, 0x8}}, {0xc010268be0, 0xb}, 0x4f5b97, 0x0, {{0x0, ...}, ...}, ...}, ...)
cosmos_1  |     github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x171
cosmos_1  | github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000e4e700, 0x0)
cosmos_1  |     github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:398 +0xb7b
cosmos_1  | created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
cosmos_1  |     github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x85
cosmos_1  | 2021-12-15 17:29:23,957 INFO exited: cosmos-daemon (exit status 2; not expected)
```

**Comment by yaruwangway** [comment]
For ` panic: UnmarshalJSON cannot decode empty bytes` , please check if you have the correct binary version

**Comment by m-not** [comment]
I am using a ready-made binary assembly:
https://github.com/cosmos/gaia/releases/download/v6.0.0/gaiad-v6.0.0-linux-amd64

And I repeat that the same container assembly works fine in the update. Only clean install doesn't work.

**Comment by suggalla** [comment]
I'm on v6.0.0:
`cosmos_1  | 11:04PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v6.0.0`

**Comment by glnro** [comment]
@m-not Are you mounting volumes with the old container (chain) data to the new container?

**Comment by m-not** [comment]
No, this is a fresh installation on a new server, I want to rebuild the chain from scratch.

And as I already wrote, the update with the same container went fine for me.

**Comment by suggalla** [comment]
I'm also trying to sync from scratch

**Comment by glnro** [comment]
@m-not Do you mean you want to resync the entire chain from the beginning of `cosmoshub-4` or just from after the upgrade to Vega V6.0.0? If you want to do the latter, you will need to bring over the genesis file and the contents of `~/.gaia/data` for this to work. We are in the process of bringing the docs up to date on joining mainnet but in the mean time, check out the [mainnet docs](https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html) for further explanation and information on state sync & quick sync.

**Comment by m-not** [comment]
No, I want to do the first, "sync the whole chain from the beginning of cosmoshub-4", on version V6.0.0.
I upgraded from version 5.0.8 to 6.0.0 successfully.

**Comment by glnro** [comment]
@m-not just to clarify, so with the new container in question, you successfully performed the upgrade, or the upgrade was done on the old container?

**Comment by m-not** [comment]
I will try to clarify, there was a build of the docker container 5.0.8, the version was changed in the dockerfile and the container was rebuilt.
On the product host, the container was updated to v6.0.0, the update was successful.
Next, I take a new host, and deploy container 6.0.0 to it, start it, sync starts, and then an error occurs.

The problem is in starting a new container for initial synchronization.

**Comment by glnro** [comment]
@m-not Gotcha, so it sounds like you're trying to sync the chain with v6.00 without any chain state. Unfortunately this is impossible. You would either need to persist the data from your previous container, or start the new container from v4 and upgrade to Delta and Vega again.

**Comment by m-not** [comment]
Okay, thanks for the clarification. This is, of course, a very uncomfortable situation. It's good when you can take the latest version of a node and start the chain from scratch without going through several updates at once or looking for (making) a snapshot of the chain to bring up a new node.

Is there a public Vega snapshot somewhere that I could download?

**Comment by uditvira** [comment]
snapshots here https://quicksync.io/networks/cosmos.html

**Comment by suggalla** [comment]
> @m-not Gotcha, so it sounds like you're trying to sync the chain with v6.00 without any chain state. Unfortunately this is impossible. You would either need to persist the data from your previous container, or start the new container from v4 and upgrade to Delta and Vega again

This is highly inconvenient. Is this documented somewhere? How are new node hosts expected to setup?

**Comment by glnro** [comment]
@suggalla We are currently working on a more comprehensive start up guide that will be available shortly.

**Comment by m-not** [comment]
> snapshots here https://quicksync.io/networks/cosmos.html

Many thanks.

**Comment by crstalli** [comment]
This seems like it will be problematic to the long term maintainability of the project if we don't have an easy way to spin up a node from scratch. Wouldn't we benefit from having the whatever is needed to sync from 4.2.1 to the current available in the current node so that you can sync it from scratch? I can imagine this happening again, and to spin up a new node, you need to spin up X nodes and upgrade before arriving at the current. 

Is it feasible to have the next version be able to sync the chain previous to 6910000 and then to the current? 

Also, this link: [in-place store migration (opens new window)] (https://docs.cosmos.network/v0.43/architecture/adr-041-in-place-store-migrations.html#adr-041-in-place-store-migrations)  gives an 404 which is found on https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html .

**Comment by glnro** [comment]
@crstalli You can easily spin up a node with the latest version of Gaia and enable state sync to bootstrap your node from a height in the current slashing period (within 3 weeks). If you wanted to run a full archive node and block sync from scratch, then this will naturally take some time. We're in the process of combing through the documentation to identify broken links and consolidate different tutorials for spinning up a node based on a few main use cases. We appreciate your patience while we update and are happy to answer any questions about this process in the meantime.

**Comment by glnro** [comment]
You can refer to the [vega testnet](https://github.com/cosmos/vega-test/tree/add-state-sync-info) instructions in the meantime and just replace the rpc servers.

**Comment by yaruwangway** [comment]
if you do not care previous blocks, you can do a snapshot sync, a ref for how to do it: https://github.com/cosmos/vega-test/tree/add-state-sync-info/public-testnet#using-state-sync.
so basically you need change in `config.toml`
find `[statesync] ` section in `config.toml` 
- set `enable = true`,
- set a `trust_height`, and a corresponding `trust_hash`, just find a recent height and hash from here https://www.mintscan.io/cosmos
- set  `rpc_servers`, you need two rpc servers here
- you also need a genesis file with the correct `chain-id`

**Comment by wodingdong** [comment]
I ran into the same problem, Where can i find seed node?

**Comment by wodingdong** [comment]
> I ran into the same problem, Where can i find seed node?

in `lanch page ` https://cosmos.network/launch   I can't find usefull seed node

**Comment by okwme** [comment]
Hello @wodingdong we've updated our join mainnet docs here: https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html which include a link to the address book provided by quicksnyc here: https://quicksync.io/addrbook.cosmos.json.

this information can also be found in the chain registry repo here: https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json

will close this issue now, please let us know if there are further problems and we'll reopen
