### ISSUE TITLE
use merging to back port to long lived branch

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/gaia#1122]
## Summary 

mergify is used by the comsos-sdk and tendermint to back port prs to long lived branches. Gaia should do the same.

**Comment by yaruwangway** [comment]
Hi, @marbar3778 , do you mean this https://github.com/cosmos/cosmos-sdk/blob/dbc19b3c545ac3d9e812a43b40f4609079577b6e/.mergify.yml#L19-L26

**Comment by tac0turtle** [comment]
yea
