### ISSUE TITLE
gaia v6.0.0 cosmos/tx/v1beta1/txs How to convert broadcast transaction parameters

### ISSUE THREAD

**Issue by jc0803kevin** [cosmos/gaia#1123]
![f413e80da3f4a819c7b836f2aaf5240](https://user-images.githubusercontent.com/16516973/146503924-8bc6e8cb-ba2f-4a76-a769-8eee76bc9ed3.png)

```json
{
  "tx": {
    "msg": [
      "string"
    ],
    "fee": {
      "gas": "string",
      "amount": [
        {
          "denom": "stake",
          "amount": "50"
        }
      ]
    },
    "memo": "string",
    "signature": {
      "signature": "MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH"
      },
      "account_number": "0",
      "sequence": "0"
    }
  },
  "mode": "block"
}

```

gaia v6.0.0 

The parameters of the broadcast transaction interface have changed, how to serialize the original parameter interface into txBytes

**Comment by okwme** [comment]
Please check the release notes of [gaia v6.0.0](https://github.com/cosmos/gaia/releases/tag/v6.0.0)

  * **BREAKING CHANGE NOTICE** While a full list of breaking changes should be checked within the Cosmos SDK v0.44.3 [CHANGELOG.md](https://github.com/cosmos/cosmos-sdk/blob/release/v0.44.x/CHANGELOG.md#v0443---2021-10-21), it's imortant to highlight [PR #10041](https://github.com/cosmos/cosmos-sdk/pull/10041) which impacts **WALLETS AND EXCHANGES**. This update has removed the deprecated the legacy REST endpoints for broadcast & encode. **This means `POST /tx` and `POST /txs/encode` no longer work**. Please see the [REST Endpoints Migration guide](https://docs.cosmos.network/master/migrations/rest.html) to migrate to the new REST endpoints.

If this doesn't address your issue please reopen and give us some more context.

thank you!
