### ISSUE TITLE
Compile v6.0.0 error!

### ISSUE THREAD

**Issue by wodingdong** [cosmos/gaia#1127]
## Version
go version: go version go1.17.5 linux/amd64
gaiad version : v6.0.0

## Steps to Reproduce

> root@187ba10d5ee5:/home/atom/gaiad-v6.0.0# make
```
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.AppName=gaiad -X github.com/cosmos/cosmos-sdk/version.Version=- -X github.com/cosmos/cosmos-sdk/version.Commit= -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/tendermint/tendermint/version.TMCoreSemVer=v0.34.14 -w -s' -trimpath  ./...
# runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/stubs.go:9:7: PtrSize redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch.go:24:38: previous declaration
/usr/local/go/src/runtime/internal/sys/stubs.go:10:24: undefined: Uintreg
/usr/local/go/src/runtime/internal/sys/stubs.go:16:7: StackGuardMultiplier redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch.go:27:74: previous declaration
make: *** [Makefile:102: install] Error 2
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
could you leave the steps to how you got to this? I can't reproduce this locally

**Comment by wodingdong** [comment]
1.Choose a newly installed ubuntu20.04 system
2.sudo apt-get update
3.install go 1.17.5 from https://go.dev/dl/  and Make sure it is installed correctly
4.git clone from `https://github.com/cosmos/gaia.git`  and checkout to v6.0.0
5.excute  "make install"

**Comment by glnro** [comment]
Hi @wodingdong try taking another look at the [Gaia Installation Guide](https://hub.cosmos.network/main/getting-started/installation.html) as this might be an issue with how Go is installed on your machine.

**Comment by yaruwangway** [comment]
Hi maybe you can `cd cmd/gaiad` and then `go build` to see if you can build the binary there

**Comment by okwme** [comment]
Hi @wodingdong ,
i'm going to close this issue. If you're still having problems please re-open and provide more details.
Thank you!
