### ISSUE TITLE
I[2019-08-25|20:04:38.384] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor I[2019-08-25|20:04:38.384] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10 I[2019-08-25|20:04:38.384] No addresses to dial nor connected peers. Falling back to seeds module=pex 

### ISSUE THREAD

**Issue by ying2025** [cosmos/gaia#113]
![image](https://user-images.githubusercontent.com/28092539/63663364-aa9eeb00-c7f4-11e9-88c8-a7f359472106.png)
how to solve this problem ?
I generate genesis.json by myself
![image](https://user-images.githubusercontent.com/28092539/63663431-ef2a8680-c7f4-11e9-90bf-de017100d5f2.png)

**Comment by alexanderbez** [comment]
Thanks @ying2025 but I don't quite follow your question? Could you perhaps rephrase? Also, this question belongs in Tendermint most likely. Please ask in that repo 👍

**Comment by ying2025** [comment]
Validator' s public key is different, but the address is the same. I donnt know why. @alexanderbez 
I init the test chain, add the validator, generate gentx, add the delegator account to launch/account,  take the genesis.json as a template, and replace gentx in launch/gentx.  Then I generate genesis.json by lauch, and start chain by this genesis. It cause the validator is a litte different, so what should I do?
