### ISSUE TITLE
Default to Rocksdb

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1134]
## Summary

The `whisky on the rocks` series of patches powers nearly every ibc relay operator's nodes on busy networks like Gaia, Terra, Osmosis and Juno.
 
## Problem Definition

We should move sober gaia to a rocksdb by default build and release process so that she:

* syncs about 3x faster
	* save operator time
	* save operator money
	* grow network of operators due to lower time burden

## Proposal

I'm proposing that we use the following replace line:

https://github.com/notional-labs/osmosis/blob/54c0b7e2c1dd01dd46e7430c155aba9f78db6303/go.mod#L126

in go.mod until either:

* tecbot accepts a pr fixing his gorocksdb lib

or

* we change the module path for the cosmos gorocksdb lib and update tm-db so that it imports the cosmos gorocksdb lib.

The performance improvements to many aspects of operating gaia are quite incredible with this one little fix.  

In the next 2-4 weeks, Notional should have a quicksync.io style server set up at an unlimited 10gbps provider in the united states.  If anyone in the community is aware of hosting centers with true 10gbps connections in asia, preferably Singapore or Hong Kong, we'd glady provide direct asia coverage, too. 

This service will provide:

* Archive
* Default
* Fully Pruned

snapshots and should make it much simpler for operators to use rocksdb.  Since rocksdb also helps with read performance, analytics on Gaia can be improved, too. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
https://github.com/tendermint/tm-db/issues/211

**Comment by tac0turtle** [comment]
sync is faster but how is overall size of state compared? how is the speed when caught up compared to other databases.
