### ISSUE TITLE
Error: wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by jungyeon0904** [cosmos/gaia#1139]
## Summary of Bug
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected FEA4045DE7554E7F3B9AC1BB37AB38BCC2A1A5C59DDD4E3B5BED0B85EF583F54, got 0504AF169FD36B9BC18C1D9CD5FFADA7AFD2B5A6E8C7EB13329FC91D75997F44

![image](https://user-images.githubusercontent.com/57450244/148045915-4f3f307d-3980-43b5-a307-746a321dbb12.png)

I recently upgraded from v5.0.8 to v6.0.0.
The upgrade was done manually using a github. below:
$git checkout -b v6.0.0 origin/release/v6.0.0
$make install

Then, when the mainnet node was executed, the following error occurred.
![image](https://user-images.githubusercontent.com/57450244/148046219-46e5709d-edff-4a58-bc46-bb8c2c02e2df.png)
![image](https://user-images.githubusercontent.com/57450244/148046235-507892ed-61fb-4609-b801-2c106979f4e7.png)

Node can no longer be synchronized at block height 8695260. Please help me.
When I looked at Cosmos Discord, there were many people who experienced the same phenomenon as me, but there was no solution.
I am a beginner developer interested in cryptocurrency. Please help me.

## Version
root@computer-System-Product-Name:~# go version
go version go1.17.5 linux/amd64
root@comnet-System-Product-Name:~# gaiad version
v6.0.0
root@comnet-System-Product-Name:~# gaiad version --long
name: gaia
server_name: gaiad
version: v6.0.0
commit: 6ed5b7397a57c42112cf1b16f550bd0a6e263953
build_tags: netgo,ledger
go: go version go1.17.5 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/ChainSafe/go-schnorrkel@v0.0.0-20200405005733-88cbf1b4c40d
- github.com/Workiva/go-datastructures@v1.0.52
- github.com/armon/go-metrics@v0.3.9
- github.com/beorn7/perks@v1.0.1
- github.com/bgentry/speakeasy@v0.1.0
- github.com/btcsuite/btcd@v0.22.0-beta
- github.com/cespare/xxhash/v2@v2.1.1
- github.com/coinbase/rosetta-sdk-go@v0.6.10
- github.com/confio/ics23/go@v0.6.6
- github.com/cosmos/cosmos-sdk@v0.44.3 => github.com/cosmos/cosmos-sdk@v0.44.2
- github.com/cosmos/go-bip39@v1.0.0
- github.com/cosmos/iavl@v0.17.1
- github.com/cosmos/ibc-go/v2@v2.0.0
- github.com/cosmos/ledger-cosmos-go@v0.11.1
- github.com/cosmos/ledger-go@v0.9.2
- github.com/davecgh/go-spew@v1.1.1
- github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f
- github.com/dvsekhvalnov/jose2go@v0.0.0-20200901110807-248326c1351b
- github.com/enigmampc/btcutil@v1.0.3-0.20200723161021-e2fb6adb2a25
- github.com/felixge/httpsnoop@v1.0.1
- github.com/fsnotify/fsnotify@v1.5.1
- github.com/go-kit/kit@v0.10.0
- github.com/go-logfmt/logfmt@v0.5.0
- github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2
- github.com/gogo/gateway@v1.1.0
- github.com/gogo/protobuf@v1.3.3 => github.com/regen-network/protobuf@v1.3.3-alpha.regen.1
- github.com/golang/protobuf@v1.5.2
- github.com/golang/snappy@v0.0.3
- github.com/google/btree@v1.0.0
- github.com/google/orderedcode@v0.0.1
- github.com/gorilla/handlers@v1.5.1
- github.com/gorilla/mux@v1.8.0
- github.com/gorilla/websocket@v1.4.2
- github.com/gravity-devs/liquidity@v1.4.2
- github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0
- github.com/grpc-ecosystem/grpc-gateway@v1.16.0
- github.com/grpc-ecosystem/grpc-gateway/v2@v2.0.1
- github.com/gsterjov/go-libsecret@v0.0.0-20161001094733-a6f4afe4910c
- github.com/gtank/merlin@v0.1.1
- github.com/gtank/ristretto255@v0.1.2
- github.com/hashicorp/go-immutable-radix@v1.0.0
- github.com/hashicorp/golang-lru@v0.5.4
- github.com/hashicorp/hcl@v1.0.0
- github.com/hdevalence/ed25519consensus@v0.0.0-20210204194344-59a8610d2b87
- github.com/improbable-eng/grpc-web@v0.14.1
- github.com/klauspost/compress@v1.11.7
- github.com/lib/pq@v1.10.2
- github.com/libp2p/go-buffer-pool@v0.0.2
- github.com/magiconair/properties@v1.8.5
- github.com/mattn/go-isatty@v0.0.14
- github.com/matttproud/golang_protobuf_extensions@v1.0.1
- github.com/mimoo/StrobeGo@v0.0.0-20181016162300-f8f6d4d2b643
- github.com/minio/highwayhash@v1.0.1
- github.com/mitchellh/go-homedir@v1.1.0
- github.com/mitchellh/mapstructure@v1.4.2
- github.com/mtibben/percent@v0.2.1
- github.com/pelletier/go-toml@v1.9.4
- github.com/pkg/errors@v0.9.1
- github.com/pmezard/go-difflib@v1.0.0
- github.com/prometheus/client_golang@v1.11.0
- github.com/prometheus/client_model@v0.2.0
- github.com/prometheus/common@v0.29.0
- github.com/prometheus/procfs@v0.6.0
- github.com/rakyll/statik@v0.1.7
- github.com/rcrowley/go-metrics@v0.0.0-20200313005456-10cdbea86bc0
- github.com/regen-network/cosmos-proto@v0.3.1
- github.com/rs/cors@v1.7.0
- github.com/rs/zerolog@v1.23.0
- github.com/spf13/afero@v1.6.0
- github.com/spf13/cast@v1.4.1
- github.com/spf13/cobra@v1.2.1
- github.com/spf13/jwalterweatherman@v1.1.0
- github.com/spf13/pflag@v1.0.5
- github.com/spf13/viper@v1.8.1
- github.com/strangelove-ventures/packet-forward-middleware@v1.0.1
- github.com/stretchr/testify@v1.7.0
- github.com/subosito/gotenv@v1.2.0
- github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca
- github.com/tendermint/btcd@v0.1.1
- github.com/tendermint/crypto@v0.0.0-20191022145703-50d29ede1e15
- github.com/tendermint/go-amino@v0.16.0
- github.com/tendermint/tendermint@v0.34.14
- github.com/tendermint/tm-db@v0.6.4
- github.com/zondax/hid@v0.9.0
- golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5
- golang.org/x/net@v0.0.0-20210903162142-ad29c8ab022f
- golang.org/x/sys@v0.0.0-20211004093028-2c5d950f24ef
- golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
- golang.org/x/text@v0.3.6
- google.golang.org/genproto@v0.0.0-20210602131652-f16073e35f0c
- google.golang.org/grpc@v1.40.0 => google.golang.org/grpc@v1.33.2
- google.golang.org/protobuf@v1.27.1
- gopkg.in/ini.v1@v1.63.2
- gopkg.in/yaml.v2@v2.4.0
- gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b
- nhooyr.io/websocket@v1.8.6
cosmos_sdk_version: v0.44.3

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
Hi @jungyeon0904 , so you upgraded successfully and produced a few blocks after upgrade, then you observed the block hash wrong ? 
Also please confirm again by cmd `gaiad version` to see which version of binary you are using now.

**Comment by jungyeon0904** [comment]
Hi @yaruwangway . yes, I upgraded from block height 8694999 to Vega. And an error occurred during synchronization up to block height 8695260.

cmd gaiad version:
root@comnet-System-Product-Name:~/gaia# gaiad version
v6.0.0

cmd gaiad version --long:
root@comnet-System-Product-Name:~/gaia# gaiad version --long
name: gaia
server_name: gaiad
version: v6.0.0
commit: "6ed5b7397a57c42112cf1b16f550bd0a6e263953"
build_tags: netgo,ledger
go: go version go1.17.5 linux/amd64

**Comment by okwme** [comment]
hi @jungyeon0904 it looks like you ran the upgrade at the wrong height. Did you manually stop your node at that height (or use the config.toml --halt-height setting)? It seems strange if you were able to run gaia v6.0.0 at 8,694,999 in the first place so maybe i'm mistaken.

I'd suggest using https://quicksync.io/networks/cosmos.html to get a node online as fast as possible. If you're interested in using state sync to get a node up to date as fast as possible please see the instructions [here](https://github.com/cosmos/mainnet/blob/306363b874e5dea91d3305788f2d864713aa10e0/README.md).

If you're still having trouble (or have more information about the app hash mismatch) please re-open this issue.
