### ISSUE TITLE
Extend cli commands to allow for easy connection to testnets

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/gaia#114]
The Jenkins integration is a great feature for frequently deploying internal testnets. However with Gaia/Cosmos hub we won't be deploying multiple testnets a week. Rather we will get some normal validators on a google hangout and manually launch the next testnet. 

Now that we have the genesis files for most of the old testnets in this repo, we need to extend the gaia cli to allow users to run `gaia node start --testnet=gaia-3`, which sets up everything in order to synchronise with the network via a fullnode. 

The second extension should be `gaia client init --testnet=gaia-3`, which automatically takes the chain-id and node info from the relevant config.toml file.

I think in the long run we should consider moving the genesis files for the testnets into code, as to cleanup this repo. That way, the above commands wouldn't need to read a file from disk, but could rather just use the config object in the binary.

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/586
