### ISSUE TITLE
Enable state-sync by default

### ISSUE THREAD

**Issue by nooomski** [cosmos/gaia#1145]
## Summary

Default `snapshot-interval` to an agreed upon standard.

## Problem Definition

Not enough peers are enabling snapshots, which makes it harder for new nodes to sync as the p2p isn't optimised to find state-sync enabled nodes.

## Proposal

Set `snapshot-interval` to default to a standard in `app.toml`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
I think after speaking with a few people we should standardize the interval to `1000`

**Comment by tac0turtle** [comment]
here is an example of what needs to be done https://github.com/osmosis-labs/osmosis/pull/737 & https://github.com/tharsis/evmos/pull/202

don't think this needs much of a feedback cycle setting to 1500 and keep every 2 is sufficient, you can increase it if needed.

**Comment by glnro** [comment]
I have a forthcoming issue and proposed change for Gaia I'm about to publish based on what Osmosis did...will link shortly
