### ISSUE TITLE
convert module readiness checklist into github issue template

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1155]
## Summary

we have a very useful module readiness checklist inside the [gaia wiki](https://github.com/cosmos/gaia/wiki/Hub-Module-Readiness-Checklist-(Blank)). i think this material would be better served as a github issue template or in some way more integrated into the github issue tracking system or project boards. then we could track how ready each new feature coming to the hub is for actually getting into the next release.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
- issue template should have a check mark for each section outlined in the wiki. Could denote whether completed or whether there is a new issue created for each of the sub-tasks. probably the latter is better.
 - create a new directory in docs for something like https://github.com/cosmos/cosmos-sdk/tree/master/docs/architecture in the cosmos sdk.
     - should have a README.md to explain what this directory and files are for, and how to create one
     - should have a template that looks similar to https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-template.md or https://github.com/cosmos/ibc/blob/master/spec/ics-template.md

**Comment by glnro** [comment]
@okwme what's the status on this...anything else other than what we've merged that you'd like to see added?
