### ISSUE TITLE
Either update or remove the changelog document in the Migration dir

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1157]
## Summary

The migration dir of the docs of the gaia repo contains a breaking changes document: https://github.com/cosmos/gaia/blob/main/docs/migration/breaking_changes.md

This could be a good resource to direct different users to to let them know about breaking changes between versions of Gaia's upstream dependencies (Cosmos-SDK, Tendermint, IBC).

However this document is out of date and I question whether the format was suitable to make it as useful as possible. It contains all breaking changes instead of specifically breaking changes between versions of Gaia. It must have been difficult to keep this up to date as well.

I suggest removing it and committing to creating wholistic upgrade instructions between breaking releases of gaia where these changes are collated for specific users and specific instances.

Any thoughts?

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Agreed though I'm not sure where those new instructions would live, and where the best place to archive the existing document. What action items do we want coming from this issue?

**Comment by okwme** [comment]
these are inluded in our our changelog / release notes.

**Comment by okwme** [comment]
let's nuke em 💣
