### ISSUE TITLE
Add info to 'upgrade instructions' wiki: https://github.com/cosmos/gaia/wiki/Cosmos-Hub-2-Upgrade

### ISSUE THREAD

**Issue by gavinly** [cosmos/gaia#116]
@alexanderbez, we'll want instructions for validators to obtain the timestamp from the target export block. I'd like to add info necessary for a recovery scenario to the instructions wiki. @zmanian please let me know if this looks correct or not. Here are my requests:

During the upgrade process, each validator must preserve a snapshot of the node state of the target export block height to preserve recovery of their validator and sentry nodes to the cosmoshub-2 chain. // Add this to https://github.com/cosmos/gaia/wiki/Cosmos-Hub-2-Upgrade#upgrade-procedure

### Recovery Scenario
In the event that a validator determines that the cosmoshub-3 chain is unlikely to start, or if export block time + 6 hours has elapsed without block generation, validators must resume signing on cosmoshub-2. 

Governance procedures on the cosmoshub-2 chain will then be used to determine a future course of action for the network. // Create this as a new subsection

**Comment by alexanderbez** [comment]
@gavinly I've added two entries on recovery and getting a block's UTC timestamp. Please review.

**Comment by gavinly** [comment]
Looks good to me, thank you! @zmanian could you please review?

**Comment by alexanderbez** [comment]
Will close for now. @zmanian feel free to make any adjustments 👍
