### ISSUE TITLE
gaia node init should output a success message

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#118]
and information that stuff was put in `~/.cosmos-gaia-cli`

**Comment by melekes** [comment]
I think right now you need to pass `--log_level="main:info"` or `--log_level="*:info"` in order to see the messages.

**Comment by melekes** [comment]
Not sure where to look for code here, but at least it's fixed on Tendermint side https://github.com/tendermint/tendermint/pull/1193

**Comment by zramsay** [comment]
sweet 👍 
this'll work when gaia updates to latest tendermint
