### ISSUE TITLE
ERROR: Error during handshake: Error on replay: Block time 2019-09-03 02:58:00.048670958 +0000 UTC is not equal to genesis time 2019-03-13 23:00:00 +0000 UTC

### ISSUE THREAD

**Issue by ying2025** [cosmos/gaia#118]
Unbonding Height:           0
  Unbonding Completion Time:  1970-01-01 00:00:00 +0000 UTC
  Minimum Self Delegation:    1000000000000
  Commission:                 rate: 0.100000000000000000, maxRate: 0.200000000000000000, maxChangeRate: 0.010000000000000000, updateTime: 2019-03-13 23:00:00 +0000 UTC
---rewards--- { 2}
---rewards.Rewards--current--  --rewards.Rw--  --val token-- 2000000000000
====historical===  2
----calculateDelegationRewardsBetween---  
=====rewards====== 
ERROR: Error during handshake: Error on replay: Block time 2019-09-03 02:58:00.048670958 +0000 UTC is not equal to genesis time 2019-03-13 23:00:00 +0000 UTC

**Comment by alexanderbez** [comment]
Can you please provide more information @ying2025 ?
