### ISSUE TITLE
Standardize Makefile commands with SDK

### ISSUE THREAD

**Issue by fedekunze** [cosmos/gaia#120]
## Summary

Update the Gaia Makefile commands names to match the ones on the SDK.

## Problem Definition

The difference in the `Makefile` commands with the SDK is tedious and I have to look at the file to be able to run them.

## Proposal

Standardize the common commands with the SDK.

cc: @mircea-c @alessio @jackzampolin @alexanderbez 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
overlapping are currently: tools, lint, test, go-mod-cache, go.sum, distclean, format, benchmark

which other ones should match? @fedekunze

**Comment by alexanderbez** [comment]
++ Let's get them lined up and standardized. Please, also, no snake-case.

**Comment by alexanderbez** [comment]
@alessio do you think you can handle this?

**Comment by fedekunze** [comment]
FYI the sims are already updated on https://github.com/cosmos/gaia/pull/119
