### ISSUE TITLE
docs: outdated link to Lunie

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#1202]
https://hub.cosmos.network/main/resources/ledger.html
last sentence First prgh

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
Fixed in PR #1205 
Thanks for highlighting @zramsay !
