### ISSUE TITLE
`gaiad keys add` doesn't support both `--hd-path` and `--ledger` simultaneously

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#1203]
## Summary of Bug

expectation:
that 
`gaiad keys add secondAccount --hd-path "44'/118'/1'/0/0" --ledger`
would result in adding the second account that already exists on a Ledger. The account was created using Ledger Live and was also added to Keplr using the HD path supplied by Ledger Live (account -> settings -> advanced)

Instead I got this error: `cannot set custom bip32 path with ledger` and tracked down
[this bit of code](https://github.com/cosmos/cosmos-sdk/blob/master/client/keys/add.go#L200-L204) that explicitly prevents the CLI from using HD path with the ledger.

## Version

4.0.0
 

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
I think the reason you can't set a custom bip32 path is because the Cosmos ledger app only accepts `coin_type` 118. So I have a feeling this is a desired restriction. Care to weigh in @okwme ?

**Comment by zramsay** [comment]
so i did get it working using `--account=N` and apparently `--index=N` (see @alexanderbez comment in the linked issue) works the same. seems those two flags perform the same function (?)

**Comment by nooomski** [comment]
Thanks for reporting back. Glad you found a workaround! Will close this issue as it's an SDK specific problem.
