### ISSUE TITLE
Gaia Upgrade has better logs

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1216]
## Summary

The last upgrade no one could tell if it was working and just taking a long time or if it was broken. We should have better logs to let people know it's alllllright.

## Proposal

investigate and execute methods for adding logs. Check out how provenenance did it:
https://github.com/provenance-io/provenance/blob/main/x/metadata/keeper/migrations.go
https://github.com/provenance-io/provenance/blob/main/app/upgrades.go#L128-L136

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
we might wait for a backport release of sdk-0.45.1 for adding migration logs to 0.45.
https://github.com/cosmos/cosmos-sdk/issues/11048

**Comment by mmulji-ic** [comment]
@yaruwangway states its done!
