### ISSUE TITLE
gaiacli command not found?

### ISSUE THREAD

**Issue by iamyh** [cosmos/gaia#122]
I do as README.md,but found "gaiacli" is not found, does it means "gaia client"?

another problem is when i do "gaia client tx bond --fee 10fermion --name myaccount --pubkey ${pubkey}", it shows "ERROR: unknown flag: --pubkey"?

**Comment by rigelrozanski** [comment]
Which document are you referencing - any old documents would have referenced `gaiacli` new ones should reference `gaia client` there may be antiquated documentation. 

Additionally you can see the available flags with "gaia client tx bond --help" note that pubkey is not an available flag (so of course it will give an error!) - how gaia has been designed in this version allows for the `pubkey` to be derived internally when the `--name` is provided with proper credentials (which the CLI will then ask for)

**Comment by iamyh** [comment]
I did it as README.md in master branch.After i did  "make all",then i go to directory $GOBIN,only can saw the gaia,but not gaiacli.

when i do command "gaia client tx bond --help"， it  will be show usage.

I feel README.md in master branch is too old.

**Comment by krisrp** [comment]
They're apparently in the process of refactoring the docs and moving the gaia codebase into the cosmos-sdk repo.

New docs are here: https://github.com/cosmos/cosmos-sdk/tree/docs-refactor/docs/staking

**Comment by rigelrozanski** [comment]
thanks @krisrp, I'm going to leave this issue open until master branch docs aren't messed up

**Comment by zramsay** [comment]
obsolete. will be fixed once staking module moved to SDK repo
