### ISSUE TITLE
figure out how to update the cosmos docs swagger dropdown to include latest release numbers

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1222]
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
Done but need a review on https://github.com/cosmos/v1.cosmos.network/pull/233

**Comment by nooomski** [comment]
Solved by https://github.com/cosmos/v1.cosmos.network/pull/236
