### ISSUE TITLE
Timing issues around provision block

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#123]
As the provision block is supposed to arrive as the first block in every hour, some clocks may be slightly out of sync and some validators may view this as arriving slightly before the hour? Maybe we should add a bit of leeway so that a block that was slightly before the hour of a local clock is accepted? Need to verify how this clock mechanism works for the provided time of a block

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/591

**Comment by alexanderbez** [comment]
The commands installed correctly based on the output you've provided. Double-check your GOPATH and PATH env variables.
