### ISSUE TITLE
Rest Api "/tx/coin/{account}" can't query transaction history of an account

### ISSUE THREAD

**Issue by zhiqiang-bianjie** [cosmos/gaia#124]
I used gaia2 to set up a local blockchain and send transactions are normal, but returned empty when using "/tx/coin/{account}" to query my transaction history. gaia2 public network test environment, the rest is normal, do we still need some other special configuration

**Comment by rigelrozanski** [comment]
Can you explain the exact commands (in order) you are using to recreate your error? Are you using REST?

**Comment by zhiqiang-bianjie** [comment]
@rigelrozanski ，Thank you for your answer。I have found the reason for the error, the following information is not configured in the config.toml file:
[tx_index]
index_all_tags = true.
