### ISSUE TITLE
Process improvements around provisioning and maintaining test instances

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1240]
## Summary

Process improvement to make sure that all DigitalOcean instances are tagged, by the team/user using them so that they can be traced and cleaned up systematically when not needed.

## Problem Definition

Dangling instances with test code are security issue and also rack up costs.

## Proposal

Align with other dev teams to find out what instances are still required & clean up unused ones.
Align on mechanism to identify what images on how to trace back images to their owner.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mmulji-ic** [comment]
@glnro please add documentation to hub-eng!

**Comment by mpoke** [comment]
No longer relevant as most nodes were shut down.
