### ISSUE TITLE
Rosetta Error 502 after upgrading to v6.0.0

### ISSUE THREAD

**Issue by panlilu** [cosmos/gaia#1241]
## Summary of Bug

Rosetta command returns 500 after upgrading to v6.0.0

## Version

v6.0.0

## Steps to Reproduce

1. Sync a v6.0.0 node via [State Sync](https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html#state-sync)
2. Enable Rosetta API according to the docs here: https://docs.cosmos.network/master/run-node/rosetta.html. 
3. Run with the rebuild v6.0.0 binary with command`./gaiad rosetta --network cosmoshub-4 --log_level trace --addr "0.0.0.0:8080" --grpc "127.0.0.1:9090" --tendermint "127.0.0.1:26657" --trace --blockchain COSMOS`
4. result
```
WARNING: The Rosetta server is still a beta feature. Please do not use it in production.
Error: rosetta: (502) bad gateway
Usage:
  gaiad rosetta [flags]

Flags:
      --addr string         the address rosetta will bind to (default ":8080")
      --blockchain string   the blockchain type (default "app")
      --grpc string         the app gRPC endpoint (default "localhost:9090")
  -h, --help                help for rosetta
      --network string      the network name (default "network")
      --offline             run rosetta only with construction API
      --retries int         the number of retries that will be done before quitting (default 5)
      --tendermint string   the tendermint rpc endpoint, without tcp:// (default "localhost:26657")

Global Flags:
      --home string         directory for config and data (default "/home/deploy/.gaia")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```

**Comment by glnro** [comment]
Hi @panlilu, you might want to check out [this conversation](https://github.com/cosmos/gaia/issues/1129#issuecomment-1016749195) for more context. Try disabling rosetta when starting up the node, and then turning it back on once you've synced.

**Comment by panlilu** [comment]
I'm not running the node in docker, so there is no option of "disabling rosetta".
The node is fully synced(via [State Sync](https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html#state-sync)) and have caught up with the main-chain.
Rosetta is run manually after the node synced.
I have read  the conversation mentioned.

**Comment by panlilu** [comment]
I think this issue is very similar to https://github.com/cosmos/cosmos-sdk/issues/10088

**Comment by okwme** [comment]
hey @fdymylja have you encountered this issue before?

**Comment by fdymylja** [comment]
> hey @fdymylja have you encountered this issue before?

pretty confident it's a connectivity issue on the gRPC/tendermint endpoints.

Are you sure the node is correctly exposed at the mentioned ip:port?

**Comment by panlilu** [comment]
change
--tendermint "127.0.0.1:26657"
to
--tendermint "localhost:26657"

and it's ok now

this config is working before v6.0.0

Thanks for the hint.
Issue closed.

**Comment by panlilu** [comment]
When I remove the  '--grpc "127.0.0.1:9090" '
it wait some seconds and return `Error: maximum number of retries exceeded, last error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address map[address:0.0.0.0:9090 enable:true]: too many colons in address"`

Change back to  '--grpc "127.0.0.1:9090" ' or '--grpc "127.0.0.1:9090" ' it fail with `Error: rosetta: (502) bad gateway` immediately.

When the node is down, it returns `Error: maximum number of retries exceeded, last error: rpc error: code = Unavailable desc = connection closed` after some seconds

**Comment by glnro** [comment]
When you go into `app.toml`, what values do you have for 'gRPC Configuration' ?

**Comment by panlilu** [comment]
@glnro 
```
###############################################################################
###                           gRPC Configuration                            ###
###############################################################################

[grpc]

# Enable defines if the gRPC server should be enabled.
enable = true

# Address defines the gRPC server address to bind to.
address = "0.0.0.0:9090"
```

**Comment by glnro** [comment]
@panlilu what are your seeds and peers in `config.toml`

**Comment by panlilu** [comment]
```
# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
seeds = "ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656,bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,585794737e6b318957088e645e17c0669f3b11fc@54.160.123.34:26656,df57f70cd3a104dcbd14d1aac9eb260c99a620e0@121.78.247.247:26656,11dfe200894f38e411beca77928e9dd118e66813@94.130.98.157:26656,5b4ed476e01c49b23851258d867cc0cfc0c10e58@206.189.4.227:26656,654f47a762c8f9257aef4a44c1fb5014916d8b20@99.79.60.15:26656,366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656,547bfac343b9b4bd54ce9cb891c4bca3db2a0922@157.230.116.241:26656,d6318b3bd51a5e2b8ed08f2e520d50289ed32bf1@52.79.43.100:26656,1bfda3d59e70290a3dada9bb809dd954371850d3@54.180.225.240:26656,6ee94c2093505e8790442c054e6e1e0211d36583@44.239.140.195:26656,ec779a2741da6dd2ccdaa6dfc0bebb10e595dfa4@50.18.113.67:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,047f723806ee702b211e7227f89eacd829aabd86@52.9.212.125:26656,b0e746acb6fbed7a0311fe21cfb2ee94581ca3bc@51.79.21.187:26656,82772547c4575c18dfe6e75aafe521cf7d4dc8de@142.93.157.186:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656"
# Comma separated list of nodes to keep persistent connections to
persistent_peers = "ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656,bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,585794737e6b318957088e645e17c0669f3b11fc@54.160.123.34:26656,df57f70cd3a104dcbd14d1aac9eb260c99a620e0@121.78.247.247:26656,11dfe200894f38e411beca77928e9dd118e66813@94.130.98.157:26656,5b4ed476e01c49b23851258d867cc0cfc0c10e58@206.189.4.227:26656,654f47a762c8f9257aef4a44c1fb5014916d8b20@99.79.60.15:26656,366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656,547bfac343b9b4bd54ce9cb891c4bca3db2a0922@157.230.116.241:26656,d6318b3bd51a5e2b8ed08f2e520d50289ed32bf1@52.79.43.100:26656,1bfda3d59e70290a3dada9bb809dd954371850d3@54.180.225.240:26656,6ee94c2093505e8790442c054e6e1e0211d36583@44.239.140.195:26656,ec779a2741da6dd2ccdaa6dfc0bebb10e595dfa4@50.18.113.67:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,047f723806ee702b211e7227f89eacd829aabd86@52.9.212.125:26656,b0e746acb6fbed7a0311fe21cfb2ee94581ca3bc@51.79.21.187:26656,82772547c4575c18dfe6e75aafe521cf7d4dc8de@142.93.157.186:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656"
```

**Comment by panlilu** [comment]
I start a new node sync without State Sync(https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html), and still got 502.

**Comment by glnro** [comment]
Hi @panlilu can you provide the exact steps you took to reproduce and the method you used to sync (you said you didn't use state sync...did you try blocksync or quicksync?).

You might also find https://hub.cosmos.network/main/getting-started/quickstart.html helpful.

**Comment by glnro** [comment]
Hi @panlilu , we'll close this issue in 24-48 hours if we don't hear back from you before then. If the issue persists we can always re-open.
