### ISSUE TITLE
wrong Block.Header.LastResultsHash

### ISSUE THREAD

**Issue by agouin** [cosmos/gaia#1242]
## Summary of Bug

Using `v6.0.0` on the vega testnet runs into periodic `precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.LastResultsHash` errors, requiring a newer snapshot or downgrading to `v6.0.0-rc3` to proceed. 

## Version

gaia - `v6.0.0`
chain-id: `vega-testnet` 

## Steps to Reproduce

- Run the vega testnet [example setup](https://github.com/cosmos/vega-test/tree/master/public-testnet#example-setup) using v6.0.0 for the GAIA_BRANCH, or any adaptation of it using the v6.0.0 gaia binary on the vega testnet. 
- After some time (8 hours in one case, other times was happening as often as every hour), the node will run into the error during runtime, but not panic. It stops syncing but does not exit. 

```
7:49PM ERR CONSENSUS FAILURE!!! err="precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.LastResultsHash.  Expected C6B1264BD64B0D1C182874D1115A4FF512D2EF60C828E87147556079F9B0A7BD, got 479AE77C9CE96CF310B0922601A65AA9854EB14CBA0A95B0B59EC78ED837DAA7"

goroutine 257 [running]:
github.com/tendermint/tendermint/blockchain/v0.(BlockchainReactor).poolRoutine(0xc000d15340, 0x1)
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(BlockchainReactor).SwitchToFastSync
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:125 +0xef
```

- Restarting the node results in an immediate panic
```
panic: Failed to process committed block (8535500:755D2FCF43A9507F7C61AF7140B9D0C41DE46CED718788EB53CF426784D10682): wrong Block.Header.LastResultsHash.  Expected C6B1264BD64B0D1C182874D1115A4FF512D2EF60C828E87147556079F9B0A7BD, got 479AE77C9CE96CF310B0922601A65AA9854EB14CBA0A95B0B59EC78ED837DAA7

goroutine 313 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0005d1a40, 0x1)
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:125 +0xef
```

The only way I found to recover using `v6.0.0` is to start fresh again, such as `unsafe-reset-all`, and waiting until the next 1000-block snapshot is available before starting the node again. 

On all 4 sentries I was running with this configuration, they all ran into this issue at the same blocks:
https://vega-explorer.hypha.coop/blocks/8516441
https://vega-explorer.hypha.coop/blocks/8533528
https://vega-explorer.hypha.coop/blocks/8534754
https://vega-explorer.hypha.coop/blocks/8535500
https://vega-explorer.hypha.coop/blocks/8541719

I then tried downgrading to `v6.0.0-rc3`, and it was able to proceed past the error block without an `unsafe-reset-all`, and without a new snapshot.

This leads me to suspect that the issue stems from [6ed5b73](https://github.com/cosmos/gaia/commit/6ed5b7397a57c42112cf1b16f550bd0a6e263953) since that is the only change between `v6.0.0-rc3` and `v6.0.0`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jackzampolin** [comment]
Here is the major change from that PR:

https://github.com/cosmos/cosmos-sdk/blob/b6c77e6c819f8a51166649eaef125d1bfb276f04/x/auth/ante/setup.go#L32

**Comment by glnro** [comment]
Hi @agouin , the official release branch for Vega is `v6.0.0-rc3`, so you would need to sync from scratch with the correct version of `gaiad`...see the Hub docs on [using state sync when joining the vega testnet](https://hub.cosmos.network/main/hub-tutorials/join-testnet.html#state-sync).

**Comment by yaruwangway** [comment]
Hi @agouin , yeah, so you can see, the v6 release has some changes from v6 rc3, this is because we have to migrate auth module after staking.
so please use v6-rc3 on vega testnet. for mainnet, you can use v6.0.0

**Comment by agouin** [comment]
Thanks for confirmation that this is expected behavior. Closing!
