### ISSUE TITLE
github actions cleanup

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1247]
## Proposal

* remove export and import
  * not how we do ugrades anymore
* non-determinism is commented out, should be added back
  * actually it's in the releas-sims file so it's ok
*  put all the sim stuff in one file
* maybe remove labeled
  * only runs when the sim label is there (PR without the "sim" label it will kick it off)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tokamak-git** [comment]
@mmulji-ic im kinda already doing this, guess it would make sense for me add this to my sprint goals?

**Comment by mmulji-ic** [comment]
@tokamak-git yep, please do.

**Comment by tokamak-git** [comment]
Update: 

- After investigation and debugging it looks like there may be a bug in the `sims.yml` for our actions.
  - This is a peculiar behavior that makes local testing tedious and time consuming.
- Have created a readme for actions as part of #916 
  -  it would make sense to add similar information for other actions.
  
  @mmulji-ic do these seam like areas we would like to prioritize ?
