### ISSUE TITLE
create end to end tests

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1248]
## Summary

@alexanderbez  to send initial links to versions we can use as starting points

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mmulji-ic** [comment]
Closing in favour of [Integrate ICA testing into CI pipeline](https://github.com/cosmos/gaia/issues/1360) & #1361
