### ISSUE TITLE
An account with a balance of 0 can also initiate a commission transaction and the transaction is included in the block？

### ISSUE THREAD

**Issue by zhiqiang-bianjie** [cosmos/gaia#125]
I created a new account with a balance of 0. But when the delegate function was called, the check_tx process passed, the error "No such account" occurred during the deliver_tx phase, and the transaction was also included in the block. Why not check the account information in the check_tx stage, if the balance is not enough, return the error directly. Is this a bug?

**Comment by rigelrozanski** [comment]
An account does not exist if it has a zero balance. Nothing is recorded to state until there is balance. There have been problems with checking the account balance at the CheckTx stage with constraints of the old SDK, hopefully should be mitigated during the port to new SDK in gaia-4.

I'm going to leave this issue open for gaia-4 port, Thanks

**Comment by zhiqiang-bianjie** [comment]
ok,I understand

**Comment by zramsay** [comment]
closing as obsolete. please re-open in SDK repo if still applicable
