### ISSUE TITLE
release gaia v6.0.1, 6.0.4

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1252]
## Summary

there are a number of PRs that should be included in a non-state breaking patch release of gaia.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
I think these should probably be included:
* https://github.com/cosmos/gaia/commit/60eff8e3e7635ed57b2c758f200495eaaae70cca
* https://github.com/cosmos/gaia/commit/7210515cacab36043eb55b65aaa82ab8e371d2f4
* https://github.com/cosmos/gaia/commit/fa98d2255cfc909f98679974c9f5a2a50547aa45
* https://github.com/cosmos/gaia/commit/1dcab2873d6ced6f8abf84a2d18183180dee6e91
* https://github.com/cosmos/gaia/commit/4aea4169e10b9304dcc0bf535ffe7ce93e8b3348
* https://github.com/cosmos/gaia/commit/1bcbf62950eabcf627ed586416779f6e5469ad7c
* https://github.com/cosmos/gaia/commit/e287dbf8cc903289af5839f05db9064b3c25b3b2
* https://github.com/cosmos/gaia/commit/e3e241f476d0c2ea107adb3d1c908de406889066
* https://github.com/cosmos/gaia/commit/5bf3ec33b9f26b027b9d675818223da7867e2c24
* https://github.com/cosmos/gaia/commit/a4d718e2931a3ce0a353d2e4df05b962c758beab
*

**Comment by yaruwangway** [comment]
without https://github.com/cosmos/gaia/commit/1bcbf62950eabcf627ed586416779f6e5469ad7c, gaia v7 will use tendermint 0.34.14 due to sdk v0.45.1 uses tendermint 0.34.14, so v6 should not bump to tendermint v0.34.15

**Comment by yaruwangway** [comment]
same reason for removing https://github.com/cosmos/gaia/commit/e3e241f476d0c2ea107adb3d1c908de406889066
