### ISSUE TITLE
help  help help !

### ISSUE THREAD

**Issue by wadelee1986** [cosmos/gaia#126]
who can give me some test coins？

67BC923D87FA4B902E17CF73E949C36232E4D657

**Comment by rigelrozanski** [comment]
are you a human :P  => do you keep getting that error when you retry?

**Comment by wadelee1986** [comment]
yes, every time.

**Comment by greg-szabo** [comment]
Did you disable ad blockers in the browser?
The site uses Google's Recaptcha and it works for me. Something is wrong with your computer according to Google.

**Comment by wadelee1986** [comment]
@greg-szabo 

thank you, 
I am from China, can't access google  services.

**Comment by wadelee1986** [comment]
@greg-szabo

Can you help me  Get some tokens ?

D4AD345BA1E707E9732FD12BF8CE2E67F2768DB3

**Comment by krisrp** [comment]
@wadelee1986 

I sent you 25 tokens.

**Comment by wadelee1986** [comment]
@krisrp 

I have received it .
Thank you.
