### ISSUE TITLE
Setup Cosmos Hub container registry

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1263]
Where to host ?
Github registry / Docker Hub registry?

**Comment by pratikbin** [comment]
I would consider docker hub, cause then people that are using organization wide docker registry cache can benefit from it.

You can also host it on both.

**Comment by tokamak-git** [comment]
Hey folks, have configured ghcr: `GitHub container registry` and have been able to push an image to it aswell under the cosmos branding.

Shall close this if no further investigation/modification is required.

**Comment by mmulji-ic** [comment]
@tokamak-git @okwme - any idea who owns this repo? https://hub.docker.com/u/interchain

**Comment by bert2002** [comment]
Are you going to publish more updated docker images in the future?
