### ISSUE TITLE
Create Archive Node Setup for Cosmos hub 4

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1264]

**Comment by glnro** [comment]
For volume size see https://quicksync.io/networks/cosmos.html

**Comment by tokamak-git** [comment]
Hey @mmulji-ic noticed we changed the sprint for this ticket
Shall I move on for this at the moment?

**Comment by faddat** [comment]
#1415 is related to this work

**Comment by mmulji-ic** [comment]
@tokamak-git discussed with @glnro, we can close this.
