### ISSUE TITLE
Add Archive Node for Cosmoshub-3

### ISSUE THREAD

**Issue by tokamak-git** [cosmos/gaia#1269]
Acceptance Criteria

- [x] Boostrap Node
- [x] Setup Grafana
- [x] Test - Query first & last 10 blocks
- [x] Firewall enabled

**Comment by glnro** [comment]
RPC Endpoint https://rpc-cosmoshub-3.interchain.io/
Rest Endpoint https://rest-cosmoshub-3.interchain.io/node_info

[Grafana Node Exporter Dashboard](https://mission-control.cosmoshub.interchain.io/d/EQ4YHuynk/node-exporter-cosmoshub-archives?orgId=1&refresh=5s&var-DS_PROMETHEUS=default&var-job=cosmoshub-3-archive-node&var-node=161.35.29.223:9100&var-diskdevices=%5Ba-z%5D%2B%7Cnvme%5B0-9%5D%2Bn%5B0-9%5D%2B)
