### ISSUE TITLE
gaiad runtime error

### ISSUE THREAD

**Issue by simpleshark** [cosmos/gaia#127]
![图片](https://user-images.githubusercontent.com/53416922/64937080-6b136e00-d88b-11e9-8fc5-6e1257730b3e.png)

gaiad version is 2.0.0,and genesis.json is copying from 'https://raw.githubusercontent.com/cosmos/launch/master/genesis.json'

**Comment by alexanderbez** [comment]
Please read the disclaimer in the readme. Also, the [launch repo](https://github.com/cosmos/launch).
