### ISSUE TITLE
Setup Nginx and sentry nodes for archive nodes

### ISSUE THREAD

**Issue by tokamak-git** [cosmos/gaia#1270]

**Comment by okwme** [comment]
should be able to look at the nginx config in vega-rpc.interchain.io for example nginx files with certbot and proxy redirect for specific ports

**Comment by okwme** [comment]
maybe add an example of the nginx file as a template to our docs somewhere

**Comment by okwme** [comment]
DNS - points to IP address of server with each relevant subdomain
one NGINX file on server for each subdomain
NGINX file reverse proxy to the open ports locally
make sure there's configuration for the following four:
* RPC
* REST
* WS
* gRPC

**Comment by okwme** [comment]
Future improvements could include:
* https://nginxproxymanager.com
* https://traefik.io/

**Comment by mmulji-ic** [comment]
Currently only for internal use, external use cases should wait till after Rho.
