### ISSUE TITLE
Add SSL subdomain with nginx proxy redirect to serve gRPC

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1273]
## Summary

gRPC doesn't work without SSL/TLS. Certbot doesn't work on bare IP addresses. We should set up a new subdomain for our cosmoshub-4 archive node that correctly exposes port 9090 (gRPC) so that it's publicly accessible. This will be useful for relayers as @charleenfei has informed me.

we need to set up NGINX with various subdomains we want to use to expose various ports. @yaruwangway did something simialr already for the vega testnet. We should do it as well for port 9090 with a subdomain like `grpc-cosmoshub-4.interchain.io`. This could go into the scope of #1264 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
@okwme There's an existing ticket under the main story for all of these endpoints, let's consolidate and add this to the acceptance criteria of https://github.com/cosmos/gaia/issues/1265

**Comment by glnro** [comment]
There's a second story for configuring nginx https://github.com/cosmos/gaia/issues/1270

**Comment by okwme** [comment]
good call @glnro !
commented on both issues, will close this one now
