### ISSUE TITLE
Error in quickstart instructions

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1276]
## Summary of Bug

trying out the step for applying sed to the genesis file:
```
> sed -i 's/minimum-gas-prices = ""/minimum-gas-prices = "0.001uatom"/' app.toml
```
but i get this error:
```
sed: 1: "app.toml": command a expects \ followed by text
```

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
same goes for 
```
sed -i 's/persistent_peers = ""/persistent_peers = "6e08b23315a9f0e1b23c7ed847934f7d6f848c8b@165.232.156.86:26656,ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656,538ebe0086f0f5e9ca922dae0462cc87e22f0a50@34.122.34.67:26656,d3209b9f88eec64f10555a11ecbf797bb0fa29f4@34.125.169.233:26656,bdc2c3d410ca7731411b7e46a252012323fbbf37@34.83.209.166:26656,585794737e6b318957088e645e17c0669f3b11fc@54.160.123.34:26656,5b4ed476e01c49b23851258d867cc0cfc0c10e58@206.189.4.227:26656"/' config.toml

```
with error
```
sed: 1: "config.toml": command c expects \ followed by text
```

**Comment by glnro** [comment]
I actually JUST ran into this...it's a mac thing...can update with a commend for mac users

**Comment by okwme** [comment]
looks like in the https://github.com/cosmos/vega-test/blob/master/local-testnet/README.md docs there's a misisng single quote like this:

```
sed -i '' 's/minimum-gas-prices = ""/minimum-gas-prices = "0uatom"/g' $HOME/config/app.toml
```

**Comment by okwme** [comment]
is that just for macs?

**Comment by glnro** [comment]
Add two single quotes after the i flag `sed -i''  's/minimum-gas-prices = ""/minimum-gas-prices = "0.001uatom"/"'' app.toml`

https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

**Comment by glnro** [comment]
I guess it depends on the machine of the original author...could be a good ticket to add to the backlog to run everything on a mac as well to see if we run into similar issues...we do specify in installation the instructions are assuming an ubuntu dist but there's no reason to not also include instructions for mac

**Comment by okwme** [comment]
good call
also added `$HOME/.gaia/config/` to the end of the commands so it's not dependent on them being in the right directory:
https://github.com/cosmos/mainnet/pull/161

**Comment by okwme** [comment]
also need to make sure that the link to QuickStart in https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html is updated. It's currently pointing to a specific commit.

**Comment by glnro** [comment]
> good call also added `$HOME/.gaia/config/` to the end of the commands so it's not dependent on them being in the right directory: [cosmos/mainnet#161](https://github.com/cosmos/mainnet/pull/161)

There's a line above that block that has the user cd'ing into that directory before executing everything...if we do that then that line can be removed

**Comment by glnro** [comment]
> also need to make sure that the link to QuickStart in https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html is updated. It's currently pointing to a specific commit.

I can push that change unless you're already on it in https://github.com/cosmos/mainnet/pull/161
