### ISSUE TITLE
Documentation returns 404

### ISSUE THREAD

**Issue by julienrbrt** [cosmos/gaia#1281]
## Summary of Bug

The Cosmos Hub documentation seems misconfigured / offline.
It's returning a 404 on all pages.

## Version

N/A

## Steps to Reproduce

- Visit <https://hub.cosmos.network>

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @julienrbrt Thanks for submitting we're working on this to restore as soon as possible 🤞

**Comment by glnro** [comment]
@julienrbrt Docs are live again, closing for now but feel free to reopen if you have an additional concern
