### ISSUE TITLE
ERROR: unrecognized concrete type name auth/Account

### ISSUE THREAD

**Issue by dev-lc** [cosmos/gaia#129]
## Summary of Bug

I created a new account by gaiacli from [master branch](https://github.com/cosmos/gaia) (old version, I don't remember the exact commit. It was on 16 Aug 2019).
Now I'm trying to query the state of my account but get the error.

What I also tried: 
-- I performed a checkout with the commit 72a5f93, builded the tools (origin keys db was on my disk). Result the same.
-- Using version v2.0.0, I restored keys using the mnemonic (it was successful). But querying provides the same error.

## Version

name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.0
commit: 3c70fee433956ba32e35705193a5f7a7d5b63277
build_tags: netgo,ledger
go: go version go1.13 linux/amd64

## Steps to Reproduce

```
root@cosmos-atom:# gaiacli config
chain-id = "cosmoshub-2"
node = "https://cosmoshub-rpc.chainlayer.net:443"
trust-node = true

root@cosmos-atom:# gaiacli query account cosmos1g4uk7a7z08ghkqgaw77sd0h9dc0cuvvjt0dc39
ERROR: unrecognized concrete type name auth/Account
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Again, comoshub-2 (mainnet) works with v0.34.7 and not v2.0.0. Please review the README :)
