### ISSUE TITLE
Regression between 0.34.3 and 0.34.4 for displaying keys from gaiacli

### ISSUE THREAD

**Issue by jleni** [cosmos/gaia#13]
## Summary of Bug
Linked to https://github.com/cosmos/ledger-cosmos/issues/144

> Displaying my key on the device with gaiacli works on v0.34.3 but not on v0.34.4
> gaiacli version
> 0.34.3-107-g829ce17d0
> gaiacli keys show -d zaki-ledger
> NAME:	TYPE:	ADDRESS:					PUBKEY:
> zaki-ledger	ledger         xxx                                         xxx
> Keys is displayed on the ledger
> 
> gaiacli version
> 0.34.4
> NAME:	TYPE:	ADDRESS:					PUBKEY:
> zaki-ledger	ledger  xxx   xxx
> ERROR: [APDU_CODE_INS_NOT_SUPPORTED] Instruction code not supported or invalid
> Key is not displayed on the ledger.
> 

Environment info:
> Nano S
> Cosmos App V1.5
> Mac OS
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jleni** [comment]
Ok, I have analysed the issue. Here are my findings:

This is the PR to add support for v1.5.0 https://github.com/cosmos/cosmos-sdk/pull/4227
While it was merged into master before the release of Cosmos App v1.5.0, I seems it did not make the cut for v0.34.4

At the moment:

| gaiacli  | cosmos app v1.1.1 | cosmos app v1.5 | cosmos app v1.5.2 (not released)|
| ------------- | :-------------: |:--:|:--:|
| v0.34.3  | :white_check_mark:  |  |
| v0.34.4  | :white_check_mark:  |  |
| master  | :white_check_mark:  | :white_check_mark: | :white_check_mark:
| device menu  |  |  | :white_check_mark:

@jackzampolin should we have a 0.34.5 with App v1.5 support or master will be soon released as 0.35.x ?

**Comment by alexanderbez** [comment]
Correct, this was recently updated...way after 0.34.4 was released. We have merged PRs marked for a next point release: https://github.com/cosmos/cosmos-sdk/pulls?q=is%3Apr+label%3Anext-minor-release+is%3Aclosed

I'm not sure if/when we plan on doing this? The goal was bi-weekly. I can get started on it this week.

**Comment by jleni** [comment]
Closing now that 0.34.5 is available
