### ISSUE TITLE
Add Grafana dashboards and document onboarding for new services

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1312]
## Summary

Add Grafana dashboarding.
Dashboard Application/Server status.
Implement alerting.
Document so that onboarding of new services can be accelerated.

## Problem Definition

Require insight into application and machine status to be able to take proactive maintenance steps.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
This is basically almost done
