### ISSUE TITLE
Can't move funds

### ISSUE THREAD

**Issue by valuead** [cosmos/gaia#133]
Gaia 3002
I can NOT move tokens in the same node 
root@ip-172-31-1-171:~# gaia client tx send --amount=1fermion --name=Cosmosdrom1 --to=530B5DD6C8EFB3CC95F57DECD6A0E8A23B807D51
**ERROR: (20) Invalid address**

root@ip-172-31-1-171:~# gaia client keys list
All keys:
Cosmodrom1	3D3EB9CCFFCA8C1E3347206259939BE0CCB31D4C
Cosmodrom2	D8562AD2E98A5408CAEDEB111F450BCAF8B74C7E
Cosmodrom3	530B5DD6C8EFB3CC95F57DECD6A0E8A23B807D51

**ERROR: (20) Invalid address when i try to move from Cosmodrom1 to any of two**
root@ip-172-31-1-171: ~ # gaia client query account 3D3EB9CCFFCA8C1E3347206259939BE0CCB31D4C
{
"height": 28890,
"data": {
"coins": [
{
"denom": "fermion",
**"amount": 99**
}
],
"credit": []
}
}
root@ip-172-31-1-171:~ # gaia client query account D8562AD2E98A5408CAEDEB111F450BCAF8B74C7E
**ERROR: Account bytes are empty for address D8562AD2E98A5408CAEDEB111F450BCAF8B74C7E**
root@ip-172-31-1-171:~# gaia client query account 530B5DD6C8EFB3CC95F57DECD6A0E8A23B807D51
**ERROR: Account bytes are empty for address 530B5DD6C8EFB3CC95F57DECD6A0E8A23B807D51**
1+JHC
why second and third is not returning standard responds with the "amount": 0 ???

**Comment by zramsay** [comment]
`Account bytes are empty` is the (admitedly vague) error message for `"amount": 0`. Please open an issue in SDK repo if still relevant
