### ISSUE TITLE
Gaiad completion script

### ISSUE THREAD

**Issue by tokamak-git** [cosmos/gaia#1331]
Gaiad has been build using cobra, which offers a good built in completion script generator.
I have been able to use this script as a plugin for 0h-my-zsh.

It would be good to have this as a dedicated plugin on the hmz official repository, plus to have instructions to setup this script for new users.

Furthermore we could explore the auto generated script itself and add features to it as required.

**Comment by tokamak-git** [comment]
have created a fork and experimented with running this via local installation. 
 
 Current status:
 Able to use gaiad completion
 
 Experiment:
 used a similar solution for the new ignite cli and found we can configure that as well.
 
 questions  @okwme:
- do you think it would make sense to write a combined completion engine?
- if yes what tools should be included?
- this would lead to a section regarding configuration and setup in our docs. Thus do you think this completion should live in gaia? or do you think it makes sense to create a dedicated repository for this?

**Comment by yaruwangway** [comment]
Hi @tokamak-git , what do you mean by combined completion engine ? can you link your experiment code here ? thanks!

**Comment by tokamak-git** [comment]
Closing this for the time-being as its being de-prioritize.

**Comment by MSalopek** [comment]
Closing as related PRs were closed. Will re-open in case of increased interest.
