### ISSUE TITLE
Gaia should expose it's own http endpoints

### ISSUE THREAD

**Issue by zmanian** [cosmos/gaia#134]
Gaia should expose http endpoints for things like getting IBC packets + proofs, and querying account state and possibly sendtx if this superior to tendermint endpoints. If the tenderment RPC on 46657 can be extended do that, otherwise perhaps run a server on 46658. This will simplify things for hosted wallet implementers and other integrators.

**Comment by adrianbrink** [comment]
I am in favour of extending the Tendermint RPC either directly or through the `query` endpoint. Allowing the application to expose an RPC server directly is a slippery slope, that might cause a lot of problems. The only endpoints that the application can safely expose are read-only ones, e.g. it could expose an endpoint to read from the state but it can't allow writing. If the app server allows writing we need to route that write through consensus.

I am in favour of putting all reading functionality behind the query endpoint and not having the application a single server besides the abci server.

**Comment by zmanian** [comment]
I haven't looked at the code but I think the Query endpoint could allow delegation to the abci app instead of directly reaching into the state tree.

On the whole, I don't understand the query endpoints capabilities well enough.

**Comment by zmanian** [comment]
wait I forgot about `gaia rest-server`
