### ISSUE TITLE
notice: upgrade from v6 to theta v7 on testnet

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1342]
## Summary of Bug
upgrade with **cosmovisor autodownload**:

if upgrade from v6.0.0 to v7, please use cosmovisor v0.1
if upgrade from v6.0.4 to v7, can use cosmovisor latest version.

v6.0.0 uses sdk 0.44.3 while v6.0.4 uses sdk 0.44.5, cosmovisor   (version > 0.1 )with auto-download enabled only support cosmos-sdk (version> 0.44.3).

This also applies on mainnet.
ref: https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor

@uditvira  thank you for testing!

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
this is completed but in a PR that is waiting to be merged until the theta upgrade happens:
https://github.com/cosmos/gaia/pull/1372/files

**Comment by yaruwangway** [comment]
ok, i see, so **before** livehub use the new major release, 
docs related to new release and code influence binary build should target `Theta-main`, other docs and tests can be targeting `main` or `Theta-main`(we anyway cherry pick later) 

Is this correct? @okwme
