### ISSUE TITLE
Missing address in signing_infos of rest api

### ISSUE THREAD

**Issue by liangping** [cosmos/gaia#1344]
## Summary of Bug

visit: https://cosmos.api.ping.pub/cosmos/slashing/v1beta1/signing_infos
```
  "info": [
    {
      "address": "",   ADDRESS SHOULD NOT BE EMPTY.
      "start_height": "0",
      "index_offset": "13174927",
      "jailed_until": "1970-01-01T00:00:00Z",
      "tombstoned": false,
      "missed_blocks_counter": "0"
    },
    {
      "address": "", ADDRESS SHOULD NOT BE EMPTY.
      "start_height": "0",
      "index_offset": "13174927",
      "jailed_until": "1970-01-01T00:00:00Z",
      "tombstoned": false,
      "missed_blocks_counter": "40"
    },
    {
      "address": "cosmosvalcons1qrxwan7srvknxwsm264l0nlc56uw6fd3mq0s7v",
      "start_height": "4211581",
      "index_offset": "3958948",
      "jailed_until": "1970-01-01T00:00:00Z",
      "tombstoned": false,
      "missed_blocks_counter": "26"
    },
```

## Version

"cosmos_sdk_version":"v0.44.3"

## Steps to Reproduce

Not see this issue on other blockchains: like Osmosis

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
Hello @liangping thanks for posting! This is an issue with the Cosmos SDK. Could you please re-open at https://github.com/cosmos/cosmos-sdk?

**Comment by okwme** [comment]
actually made it for you already @liangping  https://github.com/cosmos/gaia/issues/1734
