### ISSUE TITLE
Integrate IBC packet forwarding into CI pipeline

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1361]
Initially see script from Justin:
https://github.com/cosmos/relayer/blob/justin/ibc-router-demo/dev-env-demo

Also take a look at IBC testing repo from Strangelove:
https://github.com/strangelove-ventures/ibc-test-framework

**Comment by okwme** [comment]
this should be possible by using our current E2E setup, where we send a token from chain a to chain b which is forwarded back to chain a. the middleware doesn't care if the third chain is actually the same as the first and the feature can be tested this way without creating a third blockchain in our E2E.

**Comment by okwme** [comment]
#1797
