### ISSUE TITLE
send error

### ISSUE THREAD

**Issue by ItsFunny** [cosmos/gaia#1366]
## Summary of Bug

gaiad tx bank send user cosmos17uvs0kp87z25ys5343ssvj3xjpqjpnkyxxfaev 1000samoleans  --home ./data/ibc-0 --keyring-backend="test"

## Steps to Reproduce
gaiad tx bank send user cosmos17uvs0kp87z25ys5343ssvj3xjpqjpnkyxxfaev 1000samoleans  --home ./data/ibc-0 --keyring-backend="test"

gaiad tx bank send user cosmos17uvs0kp87z25ys5343ssvj3xjpqjpnkyxxfaev 1000samoleans  --home ./data/ibc-0 --keyring-backend="test"
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @ItsFunny can you explain what the error is that you're experiencing?

**Comment by yaruwangway** [comment]
Hi, please try to add `--from` and your sender should be the address of sender, not the key name,
or you did `export user=` ?

**Comment by yaruwangway** [comment]
Hi, sry, my misunderstanding, sender can be the key name.

**Comment by yaruwangway** [comment]
> Hi, please try to add `--from` and your sender should be the address of sender, not the key name, or you did `export user=` ?

Hi, sry, my misunderstanding, sender can be the key name.

**Comment by ItsFunny** [comment]
sorry for my mistake ,i failed because of mismatching the --node 
:-(
