### ISSUE TITLE
2nd redelegation bonding time

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1376]
## Summary
Right now, in cosmoshub, if a delegator redelegates, it can happen immediately. But if the delegator wants to redelegate again, the delegator has to wait 3weeks. 

The second time redelegation should happen immediately as well specially when the validator is jailed. 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
This is from the feedback of community channel. 

why the unbonding period of the 2nd redelegation has to wait 3 weeks ?
can we make the 2nd redelegation gas higher to avoid the problems that long unbonding period solves?

**Comment by okwme** [comment]
this is an SDK issue for the staking module, we should create an issue there, reference this one and close it here. @yaruwangway can you do that?

**Comment by yaruwangway** [comment]
This design is for not allow delegators to redelegate each time so quickly to avoid slashes and other things related to the validators.
