### ISSUE TITLE
workflow: automating the release process and the upgrade proposal generation

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1377]
## Summary

automation of the release process:

- [ ] publish the release note draft automatically from a file called RELEASE_NOTE once the tag is pushed.
- [ ] generate an upgrade proposal from a file once the tag is pushed. This is more for moving all the the binary links and checksums to the upgrade proposal for cosmovisor users using auto-download 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
this is done as of cosmos/gaia#1378  🎉

the generation proposal will remain open in issue cosmos/hub-eng#21
