### ISSUE TITLE
Cosmos SDK Upgrade

### ISSUE THREAD

**Issue by philipjames44** [cosmos/gaia#1379]
## Summary
Upgrade cosmos sdk to v0.45.1 from 0.44.6

## Problem Definition
Some authz bug fixes were introduced in cosmos sdk v0.45 so it would be great to loop them in so nodes can leverage authz use cases.

## Proposal

Upgrade to version 0.45.1 in https://github.com/cosmos/gaia/blob/main/go.mod#L6
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hey @philipjames44 this is planned in https://github.com/cosmos/gaia/releases/tag/v7.0.0
