### ISSUE TITLE
Release 7.0.1 meta issue

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1386]
## Meta Issue for next minor release after Theta.

Issues to be included:
- [ ]  [#1305 update tendermint and tm-db. remove gorocksdb replace](https://github.com/cosmos/gaia/pull/1305 )
- [ ] [#1387 Bump the tendermint version to v0.34.17] (https://github.com/cosmos/gaia/pull/1387)

**Comment by yaruwangway** [comment]
also this one 
https://github.com/cosmos/gaia/pull/1387
