### ISSUE TITLE
Scripts and proceedure for backups

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/gaia#139]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
Hey @jackzampolin not a lot of context here. This still up to date or can I close?

**Comment by okwme** [comment]
closing now please open with more context if this is still a relevant issue @jackzampolin
