### ISSUE TITLE
Panic occurred after upgrading to v0.37

### ISSUE THREAD

**Issue by freddieee** [cosmos/gaia#140]
`
I[2019-09-24|22:36:55.624] Starting ABCI with Tendermint                module=main 

I[2019-09-24|22:36:56.858] Starting multiAppConn                        module=proxy impl=multiAppConn

I[2019-09-24|22:36:56.858] Starting localClient                         module=abci-client connection=query impl=localClient

I[2019-09-24|22:36:56.858] Starting localClient                         module=abci-client connection=mempool impl=localClient

I[2019-09-24|22:36:56.858] Starting localClient                         module=abci-client connection=consensus impl=localClient

I[2019-09-24|22:36:56.858] Starting EventBus                            module=events impl=EventBus

I[2019-09-24|22:36:56.858] Starting PubSub                              module=pubsub impl=PubSub

I[2019-09-24|22:36:56.868] Starting IndexerService                      module=txindex impl=IndexerService

I[2019-09-24|22:36:56.868] ABCI Handshake App Info                      module=consensus height=0 hash= software-version= protocol-version=0

I[2019-09-24|22:36:56.868] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
panic: json: cannot unmarshal object into Go value of type string
`

I followed the instructions completely and got this error after I start the node, the go version is v0.13,
Also, when I try to run 
`
gaiad migrate v0.37 cosmoshub_2_genesis_export.json --chain-id=cosmoshub-3 > genesis.json
`
it did not pass, so I have to migrate to v0.36

**Comment by alexanderbez** [comment]
Fixed in https://github.com/cosmos/cosmos-sdk/pull/5099
