### ISSUE TITLE
Integrate Min Fee module

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1429]

**Comment by mmulji-ic** [comment]
@okwme is this fixed the sdk change that Bez is making atm, that is scheduled for 7.0.2?

**Comment by mmulji** [comment]
Indeed @okwme this was done for 7.0.2, as a result closing.

**Comment by yaruwangway** [comment]
this is not finished yet.

**Comment by yaruwangway** [comment]
this refers to  global min fee or some other features?
