### ISSUE TITLE
Migration Testing

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/gaia#143]
## Summary / Problem Definition

Between major version of Gaia, and by proxy the SDK, where genesis state breaks, a migration is required via `gaiad migrate`. This process is critical to successful upgrades. However, testing these migrations on the exported state of Gaia is extremely manual and prone to error (e.g.  human forgetting to execute testing). The failed cosmoshub-3 upgrade is an example of this.

## Proposal

I propose we introduce two testing suites to alleviate the issue:

1. Implement a tool/script through Docker that starts with a static v0.34.x (since this is the min version we support for migration) genesis file and loops through all major versions, calls `migrate` and finally starts a localnet. Add this as a CI job.

2. Similar to (1), perform the same process with the same tool but with an exported mainnet genesis state. This will require modifying powers and key pairs so the network can start.

/cc  @mircea-c @zmanian @jackzampolin @marbar3778 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
This isn't as high priority as we currently can emulate this via simulation on migrated mainnet state through a slack bot.

**Comment by zmanian** [comment]
I think the community is planning to implement 2
