### ISSUE TITLE
Integrate Global Fee module

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1431]

**Comment by yaruwangway** [comment]
Global fee is to set up a global fee that all tx has to satisfy unless the msg type is in bypass msg types config.
Here is a few scenarios:
- `min_gas_price = 1stake`, `globalfee = [2stake, 2photon]`, tx with `gas-price = 1stake`, fail
- `min_gas_price = 1stake`, `globalfee = [2stake, 2photon]`, tx with `gas-price = 2stake`, pass
- `min_gas_price = 1stake`, `globalfee = [2stake, 2photon]`, tx with `gas-price =2photon` fail ? 

@okwme is this correct? this means (fees_paid  > min_gas_price && fees_paid > one of globalfees) right ?

**Comment by okwme** [comment]
once global fee is added, min_gas_price will be obsolete. it will no longer be on a node by node basis to set min_gas_price but instead that value comes from the global fee instead.

**Comment by yaruwangway** [comment]
so if`globalfee = []`, then we still check min-gas price ?

actually present bypass decorator will check and deduct fees if not bypass fee. 
so there is a moment (before gov proposal settingup globfee) we will have min_gas_price  = some value and globalfee = []. 

That means we still keep the min_gas_price checks, but before this, we check if there is global fee is empty
if global fee empty, check min gas price
if global fee nonempty, skip min gas price check, right ?

**Comment by okwme** [comment]
no we should configure a default value for globalfee so that it is never empty. It should begin with `0uatom` as the fee.

**Comment by yaruwangway** [comment]
@okwme  
if the globalfee=0uatom, do we still check min gas price in app.toml ?

and we later change to a non zero global fee by gov proposal right?

**Comment by yaruwangway** [comment]
it is about the transition period we have gobal fee module but not using it. we use min gas price. we need to have a logic there switch min gas price to global fee if the gov propobal passed, otherwise , still use min gas price.

**Comment by yaruwangway** [comment]
> once global fee is added, min_gas_price will be obsolete. it will no longer be on a node by node basis to set min_gas_price but instead that value comes from the global fee instead.

this means we do not let node to config their own gas price? even they want to be higher than global fee ?
