### ISSUE TITLE
Update of liquidity module to v0.46

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1435]

**Comment by faddat** [comment]
shouldn't we remove the liquidity module?

**Comment by okwme** [comment]
can't remove liquidity yet, still funds in pools. Crescent working on removing the rest and force ejecting the rest in a future upgrade @faddat .

this issue is partially solved with PR #1482. It's just an alpha release so can't close completely but underway

**Comment by jaybxyz** [comment]
Yeah, as @okwme replied, funds are still in pools at this time. To give you an update, we have some statistics. At the time of writing, there are 13041 addresses that still hold pool coin(s) and they worth about $1144. We've implemented force withdrawal functionality and right now we're simulating it to make sure that it is implemented in a right way and throughly tested.

**Comment by mmulji-ic** [comment]
@okwme still in Rho?

**Comment by okwme** [comment]
just updated from @dongsam :
https://github.com/Gravity-Devs/liquidity/releases/tag/v2.0.0-rc2

**Comment by okwme** [comment]
hi @dongsam is there a final release of v2 now that cosmos sdk v0.46 is out?

**Comment by dongsam** [comment]
@okwme 
https://github.com/Gravity-Devs/liquidity/releases/tag/v2.0.0 
Here is the final release v2.0.0, which is using cosmos-sdk v0.46.0

**Comment by okwme** [comment]
thank you @dongsam !
closed with #1496

**Comment by okwme** [comment]
hi @kogisin any update on the changes needed for the removal of the module?

**Comment by jaybxyz** [comment]
Hey @okwme,

The removal of the module can be accomplished after forcefully withdrawing all pool coins that exist in the Cosmos Hub and we’ve gathered necessary statistics (how much worth of pool coins are out of Cosmos Hub, a number of addresses that hold pool coins, and etc) and implemented to test the force withdrawal functionality by forking Gaia to see if it works in May 20th. We will need to run this again when the time is planned out. 

If I remember correctly from the last conversation, there needs to be a separate plan after the Rho Upgrade. We’re thinking of having an on-chain upgrade governance proposal to forcefully withdraw all pool coins in the Hub and we are planning to implement the functionality in Gaia after the Rho upgrade. So, we are constantly keeping on our eyes on [this issue](https://github.com/cosmos/gaia/issues/1535) to track how much work leftover before the Rho Upgrade. Can you give us an estimate timeline for the Rho upgrade?

I think it will be better to create a separate issue just for this or create a Slack channel to discuss further offline.
