### ISSUE TITLE
CI settings prevent updates to older gaias

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1449]
## Summary of Bug

* https://github.com/cosmos/gaia/runs/6164055056?check_suite_focus=true

## Version

all

## Steps to Reproduce

Update older versions of gaia, or in the case of the codecov issue, do anything at all

https://github.com/cosmos/gaia/runs/6164055056?check_suite_focus=true#step:8:30

## Suggested solutions

* Stop using the diff ci action
* consider replacing codecov with a more portable solution that does not rely on an api key
* backport this to all gaias

https://github.com/cosmos/gaia/pull/1448

## note

due to the fact that there seems an issue with the cosmos codecov api key generally or with the whole service, any PR's that have cone in recently will need their ci jobs re-run

this has hit tm-db as well:

https://github.com/tendermint/tm-db/runs/6163210118?check_suite_focus=true

## 2nd note:
it hurts more than the linters
https://github.com/faddat/gaia/blob/84de16ef50b0dad6ec164b99610a80bf16d9ec01/.github/workflows/sims.yml#L125

ci jobs are free, why are we trying to conserve them?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by faddat** [comment]
Like this:

https://github.com/cosmos/gaia/runs/6615907131?check_suite_focus=true#step:4:75

**Comment by faddat** [comment]
yep.  this one, dated a month ago, detailed the issues with all the pr's

**Comment by mmulji-ic** [comment]
Hey @faddat do have suggestions for alternative codecov tooling?

**Comment by faddat** [comment]
Just had a call with @okwme -- so, we found that the linter was missing this line:

#1623 
#1624 

However, the main branch contains linting issues.  They're not being caught because of the diff.

They are grandfathered-in.  We saw this with:

* https://github.com/cosmos/cosmos-sdk/pull/12702
* https://github.com/cosmos/cosmos-sdk/pull/12141
* https://github.com/cosmos/ibc-go/pull/1418

**Comment by okwme** [comment]
Linting errors should all be fixed at this point in main.
Since we removed checkdiff linters will be run all the time as well.
still needs to be backported to v7.0.x (can go into current work on v7.0.3) and v6.0.x according to #1549

**Comment by okwme** [comment]
hey @faddat i'm having trouble narrowing down what changes need to be backported for #1669 
it's the last thing to close this issue, can you help with a backport PR with just the relevant changes?

**Comment by mpoke** [comment]
Update:

- [ ] understand issue with using the diff CI action
- [x] replace codecov with Sonarcloud (i.e., config Sonarcloud)

**Comment by mpoke** [comment]
Closing as codecov was updated to Sonarcloud. If the problem persists, we'll reopen.
