### ISSUE TITLE
Speed Runs

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1450]
## Summary

Archive nodes are hard to maintain and hard to create.  We should have a system in place testing our release branches sequentially, and timing it.

## Problem Definition

* It takes a very long time to sync from v4-7
* In order to approach this problem, we need to test release branches sequentially and get feedback on how long that takes
* github actions is not the right tool for the job

## Proposal

Create a gitlab CI server for this purpose

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
@faddat Interesting to do, but will check back nearer the end of the qtr once we've cleared Rho.

**Comment by mpoke** [comment]
@faddat is this issue still relevant? If yes, could you please provide more context?

**Comment by mpoke** [comment]
Closing this issue as outdated. If it still relevant, please reopen and provide more context.
