### ISSUE TITLE
Checksum mismatch on varnamelen dependency during build

### ISSUE THREAD

**Issue by mzabaluev** [cosmos/gaia#1461]
## Summary of Bug

Build fails due to a corrupted checksum on `github.com/blizzy78/varnamelen`.

## Version

v7.0.1
(not fixed as of c934600f3287ccc251830659ad29a92641746046)

## Steps to Reproduce

Check out the repository and run `make install`.

I get a build error:

```
verifying github.com/blizzy78/varnamelen@v0.6.1/go.mod: checksum mismatch
	downloaded: h1:mGBHm+Uo4e8JnZEKHRoZgVEOQdSBdQfY/x+k4NAXBWA=
	go.sum:     h1:zy2Eic4qWqjrxa60jG34cfL0VXcSwzUrIx68eJPb4Q8=
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment]
Hi @mzabaluev we've tried reproducing the error but don't see the hash mismatch. Can you confirm this fails for you when you use a proxy? There could be an issue with your network or the CDN in your area. At this moment we can't reproduce the error.

Also did you use `go ​clean -modcache` before running?

**Comment by mzabaluev** [comment]
> Hi @mzabaluev we've tried reproducing the error but don't see the hash mismatch. Can you confirm this fails for you when you use a proxy?

I need some education on this. Is there a proxy I can try?

> There could be an issue with your network or the CDN in your area.

Maybe, but exactly the same problem was seen in https://github.com/open-telemetry/opentelemetry-go/issues/2760, and the developers have fixed it by updating the dependencies.

> Also did you use `go ​clean -modcache` before running?

I just did, it does not help.

**Comment by okwme** [comment]
HI @mzabaluev 
I've also just tried to install after running `go clean -modcache` and had no problem.
i'm using `go version go1.17.5 darwin/amd64`
there's minimum requirement of 1.17, can you confirm your verison?

**Comment by mzabaluev** [comment]
I've been using `go version go1.16.15 linux/amd64`.
Tried with the docker container `docker.io/library/golang:1.18.1`, and the problem did not appear.
Weird for it to manifest this way, but I'm ready to accept that the old go version was the cause of the problem.
