### ISSUE TITLE
Is governance syncretic?

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1462]
## Summary of Bug

The cosmos hub contains no software functionality to remove validators that vote no with veto.

This is because It’s not only validators who vote, it is everyone.

Anyone can and should vote no with veto on this tremendously broken proposal.

But wait jacob this is github!, yes I have put this on get home because the proposal was made by the individual running the cosmos hub, it seems there must be a bug because the code doesn’t do what he thinks it does.  

https://twitter.com/gadikian/status/1520547855177437184

## Version

SDK v0.45.*

## Steps to Reproduce

![CF923B0A-3457-4426-ABAA-11ADE83637CB](https://user-images.githubusercontent.com/7142025/166126960-bcae7e71-e111-4b5a-bb58-39232cab68a3.jpeg)
![51EA4B2F-EC34-4EBD-996D-9C0DAC2091A0](https://user-images.githubusercontent.com/7142025/166126963-13921ca5-4b82-41fd-afde-d52032b1e2ea.jpeg)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by nooomski** [comment]
Hi @faddat , there was no misunderstanding or bug in terms of the code. Nobody on the team was under the impression that No with Veto was somehow enforced in the Gaia binary, nor is there any current intention to do so. So if you don't mind, I am going to close this issue as there is no work that can be implemented right now based on it and prop 69 has failed anyway :)
