### ISSUE TITLE
Cosmos ATOM - Theta upgrade issue

### ISSUE THREAD

**Issue by sankararaok** [cosmos/gaia#1471]
Hi Team,
I have a Cosmos Archive ATOM Node running and synched successfully before the Theta upgrade.
I have pulled the latest code for theta upgrade and build the code , generated the docker image and tried starting node, But node is not running , throwing me the below error - Error: couldn't read GenesisDoc file: open /root/.gaia/config/genesis.json: no such file or directory,

Docker command used - sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-cosmosatom/gaia/.gaia:/gaia/.gaia gaiaapr22:latest gaiad start --pruning nothing. 

My config file location is  /disk/node-cosmosatom/gaia/.gaia/config.

Please guide me on this issue to resolve the issue.

**Comment by glnro** [comment]
Hi @sankararaok try passing the `--home` flag

**Comment by sankararaok** [comment]
Hi,
I am using , 
sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-cosmosatom/gaia/.gaia:/gaia/.gaia gaiaapr22:latest gaiad start --pruning nothing 
I tried setting $HOME as /disk/node-cosmosatom/gaia, it didn't worked, also used --home in the docker command as below but got home flag not available in docker.
sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-cosmosatom/gaia/.gaia:/gaia/.gaia --home="/disk/node-cosmosatom/gaia"  gaiaapr2022:latest gaiad start   --pruning nothing

**Comment by glnro** [comment]
you need to pass `--home` to gaiad

**Comment by nooomski** [comment]
Hey @sankararaok , you're not using the `--home` flag correctly. It's in the wrong place and it doesn't need the `=` sign. Please try: 
`sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-cosmosatom/gaia/.gaia:/gaia/.gaia gaiaapr2022:latest gaiad start --pruning nothing --home /disk/node-cosmosatom/gaia`

**Comment by sankararaok** [comment]
Thank you , for the solution, i have used the --home flag, it points to the right config folder now.
But still i am getting the below error, 
8:39AM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.
Error: couldn't read GenesisDoc file: open /disk/node-cosmosatom/gaia/.gaia/config/genesis.json: no such file or directory.

But i have genesis.json , in the same location, I have given permissions for the folders as well.

**Comment by glnro** [comment]
It's looking for genesis in the config of your _gaia_ home which seems to be `/disk/node-cosmosatom/gaia/.gaia` ....so that's what you need to set your home flag for `gaia start`, not your working directory for the container.

**Comment by sankararaok** [comment]
Thank you, 
I have used the below docker command, 
sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-cosmosatom/gaia/.gaia:/gaia/.gaia gaiaapr2022:latest gaiad start --pruning nothing --home /disk/node-cosmosatom/gaia/.gaia

It is giving me  the error,  Error: couldn't read GenesisDoc file: open /disk/node-cosmosatom/gaia/.gaia/config/genesis.json: no such file or directory.
Which is strange for me.
![atomerror](https://user-images.githubusercontent.com/30615487/167829768-0390698c-8d6a-4348-a4aa-bd446dc5189b.JPG)

Please guide me here.

**Comment by glnro** [comment]
@sankararaok is this home folder the working directory on the docker container or your local machine?

**Comment by sankararaok** [comment]
I am running node on a ubuntu server, added a disk named 'disk'. created a folder structure node-cosmosatom/gaia 
and used the below command to run the node. For earlier versions I haven't faced this issue.

sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-cosmosatom/gaia/.gaia:/gaia/.gaia gaiaapr2022:latest gaiad start --pruning nothing --home /disk/node-cosmosatom/gaia/.gaia

**Comment by glnro** [comment]
Ok if you're mounting a volume then gaia home needs to be the directory on the container not the disk

**Comment by sankararaok** [comment]
can you pls give the docker command? I have used the below, seems working, Theta migration started.
sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /disk/node-cosmosatom/gaia/.gaia:/gaia/.gaia gaiaapr2022:latest gaiad start --pruning nothing --home /gaia/.gaia

Thank you glnro.
