### ISSUE TITLE
Config app.toml param bypass-min-fee-msg-types not work

### ISSUE THREAD

**Issue by fx0x55** [cosmos/gaia#1486]
## Summary of Bug
Append parameter `bypass-min-fee-msg-types` to `app.toml` not work

This can be work if `bypass-min-fee-msg-types` is placed at the beginning of `app.toml` or before [Telemetry]

## Version

main-97a79c38beab15032347344b2d588a59ff2b292a
## Steps to Reproduce

1. gaiad testnet --v 1
2. update app.toml  `bypass-min-fee-msg-types` params to ['/cosmos.staking.v1beta1.MsgDelegate']
3. gaiad start --home ./mytestnet/node0/gaiad
5. gaiad tx staking delegate cosmosvaloper105jmphl0qh04ner2v2dxkdvwhcgkvar4jyjn7h 1stake --from node0 --chain-id=chain-AW5wPV

result:
```
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgDelegate","delegator_address":"cosmos1l7dvcejsa2tswqrzwr0rjmqcwmjxgwalztt6js","validator_address":"cosmosvaloper105jmphl0qh04ner2v2dxkdvwhcgkvar4jyjn7h","amount":{"denom":"stake","amount":"1"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 13
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'insufficient fees; got:  required: 20stake: insufficient fee'
timestamp: ""
tx: null
txhash: 1703C4958EE89149795D7F3666411ACF0D03409500DF0FC17552860090F67EA8
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Hi, @fx0x55 , can you try with v7.0.2 ?  thanks!

**Comment by yaruwangway** [comment]
hi @alexanderbez , do you know why ? I repeated and got the same result, `bypass-min-fee-msg-types` has to be before `telemetry` ?

**Comment by fx0x55** [comment]
> Hi, @fx0x55 , can you try with v7.0.2 ? thanks!

The version I used was 7.0.2

**Comment by fx0x55** [comment]
It may be a problem with the toml file format

`bypass-min-fee-msg-types` parameter is considered a parameter of the [state-sync] struct

**Comment by okwme** [comment]
todo:
* check if there is an `app.toml` validate function that could be exposed or enforced to be run

**Comment by mmulji-ic** [comment]
@yaruwangway prio for next point release, timebox till Wed and report back.

**Comment by yaruwangway** [comment]
update: 

`bypass-min-fee-msg-types` has to put before or after the default [`DefaultConfigTemplate`](https://github.com/cosmos/gaia/blob/f2be720353a969b6362feff369218eb9056a60b9/app/params/config.go#L15), not in the middle of the `DefaultConfigTemplate`, which means `bypass-min-fee-msg-types` has to be at the beginning or end of the `app.toml` file. because gaia uses a CustomAppConfig which consists of `DefaultConfigTemplate` from sdk and an extra field of `bypass-min-fee-msg-types` .

In next gaia rho release, there will be default
```
bypass-min-fee-msg-types = ["/ibc.core.channel.v1.MsgRecvPacket", "/ibc.core.channel.v1.MsgAcknowledgement", "/ibc.core.client.v1.MsgUpdateClient", ]
```
at end of the app.toml file which users can custom there.

**Comment by yaruwangway** [comment]
the default `bypass-min-fee-msg-types = ["/ibc.core.channel.v1.MsgRecvPacket", "/ibc.core.channel.v1.MsgAcknowledgement", "/ibc.core.client.v1.MsgUpdateClient", ]` is not in v7.

**Comment by mmulji-ic** [comment]
@yaruwangway that was the only intended or main use case to have IBC messages be exempted. Do we know if any validators/relayers are using this config parameter? Except of course, the example above '/cosmos.staking.v1beta1.MsgDelegate'

**Comment by yaruwangway** [comment]
I dont know who is using it. `['/cosmos.staking.v1beta1.MsgDelegate']` is just an example for testing. The default ` bypass-min-fee-msg-types ` in rho does not included `/cosmos.staking.v1beta1.MsgDelegate`

**Comment by mmulji-ic** [comment]
@yaruwangway @okwme if we can't fix this issue with the aforementioned spike, then we should still do a point release. @yaruwangway tag me or @glnro to sit in tomorrow morning.

For the time being, we can put something in the changelog or upgrade instructions, that mentions this.

**Comment by mmulji-ic** [comment]
Depending on timing maybe add to 7.0.4
