### ISSUE TITLE
Documentation flow references

### ISSUE THREAD

**Issue by sabau** [cosmos/gaia#15]
## Summary

Some portion of docs references to the staging docs, the flow need to be updated after gaia split:
`## Docs Build Workflow`

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
seems this was fixed, closing the issue
