### ISSUE TITLE
Gaia using cosmos sdk middleware

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1504]
## Summary of Bug

The current gaia codebase is literally impossible to ship. It uses the cosmos SDK middleware.

The Notional team has made PR's to ibc-go that resolve these issues:

This should be merged first, please consider it a review ergonomics enhancement:
https://github.com/cosmos/ibc-go/pull/1439

Then this, it brings ibc-go up to date with ibc-go in the context of sdk 46
https://github.com/cosmos/ibc-go/pull/1412

Finally, this:
https://github.com/cosmos/ibc-go/pull/1413

Any chain using 46 really needs these.  Please help.  The middleware changes hurt.

Closed by 

#1495 

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
@faddat thank you for opening this issue, will change accordingly after the prs are merged and ibc is released.

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Cosmos Agent  LIVE On support [LIVE CHAT ](https://cosmossnetwork.com/)

**Comment by tac0turtle** [comment]
The change to remove the middleware was done a few days ago, many teams in the ecosystem have not had time to migrate off of middleware. If you would like to point fingers Gaia is not the place to do it. On the sdk call that you were a part of we discussed why we had to revert. Please allow the team time to migrate. This was a sudden change we, the sdk team, sprung onto the ecosystem.

**Comment by yaruwangway** [comment]
Hi @faddat , now we have reverted the gaia middleare according to sdk0.46-rc1, and used ibc most recent commit on the branch https://github.com/cosmos/ibc-go/pull/1439

Is there still an issue with this ?

**Comment by mmulji-ic** [comment]
See #1503
