### ISSUE TITLE
Abuse of contributors covenant by Billy Rennekamp

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1516]
## Summary

Billy Rennekamp has been using the contributors covenant to stifle discussion of the cosmos hub.

The contributors covenant is a huge, sprawling document that most people violate several times per day and makes political discourse in cosmos totally impossible. and is wasting time.  But if I didn't spend time this way I could get knocked out of cosmos or repositories.

https://github.com/cosmos/ibc-go/pull/1317

Earlier discussion of this was deleted without discussion from the IBC-go repository.

I think Billy has access to the email in the contributors covenant in ibc-go.  I'm not going to report there.  I will report here.

If this issue gets deleted, I will report that.

And so on.

https://github.com/notional-labs/notional/blob/master/incidents/Letter%20to%20the%20cosmos%20ecosystem%20concerning%20the%20care%20and%20maintenance%20of%20the%20cosmos%20hub.pdf

**unlike Billy, I was elected**.

## Problem Definition

Billy is abusive, and Billy himself doesn't read issues and pull requests, and makes inaccurate reviews in addition to being abusive.

Billy denigrates contributors, calling their contributions "drive by PR's" when all of them point back to the same issue, #1449.

Billy's abusive behavior is causing me to reconsider involvement on several key cosmos repositories.

This should not be discussed in private.

 
## Proposal

Remove Billy from the ICF or remove the CoC or replace the CoC with Jacobs tiny CoC
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by tac0turtle** [comment]
Hey, Jacob. We value all contributors to the gaia and all of the products of the cosmos stack. IG employees do not work for or represent the ICF. Please stop spreading misinformation, this is not correct. Cosmos is built on the foundation of contributors who bring people up even in adverse conditions. 


I will be closing this issue and locking the conversation as this is unacceptable.
