### ISSUE TITLE
Balance incorrect when querying address. 

### ISSUE THREAD

**Issue by yj0x0x** [cosmos/gaia#1518]
## Summary of Bug

Address `cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962 ` balance is not correct on block height `8695158 ` Tx hash is `002D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0 `. 

## Version
V6.0.4
Node is archive node to set up config pruning nothing. 
This node sync from v4.2.1 which block height started `5200791`. 

## Steps to Reproduce
Address `cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962`balance was 0 before block height `8695158`. 
But transaction `002D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0` includes balance change like below. 

This return possibly can get through Rosetta API.  

```
        {
                "transaction_identifier": {
                    "hash": "002D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "coin_received",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962"
                        },
                        "amount": {
                            "value": "24",
                            "currency": {
                                "symbol": "pool32DD066BE949E5FDCC7DC09EBB67C7301D0CA957C2EF56A39B37430165447DAC",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "coin_spent",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962"
                        },
                        "amount": {
                            "value": "-356604",
                            "currency": {
                                "symbol": "ibc/2181AAB0218EAC24BC9F86BD1364FBBFA3E6E3FCC25E88E3E68C15DC6E752D86",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 2
                        },
                        "type": "coin_spent",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962"
                        },
                        "amount": {
                            "value": "-24770",
                            "currency": {
                                "symbol": "uatom",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 3
                        },
                        "type": "coin_spent",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962"
                        },
                        "amount": {
                            "value": "-11160745",
                            "currency": {
                                "symbol": "ibc/2181AAB0218EAC24BC9F86BD1364FBBFA3E6E3FCC25E88E3E68C15DC6E752D86",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 4
                        },
                        "type": "coin_spent",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962"
                        },
                        "amount": {
                            "value": "-775230",
                            "currency": {
                                "symbol": "uatom",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 5
                        },
                        "type": "coin_spent",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962"
                        },
                        "amount": {
                            "value": "-24",
                            "currency": {
                                "symbol": "pool32DD066BE949E5FDCC7DC09EBB67C7301D0CA957C2EF56A39B37430165447DAC",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 6
                        },
                        "type": "coin_received",
                        "status": "Success",
                        "account": {
                            "address": "cosmos13s0lj78gujy89vn9780gq6qn4v937ywjasyw2q"
                        },
                        "amount": {
                            "value": "356604",
                            "currency": {
                                "symbol": "ibc/2181AAB0218EAC24BC9F86BD1364FBBFA3E6E3FCC25E88E3E68C15DC6E752D86",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 7
                        },
                        "type": "coin_received",
                        "status": "Success",
                        "account": {
                            "address": "cosmos13s0lj78gujy89vn9780gq6qn4v937ywjasyw2q"
                        },
                        "amount": {
                            "value": "24770",
                            "currency": {
                                "symbol": "uatom",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 8
                        },
                        "type": "coin_received",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1xtwsv6lff8jlmnracz0tke78xqwse22h4sez9u"
                        },
                        "amount": {
                            "value": "11160745",
                            "currency": {
                                "symbol": "ibc/2181AAB0218EAC24BC9F86BD1364FBBFA3E6E3FCC25E88E3E68C15DC6E752D86",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 9
                        },
                        "type": "coin_received",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1xtwsv6lff8jlmnracz0tke78xqwse22h4sez9u"
                        },
                        "amount": {
                            "value": "775230",
                            "currency": {
                                "symbol": "uatom",
                                "decimals": 0
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 10
                        },
                        "type": "coin_received",
                        "status": "Success",
                        "account": {
                            "address": "cosmos13s0lj78gujy89vn9780gq6qn4v937ywjasyw2q"
                        },
                        "amount": {
                            "value": "24",
                            "currency": {
                                "symbol": "pool32DD066BE949E5FDCC7DC09EBB67C7301D0CA957C2EF56A39B37430165447DAC",
                                "decimals": 0
                            }
                        }
                    }
                ]
            }
```

operation below is weird that because  address `cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962` didn't have any balance for assets on chain. 

```
 {
                        "operation_identifier": {
                            "index": 2
                        },
                        "type": "coin_spent",
                        "status": "Success",
                        "account": {
                            "address": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962"
                        },
                        "amount": {
                            "value": "-24770",
                            "currency": {
                                "symbol": "uatom",
                                "decimals": 0
                            }
                        }
                    },
```

I have traced this address asset through bulletin rest api like below. 

```
 curl -X GET -H "Content-Type: application/json" -H "x-cosmos-block-height: 8695158" http://localhost:1317/cosmos/bank/v1beta1/balances/cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962
 
 result ; 
 
 {
    "balances": [],
    "pagination": {
        "next_key": null,
        "total": "0"
    }
}

 curl -X GET -H "Content-Type: application/json" -H "x-cosmos-block-height: 8695157" http://localhost:1317/cosmos/bank/v1beta1/balances/cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962

 {
    "balances": [],
    "pagination": {
        "next_key": null,
        "total": "0"
    }
}

```

There were no balance about this address but there were activity . 
I also compare through `api.cosmos.network/cosmos/bank/v1beta1/balances/`. 
Result also same. 

Is there some issue about block data or something?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Hi @yj0x0x , thanks for reporting this issue.
`2D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0` is the block hash?
what is the txhash ? i could not find the addr in that block height

**Comment by yj0x0x** [comment]
Hello.  @yaruwangway 
This hash is the end blocker hash. 
because this hash started with `00` prefix. 

ref : https://github.com/cosmos/cosmos-sdk/blob/9fd866e3820b3510010ae172b682d71594cd8c14/server/rosetta/types.go#L15-L24

So, if you wanted to see this Tx you have to check through Rosetta API. 

Here is the block info (ref : https://www.mintscan.io/cosmos/blocks/8695158 ) 
Block height is 8695158 , Block hash is  `2D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0 `. 

> Hi @yj0x0x , thanks for reporting this issue. `2D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0` is the block hash? what is the txhash ? i could not find the addr in that block height

**Comment by yj0x0x** [comment]
@yaruwangway Ping.

**Comment by yaruwangway** [comment]
hi, i do not find this transaction or this addr in block height `8695158 `. where do you see it ? 
@glnro can you check as well ?

**Comment by yj0x0x** [comment]
This Transaction couldn't see in the usual rest api request. 
This has to be searched through the Rosetta API. 
Couldn't find the tx through the Rosetta API request?

**Comment by yj0x0x** [comment]
Did you check that this transaction format is the `end blocker` transaction hash?? @yaruwangway @glnro

**Comment by yj0x0x** [comment]
@yaruwangway Ping.

**Comment by yaruwangway** [comment]
Hi @yj0x0x, i need to ask my colleagues , i will get back to you this week.

**Comment by tac0turtle** [comment]
> Address `cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962 ` balance is not correct on block height `8695158 ` Tx hash is `002D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0 `.

hey are you able to provide a valid txhash, this txhash doesn't seem to exist on the cosmos hub. I checked across a few nodes and block explorers. I also searched many nodes for the balance of that account at the heights mentioned and the values were always 0. 

if we look at mintscan for the address provided https://www.mintscan.io/cosmos/account/cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962 the first transaction was at height 9430499. Are you sure there are transactions to this account at the heights you are specifying

**Comment by yj0x0x** [comment]
Hello @marbar3778 . 
Txhash `002D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0 ` can get through only rosetta api. 
Can I ask you check this hash through Rosetta? 
This hash possibly to see through below curl request. 
```
curl -X POST  -H "Content-type: application/json" http://localhost:8080/block -d '{"network_identifier": {"blockchain": "app","network": "network"},"block_identifier": {"index": 8695158}}'
```

**Comment by yj0x0x** [comment]
Thing is when you have seen that tx `002D9BEECFD46E4B35339D47166B7D0CE6F357DFA54AF3EBD1854ACC33A4D4CFB0` return, It had `uatom` amount changed. even if it didn't has amount on its account.

**Comment by yaruwangway** [comment]
and your node is still syncing mainnet ?

**Comment by yj0x0x** [comment]
yes. 
You want to see the rosetta api result?

**Comment by yj0x0x** [comment]
[block-8695158-rosetta-api-result.json.zip](https://github.com/cosmos/gaia/files/8869641/block-8695158-rosetta-api-result.json.zip)

**Comment by yj0x0x** [comment]
@marbar3778 @yaruwangway 
Can I ask that you guys check this tx through the Rosetta API?

**Comment by yaruwangway** [comment]
i am setting up rosetta, and get 
`WARNING: The Rosetta server is still a beta feature. Please do not use it in production.`
so you just setup in app.toml `rosetta = true" and query?

**Comment by yj0x0x** [comment]
Yes.

**Comment by yaruwangway** [comment]
now on your data you run v7 to sync the mainnet, right?

**Comment by yj0x0x** [comment]
No. I prevent to sync so node version is the `v6.0.4`.

**Comment by yj0x0x** [comment]
Node version affects to block data return through Rosetta API?

**Comment by yaruwangway** [comment]
i just want to confirm you data is correct by still syncing. if the block data is wrong, you could not  continue to sync anymore.

**Comment by yj0x0x** [comment]
Node on my side , I set up this prevent syncing. 
Need to upgrade? 
I think upgrade isn't belong to this issue.

**Comment by yj0x0x** [comment]
My node height is `10085397 `.

**Comment by yaruwangway** [comment]
upgrade is not belonging  to this issue, but we need to verify your data is correct, which means you should have the same data as most of other nodes, if your data is different from them, you are not able to sync. we need to verify this.

**Comment by yj0x0x** [comment]
Can I ask that you check this file? 
https://github.com/cosmos/gaia/issues/1518#issuecomment-1150974451

I attached return from my node through rosetta api.

**Comment by yaruwangway** [comment]
this addr is not in the mintscan on that hight. you can query your node about this tx hash, `gaiad q tx [tx hash]`, if you get the same result, this is not a rosetta issue, your data is probably wrong.

**Comment by yj0x0x** [comment]
OK.
I mentioned already that this data couldn't get through normal builtin rest api, like `/cosmos/tx/v1beta1/txs/{Txhash}`. 
Because As I mentioned,  This TX is `EndBlocker tx hash`. 
SO if you want to check this data is in the node or not, rosetta api request is essential not `/cosmos/tx/v1beta1/txs/{Txhah}`. 

Can I ask you that you checked this comment? (https://github.com/cosmos/gaia/issues/1518#issuecomment-1143583592)

**Comment by yj0x0x** [comment]
And did you check this tx through rosetta api? as I explain before?

**Comment by yj0x0x** [comment]
What is difference between `gaiad q tx [tx hash] ` & `/cosmos/tx/v1beta1/txs/{Txhash}`? 
AFAIK, these are same.

**Comment by yj0x0x** [comment]
And My node's data wasn't wrong, If wronged, How node can sync till `10085397 `?

**Comment by yj0x0x** [comment]
@yaruwangway Ping.

**Comment by yaruwangway** [comment]
> And My node's data wasn't wrong, If wronged, How node can sync till `10085397 `?

if you are syncing with some nodes and form another network, you can have data that is diff from the livehub.  but I am not sure you are in this situation. 

so can you start your node and keep syncing ? here is some info of nodes you can sync with.
https://chain-registry.netlify.app/

or you can expose your api so that we can query.

cc @mmulji-ic  what is your opinion ?

**Comment by yj0x0x** [comment]
First of all, I want to ask you that check that I suggest I had aforementioned. 
Cosmos's node has same data through Rosetta API that I provided? 

From the first and till now, you just ask me that node is synced or not, and you haven't sure that data were same or not. 

Please check that I provided to you. 
Were those too difficult to check on your side?

**Comment by yj0x0x** [comment]
Endblocker transaction data get through the Rosetta API has flaws to parse node's data?

**Comment by yj0x0x** [comment]
And here are the part of configs that I set up as seedsnode. 

```
# seeds = "bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656,366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656"
# Comma separated list of nodes to keep persistent connections to
# persistent_peers = "6e08b23315a9f0e1b23c7ed847934f7d6f848c8b@165.232.156.86:26656,ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656,538ebe0086f0f5e9ca922dae0462cc87e22f0a50@34.122.34.67:26656,d3209b9f88eec64f10555a11ecbf797bb0fa29f4@34.125.169.233:26656,bdc2c3d410ca7731411b7e46a252012323fbbf37@34.83.209.166:26656,585794737e6b318957088e645e17c0669f3b11fc@54.160.123.34:26656,5b4ed476e01c49b23851258d867cc0cfc0c10e58@206.189.4.227:26656,11dfe200894f38e411beca77928e9dd118e66813@94.130.98.157:26656,654f47a762c8f9257aef4a44c1fb5014916d8b20@99.79.60.15:26656,366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656,d6318b3bd51a5e2b8ed08f2e520d50289ed32bf1@52.79.43.100:26656,1bfda3d59e70290a3dada9bb809dd954371850d3@54.180.225.240:26656,6ee94c2093505e8790442c054e6e1e0211d36583@44.239.140.195:26656,ec779a2741da6dd2ccdaa6dfc0bebb10e595dfa4@50.18.113.67:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,047f723806ee702b211e7227f89eacd829aabd86@52.9.212.125:26656,b0e746acb6fbed7a0311fe21cfb2ee94581ca3bc@51.79.21.187:26656,82772547c4575c18dfe6e75aafe521cf7d4dc8de@142.93.157.186:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656,f122129f53b7c584df6cee77716dcc636d5c5e18@167.172.59.196:26656,241b17dba97a2ed3c3747d12781fb86c9706e2d4@95.179.136.131:26656,f1b16c603f3a0e59f0ce5179dc80f549a7ecd0e2@sentries.us-east1.iqext.net:26656"
```

**Comment by yj0x0x** [comment]
I don't know why you never mention about Enblocker transaction's event mechanism till now.

**Comment by yj0x0x** [comment]
I think your team has daily snapshot in light of based on the [ this issue](https://github.com/cosmos/gaia/issues/1313#issue-1155391851).

**Comment by yj0x0x** [comment]
if node syncing goes well then node data on my side doesn't have any issue right?
@yaruwangway

**Comment by yaruwangway** [comment]
i only have v7 node upgraded from v6, and this might have some issues with rosetta api, which failed to connect port.
I tested the next rho version is working but that is not released.
are you using offline mode ?

there might be two possibilities:
1.  your data issue
2. rosetta issue

or some other issues i m not aware of.

if you start to sync, can you expose it, so that we can query it.

**Comment by yj0x0x** [comment]
No I'm turn on rosetta api online. 

Querying from your side, I can't decide it. 
But In case of proceed syncing I will do and let you know. 

And Please check the Endblock transaction hash's contents what i provided. 
I think this issue related with `liquidity` module.

**Comment by yaruwangway** [comment]
hi maybe you can join the [discord](https://discord.com/invite/cosmosnetwork) there to discuss with more developers.

**Comment by yj0x0x** [comment]
OK. Thanks. 
Please don't close this MR before got the resolution.

**Comment by mmulji-ic** [comment]
Sure @yj0x0x we'll keep it open. Do let us know if you have a resolution.

**Comment by yaruwangway** [comment]
will keep it open till rho (next release) rosetta tested .

**Comment by yj0x0x** [comment]
Hello @yaruwangway  @mmulji-ic . 
Just FYI, I am having talk with mentioned issue with @alexanderbez . 

Issue link is here. https://github.com/cosmos/cosmos-sdk/issues/12244#issue-1270268894

**Comment by mmulji-ic** [comment]
Closing after follow up with #12244 on the SDK side.
