### ISSUE TITLE
ERROR: unrecognized concrete type name auth/Account when run gaiacli query account

### ISSUE THREAD

**Issue by past2017** [cosmos/gaia#152]
## Version
gaiacli version
2.0.0

## Steps to Reproduce

1. in Ubuntu 16.04,  git clone -b v2.0.0 https://github.com/cosmos/gaia
2. cd gaia && make install
3. config gaia
```
gaiacli config
chain-id = "cosmoshub-2"
node = "http://cosmos-node.sparkpool.com:26657"
trust-node = true
```

4. gaiacli keys add test1 --recover   to import one key
5. gaiacli keys list test1
```
 name: test1
  type: local
  address: cosmos13nz5txzzyn8uk22ahdg2027clyfxggj0fdhzkh
  pubkey: cosmospub1addwnpepqd6p33h6gcrv8339d4rhnm7dn9kze4arywe0mg7vfdp8uquwjjpcxvw6dn7
  mnemonic: ""
  threshold: 0
```
6. $ gaiacli query account cosmos13nz5txzzyn8uk22ahdg2027clyfxggj0fdhzkh
**ERROR: unrecognized concrete type name auth/Account**

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Please read the readme and [launch](https://github.com/cosmos/launch) repo; The current hub works with SDK/Gaia v0.34.x.

The mainnet will be upgraded to 2.0.x in the coming weeks.
