### ISSUE TITLE
Rho: make bypass fee and global fee compatible

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1528]
## Summary
[bypass min fee](https://github.com/cosmos/gaia/blob/v7.0.2/ante/fee.go) allow config a certain types of msgs to skip fee check.
but Rho also will have another fee check antehandler: [global fee](https://github.com/confio/tgrade/tree/main/x/globalfee). 

Global fee should also allow bypass certain types of msgs set in the config. or allow config if allow bypass

## Proposal

write one antehandler to put all fee checks together: `min_gas_price` in app.toml and `globalfees` with bypass function.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
here is the [global fee module branch](https://github.com/cosmos/gaia/blob/yaru/rho-glob-fee/ante/fee.go)

**Comment by okwme** [comment]
completed!
