### ISSUE TITLE
Incorporate the rosetta cli

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1529]

**Comment by yaruwangway** [comment]
done

**Comment by mmulji** [comment]
@yaruwangway fixed in which issue?

**Comment by yaruwangway** [comment]
dont remember which PR, prob in rho-base. it is minor change. [code is here](https://github.com/cosmos/gaia/blob/3b1758faeb0d86aeb495aa0bc9d2b45b8e0a8074/cmd/gaiad/cmd/root.go#L137)
