### ISSUE TITLE
Export genesis - Block Time 

### ISSUE THREAD

**Issue by RafilxTenfen** [cosmos/gaia#1533]
## Summary of Bug

- When restarting a chain from only an exported genesis (without `data/*.db` files) the next block time uses genesis time :thinking: 
- This way if you stop the chain at block height 4 and `export` the genesis, delete the `data/*.db`, and restart the chain the block height 5 would use the `genesis_time` as the time for the new generated block

- When loading the [tendermint state](https://github.com/tendermint/tendermint/blob/v0.34.19/node/node.go#L680-L681) it uses the genesis file when there is no state from *.db and then it sets the context `LastBlockTime` with the [genesis time](https://github.com/tendermint/tendermint/blob/v0.34.19/state/state.go#L343-L344) like `LastBlockTime: genDoc.GenesisTime` and then the context header time is filled with the [time from the GenesisTime](https://github.com/tendermint/tendermint/blob/v0.34.19/consensus/replay.go#L313-L314) 

- This seems a bit weird because it happens at the tendermint layer, but tendermint doesn't have the `export` command

## Version

- git commit hash: `cd27aaaf39cc7819b5164e4baf3fd5aad23ec52a`
- gaiad version: `v7.0.2`

## Steps to Reproduce

- Go to [gaia v7.0.2](https://github.com/cosmos/gaia/releases/tag/v7.0.2) 
- Build `make`
- Run this [script](https://gist.github.com/RafilxTenfen/7f69186625b70ebb8e34d441515ffdde) 
```shell
./gaia-exported-genesis-timed.sh ./path_to_bin/gaiad-v702
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by robert-zaremba** [comment]
Sounds like a Tendermint/Cosmos SDK issue. `genDoc.GenesisTime` has a wrong time set.

**Comment by robert-zaremba** [comment]
So basically this is set to original "block 0" time.

**Comment by robert-zaremba** [comment]
let's close this issue. I created a new one in Tendermint. (see log above)
