### ISSUE TITLE
Some command outputs going to stderr instead of stdout

### ISSUE THREAD

**Issue by ASoTNetworks** [cosmos/gaia#1542]
## Version
v7.0.2

## Steps to Reproduce

Some command such as `gaiad version` and `gaiad export` goes to stderr.

Some commands such as `gaiad keys parse ...` and `gaiad q tendermint-validator-set` goes to stdout as expected.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment]
This topic was opened the SDK previous i recall as I ran into similar issues with `gaiad tx sign` and the output was no longer able to be captured with a pipe into a file.

@glnro also came across an error output recently that should have been a stdout

Found the SDK issue, it got closed but it's obviously not resolved. Going to open it again and close here.

https://github.com/cosmos/cosmos-sdk/issues/8498
