### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by tokamak-git** [cosmos/gaia#1543]
## Summary of Bug

Lack of tests coverage for cmd/gaiad/cmd
blocks #1536

## Version

main-4fc3b760a6f464150f7f14030b69eac011102d9b - current main branch

## Steps to Reproduce

https://app.codecov.io/gh/cosmos/gaia/compare/1536/tree

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
@tokamak-git we need to make this SMART
