### ISSUE TITLE
could you make an issue to "Remove `--mode validator` flag" for once the next SDK is released?

### ISSUE THREAD

**Issue by tokamak-git** [cosmos/gaia#1553]
could you make an issue to "Remove `--mode validator` flag" for once the next SDK is released?
once created I'll  merge this one as is since it's a requirement for the current rc of the SDK being used in the main branch where that docker file is being used from.

_Originally posted by @okwme in https://github.com/cosmos/gaia/pull/1552#issuecomment-1161962326_

**Comment by mmulji-ic** [comment]
Done in #1616
