### ISSUE TITLE
Rho: clean gaia/app

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1557]
## Summary
clean up `gaia/app/app.go` **after rho integration finishes.**

## Problem Definition
`app/app.go` is too big file.

## Proposal

split `app/app.go` into `app.go`, `upgrade/`, `keepers/` ,  `module.go`

 `app_test.go` into `apptest/app_test.go`

ref:
[osmosis/app](https://github.com/osmosis-labs/osmosis/tree/main/app)
[provenance/app](https://github.com/provenance-io/provenance/blob/main/app/upgrades.go)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by Anmol1696** [comment]
I would want to see this happen too. Current way of handling upgrades is very adhoc and the change in code is not limited to a clean module. Osmosis way of handling upgrades specially is something which is way cleaner and also sort of containerised.

But this would go hand in hand in splitting the whole up keepers as well as modules.
Would be willing to take this up.

**Comment by yaruwangway** [comment]
@Anmol1696 you are welcomed to take this up!  👍
but please pay attention that we are having a few prs open to work towards rho upgrade. so we will not merge this refactoring pr till other rho prs are merged. 

so you can do this refactor pr early and might need to solve a lot conflicts later.
or I can @ you when the major PR for rho is done and then you do this refactor.
both options are fine as you like.
Thank you!

**Comment by Anmol1696** [comment]
Sounds good. Thanks for the heads up. I dont mind doing conflict resolutions till this upgrade as well.

**Comment by Anmol1696** [comment]
Any plans for use the new app rewiring and [depinject](https://github.com/cosmos/cosmos-sdk/tree/main/depinject) module?
I guess the handling of upgrades in a cleaner way should still be possible with the depinject module, when we do decide to use it here in gaia.

**Comment by yaruwangway** [comment]
hi, @Anmol1696 , yeah, plan to use depinject module, but not sure if this will be in sdk0.46 since 0.46-rc2 does not have this yet. 

Hi, @marbar3778, will depinject module in sdk 0.46 or 0.47 ?

**Comment by julienrbrt** [comment]
Hey, no, `depinject` won't be included in v0.46.

**Comment by yaruwangway** [comment]
@Anmol1696 , I know we will use [depinject](https://github.com/cosmos/cosmos-sdk/tree/main/depinject), just not sure this this will be in rho or next, next upgrade. 

@okwme can you confirm here ?

**Comment by tac0turtle** [comment]
it will most likely be included in the next upgrade, post 0.46. But you will be able to write apps the current way going forward as well.
