### ISSUE TITLE
liveness tests fail

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1561]
## Summary of Bug
in some prs liveness tests fail. with err `Error: The operation was canceled.`
prolonging the timeout in test.yml is not helpful.

examples:
https://github.com/cosmos/gaia/runs/7038754281?check_suite_focus=true

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by tokamak-git** [comment]
As discussed with @yaruwangway this issue is gonna be fixed in the next tendermint release.

**Comment by okwme** [comment]
issue had to do with updating to go to v1.18 when ignite CLI only works with v1.17.
I made a new PR to replace ignite with generic gaiad binary serving the same purpose (just confirm it can generate blocks)
#1574 got merged so gonna close this issue too
