### ISSUE TITLE
 Automated hardware testing

### ISSUE THREAD

**Issue by tokamak-git** [cosmos/gaia#1563]
## Summary

Gaia currently does not have any automated testing for hardware, the good folks at Zondax have a testing framework in place.
refer: `https://interchainfoundation.slack.com/archives/C01JF0H5C48/p1656002425984909`

My proposal is to integrate their testing framework/suite into Gaia via a github action.

## Problem Definition

- Not that I am aware of.
- Possibly higher infra costs to run the testing suite, but seeing as we have generous limits using GitHub actions as a ci I believe this may not be as significant.

## Proposal

- I propose creation of an additional step in our CI (GitHub actions), where we integrate Zondax's suite.
- Ideally the test cases/scenarios are either maintained in a dedicated repository or we simply relay on Zondax for completeness in terms of testing.
- If possible it would be nice if we could run tests in parallel or at least allow for customization of test setup at the minimum.

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
The SDK are integrating this functionality, therefore closing here.
