### ISSUE TITLE
"gaiad start --x-crisis-skip-assert-invariants" exited with error "panic: UnmarshalJSON cannot decode empty bytes"

### ISSUE THREAD

**Issue by carrie143** [cosmos/gaia#1566]
## Summary of Bug
I try to run the gaia node,my version is v7.0.2,here is my step:
wget  https://github.com/cosmos/gaia/releases/download/v7.0.2/gaiad-v7.0.2-linux-amd64
```
/root/gaiad init test
cd $HOME/.gaia/config/
wget -O addrbook.json   https://quicksync.io/addrbook.cosmos.json
wget -O genesis.json.gz https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
gzip -d -f genesis.json.gz 
sed -i 's/laddr = "tcp:\/\/127.0.0.1:26657"/laddr = "tcp:\/\/0.0.0.0:26657"/g' config.toml
gaiad start --x-crisis-skip-assert-invariants
```
and shut down,this is error log
```
9:45AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
9:45AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"6ee94c2093505e8790442c054e6e1e0211d36583","ip":"44.239.140.195","port":26656}
9:45AM INF minted coins from module account amount=4309334uatom from=mint module=x/bank
panic: UnmarshalJSON cannot decode empty bytes

goroutine 73 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x2516678, 0xc0010dc0c0}, 0xc000271120, {0x24bb890, 0xc000e8efb0}, {0x24bb8e0, 0xc000e8f0a0}, {0xc00016d940, 0x9, 0x1f}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.4/x/params/types/subspace.go:109 +0x319
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x2516678, 0xc0010dc0c0}, 0xc000271120, {0x24bb890, 0xc000e8efb0}, {0x24bb8e0, 0xc000e8f0a0}, {0xc00016d940, 0x9, 0x1f}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.4/x/params/types/subspace.go:222 +0x145
github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.GetParams(...)
        github.com/gravity-devs/liquidity@v1.5.0/x/liquidity/keeper/keeper.go:56
github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.ExecutePoolBatches({{0x2516678, 0xc0010dc0c0}, {0x24bb890, 0xc000e8eff0}, {0x7fc8dc665690, 0xc0005d7080}, {0x24bd4d8, 0xc00107a990}, {0x24af120, 0xc0000ae3c0}, ...}, ...)
        github.com/gravity-devs/liquidity@v1.5.0/x/liquidity/keeper/batch.go:83 +0x125
github.com/gravity-devs/liquidity/x/liquidity.EndBlocker({{0x24ef1a8, 0xc000134000}, {0x251bf00, 0xc000022940}, {{0xb, 0x0}, {0xc004e58530, 0xb}, 0x4f5b97, {0x0, ...}, ...}, ...}, ...)
        github.com/gravity-devs/liquidity@v1.5.0/x/liquidity/abci.go:24 +0x158
github.com/gravity-devs/liquidity/x/liquidity.AppModule.EndBlock(...)
        github.com/gravity-devs/liquidity@v1.5.0/x/liquidity/module.go:173
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x24ef1a8, 0xc000134000}, {0x251bf00, 0xc000022940}, {{0xb, 0x0}, {0xc004e58530, 0xb}, 0x4f5b97, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:495 +0x33d
github.com/cosmos/gaia/v7/app.(*GaiaApp).EndBlocker(...)
        github.com/cosmos/gaia/v7/app/app.go:715
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc0004cf1e0, {0x100000000000000})
        github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:211 +0x25d
github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc00133b800, {0xc00133b800})
        github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:288 +0xdf
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc023a25e20, {0x20})
        github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:89 +0x24
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x24effa8, 0xc007bdf2c0}, {0x2505120, 0xc0005cabd0}, 0xc00497f0e0, {0x2517018, 0xc0011fe3e0}, 0x0)
        github.com/tendermint/tendermint@v0.34.19/state/execution.go:327 +0x54e
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc044df2ce0, 0x8}}, {0xc044df2cf0, 0xb}, 0x4f5b97, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000e36700, 0x0)
        github.com/tendermint/tendermint@v0.34.19/blockchain/v0/reactor.go:398 +0xb7b
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.19/blockchain/v0/reactor.go:110 +0x85
```

## Version
7.0.2

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
hi, The genesis you use is probably out of date. @glnro , can you please provide a genesis for gaiad v7 ? 
thanks !

**Comment by carrie143** [comment]
I am using this genesis json:https://github.com/cosmos/mainnet/blob/master/genesis.cosmoshub-4.json.gz @yaruwangway

**Comment by carrie143** [comment]
and now cann't get addrbook.json,this don't work,please check
curl https://quicksync.io/addrbook.cosmos.json > $HOME/.gaia/config/addrbook.json

**Comment by yaruwangway** [comment]
> I am using this genesis json:https://github.com/cosmos/mainnet/blob/master/genesis.cosmoshub-4.json.gz @yaruwangway

this is out of date, this is probably for v5 or even older. that means you need to use old version of gaia and go through several upgrade till v7. 
let me find a recent genesis for you so that you can use v7.

**Comment by tokamak-git** [comment]
Hey @carrie143, thanks for reaching out. I've checked the nodes you are trying to access It looks like the quick sync service is down.

As you know `quicksync.io` is an independent service internally we are reaching out to them to offer our assistance of they need it.

I believe you could use another archive node to pull data or blocksync or statesync, further more as they are decentralised the chances of those going down are extremely low.

Does this provide clarity?

**Comment by carrie143** [comment]
curl https://quicksync.io/addrbook.cosmos.json > $HOME/.gaia/config/addrbook.json works now.
and Can you provide me a recent genesis for v7? @tokamak-git @yaruwangway

**Comment by glnro** [comment]
Hi @carrie143 if you're using quicksync, then you don't need to download genesis.json, you can follow along [here](https://hub.cosmos.network/main/getting-started/quickstart.html#quicksync). Otherwise if you use [statesync](https://hub.cosmos.network/main/getting-started/quickstart.html#state-sync), you can just add the chain id when you init `gaiad init CUSTOM_MONIKER --chain-id cosmoshub-4
`, no need to download genesis.

This is the [genesis.json](https://github.com/cosmos/mainnet/blob/master/genesis.cosmoshub-4.json.gz) for cosmoshub-4 if you need it for any other reason.

**Comment by yaruwangway** [comment]
@glnro do you know which version of gaiad for this genesis ?

**Comment by yaruwangway** [comment]
@carrie143 ,  you can try gaiad v5 for the genesis you used. or v4, and switch to new binaries (v5 -> v6 -> v7) till upgrade height. but this will make you store a lot data, if you do not want , please try state sync, this will also bring you catch up faster.

exporting a genesis takes hours due to the size. you can try the other ways first ?

**Comment by glnro** [comment]
This genesis.json is good for any version running cosmoshub-4

**Comment by carrie143** [comment]
get it,I will try

**Comment by glnro** [comment]
Hi @carrie143 is this still an issue? If not we'll go ahead and close within 24 hours. Thank you.

**Comment by okwme** [comment]
closing after 24 hours
