### ISSUE TITLE
Easy bootstrap mechanism to join mainnet

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1592]
## Summary

Provide an easy bootstrap mechanism to allow validators to join mainnet/testnet.
See https://get.osmosis.zone/

## Problem Definition

No fuss mechanism to download the required binaries, setup config and join mainnet/testnet as required.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
@dasanchez this was the issue mentioned by Udit.

**Comment by mmulji-ic** [comment]
Check tgrade version of the script as well, thxs @yaruwangway

**Comment by mmulji-ic** [comment]
@dasanchez did you have time to look at this yet?

**Comment by dasanchez** [comment]
Not yet, we have been focused on planning and functionality to support the IS testnet so far.

**Comment by okwme** [comment]
#1848 has another feature that would improve this. Might be good to bundle the issues together

**Comment by okwme** [comment]
also this one: https://github.com/cosmos/gaia/issues/1722

**Comment by greg-szabo** [comment]
The Osmosis example uses Python3 which I think is mostly unnecessary. (Except for the huge, colored OSMOSIS banner. That's mandatory.) But that's just a minor note.

The two bigger questions are
1. Who's going to provide endpoints for this script? Osmosis has all kinds of endpoints hard-coded in the script so the node can connect and start syncing blocks:
```
    rpc_node = "https://rpc.osmosis.zone:443",
    addrbook_url = "https://rpc.osmosis.zone/addrbook",
    snapshot_url = "https://snapshots.osmosis.zone/latest"
```
2. Who will maintain the script when chain upgrades / binary upgrades happen? Is it going to be part of the release process to upgrade the script?
3.

**Comment by mpoke** [comment]
Closing as not needed and it can potentially introduce security issues.
