### ISSUE TITLE
issue with launching gaia node in docker

### ISSUE THREAD

**Issue by slider90** [cosmos/gaia#1595]
## Summary of Bug
The following image ghcr.io/cosmos/gaia:sha-fca0a63 doesn't work properly.
After launching we get the error:
>panic: runtime error: invalid memory address or nil pointer dereference

Also I tried to build the image from Dockerfile and from e2e.Dockerfile which is in main repo(7.2.0 tag). 
The same error is:
>gaia5  | 6:05PM INF initializing blockchain state from genesis.json
gaia5  | panic: runtime error: invalid memory address or nil pointer dereference
gaia5  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1525af8]

But the version 7.0.0 works fine.

My docker-compose file:
>version: '3'
services:
  cosmos:
    container_name: gaia
    image:  ghcr.io/cosmos/gaia:sha-fca0a6
    network_mode: bridge
    restart: unless-stopped
    command: --minimum-gas-prices "0.25stake"
    volumes:
      - '/data:/root/.gaia/data'
      - './app.toml:/root/.gaia/config/app.toml'
      - './genesis.cosmoshub-4.json:/root/.gaia/config/genesis.json'

**Comment by mmulji-ic** [comment]
Hi @slider90 thanks for filing the issue. 
Indeed the image ghcr.io/cosmos/gaia:sha-fca0a6, is a test image and not a tagged release image. It's not to be used. We will remove, it was an artifact from testing our automated release process.

I tried 7.0.2 tag (not the 7.2.0 tag) and that works. 

We will backfill the docker images with official release, but atm thats not a priority, focus is working for the Rho upgrade. Hope this answers this issue. If not, please reopen.
