### ISSUE TITLE
Send me more testnet token please

### ISSUE THREAD

**Issue by ItsFunny** [cosmos/gaia#1596]
I can join the testnet discord ,And My account is low balance
Please Send me more testnet tokens : cosmos10whr2tvcxmveces87kdrwp6xl42h02e84vedwh
Thanks

**Comment by yaruwangway** [comment]
Hi @uditvira, can you help ? Thank you!

**Comment by mmulji-ic** [comment]
hi @ItsFunny please request on Discord: https://discord.com/channels/669268347736686612/953697793476821092
Please reopen if you need some more help.
