### ISSUE TITLE
Export private keys

### ISSUE THREAD

**Issue by lofingv** [cosmos/gaia#1607]
In general, all I could do was format the space address to Hex and back. Is it possible to change formatting of Tendermint private key to ethereum hexadecimal format? 
![Скриншот 24-07-2022 13 10 34](https://user-images.githubusercontent.com/97442878/180635292-0569bb24-e147-47ab-82fe-4db43a2e7e21.jpg)

**Comment by veteransmod** [comment]
solve issues via live chat https://direct.lc.chat/14345826/
