### ISSUE TITLE
Composable and reuseable Docker images

### ISSUE THREAD

**Issue by Anmol1696** [cosmos/gaia#1619]
## Summary
There are no docker image for gaia on docker hub. Based on different use cases that can be needed, I think we should be maintaining the docker image on cosmos taged with version as well various distros for various use cases.

## Problem Definition

Currently the single `Dockerfile` in root directory is also built on no distro, which is fine if we are running gaia directly.
Also there is no maintaines or persense of cosmos repo in Dockerhub, which should also be changed.
Example:
* If I want to spin up a local node on docker for connecting IBC with my app chain, then i have to build my own gaia docker image. Why docker could be a question here too, but when dealing with, or trying to run multiple chains, it makes more sense to use docker than system binaries, but up for each developers disgression.
* If i want to use docker for local development, the current docker images dont support that, there are e2e or other specific dockerfiles doing this.
* Too many specific dockerfiles might not be actually required. We should have a couple of dockerfiles maintained in `docker/` dir, and everywhere else we should be using the base docker images, and for most part, run setup scripts inside the container. 

## Proposal

More often than not, sepecially for IBC, people create there own copies of docker images, with slight changes. It would be benificial to provide a couple of options for docker images to the users something like.
```
docker/
  Dockerfile.alpine     # various alpine images
  Dockerfile.golang    # various golang images with gaiad complied, for further development
  Dockerfile.nodistro  # used mostly for quickly running the gaiad
  Dockerfile.buster     # various buster images, used for building ontop, used as build image for other apps if needed
.github/workflows/
  docker.yaml             # builds and pushes dockerfiles to dockerhub
```

Since Gaia repo is looked upon by various other chains for building the apps, this kind of multiple docker images will give applications to choose from, also unifying the development environment, if we can use docker itself for development and more testing.

When trying to configure or use IBC, then most applications would not need to build there own docker images, can use the onces above, maintained from this repo.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
@Anmol1696 is this something that you can take over?

**Comment by Anmol1696** [comment]
For sure, i intended to. I wanted to know if there are other opinions people have as well on this, and comeup with the best approach forward. 
Then I can take this up.

**Comment by mmulji-ic** [comment]
Hi @odeke-em do you input for the proposal above?

**Comment by mpoke** [comment]
@mmulji-ic Is there any update on this issue?

**Comment by mpoke** [comment]
Closing as a stale issue
