### ISSUE TITLE
Gaia should maintain its own local version of its modules it uses

### ISSUE THREAD

**Issue by sunnya97** [cosmos/gaia#162]
Now that ~the Cosmos Hub~   Gaia is a launched chain, changes to it need to be approved by governance.  However, as it is currently using primarily modules from the core cosmos-sdk repo, we do not want to keep the development of core modules based on the Cosmos Hub governance.

I recommend that we fork the modules used by gaia from the cosmos-sdk repo into a modules folder within the gaia repo.  This way, the Cosmos SDK engineering team is able to maintain and upgrade the core modules as they wish, for the betterment of the Cosmos ecosystem at a large.

As Gaia governance approves changes to its own modules, the Gaia maintainers can downstream the relevant changes from the Cosmos-SDK repo.

This process will make Gaia development more in line with the development processes for other Cosmos chains.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
In theory, I believe this will probably end up turning to be the better approach. However, we don't really have a rich ecosystem of chains atm using the SDK as the basic framework. Of the ones that do, it doesn't seem to be too much of a pain point atm.

My immediate concern of doing this right is that sdk maintainers == gaia maintainers and as such will double the burden and surface area for errors. (e.g. simulation is gaia is kinda copy-pasta and we miss things sometimes).

What are your thoughts?

**Comment by sunnya97** [comment]
I think the number of SDK maintainers is increasing, as we see pull requests from core devs from Regen, Kava, etc.

The maintainers of the Gaia repo are "shackled" to the will of Gaia governance, but I don't want to halt SDK core module development by tying it to the on-chain governance of one chain.

I agree it's annoying, but I think its the reality of having a live chain and the complex software development dynamics of a general-purpose SDK and on-chain governance to decide feature upgrades.

**Comment by jackzampolin** [comment]
@sunnya97 We are over taxed with the current structure and have done quite a bit untangle dependancies already. Until we have a larger team dedicated to maintaining this I don't see this as practical or advisable. Also the PRs from other projects have gone a long way to make the modules more general and modular which is the point of reusable modules.

**Comment by ethanfrey** [comment]
I think this adds a whole lot of overhead. Currently gaia is tied to a given version of cosmos-sdk, so we can freely update sdk modules without affecting gaia.

Only when upgrading gaia deps, and it turns out the new sdk module is not in line with gaia, does this make sense to me. So, we added business logic changes in 0.38 that are distinct from gaia. Okay, you can copy the 0.36 modules into gaia and then upgrade those and maintain the fork.

No need to do it before it is needed, as this does add a huge amount of maintenance burden to an already overloaded core sdk team.

"If it ain't broke, don't fix it"

**Comment by ethanfrey** [comment]
> I think the number of SDK maintainers is increasing, as we see pull requests from core devs from Regen, Kava, etc.

As one of these contributors, I am happy to add new modules, which may or may not be used by gaia. As long as they don't alter core behavior, "does it fit with gaia" is not blocking me at all. 

What is blocking me is lack of time of core devs, leading to slow PR reviews. I think we should adopt the process that allows the most active core devs to make the fastest progress possible, while maintaining the high quality of the sdk.

**Comment by fedekunze** [comment]
@ethanfrey raised good points here. Adding the modules here will increase overhead and time spent on maintenance (which we lack of atm).

Closing
