### ISSUE TITLE
Fix automatic assignee

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1627]
## Summary

When creating new issues the gaia repo assigns a bunch of people for code review. I'm afraid this is turning to noise and we're not getting reviews as a result.

## Problem Definition

I'm having trouble finding docs that cover this. The only thing I've found is:
https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team
but it doesn't seem to cover our needs.

## Proposal

Figure out why it's assigning who it is and reduce it to a smaller group with higher reliability for reviews

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment]
looks like it's coming from CODEOWNERS.md https://github.com/cosmos/gaia/blob/main/.github/CODEOWNERS
and it seems like sam and maria got added for this PR: https://github.com/cosmos/gaia/pull/1616 because they are included for subdirectories of governance.

**Comment by mmulji-ic** [comment]
Just manually removed Maria and Sam from that issue in the UI.
@okwme looks like you manually added them ... see convo 

> @[okwme](https://github.com/okwme) okwme requested review from [ebuchman](https://github.com/ebuchman), [hxrts](https://github.com/hxrts) and [mariapao](https://github.com/mariapao) as [code owners](https://github.com/cosmos/gaia/blob/e97afd8109583b6222f85f095b0a09afe96c7158/.github/CODEOWNERS#L7) [23 hours ago](https://github.com/cosmos/gaia/pull/1616#event-7101548536)

This is the current reviewers list ... can we remove some people who are not actively reviewing?

okwme
alexanderbez
zmanian
yaruwangway
jgimeno
crodriguezvega
cmwaters
jackzampolin
mmulji-ic
glnro

**Comment by mmulji-ic** [comment]
Implemented in PR #1659

**Comment by mmulji-ic** [comment]
Close when @LexaMichaelides is added to the Github Hypha team.
