### ISSUE TITLE
Add Vesting E2E Tests

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1631]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by Pantani** [comment]
## Test Criteria

### Delayed vesting account

 - Create a delayed vesting account
 	- Balance should be equal to `original vesting coins`
 	- Transfer coins should fail
 	- Delegate coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins`

 - Wait until the `EndTime` reach
 	- Balance should be equal to `original vesting coins` - `delegated coins`
 	- Delegate coins should succeed
 	- Transfer coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`

### Permanently locked account

 - Create a permanently locked account
 	- Balance should be equal to `original vesting coins`
 	- Transfer coins should fail
 	- Delegate coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins`

### Continous vesting account

 - Create a continuous vesting account
 	- Balance should be equal to `original vesting coins`
 	- Transfer coins should fail
 	- Delegate coins should fail
 	- Balance should be equal to `original vesting coins` - `delegated coins`
  
 - Wait until the `StartTime` reach
 	- Balance should be equal to `original vesting coins`
 	- Transfer coins should fail
 	- Delegate coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins`
 
 - Wait the `(EndTime - StartTime) / 2` reach
 	- Balance should be equal to `original vesting coins` - `delegated coins`
 	- Delegate coins should succeed
 	- Transfer all coins should fail
 	- Transfer half of the coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`

 - Wait until the `EndTime` reach
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`
 	- Delegate coins should succeed
 	- Transfer all coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`

 	
**Formula**:

```
X := T - StartTime
Y := EndTime - StartTime
V' := OV * (X / Y)
V := OV - V'
```

### Periodic vesting account

 - Create a periodic vesting account
 	- Balance should be equal to `original vesting coins`
 	- Transfer coins should fail
 	- Delegate coins should fail
 	- Balance should be equal to `original vesting coins` - `delegated coins`
  
 - Wait until the first-period reach
 	- Balance should be equal to `original vesting coins`
 	- Delegate coins should succeed
 	- Transfer all coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`
 
 - Wait until the next period reach
 	- Balance should be equal to `original vesting coins`
 	- Delegate coins should succeed
 	- Transfer all coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`

 - Wait until the `EndTime` reach
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`
 	- Delegate coins should succeed
 	- Transfer all coins should succeed
 	- Balance should be equal to `original vesting coins` - `delegated coins` - `sent coins`
	
**Formula**:

```
CT := StartTime
Set V' := 0
# For each Period P:
X := T - CT
IF X >= P.Length {
	V' += P.Amount
	CT += P.Length
} ELSE {
	break
}
V := OV - V'
```
 
 
 ## CLI Commands:
 
```shell
# Add DelayedVestingAccount
gaiad add-genesis-account $DANILO_ADDR 500000uatom --vesting-amount 500000uatom --vesting-end-time <UNIX_ENDTIME>
# OR 
gaiad tx vesting create-vesting-account $DANILO_ADDR 55000000uatom <UNIX_ENDTIME> --from $BOB --gas auto --fees 5000uatom

# Add ContinuousVestingAccount
gaiad add-genesis-account $DANILO_ADDR 500000uatom --vesting-amount 500000uatom --vesting-start-time <UNIX_STARTTIME> --vesting-end-time <UNIX_ENDTIME>

# Add a permanently locked account
gaiad tx vesting create-permanent-locked-account $DANILO_ADDR 55000000uatom

# Add a periodic vesting account
gaiad tx vesting create-periodic-vesting-account $DANILO_ADDR <PERIODIC.json>

# Send Coins
gaiad tx bank send $DANILO_ADDR $BOB_ADDR 45000uatom --from danilo --gas auto --fees 50000uatom

# Delegate Coins
gaiad tx staking delegate $(gaiad keys show val1 --bech val -a) 4000uatom --from bla --gas auto --fees 5000uatom          

# Query Account
gaiad q account $DANILO_ADDR

# Query Balances
gaiad q bank balances $DANILO_ADDR
```
