### ISSUE TITLE
Add Liquidity E2E Tests

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1633]
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
This issue is blocked by https://github.com/cosmos/gaia/issues/2084.

**Comment by mmulji-ic** [comment]
The liquidity module will be removed soon, therefore additional e2e tests are not required.
