### ISSUE TITLE
Release v7.0.3

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1639]
## Summary

7.0.x contains a bump of Cosmos SDK in preparation of v7.0.3. This issue tracks other items to include (or consider including)

## Proposal

Include the following in v7.0.3

* [x]  #1638 
* [ ]  #1486 
  *  after doing a spike to determine the scope of the work
* [ ]  Test on live network for 24 hours (where are the other release checklists documented again @glnro?)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
released! thanks! @glnro @mmulji-ic
