### ISSUE TITLE
E2E tests failing intermittetently

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1643]
## Summary of Bug

There is an account sequence mismatch now that we've added back IBC tests. It happens more often on the deposit gov test than others but it's been spotted on a few. We should refactor the tests so that the account sequence isn't wrong.

## Steps to Reproduce

https://github.com/cosmos/gaia/runs/7613974783?check_suite_focus=true

but error isn't printing anything very helpful here.

I've got a new branch I'm trying things out.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
hi, can you post the err log ?

**Comment by okwme** [comment]
this is solved with #1640 
putting more tech debt e2e issues together for PRs like #1652
