### ISSUE TITLE
Ensure all relevant docker images are in cosmos org

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1645]
## Summary

- [x] we were using a tendermintdev dockerhub image of gaia for releases but don't have access to that account.
- [x] we should ensure that all relevant docker images for gaia are maintained here.
there's also the `Dockerfile` in the root dir of the project that I have no record of where it's being used, let's confirm where or remove it if it's redundant.
- [x] jacob's also got a docker image for use in gitpod, we should try consolidating that work, either through submodule or as a copy to ensure you don't have to go scrambling all over the place for each instance of docker relevant to the hub
other docker images we may want to create listed in #1619 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment]
- reproducible builds docker image is stored on tendermint devs dockerhub account and should be swapped out

**Comment by mpoke** [comment]
@mmulji-ic @MSalopek Is this issue still relevant? I think goreleaser removed the dependency, right?

**Comment by MSalopek** [comment]
Goreleaser removed tendermint deps for now.
Moving to v47 removes all other deps for proto builds. The proto-builder is already under cosmos org.

Closing for now.
