### ISSUE TITLE
Add packet forward middleware E2E tests

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1653]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by jackzampolin** [comment]
We have an existing e2e test for this that Justin wrote: https://github.com/strangelove-ventures/ibctest/blob/main/examples/packet_forward_test.go

**Comment by jackzampolin** [comment]
would you like this added into gaia?

**Comment by okwme** [comment]
wow great looking test @jackzampolin !
this looks really clean but i'm wary of adding a new testing framework in the middle of finalizing other e2e tests before an upgrade.
we have an open issue for e2e refactors after this upgrade that it might fit into better.
for this e2e i'd like to just do a minimal version that uses 2 networks instead of 3.
this should still be possible right?
send from account A on chain A to account B on chain A via account C on chain B?
(pointless use of the module but should confirm it's working correctly right?)

**Comment by mmulji-ic** [comment]
Duplicate issue closing in favour of #1361
