### ISSUE TITLE
docs: create a Features doc

### ISSUE THREAD

**Issue by nooomski** [cosmos/gaia#1668]
## Summary

We should have a page listing all the Hub features currently on-chain.

## Problem Definition

It's hard to see what the Hub actually does at the moment. This document could be an overview that links to additional documentation.

## Proposal

Would suggest to add this as `docs/hub-overview/features.md` until we have a better structure in place.

Structure of items in this doc:

- [ ] Interchain Security (when Lambda comes)
- [ ] Interchain Accounts
- [ ] Packet Forwarding Middleware
- [ ] Governance - (just some brief words on decentralized nature of the product, how it funds the ecosystem, with links to gov docs)
- [ ] Groups
- [ ] Other Modules (e.g. Global Fee, Authz, Feegrant)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Closing as docs were updated:
* https://hub.cosmos.network/main/getting-started/what-is-gaia
* a list of supported on-chain modules is available starting with `v18.x`.

In case the link was broken use link below for refetence
* https://github.com/cosmos/gaia/blob/v18.1.0/docs/docs/getting-started/what-is-gaia.md
