### ISSUE TITLE
Add new socials

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1671]
## Summary

missing https://twitter.com/CosmosGov from our socials section of readme

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by de-marauder** [comment]
Hi, is this issue still available? I'd like to work on it.

**Comment by mmulji-ic** [comment]
Hi @de-marauder it is, do you want to pick it up?

**Comment by de-marauder** [comment]
Hello @mmulji-ic, I would love to pick it up. Could you assign it to me and I'll get to work on it straight away.

**Comment by mmulji-ic** [comment]
Hi @de-marauder assigned!

**Comment by de-marauder** [comment]
Hello @mmulji-ic, I have submitted a PR for this issue in #2260

**Comment by mmulji-ic** [comment]
Thanks @de-marauder merged!
