### ISSUE TITLE
test fees for relayers

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1672]
## Summary

Cosmoshub will have two fees setups: global fee and min gas price in rho. Global fee is a new feature. 
test case 0: if global fee and min gas price is in different denoms, or each time proposing a new global fee,  the gas-price should change accordingly in order to work or continue to work.

test case 1: gas-price in hermes config has to be equal to or higher than the fee required in globalfee/min_gas _price in app.toml. If a high global fee is proposed, the present gas-price in hermes config might be too low. After gas price in hermes config updated and hermes restarts, check the existing channels and newly created channels are working with new fees.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
The above issue will be tested in dev testnet as discussed.

**Comment by okwme** [comment]
confirmed tested by @dasanchez in devnet.
