### ISSUE TITLE
Issue with the creation of client for testing the IBC

### ISSUE THREAD

**Issue by vdsprakash** [cosmos/gaia#168]
## Summary of Bug

There is an issue with the unmarshall of state.json in the creation of client.(IBC module check)
## Version

go version: go1.12.4 linux/amd64
gaiad version: 0.0.0-100-g9248903
gaiacli version: 0.0.0-100-g9248903

## Steps to Reproduce

Following the readme at [https://github.com/cosmos/gaia/blob/3ecb2998195e6afbd5f061e1558a3881275d4d76/cmd/gaiacli/README.md](url)

Command: ` gaiacli --home ibc1/n0/gaiacli tx ibc client create c1 state0.json --from n0 -y
`

Error message : **failed to unmarshall input into struct, checking for file...ERROR: error unmarshalling state file: cannot parse disfix JSON wrapper: invalid character 'c' looking for beginning of value**
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by angelorc** [comment]
Also this command
```
gaiacli --home ibc1/n0/gaiacli q ibc client node-state > state-ibc1.json
````

Output:
```
IBC client query subcommands

Usage:
  gaiacli query ibc client [command]

Available Commands:
  consensus-state Query the latest consensus state of the client
  header          Query the latest header of the running chain
  state           Query a client state
  root            Query a verified commitment root

Flags:
  -h, --help   help for client

Global Flags:
      --chain-id string   Chain ID of tendermint node
  -e, --encoding string   Binary encoding (hex|b64|btc) (default "hex")
      --home string       directory for config and data (default "/home/angelo/.gaiacli")
  -o, --output string     Output format (text|json) (default "text")
      --trace             print out full stack trace on errors

Use "gaiacli query ibc client [command] --help" for more information about a command.
```

**Comment by glnro** [comment]
Hi @vdsprakash, thanks for posting your issue! We've been behind on many reviews and apologize for such. Would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team
