### ISSUE TITLE
CI Nits

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1693]
## Summary of Bug

This commit:

https://github.com/cosmos/gaia/commit/76da6d29354be409ac72b0839eeccc488a50014b

Indicates strongly that we've got some CI issues to clean up.  Merges to main should never skip any step of CI, and they should always pass all CI checks. 

## Version

`main`

## Steps to Reproduce

I am not sure (yet)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment]
hi @faddat thanks for the issue.
I'm confused what's going on here.
the commit link you give has a failed test but the same commit passes when viewed from the merged PR.
i'm not sure if this is a problem with our CI or some kind of bug in github?
do you have any insight on what the difference between these two views might be?
<img width="487" alt="Screen Shot 2022-09-12 at 11 48 13" src="https://user-images.githubusercontent.com/964052/189624160-3cfc6966-05a1-46fb-91a7-cf7079011303.png">
<img width="877" alt="Screen Shot 2022-09-12 at 11 46 48" src="https://user-images.githubusercontent.com/964052/189623959-a4cc8dcc-7a3f-44cb-a977-c60395a18b67.png">

**Comment by okwme** [comment]
@mmulji-ic is adding a daily check to try to make sure these are always passing.
we realized it was an external dependency targeting `latest` that broke main recently and this would highlight that sooner for us.

nondeterminism is run on PRs targeting `release**` or PRs with the tag `sim`

we've increased the instances where tests are run based on your previous PRs @faddat , are there other areas you're suggesting we further modify or is the incoming change from @mmulji-ic sound like enough to close this?

**Comment by mpoke** [comment]
@mmulji-ic is still still relevant?

**Comment by mmulji-ic** [comment]
Hi @faddat , as Billy mentioned we've updated our nightly tests so that the full suite is run. https://github.com/cosmos/gaia/actions/runs/4069953631

We're always looking improve coverage and depth, if you have any suggestion please let me know.
