### ISSUE TITLE
All cosmos hub code should live here

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1696]
## Summary

Currently, working on the hub is harder than it needs to be because we've got to upgrade the liquidity module and/or the IBC router.

The best way to deal with this, is for modules imported by gaia, to live in gaia (especially if like the liquidity module and the ibc router, they were built primarily for gaia).

This would exclude:

* cosmos-sdk modules
* tendermint
* cosmos-db or tm-db

And include anything else, like the liquidity module and the IBC router. 

## Type

Build and code debt

## Impact

By moving key modules into gaia's repository, it becomes easier to maintain gaia, and PR's will require less coordination. 

## Proposed Solution

For now, the easiest path is to move the liquidity module and the IBC router into this repository.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by dimiandre** [comment]
I remember at the beginning of Cosmos everything was inside gaia repo, it has been separated after a while. 

I think some very hub-specific modules can maybe be moved here, importing everything will cause unnecessary copy-paste and boilerplate code between the two repos

**Comment by mmulji-ic** [comment]
Thanks @faddat , we have imported some modules directly into the repo, will assess whether we want the same with these. Thanks for starting this discussion. We have an upcoming session to look at a number of technical debt issues, possible to address then.

**Comment by okwme** [comment]
hey @faddat 
i feel the pain you refer to.
at this point the relevant modules are maintained by the teams that built them and so it's up to them how to manage them.
liquidity belongs to b-harvest and packet forwarding belongs to strangelove.
liquidity will go away which will simplify things but unless the gaia integration team becomes responsible for maintaining the packet forwarding i don't think it should live in gaia (there would need to be a lot of onboarding to being able to maintain the repo as well, basically the maintainers should be able to know how to fix it if it's broken too) 

mauth is the first module being maintained by the gaia integration team and so lives in the repo.
are there other modules you had in mind that would make sense to move here?

**Comment by okwme** [comment]
hey @faddat 
haven't heard back, will close in another week if there's no further objection to discuss

**Comment by faddat** [comment]
hey, questions:

* how will liquidity go away?
* can't strangelove work in this repository directly?

When we worked on https://github.com/pylons-tech/pylons the productivity boost gained from moving everything to a single repository was enormous.  

I think that moving those two here would help flow a great deal.  I'll make an example PR for liquidity.. should show just how much smoother that'd make things

**Comment by mpoke** [comment]
@faddat I opened [this issue](https://github.com/cosmos/gaia/issues/2084) for the Liquidity module. Regarding the packet forward middleware module, that's for now maintain and updated by Strangelove. We'll asses at a later date the need for the module.
