### ISSUE TITLE
Minimum Commission for proposal 76

### ISSUE THREAD

**Issue by MiB-Intern** [cosmos/gaia#1697]
## Summary

If proposal 76 passes, validator min commission should be enforced onchain.

## Problem Definition

Right now MsgEditValidator and MsgCreateValidator allow any commission value, we should check that c.Rate is above the amount decided by governance.

## Proposal

- Write AnteHandle for minimum commission check
- Write Upgrade Handler for validator commission update

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Prop [#76](https://www.mintscan.io/cosmos/proposals/76) end-date: 2022-09-08

**Comment by okwme** [comment]
closing as this proposal failed
