### ISSUE TITLE
Update Interchain Security to Cosmos SDK 0.47

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1714]
## Summary

Interchain Security is based on SDK 0.45, therefore a migration needs to occur to SDK 0.47.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
For details, see https://github.com/cosmos/interchain-security/milestone/3

**Comment by mpoke** [comment]
Closing as this work is being tracked in https://github.com/cosmos/interchain-security/issues/852
