### ISSUE TITLE
Integrate Interchain Security into Gaia

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1715]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by glnro** [comment]
https://github.com/cosmos/gaia/issues/1715

**Comment by mpoke** [comment]
ICS will be included in Gaia v9, which is WIP. See https://github.com/cosmos/gaia/tree/v9.0.0-rc1. Closing this issue as non needed.
