### ISSUE TITLE
Updated e2e Staking module tests for Liquid Staking

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1716]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
@mmulji-ic Could you add more info to this issue?

**Comment by mmulji-ic** [comment]
This was a potential feature for Rho/Lambda, but was dropped for both. I suggest closing this and creating a new issue/epic when this is relevant again.
