### ISSUE TITLE
EPIC: Update Gaia to use SDK 0.47

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1717]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by faddat** [comment]
We shouldn't make any release on 46.

**Comment by mpoke** [comment]
Closing in favor of https://github.com/cosmos/gaia/issues/2413
