### ISSUE TITLE
feat(init): Improve the init command

### ISSUE THREAD

**Issue by Pantani** [cosmos/gaia#1722]
## Summary

Improve the init command so we can quickly spin up new nodes

## Problem Definition

Starting a new node in any network can be painful without some configurations like peers and RPC servers. Engaging new users can be difficult and still tricky for the old users.

## Proposal

**Solution 1**

Add the network flag to the init command, the developer can pass only the network ID, and we can easily fetch some default peers, RPC-server, minimum gas fee, and other parameters:

E.g.:
```shell
gaiad init --network tetha-v7

gaiad init --network tetha-v7 --statesync
```
For this solution, we can use our mainnet and testnet registry repo, but we can also create a 3thr party chain registry repo for the chain developer can register your chain, and we can init with one line only.

And we can also add more flags for we can add into the config:
```shell
gaiad init --network tetha-v7 --config.statesync.enable false --app.minimum-gas-prices 0.0025uatom
```
 
 **Solution 2**
 
It's similar to the last solution, but instead, we pass a network id, we should give a URL or local path for a init file as we have for mainnet 

 E.g.:
```shell
gaiad init --network https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json

gaiad init --network /Users/home/chain.json
```
 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by puneet2019** [comment]
would love to see this feature!

**Comment by okwme** [comment]
we should be able to use https://github.com/cosmos/chain-registry for this : )

**Comment by okwme** [comment]
could be bundled into this issue: https://github.com/cosmos/gaia/issues/1592

**Comment by mpoke** [comment]
Closing as not needed
