### ISSUE TITLE
bug(log): Discovered new snapshot logs show a not correctly decoded hash

### ISSUE THREAD

**Issue by Pantani** [cosmos/gaia#1727]
## Summary of Bug

Discovered new snapshot logs show a not correctly decoded hash.

![Screen Shot 2022-08-31 at 11 46 20](https://user-images.githubusercontent.com/2406457/188545862-93a6590d-02e1-4abd-9c2b-3b1e65ae6d3b.png)

## Version

v7.0.3

## Steps to Reproduce

Sync a new chain in mainnet.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by glnro** [comment]
@Pantani I think this should be moved to Tendermint

**Comment by cmwaters** [comment]
FYI: https://github.com/tendermint/tendermint/pull/9471
