### ISSUE TITLE
missing ziphash

### ISSUE THREAD

**Issue by diligentaf** [cosmos/gaia#1729]
I get this error when I run make install 👇
The current go version is : go version go1.18beta1 linux/amd64

`root@ubuntu-s-2vcpu-4gb-intel-fra1-01:~/gaia# make install
--> Ensure dependencies have not been modified
github.com/cosmos/gaia/v8/tests/e2e : missing ziphash: open hash: no such file or directory
make: *** [Makefile:131: go.sum] Error 1
`

**Comment by yaruwangway** [comment]
please do 

```
rm go.sum
go mod tidy
```
and retry install

**Comment by okwme** [comment]
hello @diligentaf any update here?
we will close the issue if we don't hear back in another week

**Comment by diligentaf** [comment]
I figured it out.
Thanks guys!!!
