### ISSUE TITLE
Create Gov mediated ICA E2E Test

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1746]
## Problem Definition

Once `icamauth` is in main we will be able to test the entire user flow of creating and controlling an interchain account using the new gov module. The current gov E2E and the current icamauth E2E do not contain this flow.

We should make a new E2E test that focuses on the goveranance use case of interchain accounts.

## Proposal

Outline the exact flow based on @hxrts input.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by hxrts** [comment]
Happy path for Cosmos Hub swapping tokens on Osmosis and moving them back to its own community pool.
1. arbitrary message proposal: create interchain account for the cosmos hub gov module on osmosis
2. community spend proposal: 1000 ATOM, local gov module is recipient
3. arbitrary (multi) message proposal: IBC send from local gov module to remote interchain account address on osmosis + ICA exchange message to desired pool with size, slippage, etc.
4. arbitrary message proposal: ICA IBC transfer from remote ICA account back to the hub community pool

steps 2 and 3 can be combined in the next release of the cosmos sdk with bez's community pool/gov refactor https://github.com/cosmos/cosmos-sdk/pull/12852

**Comment by okwme** [comment]
blocked on cosmos sdk release v0.46.5

**Comment by mpoke** [comment]
@mmulji-ic Is this still relevant?

**Comment by mpoke** [comment]
Delayed until we upgrade to SDK 0.47

**Comment by sainoe** [comment]
closed in favour of https://github.com/cosmos/gaia/issues/2539.
