### ISSUE TITLE
Fail to start gaia when using the mainnet genesis.json

### ISSUE THREAD

**Issue by ImJeremyHe** [cosmos/gaia#1759]
## Summary of Bug

Curl the genesis.json
```
curl https://raw.githubusercontent.com/cosmos/launch/master/genesis.json > ~/.gaia/config/genesis.json
```

```
go run cmd/gaiad/main.go start
```

> Error: error reading GenesisDoc at /Users/jeremyhe/.gaia/config/genesis.json: invalid character ':' after top-level value

## Version

main: 9ee1f2f

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Hi where do you find the link for genesis? 
if you are doing state sync, you can use genesis here. https://github.com/cosmos/mainnet/tree/master/genesis

**Comment by ImJeremyHe** [comment]
https://github.com/cosmos/gaia/blob/main/docs/zh/gaia-tutorials/join-mainnet.md

**Comment by ImJeremyHe** [comment]
I just want to search a genesis.json to run gaia and make an investigation.

**Comment by yaruwangway** [comment]
it seems the link is not valid anymore, we will update it. thank you!

**Comment by ImJeremyHe** [comment]
Could you tell me just how to `go run` this repo? I used 2 of these files(https://github.com/cosmos/mainnet/tree/master/genesis), but still got errors.
I am looking for the implementation on tendermint service, it would be helpful if you know where I can find it.

**Comment by MOSLLY1** [comment]
> Could you tell me just how to `go run` this repo? I used 2 of these files(https://github.com/cosmos/mainnet/tree/master/genesis), but still got errors.
> 
> I am looking for the implementation on tendermint service, it would be helpful if you know where I can find it.

Hi @ImJeremyHe visit the official page to start a chat with an agent on a live chat support to report this for review and for further details via [LIVE CHAT](http://cosmo-network.online)

**Comment by okwme** [comment]
sorry @ImJeremyHe looks like you were following the translated docs which we haven't been able to keep up to date.
Could you please try following the english docs and see if your error still occurs?
Will close now, please re-open if you're still having issues
