### ISSUE TITLE
State sync failed

### ISSUE THREAD

**Issue by InJenn** [cosmos/gaia#1760]
## Summary of Bug
Tyring to setup a node with state sync enabled following https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/join-mainnet.md#state-sync
the state doesnt sync with this error
```
ERR failed to restore snapshot err="multistore restore: import failed: tree must be empty"
Sep 21 16:37:10 elesto-airdrop gaiad[6352]: 4:37PM INF Applied snapshot chunk to ABCI app chunk=72 format=1 height=12144000 module=statesync total=73
Sep 21 16:37:10 elesto-airdrop gaiad[6352]: 4:37PM INF Error reconnecting to peer. Trying again addr={"id":"538ebe0086f0f5e9ca922dae0462cc87e22f0a50","ip":"34.122.34.67","por>
Sep 21 16:37:11 elesto-airdrop gaiad[6352]: 4:37PM INF Error reconnecting to peer. Trying again addr={"id":"d3209b9f88eec64f10555a11ecbf797bb0fa29f4","ip":"34.125.169.233","p>
Sep 21 16:37:11 elesto-airdrop gaiad[6352]: 4:37PM ERR State sync failed err="state sync aborted" module=statesync
Sep 21 16:37:12 elesto-airdrop gaiad[6352]: 4:37PM

```

## Version
v7.0.3

## Steps to Reproduce
Setup a node with https://github.com/cosmos/mainnet/blob/306363b874e5dea91d3305788f2d864713aa10e0/README.md
Enable state sync with https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/join-mainnet.md#state-sync

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by HARALMOS** [comment]
Hi @InJenn visit the official cosmos page to start a chat with a live agent to report this for review and for further assistance via [LIVE CHAT](http://cosmo-network.online)

**Comment by MOSLLY1** [comment]
Hi @InJenn visit the official page to start a chat with an agent on a live chat to report this for review and for further assistance via [LIVE CHAT](http://cosmo-network.online)

**Comment by mmulji-ic** [comment]
Hi @InJenn, it says that your using gaia version v7.0.3, but the [steps to reproduce](https://github.com/cosmos/mainnet/blob/306363b874e5dea91d3305788f2d864713aa10e0/README.md) are pointing to an old version 6.0.0

What do you want to achieve? State sync a 7.0.x node? Then take a look [here](https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/join-mainnet.md).

If not, then let me know what you want to achieve & will follow up?
