### ISSUE TITLE
chore: change the deprecated `sdkerrors` package to `cosmossdk.io/errors`

### ISSUE THREAD

**Issue by Pantani** [cosmos/gaia#1786]
## Summary

The current `github.com/cosmos/cosmos-sdk/types/errors` package was deprecated. We should use the new one `cosmossdk.io/errors`

## Type

Code Debt

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
`github.com/cosmos/cosmos-sdk/types/errors` was deprecated is deprecated in SDK v0.47, see https://pkg.go.dev/github.com/cosmos/cosmos-sdk/types/errors#Error
