### ISSUE TITLE
feat: add bech32-convert to gaia

### ISSUE THREAD

**Issue by glnro** [cosmos/gaia#1788]
## Summary
Add the  `bech32-convert` subcommand to `debug` that is currently implemented in osmosis. This would serve as a general UX improvement as well as prepare for future roadmap features like bech32 forwarding.

## Problem Definition
If a user wishes to convert a bech32 address to the equivalent on another chain, there is currently no way to do this via the gaia cli.

## Proposal
Implement `ConvertBech32Cmd` in gaia according to [osmosis' command](https://github.com/osmosis-labs/osmosis/blob/e90fc2dec83e11de942ed007527e7611a8eab188/cmd/osmosisd/cmd/bech32.go). Nice to have implementation could also include abstracting the logic out into a separate helper function.

The command should natively convert any address to the `cosmos` prefix, and accept a flag for an alternative chain prefix. 

## Acceptance Criteria
1. Should natively convert any valid bech32 address to a cosmos prefixed address
Input:
`gaiad debug bech32-convert akash1a6zlyvpnksx8wr6wz8wemur2xe8zyh0ytz6d88`
Output:
`cosmos1a6zlyvpnksx8wr6wz8wemur2xe8zyh0yxeh27a`

2. Should convert any valid bech32 address to the prefixed address
Input:
`gaiad debug bech32-convert cosmos1a6zlyvpnksx8wr6wz8wemur2xe8zyh0yxeh27a --prefix osmo`
Output:
`osmo1a6zlyvpnksx8wr6wz8wemur2xe8zyh0ywzy6g0`

3. Should return the same address if converting a native address
Input:
`gaiad debug bech32-convert cosmos1a6zlyvpnksx8wr6wz8wemur2xe8zyh0yxeh27a`
Output:
`cosmos1a6zlyvpnksx8wr6wz8wemur2xe8zyh0yxeh27a`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by ivanovpetr** [comment]
Would be happy to work on it!

**Comment by okwme** [comment]
thank you @ivanovpetr !!!
