### ISSUE TITLE
docs: Gaia Docs Upgrade needs a facelift

### ISSUE THREAD

**Issue by glnro** [cosmos/gaia#1794]
## Summary

In the [Gaia Docs](https://hub.cosmos.network/), there's several sections covering the subject of upgrades. 
Under Tutorials:
[Joining Mainnet: Releases & Upgrades](https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html#releases-upgrades)
[Upgrading Your Node](https://hub.cosmos.network/main/hub-tutorials/upgrade-node.html)
[Live Upgrade Tutorial](https://hub.cosmos.network/main/hub-tutorials/live-upgrade-tutorial.html)

Some of this information is out of date, or needs to be consolidated. 

Additionally, important information including [software versions and upgrade heights](https://github.com/cosmos/gaia/tree/main/docs/roadmap) are not in an easy to access location in the docs.

## Type
Documentation Debt

## Impact
As more devs and users in the ecosystem need to access earlier versions of the cosmos hub and run historical queries, and with two important upgrades approaching, the hub team can expect an increased volume of queries on the subject. This could contribute to a negative user experience, constrained team resources, and potentially open up individuals to making otherwise avoidable mistakes.

## Proposed Solution
Take inventory of the current upgrade docs, speak with stakeholders, and develop an MVP outline for critical topics to address in the docs. Consolidate what currently exists with what's missing, and create a single location in the docs for users to rely on. 

Additionally, adding information from [cosmos hub history](https://github.com/cosmos/gaia/tree/main/docs/roadmap) to [cosmos.directory](https://cosmos.directory/cosmoshub/chain) would also reduce confusion about historical upgrade information.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by nooomski** [comment]
Here's an [overview](https://docs.google.com/spreadsheets/d/1t3yLw5xCZmrbeiUqJrDYfqzsSuoPrbtK-_n4RV-i_EU) of all the current docs and a proposed structure that was discussed with the Hub team at Interchain as well as Hypha.
