### ISSUE TITLE
Tech Debt: 47 instead of 46

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1828]
Hey, so,

Myself and Notional have been likely the largest users of the 46 series SDK.  

Kudos to efforts from Umee, as well.

With that said--

I think that we should retract it.

Notional's efforts around Cosmos SDK v0.46.* are on pause due to dragonberry.  While one side of my brain is screaming "hey, we gotta patch 46, and get going again" I try my best to stick to realism and pragmatism.  

There aren't enough experienced engineers in cosmos to maintain all of the things well.  47 contains a number of clear improvements over 46, and will likely result in more maintainable, nimble chains for all.  I'd like to recommend:

* efforts at patching 46 be redirected towards building 47 and ensuring that 45 and 44 are very solidly patched
* 47 be considered a "unity release" -- key libraries like:

  * ibc-go
  * cosmwasm
  * interchain-accounts-demo

Should be upgraded to 47.  

Therefore I propose:

* ecosystem efforts be directed towards ensuring that 44 and 45 are secured against dragons
* Teams using 46 (Umee, Pylons, Quasar, okp4, eve, and a few others ) be assisted with migration away from 46 in a very active, hands-on manner to ensure that when 47 makes its final release, all support for 46 can be terminated
* Concise migration documents be created containing best practices and guidelines for moving to 47 from 44, 45, 46.
* Efforts to communicate the changes in 47 communicated on twitter, facebook, youtube, etc
* Osmosis-sdk terminated in favor of 47
* Termination of efforts to move Gaia to 46
* Officially frowning upon SDK forks, and facilitating replaces / patches in the style of https://github.com/iqlusioninc/liqudity-staking-module / https://github.com/mars-protocol/hub

Notional and I ca help with a great deal of this work.  Overall, we feel that it is best to secure what's widely deployed (44, 45) and then move to 47 while providing assistance to teams who've deployed 46 or are building on 46.

If you would like to join a chat group on this topic, please drop your twitter handle here and I'll spin that up.  

**to re-emphasize: I genuinely think it's best to walk away from 46**

**to re-emphasize: we should prioritize 44 and 45, then 47**

**to re-emphasize: Gaia should never make a release on 46**

## Key Github Issues relating to 47

https://github.com/cosmos/cosmos-sdk/issues/13408

https://github.com/cosmos/cosmos-sdk/issues/13456

**Comment by mpoke** [comment]
Thanks @faddat. The current plan is to upgrade directly to SDK 0.47.
