### ISSUE TITLE
Quicksync with existing validator private key doesn't work

### ISSUE THREAD

**Issue by bb4L** [cosmos/gaia#1836]
## Summary of Bug

I tried to setup an cosmos node with quicksync using a existing validator private key ( following the instructions given here: https://hub.cosmos.network/main/getting-started/quickstart.html )

When i try to start the node i always get the following output:

```
panic: state.AppHash does not match AppHash after replay. Got
...
cosmos  | Did you reset Tendermint without resetting your application's data?

```

## Version
`7.1.0`

## Steps to Reproduce
- setup quicksync node form the docs (https://hub.cosmos.network/main/getting-started/quickstart.html)
-  add the private key of the validator 
-  run the node `gaiad start --x-crisis-skip-assert-invariants`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by williambanfield** [comment]
Hey @bb4L, does this same issue occur with different keys or only with the key you are using? I don't _think_ that that should influence the AppHash here :thinking:

**Comment by tac0turtle** [comment]
it looks like you didnt reset you application data. When using quicksync or a snapshot you have to reset-unsafe in order to reset the application state. Its not possible to stop your node, switch db data and height then start without resetting

**Comment by bb4L** [comment]
> Hey @bb4L, does this same issue occur with different keys or only with the key you are using? I don't _think_ that that should influence the AppHash here 🤔

i _think_ having no key defined would have started it up iirc


> it looks like you didnt reset you application data. When using quicksync or a snapshot you have to reset-unsafe in order to reset the application state. Its not possible to stop your node, switch db data and height then start without resetting

but if i would do the `reset-unsafe` then i would resync from scratch wouldn't i? so the quicksync wouldn't be used, would it?

**Comment by tac0turtle** [comment]
> but if i would do the `reset-unsafe` then i would resync from scratch wouldn't i? so the quicksync wouldn't be used, would it?

you need to reset then put the new data into the data directory. then it will start up

**Comment by bb4L** [comment]
> > but if i would do the `reset-unsafe` then i would resync from scratch wouldn't i? so the quicksync wouldn't be used, would it?
> 
> you need to reset then put the new data into the data directory. then it will start up

ok i did that:
-  reset
- import with quicksync

but i still get the same error
