### ISSUE TITLE
Tech Debt(e2e): create a docker package

### ISSUE THREAD

**Issue by Pantani** [cosmos/gaia#1841]
## Summary

All code and logic is inside the e2e package. We should create a reusable package to handle docker exec commands so we can easily call and reuse them along the project. This will create a better abstraction and understanding of the code.

## Type

Architecture Debt | Code Debt 

## Impact

Harder to maintain and understand

## Proposed Solution

Create the docker package so we can call in the e2e tests

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by Pantani** [comment]
also, we can have a better organization by splitting the other helpers go files into packages like:

```
- e2e (e2e tests and helper packages)
  - resources (docker files and scripts)
  - docker (docker package to handle docker commands)
  - query
  - chain (chain and validator stuff)
  - io (handle file and genesis stuff)
  - wallet (handle adders and mnemonic stuff)
```

**Comment by mpoke** [comment]
@MSalopek could you please asses the utility of the proposed solution?

**Comment by MSalopek** [comment]
The ideas here are great and we can use them in the future.
It would require major overhaul of the e2e system so I would not do this right away.

We should do it next time we introduce major features to the e2e testing framework

**Comment by mpoke** [comment]
Closing as the amount of work needed does not justify the benefits. See https://github.com/cosmos/gaia/issues/1841#issuecomment-1466182028
