### ISSUE TITLE
tech debt(x/globalfee): missing tests for globalfee module

### ISSUE THREAD

**Issue by Pantani** [cosmos/gaia#1847]
## Summary

Test are missing for `globalfee` types, client, and ante handler.

## Type

Test Debt

## Impact

We need more test coverage to rely on the code.

## Proposed Solution

- Add tests for `ante/fee_utils.go` methods
- Add tests for `cli/query` commands
- Add tests for `ante/params.go` methods

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Hi, @Pantani , if you did not start working on this one ? i can take it.

**Comment by Pantani** [comment]
Great!! You can take this one. I didn't start yet

I think a table test should fit good here

**Comment by yaruwangway** [comment]
add global fee cli test: https://github.com/cosmos/gaia/pull/1858#issuecomment-1303526624
