### ISSUE TITLE
build: create `curl` gaia binary install script

### ISSUE THREAD

**Issue by Pantani** [cosmos/gaia#1848]
## Summary

Create a script so we can easily download Gaia instead build from the source or manually download from GitHub.

## Problem Definition

We can make the developer's life easier by creating a script for downloading and installing the Gaia binary without building from the source or manually downloading.

## Proposal

Create a script so we can download and install the binary as the [Ignite does](https://docs.ignite.com/#install-ignite-cli):

```shell
curl https://get.ignite.com/cli! | bash
```

We can create the same logic for Gaia:

```shell
curl https://get.cosmos.com/gaia! | bash
```

And we can also choose a binary version:

```shell
curl https://get.cosmos.com/gaia@v7.1.0 | bash
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
See #1592 , check with Hypha how far they are with their script

**Comment by Pantani** [comment]
this is the standard install script. It's easy to use and we can up it quickly:

https://github.com/jpillora/installer
https://github.com/ignite-hq/installer

**Comment by mpoke** [comment]
@mmulji-ic is this issue still relevant?

**Comment by mpoke** [comment]
@yaruwangway what's the status of this issue?

**Comment by mpoke** [comment]
Closing as this might result in a potential security issue.
