### ISSUE TITLE
remove usage of cosmos-sdk/simapp

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/gaia#1883]
## Summary of Bug

We should remove all usages of simapp we are able to, in 0.47 the dependence of simapp should be non existent. This quick and easy migration now should help the upgrade later on

**Comment by mpoke** [comment]
Closing as this work is tracked by https://github.com/cosmos/gaia/issues/2540

**Comment by sainoe** [comment]
Sovled by #2744
