### ISSUE TITLE
Create Group mediated ICA E2E Test

### ISSUE THREAD

**Issue by Pantani** [cosmos/gaia#1904]
## Problem Definition

Once `icamauth` is in main we will be able to test the entire user flow of creating and controlling an interchain account using the group module. The current gov E2E and the current icamauth E2E do not contain this flow.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
@mmulji-ic is this still relevant?

**Comment by mpoke** [comment]
Closing as duplicate #1746
