### ISSUE TITLE
IBC using fee keeper improperly

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#1910]
the [ICA host is using the fee keeper as the ](https://github.com/cosmos/gaia/blob/main/app/keepers/keepers.go#L338)ics4wrapper but if it is not planned to use fee middleware, then you could just use the channel keeper, like it's done [in the ICA controller](https://github.com/cosmos/gaia/blob/main/app/keepers/keepers.go#L330). However we still have the feekeeper, we should either remove it or use it correctly.

**Comment by yaruwangway** [comment]
Hi @damiannolan, can we just replace `appKeepers.IBCFeeKeeper` -> `appKeepers.IBCKeeper.ChannelKeeper` ?
also, when I registered ica, I have to pay a fee which is higher than the chain required. Do you know if this is related to Hermes or ica module ? thank you!

**Comment by damiannolan** [comment]
> can we just replace `appKeepers.IBCFeeKeeper` -> `appKeepers.IBCKeeper.ChannelKeeper`?

Yes, the fee keeper should be replaced with the channel keeper as @okwme suggests. Both `controller` and `host` modules should be configured to either both use the fee keeper _or_ both use the channel keeper as the `ICS4Wrapper` argument of the `NewKeeper` constructor funcs. As long as they are both aligned its fine. Note that its possible to have both use the fee keeper but still create a non-incentivized (fee disabled) channel, the fee middleware will simply pass through and no-op if that's the case. 
Whether the channel is created as fee enabled or disabled is based off of the [`msg.Version` arg provided here](https://github.com/cosmos/gaia/blob/main/x/icamauth/keeper/msg_server.go#L30). 

> when I registered ica, I have to pay a fee which is higher than the chain required

I'm not sure this is directly related to interchain accounts, but the gas costs should be more than a regular bank send for example. I am assuming this is referring to gas fees(?), the gas costs are expected to be more than usual as the controller module's `RegisterInterchainAccount` method routes a `MsgChannelOpenInit` [here](https://github.com/cosmos/ibc-go/blob/main/modules/apps/27-interchain-accounts/controller/keeper/account.go#L68-L73) to core ibc to initiate the channel handshake (a relayer then acts on the events emitted to complete the subsequent handshake steps).
This would result in higher gas costs for more store read/writes as more actions are being performed.

Does this make sense? If you have any more questions don't hesitate to ask! :)

**Comment by yaruwangway** [comment]
Thank you so much !

**Comment by mpoke** [comment]
@yaruwangway is this issue still relevant?

**Comment by yaruwangway** [comment]
This was for ibc-go v5 in gaia v8-rc,  we can close it.
