### ISSUE TITLE
Unable to sign multisignature transaction

### ISSUE THREAD

**Issue by poiug07vsys** [cosmos/gaia#1916]
I followed [this tutorial](https://www.figment.io/resources/how-to-multi-sig-on-cosmos) and [official tutorial](https://hub.cosmos.network/main/hub-tutorials/gaiad.html#multisig-transactions), updating the necessary parts.

On `gaiad tx multisign unsignedTx.json k1k2k3 k1.json k2.json > signedTx.json`
if fails with:
```
Enter keyring passphrase:
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account cosmos1uemhvfl5v6590hkkwn9jfcgtgmnjla0e3faa08 not found: key not found
```

How to reproduce on fresh installation of gaiad(ubuntu docker container):
1. `gaiad keys add ki` for i=1,2,3
2. `gaiad keys add k1k2k3 --multisig-threshold=2 --multisig=k1,k2,k3`
3. `gaiad tx bank send cosmos1uemhvfl5v6590hkkwn9jfcgtgmnjla0e3faa08 cosmos1uemhvfl5v6590hkkwn9jfcgtgmnjla0e3faa08 10000uatom --generate-only > unsignedTx.json`
4. `gaiad tx sign unsignedTx.json --multisig=cosmos1uemhvfl5v6590hkkwn9jfcgtgmnjla0e3faa08 --from=k1 --output-document=k1signature.json --chain-id cosmoshub-4`

Notes:
* gaiad version: v7.1.0
* Adding --amino and/or --offline flags doesn't help.

**Comment by Meryn00** [comment]
@poiug07vsys visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by okwme** [comment]
I think that's correct, this account doesn't exist: https://www.mintscan.io/cosmos/account/cosmos1uemhvfl5v6590hkkwn9jfcgtgmnjla0e3faa08

**Comment by poiug07vsys** [comment]
@okwme 
> I think that's correct, this account doesn't exist: https://www.mintscan.io/cosmos/account/cosmos1uemhvfl5v6590hkkwn9jfcgtgmnjla0e3faa08

Sorry, I am quite new to this chain itself. Do I need to somehow register on chain first before using some keys? My expected behaviour - it will generate and sign these transactions and just fail with insufficient amount or smth.

**Comment by yaruwangway** [comment]
Hi @poiug07vsys,  in step3 generating unsigned tx, you need to add `--from=<multisig_address> `

please let me know if this is still an issue, thank you!

**Comment by poiug07vsys** [comment]
Thanks everyone. The error was in fact that the address is not registered and does not exist on chain at the time of tx broadcast. I didn't know address need to be present on chain to work.
