### ISSUE TITLE
app: (*GaiaApp).prepForZeroHeightGenesis mixes panic and log.Fatal

### ISSUE THREAD

**Issue by odeke-em** [cosmos/gaia#1925]
The code in that mentioned method mixes panics with log.Fatal of which log.Fatal immediately ends the program and doesn't allow any deferred functions to run for cleanup nor any recovers either. We need to ascertain which need panics and which don't. At least a comment in the code would make things much better
![image](https://user-images.githubusercontent.com/4898263/203666322-163a5f03-5733-48b7-8b08-de74ebf4d643.jpeg)

/cc @elias-orijtech @mmulji-ic

**Comment by yaruwangway** [comment]
Fatal is removed.
