### ISSUE TITLE
performance: send over CPU and RAM profiles to Orijtech for analysis

### ISSUE THREAD

**Issue by odeke-em** [cosmos/gaia#1926]
Kindly reaching out for overall performance and security profiling quarterly so as to figure out what's going on in gaiad and help improve things. Please kindly follow the instructions below to collect and send over profiles to us at Orijtech Inc per https://www.notion.so/orijtech/gaiad-CPU-Memory-profiling-c6d71648cd4c4e0792a016e52ccb257b#d547be1b4f0e48beb1180b712b19d2d3 or inlined below

# gaiad CPU & Memory profiling

## Problem statement:

Our goal is to help debug what's consuming RAM inside gaiad instances. Collecting profiles helps us figure out what’s going on inside nodes and what to focus on for performance targets For this we have to get creative and perhaps rely on discrete continuous profiles by folks running nodes on their mainnet. The instructions below will collect profiles over say 1.5 hours, you can increase the time by increasing the number of profiles collected

## Goals:

- Hook into the mainnet through a node running gaiad
- Use net/http/pprof as the HTTP endpoint
- Collect CPU and RAM profiles by passing in a custom profiles collector

## Step 1: add net/http/pprof into cmd/gaiad

Firstly plus stop your running gaiad. Next we shall add profiling hooks into a patch of gaiad. To do so please edit the file `cmd/gaiad/main.go` and make it look like this having added our pprof import 

```go
package main

import (
        "net/http"
        _ "net/http/pprof"
        "os"

        svrcmd "github.com/cosmos/cosmos-sdk/server/cmd"
        "github.com/cosmos/cosmos-sdk/server"

        app "github.com/cosmos/gaia/v8/app"
        "github.com/cosmos/gaia/v8/cmd/gaiad/cmd"
)

func main() {
        go func() {
                if err := http.ListenAndServe(":6060", nil); err != nil {
                        panic(err)
                }
        }()

        rootCmd, _ := cmd.NewRootCmd()

        if err := svrcmd.Execute(rootCmd, "", app.DefaultNodeHome); err != nil {
                switch e := err.(type) {
                case server.ErrorCode:
                        os.Exit(e.Code)
                default:
                        os.Exit(1)
                }
        }
}
```

Please now run make install and get your node running again. After say 10 seconds once it is running great, please proceed onto the next step. 

## Step 2: Collect profiles

Please add this code below to a file called `collect_profiles.go` 

```go
package main

import (
	"archive/zip"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"path/filepath"
	"time"
)

func main() {
	dir := "gaiad_profiles"
	if err := os.MkdirAll(dir, 0755); err != nil {
		panic(err)
	}

	zipfileName := filepath.Join(dir, "profiles.zip")
	outzip, err := os.Create(zipfileName)
	if err != nil {
		panic(err)
	}
	defer func() {
		if err := outzip.Close(); err != nil {
			panic(err)
		}
		println("Please submit the zip file", zipfileName)
	}()

	zw := zip.NewWriter(outzip)
	if err != nil {
		panic(err)
	}
	defer zw.Close()

	const durInSeconds = 67 // 1min7seconds
	const url = "http://localhost:6060/debug/pprof"
	for i, n := 0, 60; i < n; i++ {
		// 1. Send a request for the CPU profile
		cpuProfile, err := fetchBody(url+"/profile", durInSeconds)
		if err != nil {
			panic(err)
		}
		ramHeapProfile, err := fetchBody(url+"/heap", durInSeconds)
		if err != nil {
			panic(err)
		}
		if err := writeOutToZips(zw, i+1, cpuProfile, ramHeapProfile); err != nil {
			panic(err)
		}

		fmt.Printf("Completed %d/%d profiles\r", i+1, n)
		time.Sleep(47 * time.Second)
	}
}

func writeOutToZips(zw *zip.Writer, fileIndex int, cpuProfile, ramProfile []byte) error {
	baseName := fmt.Sprintf("%d", fileIndex)
	wcf, err := zw.Create(baseName + ".cpu")
	if err != nil {
		return err
	}
	if _, err := wcf.Write(cpuProfile); err != nil {
		return err
	}

	wmf, err := zw.Create(baseName + ".mem")
	if err != nil {
		return err
	}
	if _, err := wmf.Write(ramProfile); err != nil {
		return err
	}
	return nil
}

func fetchBody(url string, durInSeconds int) ([]byte, error) {
	url += fmt.Sprintf("?seconds=%d", durInSeconds)
	res, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()

	if code := res.StatusCode; code < 200 && code >= 300 {
		return nil, fmt.Errorf("%v failed to get a 2XX=>%d", res.Status, code)
	}

	return ioutil.ReadAll(res.Body)
}
```

and then run it by `go run collect_profiles.go` it should run for about ~38 minutes or so and each time it'll print out the progress. The profiles will be stored in a zip file under `gaiad_profiles/profiles.zip`

## Step 3: Send over your .zip file with the 60 profiles

Send your profiles over to Orijtech Inc. Please upload the zip file `gaiad_profiles/profiles.zip` and email to `emmanuel@orijtech.com`
____

Kindly cc-ing @okwme @mmulji-ic and team

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by faddat** [comment]
@baabeetaa 's research shows that pebbledb uses far less RAM than goleveldb in archive node scenarios.  (5x less)

I'd also posit that the meaningful performance bottleneck in most cases in not RAM or CPU, but in fact iops.

**Comment by yaruwangway** [comment]
Hi @odeke-em, I sent the performance test results  to your email, thank you !

**Comment by odeke-em** [comment]
> Hi @odeke-em, I sent the performance test results  to your email, thank you !

Awesome and thank you @yaruwangway! I did receive the profiles and took a look but was travelling over the weekend and I shall analyze them with the team perhaps this week.

**Comment by mmulji-ic** [comment]
Hi @odeke-em do you need more performance profiles? If so we can generate as needed. 
Do let us know your findings. If theres a specific issues with mem/perf, please open a targeted issue to investigate that problem.

**Comment by mmulji-ic** [comment]
Hi @odeke-em closing as this has been open for some time with no response.
