### ISSUE TITLE
New containers don't build old gaias

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1973]
This can be seen in the liveness test:

* https://github.com/cosmos/gaia/pull/1972

**Comment by mpoke** [comment]
Thanks @faddat. Is this issue still relevant?

**Comment by mpoke** [comment]
@faddat Could you please provide more context for this issue?

**Comment by mpoke** [comment]
@fadat Please note that we are currently maintaining only the latest two major releases of Gaia. We'll close this issue in one week due to the lack of activity.
