### ISSUE TITLE
ICA is not working?

### ISSUE THREAD

**Issue by ItsFunny** [cosmos/gaia#1977]
## Summary of Bug
'unable to resolve type URL /gaia.icamauth.v1beta1.MsgRegisterAccount: tx parse error'

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by ItsFunny** [comment]
I was tried to register ICA account ,But it failed with tx parse error

```
 gaiad tx icamauth register --from admin16 --connection-id connection-1670 --fees 1000uatom --chain-id theta-testnet-001 --node https://rpc.sentry-02.theta-testnet.polypore.xyz:443 -y -b block --fees 1000uatom
code: 2
codespace: sdk
data: ""
events: []
gas_used: "6675"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'unable to resolve type URL /gaia.icamauth.v1beta1.MsgRegisterAccount: tx
  parse error'
timestamp: ""
tx: null
txhash: 7D19D74152EDBF61C38F241E2D587230235EEDA2D80DF10CA9D2DD97FB2F27DA


```

**Comment by yaruwangway** [comment]
Hi, i think theta-testnet is running on binary without icamauth module. which binary version you use ?

**Comment by ItsFunny** [comment]
@yaruwangway  Hi I use the commit before the icamauth module was removed
And I found theta-testnet can still handle the ica message

**Comment by yaruwangway** [comment]
yeah, icamuath will not be in the next release, maybe next next. i think theta-testnet still the ica-host enabled, but no icamauth.

**Comment by ItsFunny** [comment]
Thanks 
Got it , close
