### ISSUE TITLE
test unjail in CLI and LCD

### ISSUE THREAD

**Issue by fedekunze** [cosmos/gaia#200]
_Originally posted by @fedekunze in https://github.com/cosmos/cosmos-sdk/pull/2842/review_comment/create_

I created the `doUnjail` function on cosmos/cosmos-sdk#2842, but it needs a jailed validator to be called from in order to pass the test.

**Comment by tmckenzie51** [comment]
Hi @fedekunze ! Thanks for posting your issue! We've been behind on many reviews and apologize for such. Would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team
