### ISSUE TITLE
Fast Node

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2006]
To test with current gaia:

```bash
git clone https://github.com/cosmos/gaia
gh pr checkout 2005
go install ./...
gaiad init test
```

change:
```toml
iavl-disable-fastnode = false
```

in app.toml 

then convert a pruned snapshot from quicksync:

```
cd ~/.gaia
wget https://dl2.quicksync.io/cosmoshub-4-pruned.20230110.0310.tar.lz4
lz4 -d cosmoshub-4-pruned.20230110.0310.tar.lz4 | tar xf -
time time gaiad start --p2p.seeds 3b67739570f921cc5e0db4b3efe488ce184155a9@seeds.pupmos.network:2000,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14956 
```

```log
real	7m44.687s
user	15m8.741s
sys	1m26.643s
```

The node started immediately.  Now I'll check if we have fast node enabled, I don't think we do.

**Comment by mpoke** [comment]
@faddat Do you have an update on this issue?

**Comment by mpoke** [comment]
@faddat Not clear what's the problem description and a satisfactory closing criteria. Closing for now, please reopen if necessary.
