### ISSUE TITLE
Repository consolidation

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2014]
Because the Cosmos organization is used for many different pieces of software, it can be difficult for people to navigate through it and find the information that they need about the cosmos Hub.

Let's move the mainnet and fundraiser repositories contents inside of this repository so that they can be found more easily, and deprecate the old ones so that this repository becomes the canonical source of information about the hub.

https://twitter.com/seppwurscht/status/1613494872417116162

**Comment by mpoke** [comment]
Thanks for the suggestion @faddat. The fundraiser repo is deprecated and archived. Re. the mainnet repo, we prefer to keep it separate for now as moving it will involve to much coordination work. We'll make it clear in README.md where the info re. the mainnet can be found.

**Comment by mmulji-ic** [comment]
@faddat issue will be resolved as indicated by @mpoke , here https://github.com/cosmos/gaia/issues/2064
