### ISSUE TITLE
upgrade to go 1.19 for v8

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2015]
Go versions can't be too low, but they can be too high.

For greater consistency, we can upgrade to go 1.19 so that all validators will be using the same go runtime. 

* https://github.com/cosmos/cosmos-sdk/issues/13976

**Comment by mpoke** [comment]
Thanks @faddat for opening the issue. Gaia v8 and v9 will use SDK 0.45.11, which uses go 1.18. Once we update to SDK 0.47, we'll also upgrade the go version.
