### ISSUE TITLE
Build tags assigned incorrectly ("netgo ledger,") with Make 4.3+

### ISSUE THREAD

**Issue by sigv** [cosmos/gaia#2017]
## Summary of Bug

[Appending More Text to Variables](https://www.gnu.org/software/make/manual/html_node/Appending.html) is done in [Makefile](https://github.com/cosmos/gaia/blob/v7.1.0/Makefile#L25-L60) when working with build tags.
Something changed in Make 4.3 regarding empty values being appended to themselves using the `+=` operator.

Ubuntu 20.04 LTS ships with Make 4.2 and results in build tags `"netgo,ledger"`.
Ubuntu 22.04 LTS ships with Make 4.3 and results in build tags `"netgo ledger,"`.

Quoting the Make documentation:
> Using ‘+=’ is similar to:
> ```make
> objects = main.o foo.o bar.o utils.o
> objects := $(objects) another.o
> ```
> but differs in ways that become important when you use more complex values. 

## Version

Any project version, when building with Make 4.3 or Make 4.4.

## Steps to Reproduce

Tested on Ubuntu 22.04.1, however should apply to any distro/version as we are building upstream Make for test:

```bash
sudo apt -qy install make gcc

WORKSPACE=$(mktemp -d --tmpdir make.XXX)
cd "$WORKSPACE"

# Create minimal Makefile based on logic in repository

cat >Makefile <<EOF
build_tags = netgo
build_tags += ledger

whitespace :=
whitespace += \$(whitespace)
comma := ,
build_tags_comma_sep := \$(subst \$(whitespace),\$(comma),\$(build_tags))

.PHONY: all
all:
$(echo -e '\t')@echo '"\$(build_tags_comma_sep)"'
EOF

# Additional Makefile that uses explicit assignment

cp Makefile Makefile.proposal
sed -i 's/^whitespace += \$(whitespace)$/whitespace := $(whitespace) $(whitespace)/' Makefile.proposal

# Build relevant Make versions for testing

wget -nv https://ftp.gnu.org/gnu/make/make-4.2.tar.gz && tar -xf make-4.2.tar.gz
# Make 4.2 does not play nice with newer releases. Needs a patch to check "newer or equal" instead of just "equal".
sed -i 's/^# if _GNU_GLOB_INTERFACE_VERSION == GLOB_INTERFACE_VERSION$/# if _GNU_GLOB_INTERFACE_VERSION >= GLOB_INTERFACE_VERSION/' make-4.2/glob/glob.c
(cd make-4.2 && ./configure && make)

wget -nv https://ftp.gnu.org/gnu/make/make-4.3.tar.gz && tar -xf make-4.3.tar.gz
(cd make-4.3 && ./configure && make)

wget -nv https://ftp.gnu.org/gnu/make/make-4.4.tar.gz && tar -xf make-4.4.tar.gz
(cd make-4.4 && ./configure && make)

# Try to use the Makefiles.

make-4.2/make -f Makefile
# "netgo,ledger"
make-4.3/make -f Makefile
# "netgo ledger,"
make-4.4/make -f Makefile
# "netgo ledger,"

make-4.2/make -f Makefile.proposal
# "netgo,ledger"
make-4.3/make -f Makefile.proposal
# "netgo,ledger"
make-4.4/make -f Makefile.proposal
# "netgo,ledger"

cd
rm -rf "$WORKSPACE"
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by sigv** [comment]
It looks like [Gaia v7.1.0](https://github.com/cosmos/gaia/releases/tag/v7.1.0) was built with Make 4.3+ as well:
```text
$ ./gaiad-v7.1.0-linux-amd64 version --long 2>&1 | head -n5
name: gaia
server_name: gaiad
version: v7.1.0
commit: 5db8fcc9a229730f5115bed82d0f85b6db7184b4
build_tags: netgo ledger,
```

**Comment by yaruwangway** [comment]
Hi @sigv, thank you for opening this issue, can you check if this PR fixes what you addressed in this issue ? https://github.com/cosmos/gaia/pull/2051

**Comment by yaruwangway** [comment]
ha, sry, just saw you already opened pr, will review! @sigv

**Comment by sigv** [comment]
> ha, sry, just saw you already opened pr, will review!

No worries! And thank you!

Some background:

We (kjnodes) discovered this with [lavanet/lava@v0.4.0](https://github.com/lavanet/lava/blob/v0.4.0/Makefile#L47-L59), where the `-X` flag was not quoted, resulting in build failure. Most derivate Cosmos-based chains appear to have copy-pasted the `-X` flag quoted, as visible in [cosmos/gaia@v7.1.0](https://github.com/cosmos/gaia/blob/v7.1.0/Makefile#L68). This enables spaces in the `$(build_tags_comma_sep)` to build properly. From my understanding, this doesn't directly affect any operational aspect of the node itself, therefore backporting is entirely optional.

As for the proposed change itself, we [proposed it to Lava Network](https://github.com/lavanet/lava/commit/fff3de0c06a7a59aeb2fcceea4a5a1902c75e90e) and it was released in [lavanet/lava@v0.4.3](https://github.com/lavanet/lava/blob/v0.4.3/Makefile#L47-L59). It gets the job done. The test scenario to do is just spin up a fresh VM on 20.04 and 22.04, run builds with and without patch, compare output of `version` subcommand from the built binary. Looks reasonable to me.

Let me know if I can help with anything else!

**Comment by sigv** [comment]
@yaruwangway, any chance of having the change reviewed?

**Comment by yaruwangway** [comment]
Hi @sigv , i reviewed, all good, but we need two reviewers to get merged, i will ask my colleagues.

**Comment by sigv** [comment]
Much appreciated! 🙏🏻🥂
