### ISSUE TITLE
Tech Debt: Check all the errors and panics

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2062]
## Summary
In global fee, there are some panics related to [getting/filtering coins](), 
sdk [coin'methods also have panics](https://github.com/cosmos/cosmos-sdk/blob/4f6f6c00021f4b5ee486bbb71ae2071a8ceb47c9/types/coin.go#L86), a discussion related is [here](https://github.com/cosmos/cosmos-sdk/issues/3246#issuecomment-1399339954).
shall we return err so the err log is cleaner ?

A general check of gaia panics, fatal are also needed.

## Type
Code Debt

## Proposed Solution

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
@yaruwangway what's the status of this issue?

**Comment by yaruwangway** [comment]
The old globalfee has some coins methods that contains panic when there is err. since v11, globalfee is refactored to use sdk coins methods, therefore, this is not an issue anymore.
