### ISSUE TITLE
Add Hermes e2e tests

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2067]
Integrate Hermes e2e tests into Gaia CI for testing IBC. 

Hermes is already well tested with a gaiad version in hermes repo CI. Gaia repo can just utilize the hermes test with a gaiad version need to be tested.

- [ ] discuss with hermes team the hermes ci test coverage
- [ ] integration of hermes ci test into gaia repo

**Comment by yaruwangway** [comment]
Hi @mpoke, can you give me a bit more background ? we have hermes setup and is used for testing ibc transfer, PFM etc in CI.

**Comment by yaruwangway** [comment]
The following issues need to be figured out:
- [ ] Trigger gitHub actions across different repositories
- [ ] Config hermes test with a specific gaiad binary version, config tests to run
- [ ] Gaia repo should get test result in gaia CI.
- [ ] hermes integration tests take 30-40min, how often to run this across repo test need to be decided.
- [ ] How to check log , how easy the err can be reproduced, if gaia repo can get directly log here.
- [ ] which hermes version to use ? latest hermes release ?

more details can be found in [discussion notes](https://docs.google.com/document/d/1Q6C9vYmpF4WxfMzff_y5RL08MGXx-gM82OuNIFowbyE/edit)

**Comment by mpoke** [comment]
Closing as not needed. Hermes is already tested in e2e tests.
