### ISSUE TITLE
State sync update

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2078]
## Summary
Regarding to hub state-sync, the followings need to be fixed:
- [ ] The state sync rpc server is unavailable. https://rpc.cosmos.network/
- [ ] Find a reliable source to curl live peers, ref: https://polkachu.com/live_peers/agoric
- [ ] Update the [tutorial](https://hub.cosmos.network/main/getting-started/quickstart.html)

## Proposed Solution

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by faddat** [comment]
hey :)

I wanna suggest a whole lot that we do not attempt to fix this until v8.0.x is out and then we never again follow the policy of simply not updating existing releases. 

This is ludicrously difficult to fix before v8 is running on mainnet, and I suggest that we devote time elsewhere

**Comment by faddat** [comment]
* https://github.com/cosmos/gaia/pull/2079

Next is update state sync script then will take out of draft

**Comment by faddat** [comment]
The PR is now ready for review. 

I made an omnibus update to v7.0.x that tidies all the things.

State sync from my laptop succeeds.

**Comment by faddat** [comment]
https://github.com/cosmos/gaia/pull/2079

**Comment by yaruwangway** [comment]
present tutorial was updated and tested working
