### ISSUE TITLE
EPIC: Work towards EOL for the Liquidity module

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2084]
# Problem

The [Liquidity module](github.com/gravity-devs/liquidity) is no longer used.

# Closing criteria

The Liquidity module is removed

```[tasklist]
### Must have
- [ ] https://github.com/cosmos/gaia/issues/2346
```

```[tasklist]
### Nice to have

```

**Comment by faddat** [comment]
* https://github.com/cosmos/gaia/pull/2423

I do not believe that this is possible on any realistic timeline if we are to meet the ship schedule of version 10.

If we include this in version 10, we should expect to ship version 10 sometime between November 2023 and March 2024, if at all.

Let's get into a realistic conversation about the liquidity module. It is there. That is unfortunate. None of us wants it there. But what could be more harmful than removing a fairly benign but stupid module that goes against the grain of what we're trying to build with the hub these days?

Slashing users.
