### ISSUE TITLE
Test: Rosetta API 

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2085]
## Summary
[Rosetta]( https://www.rosetta-api.org/) is an open-source specification and set of tools for blockchain integration.
`RosettaCommand` is provided by sdk. Cosmos-sdk uses https://github.com/coinbase/rosetta-sdk-go v0.7, the latest is v0.8.

For gaia v8, `The Rosetta server is still a beta feature.` 

```
gaiad rosetta
WARNING: The Rosetta server is still a beta feature. Please do not use it in production
```

Discussion: do we test Rosetta API ?

## Proposed Solution

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
@yaruwangway What's the status of this issue?

**Comment by yaruwangway** [comment]
still the same when i test gaiad v9 , v9 is using rosetta 0.7.9
```
WARNING: The Rosetta server is still a beta feature. Please do not use it in production.
```
can bump 0.8.3 to try

**Comment by yaruwangway** [comment]
it is the same warning with rosetta v0.8.3, it is used by sdk

**Comment by mmulji-ic** [comment]
@yaruwangway can we test whether rosetta is wired correctly to complete this task? I understand that its a feature that we include historically, but we can put a health warning in the documentation.

**Comment by MSalopek** [comment]
Closing as it is no longer relevant.

Re-open if you need to.
