### ISSUE TITLE
The rpc request is abnormally slow

### ISSUE THREAD

**Issue by rayn316** [cosmos/gaia#2160]
## Summary of Bug

During the processing of some rpc requests, the time to return data is very long

The return time of this request interface is normal
```
curl -s -w '\n%{time_connect}:%{time_starttransfer}:%{time_total}\n' http://127.0.0.1:31442/cosmos/bank/v1beta1/params
{
  "params": {
    "send_enabled": [
    ],
    "default_send_enabled": true
  }
}
0.000088:0.001172:0.001198
```

This interface took a total of 67s, which is very strange
```
curl -s -w '%{time_connect}:%{time_starttransfer}:%{time_total}\n' http://127.0.0.1:31442/cosmos/staking/v1beta1/validators/cosmosvaloper1qphf0ferqcch0jca9hlqfm3x0eds3dpkcvpafp/delegations
{
  "delegation_responses": [
    {"delegation":{"delegator_address":"cosmos1qphf0ferqcch0jca9hlqfm3x0eds3dpkac4g9j","validator_address":"cosmosvaloper1qphf0ferqcch0jca9hlqfm3x0eds3dpkcvpafp","shares":"1000000.000000000000000000"},"balance":{"denom":"uatom","amount":"1000000"}}
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
0.000120:67.170058:67.170089
```

## Version

v7.1.0
v7.1.1

## Steps to Reproduce

# set
/node/full/cosmos/bin/gaiad init name --chain-id cosmoshub-4 --home /node/full/cosmos/
wget https://raw.githubusercontent.com/cosmos/mainnet/master/genesis/genesis.cosmoshub-4.json.gz
gzip -d genesis.cosmoshub-4.json.gz
mv genesis.cosmoshub-4.json /node/full/cosmos/config/genesis.json
curl -s addrbook.json https://snapshots.polkachu.com/addrbook/cosmos/addrbook.json -O /node/full/cosmos/config/addrbook.json

dasel put string -f /node/full/cosmos/config/app.toml "api.enable" "true"
dasel put string -f /node/full/cosmos/config/app.toml "api.address" "tcp://0.0.0.0:31442"
dasel put string -f /node/full/cosmos/config/app.toml "api.max-open-connections" "5000"
dasel put string -f /node/full/cosmos/config/app.toml "api.rpc-read-timeout" "15"
dasel put string -f /node/full/cosmos/config/app.toml "minimum-gas-prices" "0.0025uatom"

# snapshot
apt-get install wget liblz4-tool jq -y
export URL=`curl -L https://quicksync.io/cosmos.json|jq -r '.[] |select(.file=="cosmoshub-4-pruned")|.url'`
axel -n 30 $URL
lz4 -c -d `basename $URL` | tar xf -

# run
/node/full/cosmos/bin/gaiad start --home /node/full/cosmos/ --p2p.laddr tcp://0.0.0.0:31440 --rpc.laddr tcp://0.0.0.0:31441

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by rayn316** [comment]
These two interfaces also have the problem of returning data slowly or being stuck
```
curl -s -w '\n%{time_connect}:%{time_starttransfer}:%{time_total}\n' http://127.0.0.1:31442/cosmos/upgrade/v1beta1/current_plan

curl -s -w '\n%{time_connect}:%{time_starttransfer}:%{time_total}\n' http://127.0.0.1:31442/cosmos/auth/v1beta1/accounts
```

**Comment by yaruwangway** [comment]
Hi, can you check your logs ? if the node is running normally ?

**Comment by yaruwangway** [comment]
if your logs are mostly `peer conn` info with occasionally `commit block` info ?
```
INF commit synced commit=436F6D6D697449447B5B323020323433203137372031333820323220393720313137203235342037362032203133362031333120313636203136203234312031303420313338203136342031343720313638203137332031303120313930203133312032353220323137203831203732203233382032323620313235203139305D3A4435363233347D
```


```
NF service start impl="Peer{MConn{5.161.119.242:49656} 5d45bc48f6c0199c047e685fafb4309f53593f37 out}" module=p2p msg={} peer={"id":"5d45bc48f6c0199c047e685fafb4309f53593f37","ip":"5.161.119.242","port":49656}
INF service start impl=MConn{5.161.119.242:49656} module=p2p msg={} peer={"id":"5d45bc48f6c0199c047e685fafb4309f53593f37","ip":"5.161.119.242","port":49656}
Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"5d45bc48f6c0199c047e685fafb4309f53593f37","ip":"5.161.119.242","port":49656}
```

**Comment by rayn316** [comment]
During normal operation, the fast height is the same as that of the browser, and there is no error log.
![image](https://user-images.githubusercontent.com/24621599/217406501-e7084068-b580-406c-b7b5-f7804c87f385.png)

**Comment by rayn316** [comment]
When requesting the official api, you can also find that it takes a long time and has a great impact on node performance.
```
curl -s -w '\n%{time_total}\n' https://api.cosmos.network/cosmos/staking/v1beta1/validators/cosmosvaloper1qphf0ferqcch0jca9hlqfm3x0eds3dpkcvpafp/delegations

{
  "delegation_responses": [
    {"delegation":{"delegator_address":"cosmos1qphf0ferqcch0jca9hlqfm3x0eds3dpkac4g9j","validator_address":"cosmosvaloper1qphf0ferqcch0jca9hlqfm3x0eds3dpkcvpafp","shares":"1000000.000000000000000000"},"balance":{"denom":"uatom","amount":"1000000"}}
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
98.464274
```

**Comment by yaruwangway** [comment]
Hi, it is slow, there are more than 800,000 validators' delegations. This query iterates them


@MSalopek thanks for checking!

**Comment by MSalopek** [comment]
@sundafa
Thanks for sharing this and going through the trouble of getting a concise problem report. 
Did you experience similar issues on other Cosmos SDK based networks?

----
I generally agree that having slow queries is a nuisance, so here is some additional context: 
when `<API>/cosmos/staking/v1beta1/validators/<valoper_addr>/delegations
` query is being executed the entire delegation store is iterated until the specified pagination limit is reached (usually thats 100 records). At this moment that means checking >800 000 records (worst case).

These are the relevant parts of the Cosmos SDK code:
- https://github.com/cosmos/cosmos-sdk/blob/sainoe/v0.45.13-ics/types/query/filtered_pagination.go#L18
- https://github.com/cosmos/cosmos-sdk/blob/sainoe/v0.45.13-ics/x/staking/keeper/grpc_query.go#L88

I think it's common practice to store data in a separate database that is updated periodically and use it as part of your backend.

One example of that is https://github.com/forbole/bdjuno. Here, the backend service is connected to both an RPC node and a postgres database for pefrormance reasons.

Another option would be opening an issue on Cosmos SDK and suggesting changes to how queries are executed.

**Comment by rayn316** [comment]
Use other chains Tgrade and akash
Did not find the slow return of this rpc interface

```
curl -s -w '\n%{time_total}\n' https://tgrade-mainnet-rpc.allthatnode.com:1317/cosmos/staking/v1beta1/validators/tgrade1wlagucxdxvsmvj6330864x8q3vxz4x02d0ssjl/delegations

curl -s -w '\n%{time_total}\n' https://akash-api.polkachu.com:443/cosmos/staking/v1beta1/validators/akashvaloper1qvsus5qg8yhre7k2c78xkkw4nvqqgev7zw5wzs/delegations
```

**Comment by yaruwangway** [comment]
Hi,  the result return time is related to how many delegations are there, and how early the iteration comes to the validator the query queries. 
you can insert code to your local sdk https://github.com/cosmos/cosmos-sdk/blob/sainoe/v0.45.13-ics/types/query/filtered_pagination.go#L18 to count the delegations it iterates through.

**Comment by mpoke** [comment]
@sundafa Do you have any update regarding this issue?

**Comment by mpoke** [comment]
@sundafa , we'll close this issue for now. If the issue persists we can always re-open.
