### ISSUE TITLE
p2p is choked

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2182]
Problem:

Currently Gaia's p2p network is choked, due to low default inbound peers in both Tendermint and gaia. 

Solution:

```go
// initTendermintConfig helps to override default Tendermint Config values.
// return tmcfg.DefaultConfig if no custom configuration is required for the application.
func initTendermintConfig() *tmcfg.Config {
	cfg := tmcfg.DefaultConfig()

	// these values put a higher strain on node memory
	cfg.P2P.MaxNumInboundPeers = 320
	cfg.P2P.MaxNumOutboundPeers = 40

	return cfg
}
```

The problem with this solution is that it won't change existing configs.  Recommend that node operators update to an 8:1 configuration like the one shown below, so that we have enough inbound slots for users syncing gaia.

**Comment by mmulji-ic** [comment]
Hi @thanethomson any thoughts on the impact that we need to be aware of?

**Comment by mmulji-ic** [comment]
Hi @faddat talked to the Tendermint team about your suggestion, feedback was that it would result in a lot of traffic, so using these values as is is not viable. Would like to experiment with the 8:1 ratio a bit more. btw Are the latest fixes to tendermint not making an appreciable impact?

**Comment by mmulji-ic** [comment]
@faddat closing this as the original solution was not accepted. I'm assuming that upcoming improvements to Comet and the slew of parameter change props `843`, `844` & `845` will also have a +ve performance impact.
