### ISSUE TITLE
Problem with `gaiacli tx staking edit-validator` and moniker

### ISSUE THREAD

**Issue by 7768** [cosmos/gaia#219]
## Summary of Bug

```
$ gaiacli tx staking edit-validator --help
...
      --moniker string           The validator's name (default "[do-not-modify]")
...
```

When running this command
`gaiacli tx staking edit-validator --identity=AAAAAAAAAAAAAAAA`
Instead of respecting `[do-not-modify]` for when moniker isn't specified, the moniker itself gets updated all the time.

## Version

```
$ gaiacli version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.3
commit: 2f6783e298f25ff4e12cb84549777053ab88749a
build_tags: netgo,ledger
go: go version go1.12.1 darwin/amd64
```

## Steps to Reproduce

`gaiacli tx staking edit-validator --identity=AAAAAAAAAAAAAAAA --dry-run`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I attempted to replicate this without success. It does not look like a bug to me. In any case, please verify you are using the latest SDK version. If the issue persists, please create an issue in the SDK repo 👍
