### ISSUE TITLE
signature verification failed; please verify account number (11) and chain-id (ibc-test-1): unauthorized

### ISSUE THREAD

**Issue by fuluomin** [cosmos/gaia#2191]
when I use http://xxxxxxx:1317/cosmos/tx/v1beta1/txs to send  a tx ,I meet a question,

"raw_log": "signature verification failed; please verify account number (11) and chain-id (ibc-test-1): unauthorized",

I use gaiad version v7.0.0

I find some way ,like "gaiad config chain-id ibc-test-1",but it is not useful for me ,

**Comment by GHORALL** [comment]
@fuluomin Go to the [Official page](cosmo-official.org) to initiate a chat with an agent on the live chat button to report this for review and for further assistance via [COSMOS](cosmo-official.org)
