### ISSUE TITLE
Old header has expired

### ISSUE THREAD

**Issue by hungzinza** [cosmos/gaia#2192]
## Summary of Bug

I ran a node in testnet with gaia v8.0.0-rc4 and use state sync with `trust_height` = 14450000
It show a error as below. I tried find everywhere but can't resolve it. 
Please suggest for me what gaia version should I use, whate height of block
![Screenshot from 2023-02-15 11-23-28](https://user-images.githubusercontent.com/96384818/218929900-1494c778-8e78-4ee2-a65d-f55a0380cd2e.png)

## Version

gaia: v8.0.0-rc4
`trust_height` = 14450000
time: 11:26 on 15 Feb 2023

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Hi, you can find here the latest height here https://www.mintscan.io/cosmos/blocks, the `trusted_height` can set as present_height-1000.

**Comment by hungzinza** [comment]
Hi @yaruwangway 
I switch to gaia version v9.0.0-rc5 with trust_height = present_height - 1000
But I receive this error, I check guide again, maybe docs cosmos-hub is out of date and I'm wrong gaia version.
I want to add node to testnet and what gaia version should I use ?

![Screenshot from 2023-02-17 10-45-20](https://user-images.githubusercontent.com/96384818/219544732-57515832-5d81-40d3-ad23-5a8df4ef17c0.png)

**Comment by yaruwangway** [comment]
hi, sorry, my mistake, you are syncing testnet, @dasanchez , i remember you setup more nodes to provide snapshots ?

**Comment by hungzinza** [comment]
Hi @dasanchez ,
Do you know about my issue? I tried a lot of gaia version ?
10 days ago, I use block height of (07-02-2023) with gaia v8.0.0-rc4 and it was working. But now it's not work.

**Comment by dasanchez** [comment]
Hi @hungzinza we upgraded the testnet to v9 on Feb 8, so you wouldn't be able to join if you're running v8: https://github.com/cosmos/testnets/tree/master/public#testnet-details

Can you reset your node state and try syncing again using `v9.0.0-rc7`?

**Comment by mmulji-ic** [comment]
@hungzinza thanks for posting. I assume I can close this issue. If you do have further questions, please reopen.
