### ISSUE TITLE
param migration (params module is deprecated in sdk0.47)

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2214]
## Summary

Gaia v10 will use sdk 0.47.

[In sdk0.47, params store is deprecated](https://github.com/cosmos/cosmos-sdk/tree/v0.47.0-rc2/x/params), in favour of each module housing its own parameters. All the params in params module need to be migrated. [migration example](https://github.com/cosmos/cosmos-sdk/blob/main/simapp/upgrades.go#L31)
Besides, params holding in params module need to migrate to the sdk modules, [params module also holds globalfees params](https://github.com/cosmos/gaia/blob/3185b56c0b93efa0039c3bfe68fd61dad266713d/x/globalfee/types/params.go#L29-L35), so globalfees params need to migrate to global fees module.

## Proposal
The following steps need to be done:
### bank, gov, etc params migration
- [ ] all the params in the params store need to be migrated, call the migration in upgrade handler. (if the params module is sdk module)
### globalfee params migration
- [ ] add set params in globalfee module, [example](https://github.com/cosmos/cosmos-sdk/blob/0f99829fabe34ae489d71a8524fb4c82632965e3/x/gov/keeper/params.go#L10-L19)
- [ ] migrating the value from params store to globalfee store, [example](https://github.com/cosmos/cosmos-sdk/blob/main/x/gov/migrations/v5/store.go)
- [ ] change the fee antehandler to get data from globalfee store rather than params store, [example](https://github.com/cosmos/cosmos-sdk/blob/0f99829fabe34ae489d71a8524fb4c82632965e3/x/gov/keeper/params.go#L21-L31).
- [ ] call the migration in upgrade handler (version map)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
Closing as this work is tracked by https://github.com/cosmos/gaia/issues/2540

**Comment by sainoe** [comment]
Postponed to the SDKv50 upgrade which removes the `x/params` module.
