### ISSUE TITLE
remove `third_party/proto`, and use buf registry for proto deps

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2215]
## Summary

Presently, the proto deps are copied to `gaia/third_party/proto`. This causes extra works of copying when the dependencies version updates.

From sdk 0.46 onwards, we can use  refer to [buf registry](https://buf.build/explore/) for proto deps
[This was done before when we were trying to use 0.46](https://github.com/cosmos/gaia/tree/v8.0.0-rc/proto) (finally reverted to sdk 0.45)

### Concerns
Copy pasting proto files are tedious and error-prone. 

## Proposal

remove  `third_party/proto` and use buf registry.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
Closing as this work is tracked by https://github.com/cosmos/gaia/issues/2540
