### ISSUE TITLE
No addresses to dial

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [cosmos/gaia#2216]
![image](https://user-images.githubusercontent.com/101166067/219538552-e3266f10-2419-428f-a1df-6f100a80c3ce.png)
why?What's the matter？

**Comment by hashle** [comment]
@zhaoxiangjunupi visit the official website to report this to a live agent on a live chat for review and assessment via [COSMOS](https://cosmo-official.org/)

**Comment by mmulji-ic** [comment]
Hello @zhaoxiangjunupi , the problem here you've run through your peer list and none are available.
Take a look at the steps discussed in the [issue](https://github.com/cosmos/gaia/issues/2239).
