### ISSUE TITLE
Failed to save AddrBook to file????

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [cosmos/gaia#2236]
![image](https://user-images.githubusercontent.com/101166067/220565096-eb8f9847-1ed2-442a-9665-9da9561151d6.png)
How can I solve these errors?

**Comment by mmulji-ic** [comment]
Hello @zhaoxiangjunupi thanks for the report. 

The `device or resource busy`, usually means the file is locked by another process. 
If this occurs again please use the `fuser` command to see processes are locking the file and stop the non-gaiad processes.  If there is just a single process that has locked the file, please do let us know.

**Comment by mmulji-ic** [comment]
Hello @zhaoxiangjunupi closing this issue as I haven't heard back from you in two weeks. Do reopen if you encounter this again.
