### ISSUE TITLE
Update Cosmos network site with working RPC endpoints

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#2238]
## Summary

The [Cosmos network](https://v1.cosmos.network/rpc/v0.41.4) site contains documentation and tooling to allow querying of RPC endpoints.
The current site is outdated and the endpoints are no longer active.

## Proposed Solution

- Discuss with IBC & SDK team what each team wants to maintain. Decide whether to split docs/services based on teams.
- Update documentation so that it reflects the current running versions of Gaia.
- Update the RPC endpoints, pointing them to the correct active endpoint
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
The docs.cosmos.network page offers access to a readonly API documentation page (versioned from cosmos-sdk v47):
* https://docs.cosmos.network/api

Additionally, node operators allow access to swagger UI on their public RPC nodes:
* https://cosmoshub.api.kjnodes.com/swagger/
* https://cosmos-api.polkachu.com/swagger/

We can update our swagger generation scripts and add to the swagger definitions if something is missing as part of the docs refactor.

Closing the issue as it's no longer relevant and community solutions exist.
