### ISSUE TITLE
How to solve？？？？？

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [cosmos/gaia#2239]
![image](https://user-images.githubusercontent.com/101166067/220842651-5908d519-008c-4029-bce9-508c768239d2.png)

**Comment by zhaoxiangjunupi** [comment]
I have been stuck in this state. What should I do？？

**Comment by mmulji-ic** [comment]
Hello @zhaoxiangjunupi , assume that you are using v8.0.1 on mainnet, could you replace the live peers with https://polkachu.com/live_peers/cosmos

**Comment by zhaoxiangjunupi** [comment]
> 你好@zhaoxiangjunupi，假设你在主网上使用 v8.0.1，你可以用[https://polkachu.com/live_peers/cosmos替换 live peers](https://polkachu.com/live_peers/cosmos)

![image](https://user-images.githubusercontent.com/101166067/220886414-5b2ad6b8-9029-4c7a-bb26-f0cfc64cb177.png)
be utterly useless

**Comment by mmulji-ic** [comment]
Hi @zhaoxiangjunupi you're running Gaia v9, that will not be live until the [proposal](https://www.mintscan.io/cosmos/proposals/187) is voted ok and then upgrade height is reached, which is ~ 2023-03-15 12:18:06

If you want to join mainnet, please use the [v8.0.1 release](https://github.com/cosmos/gaia/releases/tag/v8.0.1)

**Comment by zhaoxiangjunupi** [comment]
> peers

I use v8.0.1 release, and the peers you provide can't be connected. Are you sure there is no problem?

**Comment by mmulji-ic** [comment]
In the screenshot above your definitely running the wrong version of Gaia:

- v9 has cosmos-sdk@v0.45.13-ics
- v8.0.1 has cosmos-sdk@v0.45.14

Regarding the peers from https://polkachu.com/live_peers/cosmos, could be that they are saturated or offline.

Theres also a list of peers in the [chain-registry](https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json) 
Take a look at the state-synch script [here](https://github.com/cosmos/gaia/pull/2209/files#diff-cde71bdc4e08a004d2f7e27135e846f2a27d6fead7329d398b74b67118e1761a) that shows how to pull in the peers from the chain registry. You don't need to use a different database as specified in the script.

**Comment by zhaoxiangjunupi** [comment]
> 在上面的屏幕截图中，您确定运行了错误版本的Gaia：
> 
> * v9 有[cosmos-sdk@v0.45.13-ics](mailto:cosmos-sdk@v0.45.13-ics)
> * v8.0.1 有 cosmos-sdk@v0.45.14
> 
> [关于来自https://polkachu.com/live_peers/cosmos](https://polkachu.com/live_peers/cosmos)的同行，可能是他们已经失败或脱线。
> 
> [链注册表](https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json)中有个对点列表 看看看看[同步](https://github.com/cosmos/gaia/pull/2209/files#diff-cde71bdc4e08a004d2f7e27135e846f2a27d6fead7329d398b74b67118e1761a)脚脚脚，它同步脚同步同步同步显示显示了了了如何如何从从链注册表中拉入中拉入对等等点点点

Many people in the community have put forward corresponding questions, but you haven't responded. The same questions, the answers you gave are wrong. I think you should test yourself

https://discord.com/channels/669268347736686612/1070874004296048640

**Comment by zhaoxiangjunupi** [comment]
> 在上面的屏幕截图中，您确定运行了错误版本的Gaia：
> 
> * v9 有[cosmos-sdk@v0.45.13-ics](mailto:cosmos-sdk@v0.45.13-ics)
> * v8.0.1 有 cosmos-sdk@v0.45.14
> 
> [关于来自https://polkachu.com/live_peers/cosmos](https://polkachu.com/live_peers/cosmos)的同行，可能是他们已经失败或者脱线。
> 
> [链注册表](https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json)中个点列表 看看[同步](https://github.com/cosmos/gaia/pull/2209/files#diff-cde71bdc4e08a004d2f7e27135e846f2a27d6fead7329d398b74b67118e1761a)，它同步同步脚同步同步显示显示了了了了如何如何从从从从链注册表链注册表中



> 在上面的屏幕截图中，您确定运行了错误版本的Gaia：
> 
> * v9 有[cosmos-sdk@v0.45.13-ics](mailto:cosmos-sdk@v0.45.13-ics)
> * v8.0.1 有 cosmos-sdk@v0.45.14
> 
> [关于来自https://polkachu.com/live_peers/cosmos](https://polkachu.com/live_peers/cosmos)的同行，可能是他们已经失败或者脱线。
> 
> [链接注册表](https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json)中个点列表 看[同步](https://github.com/cosmos/gaia/pull/2209/files#diff-cde71bdc4e08a004d2f7e27135e846f2a27d6fead7329d398b74b67118e1761a)，它同步同脚同步同步显示显示了如何从何从链表链表中

I changed the version in your way, but it's still useless. Have you tried it yourself??

**Comment by mmulji-ic** [comment]
Hi @zhaoxiangjunupi me and a colleague tried the following https://github.com/cosmos/gaia/issues/2239#issuecomment-1446540953 and found it to be working.

**Comment by mmulji-ic** [comment]
Hello @zhaoxiangjunupi as mentioned in the other issue that you've raised, I can walk through the setup together with you. In lieu of that will close this issue, as this one is related.
