### ISSUE TITLE
Validator outreach for lagging v8 validator upgrades

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#2243]
## Summary of Issue

Post v8 upgrade, it was noted that a number of validators upgraded to v8 quite late.

The Hub team should reach out to these teams and understand what the issues were with the migration and see what support is possible for future upgrades and what communication channels need to be established.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
for the migration docs, we can add the expected go version.

**Comment by mmulji-ic** [comment]
We've got feedback from a number of validators and have integrated that feedback into our release process. 
We will start a new feedback cycle for v9.
