### ISSUE TITLE
Update Gaia e2e tests to use Hermes 1.3

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#2245]
## Summary

Update Gaia e2e tests to use the latest Hermes 1.3

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
just want to share:
hermes 0.13 supports:
```
const SDK_MODULE_VERSION_REQ: &str = ">=0.41, <0.46";
const IBC_GO_MODULE_VERSION_REQ: &str = ">=1.1, <=3";
```
