### ISSUE TITLE
genesis export goes to stderr rather than stdout

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2249]
## Summary of Bug
`gaiad export` and `gaiad init` export the genesis to stderr rather than stdout.

## Concerns
Users has to export genesis by redirect stderr to stdout: `gaiad export > genesis.json  2>&1 `. 
This fix is api breaking.

## Version
gaiad v8.0.0, gaiad v9.0.0
`simd` from sdk 0.45.10 and sdk 0.45.13-ics do not have the issue with `export` but only `init`

## Steps to Reproduce
`gaiad export  > genesis.json` ,  genesis.json is empty
`gaiad export > genesis.json  2>&1 `, get exported genesis into the file
The same with `gaiad init`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Fix export: https://github.com/cosmos/gaia/pull/2250

**Comment by yaruwangway** [comment]
issue for `binary init` outputs to stderr in cosmos-sdk https://github.com/cosmos/cosmos-sdk/issues/15167

**Comment by yaruwangway** [comment]
`simd` commands output to stderr is expected. https://github.com/cosmos/cosmos-sdk/issues/15167 
nevertheless, `simd export` can output to stdout, if gaia does the same, here is the fix. https://github.com/cosmos/gaia/pull/2250  otherwise, can close this issue.

**Comment by mmulji-ic** [comment]
@yaruwangway could we also have a warning when executing that command that this function has changed? Just to make sure that people using this function get a reminder immediately that something has changed when they use it.

**Comment by mpoke** [comment]
@yaruwangway what's the impact of this issue? Is anybody affected by this?

**Comment by yaruwangway** [comment]
the impact is when export, has to redirect stderr. 
close for now since no users complain about it.
