### ISSUE TITLE
Why Stargate rpc still on cosmoshub-2 ?

### ISSUE THREAD

**Issue by kolya182** [cosmos/gaia#225]
https://stargate.cosmos.network/node_info

```js
{
protocol_version: {
p2p: "7",
block: "10",
app: "0"
},
id: "383647a44083918fc6d689868f0f4d8016d1f0dd",
listen_addr: "tcp://0.0.0.0:26656",
network: "cosmoshub-2",
version: "0.31.5",
channels: "4020212223303800",
moniker: "AiB-hub-node-0",
other: {
tx_index: "on",
rpc_address: "tcp://0.0.0.0:26657"
}
}
```

**Comment by alexanderbez** [comment]
cc @mircea-c

**Comment by kolya182** [comment]
@mircea-c Completely down https://www.host-tracker.com/InstantCheck/3/45eab934-9222-ea11-a5ff-0003ff73517a/ ?

**Comment by mircea-c** [comment]
Stargate is on http only because of a tendermint issue https://github.com/tendermint/tendermint/issues/4051

http://stargate.cosmos.network/node_info
