### ISSUE TITLE
lost peers 

### ISSUE THREAD

**Issue by infine8** [cosmos/gaia#2253]
v 8.0.0

after several hours of working the node lose its peers. nothing helps

![image](https://user-images.githubusercontent.com/2751504/221557708-1a7f1aa0-afea-4e84-ac79-0447cb1c1a7e.png)

**Comment by mmulji-ic** [comment]
Hello @infine8 , we recommend using the v8.0.1 version will have some tendermint updates to help with this.

**Comment by mpoke** [comment]
@infine8 could you please let us know if the issue still exists after upgrading to v8.0.1?

**Comment by yj0x0x** [comment]
@mpoke Still lost peers, sync speed too slow.

**Comment by mmulji-ic** [comment]
Hi @infine8 could you share your config as well as your hardware spec.

**Comment by mmulji-ic** [comment]
Hi @infine8 mainnet has moved to Gaia v9.0.1. Let us know if you are experiencing the same issues, otherwise will close this issue in a week, as v8 is now only run for archive nodes.

**Comment by mmulji-ic** [comment]
Hi @infine8 let us know if there is an update for this issue, otherwise will close next week.
