### ISSUE TITLE
Go 1.20 (and updates in general)

### ISSUE THREAD

**Issue by briancolecoinmetrics** [cosmos/gaia#2254]
## Summary

This repo currently requires Go 1.18. There is https://github.com/cosmos/gaia/issues/2015 to eventually move to 1.19, but 1.18 is EOL and 1.20 is current (and Go releases move fairly quickly).

## Type

I don't know if this is Build Debt (it most obviously occurs on build) or Code Debt (since it could require code updates). There's probably also an element of Process Debt, in that there probably should be a step at the start of each gaia version to try and move to the then-current Go release.

## Impact

Mostly the usual impact of running EOL compiler versions - upstream doesn't care about problems in this compiler version, it's missing bugfixes, and it lags performance improvements. The performance part is especially striking in this case, as Go has been fairly aggressive with performance improvements in each version.

In terms of cost to address, it takes time/effort to ensure that everything works correctly with new versions (although I personally would argue that it's easier to pay that cost one amortized by tracking the latest version since you'll want to update sooner or later).

## Proposed Solution

Short term: Move the next gaia version to Go 1.20 (or whatever is current when this happens).

Long term: Plan to move to the latest Go version on every new gaia version.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Hello @briancolecoinmetrics we are currently running in step with our major dependencies, namely Tendermint, Cosmos-SDK and IBC-Go. After v9 is released we are planning to update all of these dependencies to 1.19 and release 1.19 Gaia. Moving to 1.19 earlier would've caused some unintended issues.

In the future we will be moving to a more regular release cadence and that should include more timely updates to golang versions.
