### ISSUE TITLE
Cosmos v8.0.1 can't catch latest height. 

### ISSUE THREAD

**Issue by yj0x0x** [cosmos/gaia#2265]
## Summary of Bug
Running archive node at the moment, cosmos node couldn't catch latest height. 

## Version
v8.0.1

## Steps to Reproduce
I have download latest snapshot from https://quicksync.io/networks/cosmos.html on the 3rd of March. 
But Node can't catch latest height till now. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Hi @yj0x0x thanks for reporting. Are you managing to sync at all or just not fast enough to reach the current height? Sounds like the later. To help diagnose, could you share your config and also your hardware spec.

**Comment by yj0x0x** [comment]
@mmulji-ic Hello . Thank you for reply.

Yes. Node are not   fast enough to reach the current height. 


CPU like below. 
```
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 49
model name	: AMD EPYC 7502 32-Core Processor
stepping	: 0
microcode	: 0x8301055
cpu MHz		: 3342.731
cache size	: 512 KB
```

CPU core. 
```
# cat /proc/cpuinfo | egrep 'siblings|cpu cores' | head -2
siblings	: 64
cpu cores	: 32
```

Ram info. 
```
 # free -h
              total        used        free      shared  buff/cache   available
Mem:          503Gi       348Gi        70Gi        26Mi        84Gi       151Gi
Swap:           9Gi       615Mi       9.4Gi
```

OS version
```
 # cat /etc/issue.net
Ubuntu 20.04.6 LTS
```

Storage. 
nvme 3.5 T raid 1

Please check. 

below is 7days of sync status from now on. 
<img width="1408" alt="Screen Shot 2023-03-16 at 8 54 51 PM" src="https://user-images.githubusercontent.com/102578874/225609203-1aada01f-be77-478a-b512-8d9de3f0a7b9.png">

**Comment by mmulji-ic** [comment]
Hi @yj0x0x your hardware looks fine. In the attached chart I see the a much steeper slope 3 times, so at that point synching was faster. Anything change with the setup during that time? It could just be the network that was saturated and connected nodes didn't have all the blocks.

We bumped Tendermint we each release, I believe there were some improvements with each iteration.

Did you bump to the `v9 series` yet and if so are you experiencing the same problem?

**Comment by mmulji-ic** [comment]
Hi @yj0x0x closing as there no further update from you.
