### ISSUE TITLE
file too large

### ISSUE THREAD

**Issue by 99Kies** [cosmos/gaia#2284]
this my command line:
```
gaiad start --x-crisis-skip-assert-invariants 
```

this my bug info:
```
Error: failed to initialize database: write /home/ubuntu/.gaia/data/tx_index.db/MANIFEST-192409: file too large
```

**Comment by 99Kies** [comment]
And I ran into this problem before during the sync process.
```
2:32AM ERR failed to create state snapshot err="failed to generate snapshot chunk 21: iavl export failed for version 14249000: open /home/ubuntu/.gaia/data/application.db/215272025.ldb: too many open files" height=14249000
panic: open /home/ubuntu/.gaia/data/cs.wal: too many open files

goroutine 250375 [running]:
github.com/tendermint/tendermint/libs/autofile.(*Group).readGroupInfo(0xc0bfb796b0)
        github.com/tendermint/tendermint@v0.34.24/libs/autofile/group.go:365 +0x3f6
github.com/tendermint/tendermint/libs/autofile.(*Group).checkTotalSizeLimit(0xc0bfb796b0)
        github.com/tendermint/tendermint@v0.34.24/libs/autofile/group.go:274 +0x4a
github.com/tendermint/tendermint/libs/autofile.(*Group).processTicks(0xc0bfb796b0)
        github.com/tendermint/tendermint@v0.34.24/libs/autofile/group.go:245 +0x7c
created by github.com/tendermint/tendermint/libs/autofile.(*Group).OnStart
        github.com/tendermint/tendermint@v0.34.24/libs/autofile/group.go:140 +0x8d
```

**Comment by mmulji-ic** [comment]
Hi @99Kies thanks for adding this issue. 
Do you have details of the file mentioned? `/home/ubuntu/.gaia/data/tx_index.db/MANIFEST-192409`
The error `too many open files` should be resolved by changing the config of your linux system, allowing more files to be accessed for a specific user. See the forum [post](https://forum.cosmos.network/t/ubuntu-error-to-many-open-files-when-run-a-node/382).

**Comment by mmulji-ic** [comment]
@adizere have you encountered the `file too large` error, when accessing the `tx_index.db`?

**Comment by adizere** [comment]
> @adizere have you encountered the `file too large` error, when accessing the `tx_index.db`?

I don't think we've encountered this before.

@99Kies what was the size of the offending file `/home/ubuntu/.gaia/data/tx_index.db/MANIFEST-192409`?

**Comment by mmulji-ic** [comment]
Hi @99Kies do you have an update as to the size of the file? Did this problem reoccur?
If there is no update by next week, we will close this issue.

**Comment by mmulji-ic** [comment]
Hi @99Kies closing as no update from you regarding this issues. Please re-open if you have more information.
