### ISSUE TITLE
Remote API DoS

### ISSUE THREAD

**Issue by visualbasic6** [cosmos/gaia#2285]
Hi,

There is a DoS vulnerability in the `block_search?query=` method. Requesting the value `"block.height > 1"&page=1&per_page=10000` in a loop triggers an OOM crash. Pagination needs to be implemented here. **Every public Cosmos API I've looked at is vulnerable to the attack**. I'd also like to mention that the Cosmos team was informed of this vulnerability over a month ago and took no action. Because of this, and because of their refusal to pay bug bounties despite having a bug bounty program, and particularly because this API is no longer in scope, I've concluded that the most ethical decision for the Cosmos and open source software community was to publicly disclose this issue.

More info: https://twitter.com/123456/status/1634714205902323712

Thanks!

**Comment by reecepbcups** [comment]
> There is a DoS vulnerability in the block_height method

Correction: it is in the `block_search?query=` method, not `block_height`

**Comment by faneaatiku** [comment]
1. Is there anything else to do than limit the per_page arg to a decent number like 100, 200 search results ? 
2. Isn't this a tendermint issue ?

**Comment by mpoke** [comment]
> Isn't this a tendermint issue ?

It is. This issue should be open on the https://github.com/cometbft/cometbft repo.

**Comment by adizere** [comment]
> > Isn't this a tendermint issue ?
> 
> It is. This issue should be open on the https://github.com/cometbft/cometbft repo.

Ported here: https://github.com/cometbft/cometbft/issues/517. @visualbasic6 thanks for finding and flagging this. Aside from your experience with the "bug bounty program", on the technical side of things let's continue the discussion in the issue linked above.

**Comment by visualbasic6** [comment]
Will do - and I agree with `bug bounty program` sitting between quotation marks.

**Comment by PFC-developer** [comment]
I'm too lazy to try, but does this also affect nodes that have disabled indexing? (while it makes the node useless for querying, it will provide a remediation for validators running with open ports )

**Comment by unl1k3ly** [comment]
@PFC-developer it does not, at least from tests we ran on our side.
