### ISSUE TITLE
Missing RPC error messages

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#23]
Probably needs to be addressed in the SDK, but here for now:

```
ethanbuchman:gaia$ gaiacli tx bond --amount=5fermion --name=$MYNAME --pubkey=$PUBKEY
Please enter passphrase for bucky: 


ERROR: broadcast_tx_commit: Response error: Internal error
```

Did this while fast syncing. It doesn't say what the internal error was. From `rpc/lib/types/types.go`:

```
func NewRPCErrorResponse(id string, code int, msg string, data string) RPCResponse {
	return RPCResponse{
		JSONRPC: "2.0",
		ID:      id,
		Error:   &RPCError{Code: code, Message: msg, Data: data},
	}
}
```

Looks like we're showing the `.Message`, but not the `.Data`

**Comment by adrianbrink** [comment]
Nice, discovering bugs is progress :-)

**Comment by rigelrozanski** [comment]
@ebuchman still relevant?

**Comment by zramsay** [comment]
fixed in https://github.com/tendermint/tendermint/pull/767
