### ISSUE TITLE
Tags in installation docs

### ISSUE THREAD

**Issue by jwjanus** [cosmos/gaia#23]
Hi guys,
I wanted to install gaia from the recommended tag, however there are no tags in this repo (besides `v0.0.0`, which isn't greater than `v0.33.0`). Should I treat `v0.0.0` as the latest version? I found release versions in `cosmos-sdk`, however docs there state that I should go to this repo to join mainnet. Therefore I'm in an infinite loop now. Could you update the docs on this or maybe create a release version here? Thanks.

**Comment by TheBonseung** [comment]
I had same problem. 
I followed this guide ( https://github.com/cosmos/gaia/blob/master/docs/installation.md ).

**Comment by TheBonseung** [comment]
I needed to use ( git clone -b v0.34.5 https://github.com/cosmos/cosmos-sdk ), 
though you can see ( git clone -b v0.34.5 https://github.com/cosmos/gaia ) in the guide.

**Comment by jwjanus** [comment]
Thanks! I found it before, and managed to set up everything. My point is that there's an inconsistency in the docs

**Comment by alexanderbez** [comment]
No, the current mainnet version(s) still reside in the SDK repo. You'll find v0.34.5 there. Until the next mainnet upgrade, you won't find any official released versions here :)
