### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#230]
404 on link with text "Information on how to join the mainnet (genesis.json file and seeds) is held in our launch repo." linking to https://github.com/cosmos/launch/tree/master/latest on https://hub.cosmos.network/docs/validators/validator-setup.html

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I don't see any reference to https://github.com/cosmos/launch/tree/master/latest at all in this repo (except to some Chinese translation). Thoughts @gamarin2 ?

**Comment by gamarin2** [comment]
@okwme as explained, the site is not in sync with the repo. That's a bug that @fadeev is working on. 

@alexanderbez there are plenty of references to the launch repo here https://github.com/cosmos/gaia/blob/master/docs/gaia-tutorials/join-mainnet.md

**Comment by alexanderbez** [comment]
No, I meant there is no reference to the exact link @okwme referenced.

**Comment by gamarin2** [comment]
ah well yes, that's because the repo is up to date with working links. The site is not, as it is still on the old version (we're working on that)

**Comment by gin** [comment]
✅ This is fixed now

**Test case:**
When I go to https://hub.cosmos.network/master/validators/validator-setup.html
And click on the link "in our launch repo"
✅ Expect link to not be 404
✅ Expect link to be our launch repo

**Comment by tac0turtle** [comment]
Thank you for checking this issue. Ill close it now
