### ISSUE TITLE
Cannot query to GRPC endpoint

### ISSUE THREAD

**Issue by lehieuhust** [cosmos/gaia#2304]
## Summary of Bug

Can not access to grpc

## Version

v9.0.0

## Steps to Reproduce

When query endpoint of **interchain_security** and I have faced this error
```
grpcurl -plaintext cosmos-grpc.polkachu.com:14990 describe interchain_security.ccv.provider.v1.Query
Failed to resolve symbol "interchain_security.ccv.provider.v1.Query": file "interchain_security/ccv/v1/ccv.proto" included an unresolvable reference to ".cosmos.staking.v1beta1.InfractionType"
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Hey, thanks you for opening the issue.

It seems that you don't have the `interchain_security` protos available. We can use this issue to track what we need to do to improve the experience on gaia

Meanwhile you can try the following steps:

```bash
# get the repo with proro files
$: git clone git@github.com:cosmos/interchain-security.git

# provider chain
➜  grpcurl -plaintext \
--import-path <path_to_interchain-security_repo>/third_party \
--import-path <path_to_interchain-security_repo>/third_party/proto \
--import-path <path_to_interchain-security_repo>/proto \
--proto <path_to_interchain-security_repo>/proto/interchain_security/ccv/provider/v1/query.proto cosmos-grpc.polkachu.com:14990 describe interchain_security.ccv.provider.v1.Query

interchain_security.ccv.provider.v1.Query is a service:
service Query {
  // QueryConsumerChainStarts queries consumer chain start proposals.
  rpc QueryConsumerChainStarts ( .interchain_security.ccv.provider.v1.QueryConsumerChainStartProposalsRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerChainStartProposalsResponse ) {
    option (.google.api.http) = { get:"/interchain_security/ccv/provider/consumer_chain_start_proposals" };
  }
  // QueryConsumerChainStops queries consumer chain stop proposals.
  rpc QueryConsumerChainStops ( .interchain_security.ccv.provider.v1.QueryConsumerChainStopProposalsRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerChainStopProposalsResponse ) {
    option (.google.api.http) = { get:"/interchain_security/ccv/provider/consumer_chain_stop_proposals" };
  }
  // ConsumerChains queries active consumer chains supported by the provider
  // chain
  rpc QueryConsumerChains ( .interchain_security.ccv.provider.v1.QueryConsumerChainsRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerChainsResponse ) {
    option (.google.api.http) = { get:"/interchain_security/ccv/provider/consumer_chains" };
  }
  // ConsumerGenesis queries the genesis state needed to start a consumer chain
  // whose proposal has been accepted
  rpc QueryConsumerGenesis ( .interchain_security.ccv.provider.v1.QueryConsumerGenesisRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerGenesisResponse ) {
    option (.google.api.http) = {
      get: "/interchain_security/ccv/provider/consumer_genesis/{chain_id}"
    };
  }
  // QueryThrottleState returns the main on-chain state relevant to currently throttled slash packets
  rpc QueryThrottleState ( .interchain_security.ccv.provider.v1.QueryThrottleStateRequest ) returns ( .interchain_security.ccv.provider.v1.QueryThrottleStateResponse ) {
    option (.google.api.http) = { get:"/interchain_security/ccv/provider/throttle_state" };
  }
  // QueryThrottledConsumerPacketData returns a list of pending packet data instances
  // (slash packet and vsc matured) for a single consumer chain
  rpc QueryThrottledConsumerPacketData ( .interchain_security.ccv.provider.v1.QueryThrottledConsumerPacketDataRequest ) returns ( .interchain_security.ccv.provider.v1.QueryThrottledConsumerPacketDataResponse ) {
    option (.google.api.http) = { get:"/interchain_security/ccv/provider/pending_consumer_packets" };
  }
  // QueryValidatorConsumerAddr queries the address
  // assigned by a validator for a consumer chain.
  rpc QueryValidatorConsumerAddr ( .interchain_security.ccv.provider.v1.QueryValidatorConsumerAddrRequest ) returns ( .interchain_security.ccv.provider.v1.QueryValidatorConsumerAddrResponse ) {
    option (.google.api.http) = { get:"/interchain_security/ccv/provider/validator_consumer_addr" };
  }
  // QueryProviderAddr returns the provider chain validator
  // given a consumer chain validator address
  rpc QueryValidatorProviderAddr ( .interchain_security.ccv.provider.v1.QueryValidatorProviderAddrRequest ) returns ( .interchain_security.ccv.provider.v1.QueryValidatorProviderAddrResponse ) {
    option (.google.api.http) = { get:"/interchain_security/ccv/provider/validator_provider_addr" };
  }
}
```

And finally for any consumer chains:
```bash
grpcurl -plaintext \
--import-path <path_to_interchain_security>/third_party \
--import-path <path_to_interchain_security>/third_party/proto \
--import-path <path_to_interchain_security>/proto \
--proto <path_to_interchain_security>/proto/interchain_security/ccv/consumer/v1/query.proto <grpc-url> describe interchain_security.ccv.consumer.v1.Query
```

@lehieuhust 
I hope this helps!

**Comment by lehieuhust** [comment]
> Hey, thanks you for opening the issue.
> 
> It seems that you don't have the `interchain_security` protos available. We can use this issue to track what we need to do to improve the experience on gaia
> 
> Meanwhile you can try the following steps:
> 
> ```shell
> # get the repo with proro files
> $: git clone git@github.com:cosmos/interchain-security.git
> 
> # provider chain
> ➜  grpcurl -plaintext \
> --import-path <path_to_interchain-security_repo>/third_party \
> --import-path <path_to_interchain-security_repo>/third_party/proto \
> --import-path <path_to_interchain-security_repo>/proto \
> --proto <path_to_interchain-security_repo>/proto/interchain_security/ccv/provider/v1/query.proto cosmos-grpc.polkachu.com:14990 describe interchain_security.ccv.provider.v1.Query
> 
> interchain_security.ccv.provider.v1.Query is a service:
> service Query {
>   // QueryConsumerChainStarts queries consumer chain start proposals.
>   rpc QueryConsumerChainStarts ( .interchain_security.ccv.provider.v1.QueryConsumerChainStartProposalsRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerChainStartProposalsResponse ) {
>     option (.google.api.http) = { get:"/interchain_security/ccv/provider/consumer_chain_start_proposals" };
>   }
>   // QueryConsumerChainStops queries consumer chain stop proposals.
>   rpc QueryConsumerChainStops ( .interchain_security.ccv.provider.v1.QueryConsumerChainStopProposalsRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerChainStopProposalsResponse ) {
>     option (.google.api.http) = { get:"/interchain_security/ccv/provider/consumer_chain_stop_proposals" };
>   }
>   // ConsumerChains queries active consumer chains supported by the provider
>   // chain
>   rpc QueryConsumerChains ( .interchain_security.ccv.provider.v1.QueryConsumerChainsRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerChainsResponse ) {
>     option (.google.api.http) = { get:"/interchain_security/ccv/provider/consumer_chains" };
>   }
>   // ConsumerGenesis queries the genesis state needed to start a consumer chain
>   // whose proposal has been accepted
>   rpc QueryConsumerGenesis ( .interchain_security.ccv.provider.v1.QueryConsumerGenesisRequest ) returns ( .interchain_security.ccv.provider.v1.QueryConsumerGenesisResponse ) {
>     option (.google.api.http) = {
>       get: "/interchain_security/ccv/provider/consumer_genesis/{chain_id}"
>     };
>   }
>   // QueryThrottleState returns the main on-chain state relevant to currently throttled slash packets
>   rpc QueryThrottleState ( .interchain_security.ccv.provider.v1.QueryThrottleStateRequest ) returns ( .interchain_security.ccv.provider.v1.QueryThrottleStateResponse ) {
>     option (.google.api.http) = { get:"/interchain_security/ccv/provider/throttle_state" };
>   }
>   // QueryThrottledConsumerPacketData returns a list of pending packet data instances
>   // (slash packet and vsc matured) for a single consumer chain
>   rpc QueryThrottledConsumerPacketData ( .interchain_security.ccv.provider.v1.QueryThrottledConsumerPacketDataRequest ) returns ( .interchain_security.ccv.provider.v1.QueryThrottledConsumerPacketDataResponse ) {
>     option (.google.api.http) = { get:"/interchain_security/ccv/provider/pending_consumer_packets" };
>   }
>   // QueryValidatorConsumerAddr queries the address
>   // assigned by a validator for a consumer chain.
>   rpc QueryValidatorConsumerAddr ( .interchain_security.ccv.provider.v1.QueryValidatorConsumerAddrRequest ) returns ( .interchain_security.ccv.provider.v1.QueryValidatorConsumerAddrResponse ) {
>     option (.google.api.http) = { get:"/interchain_security/ccv/provider/validator_consumer_addr" };
>   }
>   // QueryProviderAddr returns the provider chain validator
>   // given a consumer chain validator address
>   rpc QueryValidatorProviderAddr ( .interchain_security.ccv.provider.v1.QueryValidatorProviderAddrRequest ) returns ( .interchain_security.ccv.provider.v1.QueryValidatorProviderAddrResponse ) {
>     option (.google.api.http) = { get:"/interchain_security/ccv/provider/validator_provider_addr" };
>   }
> }
> ```
> 
> And finally for any consumer chains:
> 
> ```shell
> grpcurl -plaintext \
> --import-path <path_to_interchain_security>/third_party \
> --import-path <path_to_interchain_security>/third_party/proto \
> --import-path <path_to_interchain_security>/proto \
> --proto <path_to_interchain_security>/proto/interchain_security/ccv/consumer/v1/query.proto <grpc-url> describe interchain_security.ccv.consumer.v1.Query
> ```
> 
> @lehieuhust I hope this helps!

Thank you, I have successfully get endpoint of interchain_security
