### ISSUE TITLE
Gaiad Requires Local PK from HSM Validator

### ISSUE THREAD

**Issue by gaia** [cosmos/gaia#231]
## Summary of Bug

I have

`#priv_validator_key_file = "config/priv_validator_key.json"`
along with
`priv_validator_laddr = "tcp://x.x.x.x:yyyyy"`
in place.

A gaiad restart creates another priv_validator_key.json, which caused problems until I just left the actual key in there. The HSM is signing fine.

There is no reason to leave the key in the node when you have in HSM. I must be doing something wrong. How do I tell gaiad that the PK is nowhere local?!

## Version

```
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.3
commit: 2f6783e298f25ff4e12cb84549777053ab88749a
build_tags: netgo,ledger
go: go version go1.13.1 linux/amd64
```

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks @gaia, but this issue doesn't belong here. It's either a Tendermint or KMS issue. Please move it there :)
