### ISSUE TITLE
Unable to query archival data with recent upgrade 14470501

### ISSUE THREAD

**Issue by aimxhaisse** [cosmos/gaia#2313]
## Summary of Bug

Since the Gaia migration at block 14470501, historical data is screwed up for blocks below.

## Version

gaiad-v9.0.1-linux-amd64

### Blocks >= 14470501: OK

```
$ grpcurl --max-msg-sz 400194304 -H "x-cosmos-block-height: 14470501" -plaintext NODE:PORT  cosmos.gov.v1beta1.Query/Proposals

[...]

ok
```

### Blocks < 14470501: KO

```
$ grpcurl --max-msg-sz 400194304 -H "x-cosmos-block-height: 14470500" -plaintext NODE:PORT cosmos.gov.v1beta1.Query/Proposals

ERROR:
  Code: Unknown
  Message: failed to load state at height 14470500; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 14504397): invalid request

```

This happens for all gRPC calls, no matter which module is used, using a fresh Quicksync full archival dump using `gaiad-v9.0.1-linux-amd64` version.

Is this a regression?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Thank you for opening the issue!

Would you mind sharing your node's configuration and please confirm that pruning is turned off in `app.toml`?

```bash
# default: the last 362880 states are kept, pruning at 10 block intervals
# nothing: all historic states will be saved, nothing will be deleted (i.e. archiving node)
# everything: 2 latest states will be kept; pruning at 10 block intervals.
# custom: allow pruning options to be manually specified through 'pruning-keep-recent', and 'pruning-interval'
pruning = "nothing"
```

This configuration should allow your node to keep all historic blocks.

**Comment by aimxhaisse** [comment]
Yup, pruning is disabled:

``` 
# default: the last 100 states are kept in addition to every 500th state; pruning at 10 block intervals
# nothing: all historic states will be saved, nothing will be deleted (i.e. archiving node)
# everything: all saved states will be deleted, storing only the current and previous state; pruning at 10 block intervals
# custom: allow pruning options to be manually specified through 'pruning-keep-recent', 'pruning-keep-every', and 'pruning-interval'
pruning = "nothing"
```

**Comment by yj0x0x** [comment]
Here is the same issue. 
```
{"timestamp":"2023-03-22T11:25:14.915","level":"WARN","thread":"atom","logger":,"message":"Unable to get account 
balance at cosmos1j6a0cxzhk8jqcyr9m94hv5r8nqle5yrtfn7hrx at blockheight 14280567 using http://cosmos-fullnode:1317","exception":"java.lang.IllegalStateException: Invalid response code (400): {\n  \"code\": 3,\n  
\"message\": \"failed to load state at height 14280567; version mismatch on immutable IAVL tree; version does not exist. 
Version has either been pruned, or is for a future block height (latest height: 14476324)
```
Config set up is pruning nothing. 

So it is archive node.

**Comment by aimxhaisse** [comment]
I've found a hacky fix by patching the cosmos-sdk as follows:

```
diff --git a/store/iavl/store.go b/store/iavl/store.go
index 50324c89e..619b722b7 100644
--- a/store/iavl/store.go
+++ b/store/iavl/store.go
@@ -108,7 +108,7 @@ func UnsafeNewStore(tree *iavl.MutableTree) *Store {
 // Any mutable operations executed will result in a panic.
 func (st *Store) GetImmutable(version int64) (*Store, error) {
        if !st.VersionExists(version) {
-               return &Store{tree: &immutableTree{&iavl.ImmutableTree{}}}, fmt.Errorf("version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height")
+               return &Store{tree: &immutableTree{&iavl.ImmutableTree{}}}, nil
        }
 
        iTree, err := st.tree.GetImmutable(version)
```

I'm not sure of all implications but I guess this is a regression that was introduced in the SDK bump during the Gaia v8 upgrade.

**Comment by aimxhaisse** [comment]
This affected Juno as well, quoting Reece:

> Reece | Juno-Network — Today at 16:09
> I did this back for Juno’s v13 upgrade as well. Is because of a past issue with a chain upgrade which did not add a new modules storeKey
> 
> 4-5 chains have had issues with this since the change (implemented in 45.12 I believe) 😔

So adding the new storeKey is the way forward, this is backwards compatible. I'll try to come up with a cleaner patch when I find some time if that sounds good (unless it's solved before :)).

**Comment by faddat** [comment]
I'd surely say it's a regression.

**Comment by mmulji-ic** [comment]
Validator feedback:
We found that this 1st happened with the vega upgrade (i.e. from `gravity-dex`->`v6 vega`)
But then from `v6 (vega)` -> `v7 (theta)` or from `v7 (theta)` -> `v8 (rho)` we didn’t see any regressions.
and now from `v8 (rho)` -> `v9 (lambda)` we see a regression again.

If this is how the system works, then for historical reporting purposes looks like we are being asked to run a dedicated node with older binaries until upgrade heights for every single cosmos release ?

**Comment by danbryan** [comment]
I can confirm this resolved the issue temporarily for me.

Modify `go.mod` with
```
replace github.com/cosmos/cosmos-sdk => github.com/reecepbcups/cosmos-sdk v0.45.13-ics.archive.1
```
then

```
go mod tidy
make install
```

**Comment by yj0x0x** [comment]
@MSalopek Still this issue on going? 
Nothing to patched in latest release?

**Comment by faddat** [comment]
Hey there, We have written a patch. You can find the patched version in the pull requests. We have submitted the patch to the cosmos SDK. Cosmo's SDK 45 is deprecated. The Cosmos SDK team simultaneously will not merge the patch to 45 and recommends against using a fork.

https://github.com/cosmos/gaia/pull/2390

**Comment by mmulji-ic** [comment]
> @MSalopek Still this issue on going? Nothing to patched in latest release?

Hi @yj0x0x , we'll discuss with the SDK to see if they can update this issue into `0.45.x` . Otherwise we'll discuss with the hub team on using a fork (which is definitely not preferred).

**Comment by yj0x0x** [comment]
@mmulji-ic Thank you for reply. 
As a user of cosmos node, I think this issue is critical. 
Once HF done, And Can't get block data before HF. How could be verified data in the cosmos network?

Hope that this issue will raise in serious manner, fix in ASAP personally.

**Comment by glnro** [comment]
This issue has [been addressed in the SDK and backported](https://github.com/cosmos/cosmos-sdk/pull/15683) for `v0.46` and `v0.47`. There are a few temporary workarounds until the Hub upgrades to SDK `v0.47` in the meantime which we'll provide documentation for shortly.

**Comment by faddat** [comment]
According to everything I have been told the next upgrade of the cosmos hub is also SDK 45

Proposal 104 places this under our mandate and this is not an acceptable set of solutions.

**Comment by mmulji-ic** [comment]
@faddat cleanest way is for the SDK to backport this fix to the 45 line. The transition to 47 is in progress and will take some time. Therefore the backport is preferred to avoid other complications. @yj0x0x there was a workaround discussed by Marko. We will try that first, before pressing for other options.

**Comment by yj0x0x** [comment]
@mmulji-ic Thank you letting me know. 
Please let me know how to fix this temporary in ASAP. 

Looking forward hearing from you.

**Comment by yj0x0x** [comment]
@mmulji-ic @faddat @glnro Ping.

**Comment by yj0x0x** [comment]
@mmulji-ic @MSalopek 
Consensus update is coming, any updates about this issue?

**Comment by yj0x0x** [comment]
@mmulji-ic @MSalopek @jackzampolin Anybody knows how's going on?

**Comment by yj0x0x** [comment]
@mmulji-ic @MSalopek @faddat Any update please?

**Comment by mmulji-ic** [comment]
Hi @yj0x0x checking, unfortunately we don't have the infra setup, so it takes some time. Dan mentioned a patch above, for the SDK that you can also try. We've talked to the SDK folks and they won't backport that to v0.45 line unfortunately.

**Comment by mpoke** [comment]
We're planing to upgrade Gaia to SDK 0.47 in the following months. In the meantime, please use the suggested fix.

**Comment by gilxgil** [comment]
1. Reopening, this is still a major issue for archive nodes.
2. The fix is now broken with v12.0.0. Any suggestions from the team?

**Comment by Jacoblava** [comment]
> We're planing to upgrade Gaia to SDK 0.47 in the following months. In the meantime, please use the suggested fix.

The suggested fix doesn't work anymore.
Latest upgrade to v12.0.0 broke it.
No more support for archive nodes. 
@mpoke can you please re-open the issue?

**Comment by mmulji-ic** [comment]
Hi @Jacoblava @gilxgil we'll take a look to see if we can adapt that fix or suggestion another mitigation.

**Comment by Jacoblava** [comment]
@mmulji-ic Is there any update / fix / patch for it?
This is pretty critical for all archive node runners.
No user can retrieve archive data from GAIA for over 2 weeks now.

**Comment by reecepbcups** [comment]
@Jacoblava I have updated my unofficial patch 

https://github.com/Reecepbcups/cosmos-sdk/releases/tag/v0.45.16-ics-lsm-iavlpatch.1

replace github.com/cosmos/cosmos-sdk => github.com/reecepbcups/cosmos-sdk v0.45.16-ics-lsm-iavlpatch.1

also cc @mmulji-ic

**Comment by reecepbcups** [comment]
oh and also @gilxgil ^

**Comment by Jacoblava** [comment]
Thanks a lot,
Will look at it now.

**Comment by ScepticMatt** [comment]
> @Jacoblava I have updated my unofficial patch
> 
> https://github.com/Reecepbcups/cosmos-sdk/releases/tag/v0.45.16-ics-lsm-iavlpatch.1
> 
> replace github.com/cosmos/cosmos-sdk => github.com/reecepbcups/cosmos-sdk v0.45.16-ics-lsm-iavlpatch.1
> 
> also cc @mmulji-ic

Unfortunately I get a crash on axelar archive node when syncing with this patch. But I can get historical data:

```
2023-10-18T14:44:46+02:00 INF minted coins from module account amount=1035230uaxl from=mint module=x/bank
panic: UnmarshalJSON cannot decode empty bytes
goroutine 314 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x2e5ce60, 0xc01e5d8d50}, 0xc00012e500, {0x2e32288, 0xc01ee11210}, {0x2e322b0, 0xc01ee11320}, {0xc029f09c00, 0x7, 0x20}, ...}, ...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/x/params/types/subspace.go:109 +0x2a7
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.ValidatorBondFactor(...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/x/staking/keeper/params.go:52
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.GetParams({{0x2e32288, 0xc01ee111c0}, {0x2e5ce60, 0xc01e5d8d50}, {0x2e4d180, 0xc000411710}, {0x2e5df20, 0xc00022f8c0}, {0x2e5d028, 0xc01ee1a1f8}, ...}, ...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/x/staking/keeper/params.go:76 +0x708
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.ApplyAndReturnValidatorSetUpdates({{0x2e32288, 0xc01ee111c0}, {0x2e5ce60, 0xc01e5d8d50}, {0x2e4d180, 0xc000411710}, {0x2e5df20, 0xc00022f8c0}, {0x2e5d028, 0xc01ee1a1f8}, ...}, ...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/x/staking/keeper/val_state_change.go:109 +0xd8
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.BlockValidatorUpdates({{0x2e32288, 0xc01ee111c0}, {0x2e5ce60, 0xc01e5d8d50}, {0x2e4d180, 0xc000411710}, {0x2e5df20, 0xc00022f8c0}, {0x2e5d028, 0xc01ee1a1f8}, ...}, ...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/x/staking/keeper/val_state_change.go:27 +0x98
github.com/cosmos/cosmos-sdk/x/staking.EndBlocker({{0x2e4b830, 0x3fb0c60}, {0x2e5c130, 0xc0c5353940}, {{0xb, 0x0}, {0xc0c3d486a0, 0xd}, 0x935fe7, {0x21150dfe, ...}, ...}, ...}, ...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/x/staking/abci.go:27 +0x118
github.com/cosmos/cosmos-sdk/x/staking.AppModule.EndBlock(...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/x/staking/module.go:178
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x2e4b830, 0x3fb0c60}, {0x2e5c130, 0xc0c5353940}, {{0xb, 0x0}, {0xc0c3d486a0, 0xd}, 0x935fe7, ...}, ...}, ...)
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/types/module/module.go:512 +0x1eb
github.com/axelarnetwork/axelar-core/app.(*AxelarApp).EndBlocker(...)
        /mnt/data/axelar/axelar-core/app/app.go:763
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc00057ac40, {0x40?})
        /home/matthias/go/pkg/mod/github.com/reecepbcups/cosmos-sdk@v0.45.16-ics-lsm-iavlpatch.1/baseapp/abci.go:203 +0x1fd
github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc032e7d200, {0xc032e7d200?})
        /home/matthias/go/pkg/mod/github.com/cometbft/cometbft@v0.34.27/abci/client/local_client.go:288 +0xd3
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc097c10580?, {0x20?})
        /home/matthias/go/pkg/mod/github.com/cometbft/cometbft@v0.34.27/proxy/app_conn.go:89 +0x1e
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2e4b7f8?, 0xc02031cd80}, {0x2e54bb0, 0xc0a9f16e70}, 0xc0b2856d20, {0x2e5d460, 0xc032f845d0}, 0x935fe6?)
        /home/matthias/go/pkg/mod/github.com/cometbft/cometbft@v0.34.27/state/execution.go:327 +0x714
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0d98533f8, 0x7}}, {0xc0d9853430, 0xd}, 0x1, 0x935fe6, {{0xc01671d0c0, ...}, ...}, ...}, ...)
        /home/matthias/go/pkg/mod/github.com/cometbft/cometbft@v0.34.27/state/execution.go:140 +0x16b
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0010a81c0, 0x0)
        /home/matthias/go/pkg/mod/github.com/cometbft/cometbft@v0.34.27/blockchain/v0/reactor.go:400 +0xb7a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart in goroutine 1
        /home/matthias/go/pkg/mod/github.com/cometbft/cometbft@v0.34.27/blockchain/v0/reactor.go:112 +0x6e
axelard.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by reecepbcups** [comment]
@ScepticMatt Yea this lsm patch is only for Gaia.

Axelar probably has their own fork then or they use Ethermint? My patches do not support this

**Comment by ScepticMatt** [comment]
> @ScepticMatt Yea this lsm patch is only for Gaia.
> 
> Axelar probably has their own fork then or they use Ethermint? My patches do not support this

Thanks I saw that they forked it. I forked their fork and will try if I can bypass this

**Comment by mmulji-ic** [comment]
@Jacoblava @ScepticMatt please repoen if your forked forks do not work. 
Otherwise, closing as this issue seems temporarily resolved. We hope to move to sdk47 soon and hopefully this forking will not be needed.  Thanks @Reecepbcups for updating.
