### ISSUE TITLE
Unclear Contributing.md

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/gaia#2318]
# Problem

Minor issue in Contributing.md:

https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#process-for-reviewing-prs

> All PRs require at least **one** review before merge (except docs changes, or variable name-changes which only require **one**). When reviewing PRs please use the following review explanations:

Emphasis mine. This should be adjusted, since it sounds like docs changes and variable name-changes are a special case, but are treated the same right now

# Closing criteria

The contributing.md file clearly communicates how many reviews are necessary for what types of PRs.

**Comment by mpoke** [comment]
Closing as outdated. The contributing guidelines were updated in https://github.com/cosmos/gaia/pull/2375
