### ISSUE TITLE
Adhere to Semver

### ISSUE THREAD

**Issue by heipacker** [cosmos/gaia#232]
## Summary of Bug
require github.com/cosmos/gaia: version "v2.0.3" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

## Version
v2.0.3

## Steps to Reproduce
add the following content to go.mod
github.com/cosmos/gaia v2.0.3

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Yeah, good point @heipacker. Being that Gaia is module-based, it must adhere to the standards of semver in the package structure.

**Comment by shahankhatch** [comment]
v3.0.0 is about to be released and will be semver-ed.
