### ISSUE TITLE
Test: upgrade test issues

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2328]
## Summary
When opening a new PR in gaia, the [upgrade test](https://github.com/cosmos/gaia/blob/715b5f599ce96d12ed28c70d37540340cd3b7710/.github/workflows/test.yml#L113-L156) is triggered.

However, the binary versions in this upgrade test are hard-coded. For example, present PRs are all running upgrade test from gaiad v8 to gaiad v9. This is not necessary since gaia v8 and v9 are tested many times (in every PR after v9 released).
 

## Problem Definition
Running repeated same test in every PR for the same code (tagged releases) are time consuming.

## Proposal
There are two possible solutions:

1. keep the upgrade test binary versions still hard coded, only run it when tagging a version.
2. keep the upgrade binary version configurable, `upgradeFrom` is the last released major version, `upgradeTo` is binary built from present PR.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Closing as completed in [#2328](https://github.com/cosmos/gaia/issues/2328)

Please favor reopening [#2328](https://github.com/cosmos/gaia/issues/2328) in case additional work needs to be done or there is more information.
