### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by w1t** [cosmos/gaia#233]
## Version

gaiad version
0.34.7
 gaiacli version
0.34.7

## Steps to Reproduce

1) git clone https://github.com/cosmos/gaia.git && cd gaia && git checkout v2.0.3; make install
2) build github.com/cosmos/gaia/cmd/gaiad: cannot load github.com/prometheus/client_golang/prometheus: import lookup disabled by -mod=readonly
make: *** [install] Error 1

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
try running `go get ./...` then running `make install` again. This should solve your problem

**Comment by w1t** [comment]
Hi Marbar

Thank you!

It fixed the issue. There was a permission issue in the mod cache folder on my computer

go get ./...  points out the exact location. 

Should it be included in the Makefile?

**Comment by tac0turtle** [comment]
it works fine on most systems. if the issue arises for more people we will consider a different approach in the makefile
