### ISSUE TITLE
txs always empty

### ISSUE THREAD

**Issue by OnfireMrHuang** [cosmos/gaia#234]
gaiad、gaiacli version 2.0.3
network cosmos-hub3

./cli.sh query txs --tags 'action:send&recipient:cosmos1uku8qhns5qhpvlpdpj87e4dyvfwtjhvf3u4e33' --page 1 --limit 30    
{"total_count":"0","count":"0","page_number":"1","page_total":"0","limit":"30","txs":[]}

There are two transactions on this address,but always get this.
why?

**Comment by alexanderbez** [comment]
Tx events have been updated. Please see the SDK changelog. In each module's spec, you'll find a `xx_events.md` file that outlines all the events a module emits.

So, your query should be: `message.action=send&transfer.recipient=cosmos1uku8qhns5qhpvlpdpj87e4dyvfwtjhvf3u4e33`
