### ISSUE TITLE
Docs: The command provided in the documentation does not work. 

### ISSUE THREAD

**Issue by suhas2892** [cosmos/gaia#2344]
# Problem

The below command provided in the documentation does not work. Please update this with the correct command in this [documentation](https://hub.cosmos.network/main/hub-tutorials/gaiad.html).

Command:
**gaiad config trust-node true**

# Closing criteria

Provide a command that works with the latest gaiad version.

**Comment by mmulji-ic** [comment]
Hello @suhas2892 thanks for reporting, good catch!

Trust node has been removed from the SDK and there isn't an equivalent/substitute. 
`Trust connected full node (don't verify proofs for responses)`, now there is always a verification of the proofs.
