### ISSUE TITLE
how to decode block.txs struct ?

### ISSUE THREAD

**Issue by yuexk** [cosmos/gaia#235]
when i use ` http://localhost:26657/block?height=162 ` to request the block info, get the result txs is  `"txs": [
          "ygMoKBapCkGSHS5OChRAsUryodevco67KzG/xtkqcKKsPxIUx8IB1mO1bXRY0vHThzr6b+PHVyEaDwoFdWF0b20SBjE3OTUxMxITCg0KBXVhdG9tEgQ1MDAwEMCaDBpqCibrWumHIQLYr10CGdirWdCxyo+kTFfeKBhdueAXA73uL4iF9oaz3BJAMMi8hiry0oRtO6Mp6TgJyOz3KMMEjhQ/LMpWg18fG5Ed+hvB6A3sj9isFEwz8rBEXIBz0tAK8/hSB1oOel6TqyL/AeGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMvw==",
          "xQEoKBapCj6SHS5OChQWvJhcg6nD0vdXW0VQNeLn/ptojxIUx8IB1mO1bXRY0vHThzr6b+PHVyEaDAoFdWF0b20SAzEwMBITCg0KBXVhdG9tEgQ1MDAwEMCaDBpqCibrWumHIQPW7BS0bPVegw1gvgBrFQ4bh22Wjovon8pHhtJ1ID/bhhJAyY7TEhA9rb1fRUFncRjXWfS4eiJ9BkPxpDezZaa8lrQbEBcBm4haPs6gR2d7lhAzQXMUm3Dtn7YyTpMGOFD2EA=="
        ]`， how to decode it through the cosmos RPC method ? or how to configuration the `config.toml` to solution it?

**Comment by alexanderbez** [comment]
Via the CLI or REST interfaces.

e.g.

```
gaiacli tx decode "ygMoKBapCkGSHS5OChRAsUryodevco67KzG/xtkqcKKsPxIUx8IB1mO1bXRY0vHThzr6b+PHVyEaDwoFdWF0b20SBjE3OTUxMxITCg0KBXVhdG9tEgQ1MDAwEMCaDBpqCibrWumHIQLYr10CGdirWdCxyo+kTFfeKBhdueAXA73uL4iF9oaz3BJAMMi8hiry0oRtO6Mp6TgJyOz3KMMEjhQ/LMpWg18fG5Ed+hvB6A3sj9isFEwz8rBEXIBz0tAK8/hSB1oOel6TqyL/AeGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMv+GKiOGJvOGLveGMvw=="
```
