### ISSUE TITLE
47 Upgrade

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2376]
Relevant PR's:

* https://github.com/Gravity-Devs/liquidity/pull/29
*

**Comment by mpoke** [comment]
@faddat we plan to remove the Liquidity module before the upgrade to SDK 0.47. See https://github.com/cosmos/gaia/issues/2346.

**Comment by mpoke** [comment]
Closing this issue in favor of https://github.com/cosmos/gaia/issues/2413.
