### ISSUE TITLE
trustwallet link is broken

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2379]
# Problem

https://trustwallet.com is broken resulting in `Check Markdown links` to fail. 

# Closing criteria

The link is fixed of removed.

**Comment by mmulji-ic** [comment]
... this is assuming that the org behind Trust wallet is gone, if its not and their server is just down, we disable checking for a region like so:

```
<!-- markdown-link-check-disable -->
<!-- markdown-link-check-enable -->
```

For a one-liner, you can use:
```
<!-- markdown-link-check-disable-next-line -->
```
