### ISSUE TITLE
Remove SPM

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2388]
The cosmos hub contains a deprecated software component. Today I was working with a team member to fix issues with queries that are mentioned in #2313.

```log
 gaia % go mod tidy
go: downloading github.com/cosmos/cosmos-sdk v0.45.16-ics
go: github.com/tendermint/spm@v0.1.9 requires
	github.com/cosmos/cosmos-sdk@v0.44.3: reading github.com/cosmos/cosmos-sdk/go.mod at revision v0.45.16-ics: unknown revision v0.45.16-ics
```

Here's various related work:

* https://github.com/cosmos/interchain-security/pull/812

This removes ICS from the hub and allows these fixes to happen.

* https://github.com/cosmos/interchain-security/pull/805

That makes the hubs sdk version match the one used in ics.  Hub main branch uses 45.15.  Ics should too. 

* https://github.com/cosmos/interchain-security/pull/823

That will make ics use the latest IBC.  The hub should do that too. 

So, thing is, if you try and use a patched cosmos-sdk, as we did here:

**Comment by mpoke** [comment]
@faddat Thank you for opening an issue. Could you please give more context on the problem and the desire closing criteria? 

Also note that at the moment there is no v0.45.16-ics release. The latest is v0.45.15-ics. 
> go: downloading github.com/cosmos/cosmos-sdk v0.45.16-ics

**Comment by faddat** [comment]
I am here to provide more information if needed. So you see SPM is an archived repository that was last worked on in January of 2022. It has caused chain halts.

It has also broken CLIs, and it causes chains to diverge from the normal path of development. Now in Gaia case, it may not be that severe, however, it's really best that it just not be in our precious Gaia.

**Comment by mpoke** [comment]
Is https://github.com/cosmos/gaia/pull/2442 going to fix this issue?

**Comment by mpoke** [comment]
Fixed by https://github.com/cosmos/gaia/pull/2442
