### ISSUE TITLE
Can't checkout to gaia's sdk branch/tag

### ISSUE THREAD

**Issue by catShaark** [cosmos/gaia#2391]
# Problem

I checkout to tag v0.45.13-ics on cosmos-sdk but fail everytime. I also failed to checkout to [this commit](https://github.com/cosmos/cosmos-sdk/commit/d6c8598683ce1ac8efd39941109eae78b8211ddf) which is last the commit of the v0.45.13-ics tag. When I look it up on github web, It says: [This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.](https://github.com/cosmos/cosmos-sdk/tree/v0.45.15-ics)

# Closing criteria

Dev can easily checkout to gaia's sdk

# Problem details

**Comment by faddat** [comment]
hey, I was just thinking and I have a guess, let me try something

**Comment by faddat** [comment]
@catShaark interestingly, this did not work:

```bash
 git remote add informal https://github.com/informalsystems/cosmos-sdk
git fetch --all
git checkout v0.45.15-ics
```

**Comment by julienrbrt** [comment]
v0.45.x-ics are created from the SDK repo. I personally have no issue checking them out.

**Comment by faddat** [comment]
huh -- I will record this for you cause ... there's an oddity that both Khanh and I hit.  I'm sure there's a way to handle it, but not sure which.  We also failed to check out the commit itself.  

thanks for following up


<img width="670" alt="Screenshot 2023-04-10 at 1 21 22 AM" src="https://user-images.githubusercontent.com/7142025/230789885-ff963629-9e98-490f-ae01-60b6373f0a48.png">





https://user-images.githubusercontent.com/7142025/230790449-c1ad765a-5ba5-4252-9868-7c9493095de8.mov

**Comment by julienrbrt** [comment]
> huh -- I will record this for you cause ... there's an oddity that both Khanh and I hit. I'm sure there's a way to handle it, but not sure which. We also failed to check out the commit itself.
> 
> thanks for following up
> 
> <img alt="Screenshot 2023-04-10 at 1 21 22 AM" width="670" src="https://user-images.githubusercontent.com/7142025/230789885-ff963629-9e98-490f-ae01-60b6373f0a48.png">

Weird, just cloning the SDK from GH (new folder and other machine) and `git checkout v0.45.13-ics` works for me.

**Comment by faddat** [comment]
That's super weird.

I'll try same.  Maybe both Khanh and I have something that's making it not work because we both have lots of remotes? I'm not sure. Thank you for following up.

**Comment by mmulji-ic** [comment]
I didn't have problems with fetching & checking out the tags. Try `git fetch --tags`



```
cosmos-sdk on  main via 🐹 v1.18.10 with 🐃 v1.16.0
❯ git fetch --tags
remote: Enumerating objects: 321, done.
remote: Counting objects: 100% (254/254), done.
remote: Total 321 (delta 254), reused 254 (delta 254), pack-reused 67
Receiving objects: 100% (321/321), 282.66 KiB | 1.06 MiB/s, done.
Resolving deltas: 100% (268/268), completed with 96 local objects.
From github-as-mmulji-ic:cosmos/cosmos-sdk
 * [new tag]             v0.45.12-ics -> v0.45.12-ics
 * [new tag]             v0.45.13-ics -> v0.45.13-ics
 * [new tag]             v0.45.14-ics -> v0.45.14-ics
 * [new tag]             v0.45.15-ics -> v0.45.15-ics

cosmos-sdk on  main via 🐹 v1.18.10 with 🐃 v1.16.0 took 2s
❯ git checkout v0.45.15-ics
v0.45.0        v0.45.2        v0.45.5        v0.45.8        v0.45.11       v0.45.12-ics   v0.45.13-rc.0  v0.45.14-ics   v0.45.15-rc.0
v0.45.0-rc1    v0.45.3        v0.45.6        v0.45.9        v0.45.11-ics   v0.45.13       v0.45.13-rc.1  v0.45.15
v0.45.1        v0.45.4        v0.45.7        v0.45.10       v0.45.12       v0.45.13-ics   v0.45.14       v0.45.15-ics

cosmos-sdk on  main via 🐹 v1.18.10 with 🐃 v1.16.0
❯ git checkout v0.45.15-ics
Note: switching to 'v0.45.15-ics'.
```

**Comment by mmulji-ic** [comment]
> That's super weird.
> 
> I'll try same. Maybe both Khanh and I have something that's making it not work because we both have lots of remotes? I'm not sure. Thank you for following up.

Having soo many remotes maybe is messing it up, for the time being I close this, unless a new issue crops up around the SDK repo and the tags that Gaia is using.
