### ISSUE TITLE
Same address representation for query and bond

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/gaia#24]
When you query the validator set with `gaiacli query validators` it returns a differently encoded pubkey that you cannot use for `gaiacli tx bond ...`. 

It would be great if the outputs of both commands would be encoded in the same way.

**Comment by rigelrozanski** [comment]
Hey you're right, currently the PubKey used in querying is the serialized bytes of a `crypto.PubKey` type. This will shortly be updated to be the unserialized bytes and will be able to be used as you're requested

**Comment by rigelrozanski** [comment]
Integrated in `feature/delegation`
