### ISSUE TITLE
failed to get from fields: The specified item could not be found in the keyringroot

### ISSUE THREAD

**Issue by NemezizKB** [cosmos/gaia#240]
https://github.com/cosmos/gaia/blob/ibc-alpha/ibc-demo.md
currently trying to test IBC on cosmos by following this doc
facing an issue in IBC client Creation
able to create IBCCLIENTONE but while creating IBCCLIENTZERO getting this erro
:~/ibc-testnets# gaiacli --home ibc1/n0/gaiacli \

tx ibc client create ibczeroclient
$(gaiacli --home ibc0/n0/gaiacli q ibc client node-state)
--from n1 -y -o text
failed to get from fields: The specified item could not be found in the keyringroot

**Comment by migueldingli1997** [comment]
I'm getting this issue as well. Have you managed to solve it @NemezizKB ?

**Comment by NemezizKB** [comment]
I could not solve. Instead i ran the demo script. It works when you run the IBC demo script.

**Comment by marklude** [comment]
having same issue, any solution yet?

**Comment by glnro** [comment]
Hi @NemezizKB, thanks for posting your issue! We've been behind on many reviews and apologize for such. Would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team
