### ISSUE TITLE
State-machine breaking is unclear

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#2401]
# Problem

Currently, we don't have a clear documentation of what it means for a change to be state-machine breaking. 

# Closing criteria

Add a section to CONTRIBUTING.md on state compatibility. See Osmosis as an example https://github.com/osmosis-labs/osmosis/blob/main/CONTRIBUTING.md#state-compatibility

**Comment by yaruwangway** [comment]
Hi, @mpoke , is this still an issue ?

**Comment by mpoke** [comment]
@yaruwangway Yeah, we can improve the docs regarding this topic.
