### ISSUE TITLE
Need repository access

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2408]
Hi I'm Jacob, the Cosmos have his funded my team too maintain itself. If this is to remain the official repository then let's please get me added to this repository, as well as my team members.

**Comment by mpoke** [comment]
@faddat You were added to the Cosmos org as a maintainer of the https://github.com/orgs/cosmos/teams/notional team. Please create sub-team for the Gaia repo. The format must be `team-name_repository_access-right`

**Comment by mpoke** [comment]
@faddat Let me know if you still need help with this issue. I'm closing it for now.
