### ISSUE TITLE
IBC DEMO is returning CODE :107 at the time of Receive Packets

### ISSUE THREAD

**Issue by NemezizKB** [cosmos/gaia#241]
After Channel Creation, while querying receiving the below response :
root@ip-xyz.xx.yy.z : ~ /ibc-testnets# gaiacli --home ibc0/n0/gaiacli q ibc channel end bankbankbank channelzero --indent --trust-node
{
  "channel": {
    "state": "",
    "ordering": "NONE",
    "counterparty": {
      "port_id": "",
      "channel_id": ""
    },
    "connection_hops": null,
    "version": ""
  }
}
root@ip-xyz.xx.yy.z: ~ /ibc-testnets# gaiacli --home ibc1/n0/gaiacli q ibc channel end bankbankbank channelone --indent --trust-node
{
  "channel": {
    "state": "",
    "ordering": "NONE",
    "counterparty": {
      "port_id": "",
      "channel_id": ""
    },
    "connection_hops": null,
    "version": ""
  }
}
![GIT 1](https://user-images.githubusercontent.com/55424455/71613503-e8f64d80-2bcc-11ea-82f4-046644689e74.PNG)

error log:

ibc0 <- update_client           [OK] txid(86CF6C6F6B6009D01132C2BCFEDEBB8361F9562AC27DD43D006D6EC9000C2402) client(ibczeroclient)
{"chain_id":"ibc1","account_number":"3","sequence":"11","fee":{"amount":[],"gas":"200000"},"msgs":[{"type":"ibc/transfer/MsgRecvPacket","value":{"packet":{"type":"ibc/channel/Packet","value":{"sequence":"1","timeout":"120","source_port":"bank","source_channel":"channelzero","destination_port":"bank","destination_channel":"channelone","data":"eyJhbW91bnQiOlt7ImRlbm9tIjoiYmFuay9jaGFubmVsb25lL3N0YWtlIiwiYW1vdW50IjoiMSJ9XSwic2VuZGVyIjoiY29zbW9zMXAzdzNtdnV5ajQwdXhlMDJueHJ2aDJqZDdrdGRrODQ0bTkwc2RyIiwicmVjZWl2ZXIiOiJjb3Ntb3MxdDI2M3NqNWdsc2pubXcwZXJtemFsajRmcngwa2xkbm4zOHlhbjIiLCJzb3VyY2UiOnRydWV9"}},"proofs":[{"proof":{"ops":[{"type":"iavl:v","key":"cG9ydHMvYmFuay9jaGFubmVscy9jaGFubmVsemVyby9wYWNrZXRzLzE=","data":"gQIK/gEKKQgIEAwY0QIiIMwRpE94s476y2U2KDAmD9BB/052oreIyNo0CowiUWaFCikIBhAHGNECIiDhhUlNoTRaztknWEFZF8ILtGm/OcRXT0GiXsiakyX0KwopCAQQAxjRAiIg1HZbUIHMbO4Z9luDAbUg8Dr0x4w5+lYe+YdWdgMtX3EKKQgCEAIY0QIiIHstv2dBhaCmdaNjcccS5B5fZ5C2Plhb5kYLrj1l0U9vGlAKKXBvcnRzL2JhbmsvY2hhbm5lbHMvY2hhbm5lbHplcm8vcGFja2V0cy8xEiBdOuMxd7SlsyZjAeE21JEZjUZpSQ4iqT7fqOjmUe3g+hjRAg=="},{"type":"multistore","key":"aWJj","data":"/QMK+gMKNwoMZGlzdHJpYnV0aW9uEicKJQjeAhIg8j+X63bXjzmk6HV1oXxTKVXP4DaKqJ0qcH6Q2zGHjBsKMwoIc2xhc2hpbmcSJwolCN4CEiBaSdmLIyKN4XXEBWZ6ebfwWMzmCeAaS9KPcAQdMezpVQouCgNpYmMSJwolCN4CEiCezWHlPD0NvLfoPymlSDS6H5MmqR5n9upyFTul2haGQgovCgRtYWluEicKJQjeAhIgLlfvk2BxBfQuVDx2CcfTIaMDoD6Y6I0m+E3VKdOR0WAKMgoHc3Rha2luZxInCiUI3gISIDQuYiTj+F+Y/SzK/5MMQcMJGEKn/l5aUpOE6fUR+dRGCjEKBnN1cHBseRInCiUI3gISIE4XmIeyPImYHDkfvmNJ08/NnY6PZDSP26SrCRonQH/4Ci4KA2FjYxInCiUI3gISICfzIAm0LPuCFaqxN34bb6YR6XyBt/jNacCzb4TLK28ZCi8KBG1pbnQSJwolCN4CEiCsbfuOW9e0nQX2drnxcwCne79SN2HSJ/SEwbgvw/k1FAoxCgZwYXJhbXMSJwolCN4CEiDc+tPoZ9p8khPp2Nyt6ls817WnEELASt9/El0S5beAFQouCgNnb3YSJwolCN4CEiBgzRN8GWLsrGFjidaANIM/KSFQnC0oWqX1FTmXzpaKdA=="}]}}],"height":"351","signer":"cosmos1t263sj5glsjnmw0ermzalj4frx0kldnn38yan2"}}],"memo":""}

confirm transaction before signing and broadcasting [y/N]: Y
Password to sign with 'n1':
{"height":"332","txhash":"C4EA22FA3CDDB7BAD9EBBAA83064BE1B9E57340ECA9FE7377F8143CCCB490F9E","code":107,"raw_log":"[{\"msg_index\":0,\"success\":false,\"log\":\"{\\\"codespace\\\":\\\"ibc/channels\\\",\\\"code\\\":107,\\\"message\\\":\\\"packet timeout\\\"}\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"recv_packet\"}]}]}]","logs":[{"msg_index":0,"success":false,"log":"{\"codespace\":\"ibc/channels\",\"code\":107,\"message\":\"packet timeout\"}","events":[{"type":"message","attributes":[{"key":"action","value":"recv_packet"}]}]}],"gas_wanted":"200000","gas_used":"48204","codespace":"ibc/channels","events":[{"type":"message","attributes":[{"key":"action","value":"recv_packet"}]}]}

![GIT 2](https://user-images.githubusercontent.com/55424455/71613504-e8f64d80-2bcc-11ea-9a9b-c73d01ad73fd.PNG)

**Comment by glnro** [comment]
Hi @NemezizKB, thanks for posting your issue! We've been behind on many reviews and apologize for such. Would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team
