### ISSUE TITLE
Add command to gaiad to show the address of a validator's operator address.

### ISSUE THREAD

**Issue by w1t** [cosmos/gaia#242]
## Summary

The validator address with cosmosvaloper prefix only displays once after I enter following command to create a validator.  the validator address was not stored or can not be checked anywhere.  

$ gaiacli tx staking create-validator

## Problem Definition

If i forget to write down the validator address at the time i create the validator, there is no easy way to check the validator status unless it is on top 125 list

It could be a serious issue for people joining the main net first time. they will need to self delegate a lot atoms to be on 125 list to get a feel of operating a validator, tighten up security and such.   The situation could be worse since it would be harder to get on the top 125 list later on. 
  
Unfortunately none of the commands below display validator address, which has  cosmosvaloper as prefix.

gaiad tendermint show-validator
gaiad tendermint show-address

## Proposal

1) The feature was supposed to be in the SDK, but i could not find it in gaiad and gaiacli  
https://github.com/cosmos/cosmos-sdk/issues/1274

include validator address in one of following command 

gaiad tendermint show-validator
gaiad tendermint show-address

pro:

easy to change

con: 
it will take longer release cycle and need to update validator node on main net

2) add the feature in gaiacli. 

pro: no need to upgrade the mainnet

con: less secure, specially when gaiacli runs against a remote node.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
There already exists functionality for this: `gaiacli keys show <key-name> --bech=val`, where `<key-name>` is the key name you used when you created you validator.

**Comment by EbrahimElbagory** [comment]
Is there anyway I can use this query through the api
