### ISSUE TITLE
gaiacli documentation appears out of date

### ISSUE THREAD

**Issue by mperklin** [cosmos/gaia#243]
## gaiacli documentation appears out of date

When trying to troubleshoot why my `gaiacli txs` query was no longer working, I stumbled upon [this documentation](https://github.com/cosmos/gaia/blob/495feeca8e8ba48bb59c49677ed16d01e16e61e3/docs/resources/gaiacli.md#matching-a-set-of-tags) that includes broken hyperlinks to a variety of modules to list query tags.

This documentation should be updated to provide updated/accurate info on how to use `gaiacli` to query lists of transactions.

## Version

```
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.3
commit: 2f6783e298f25ff4e12cb84549777053ab88749a
build_tags: netgo,ledger
go: go version go1.13.5 darwin/amd64
```

## Steps to Reproduce

`gaiacli query txs --tags 'delegator:cosmos1sjllsnramtg3ewxqwwrwjxfgc4n4ef9u0tvx7u' --limit 100`

This is an example of a command that appears to match the formatting of the examples in the documentation, however this command does not work with gaiacli 2.0.3.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Will address this doc once https://github.com/cosmos/cosmos-sdk/pull/5482 is merged upstream. Thanks @mperklin!
