### ISSUE TITLE
spm

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2430]
Currently the main branch imports spm

out of an abundance of caution, I recommend that we backport spm removal to ics v1.2.1

* https://github.com/cosmos/interchain-security/issues/870

**Comment by mpoke** [comment]
@faddat See https://github.com/cosmos/interchain-security/issues/870#issuecomment-1519914065 for details on this issue.

**Comment by mpoke** [comment]
**Closing criteria:** bump ICS to v1.1.1 once it's released.
