### ISSUE TITLE
External contributors pr's always fail to upload code coverage resuilts

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2431]
* https://github.com/cosmos/gaia/actions/runs/4765475629/jobs/8471240094?pr=2185

(not 100% sure this is the reaosn, we may just want to make this unconditional in ci)

**Comment by mmulji-ic** [comment]
hi @faddat , quite often we get failures as well, I think its instability with the tool. We are planning to move fully to SonarCloud. When checking PR's for merging, I check whether its a test failure or an report upload failure, that we can re-run individually. I checked CodeCov and its seems for you https://github.com/cosmos/gaia/pull/2432/checks ran the required tests ok.

See https://github.com/cosmos/gaia/issues/2436 , for CodeCov -> SonarCloud issue
