### ISSUE TITLE
The Interchain.io Archive should be linked in the gaia docs

### ISSUE THREAD

**Issue by zmanian** [cosmos/gaia#244]
We should have a link to the Interchain.io [archive](https://archive.interchain.io/) in the gaia docs.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
this is not closed. I can't find this page on https://hub.cosmos.network/
