### ISSUE TITLE
Implement CI testing against main/release branches for the selected platforms.

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#2441]
# Problem

Gaia needs to run on multiple platforms, typically validator and end user systems will differ in terms of operating system and other hardware specifics. This initial issue is to start with this type of testing across platforms and then, over time, expand or reduce scope based on platform requirements after discussions with stakeholders, see the tracking issue for these other activities #2258 .

Emphasis is NOT on running the e2e suite on different platforms, but on running user level cli operations and those that require crypto wallets.

# Closing criteria

Gaia nightly tests are run on a number of platforms/architectures.

**Comment by mmulji-ic** [comment]
@mpoke did we decide to postpone this?

**Comment by mpoke** [comment]
> @mpoke did we decide to postpone this?

We are releasing Gaia on multiple platforms. As a result, we should test for those platforms.
