### ISSUE TITLE
Request to remove Gaia Modules docs

### ISSUE THREAD

**Issue by rootulp** [cosmos/gaia#2452]
https://hub.cosmos.network/main/modules/ isn't particularly helpful b/c it doesn't list ~~any modules~~ all modules. Proposal to update this page with the modules used by Gaia or remove it entirely.

https://github.com/cosmos/gaia/blob/8a522e98a2863205cf02fb97f8ad27d091670b9d/docs/modules/README.md?plain=1#L3-L4

**Comment by mpoke** [comment]
Hi @rootulp. This section contains the GlobalFee module, i.e., 
```md
## New Modules in Rho V8

- [Global Fee](./globalfee.md)
```
Please let us know if you cannot see this section (i.e., https://hub.cosmos.network/main/modules/#new-modules-in-rho-v8).

**Comment by rootulp** [comment]
Good point, I do see that module. I don't see any other modules listed but I infer from [here](https://github.com/cosmos/gaia/blob/060d37d093da15e2e2ad28bcc0eadbd275b3f411/app/modules.go#L111-L148) that Gaia is using other Cosmos SDK modules.

**Comment by mpoke** [comment]
> Good point, I do see that module. I don't see any other modules listed but I infer from [here](https://github.com/cosmos/gaia/blob/060d37d093da15e2e2ad28bcc0eadbd275b3f411/app/modules.go#L111-L148) that Gaia is using other Cosmos SDK modules.

Yes, but those are documented in the SDK docs.  Not sure it's necessary to list here all the SDK modules. @mmulji-ic what do you think?

**Comment by mpoke** [comment]
@rootulp I'm closing this issue. Please let us know if you think we should re-open.
