### ISSUE TITLE
Test: local test script to check upgrade

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2458]
## Summary

The script sets up and upgrades the local test network from v9 to v10, with query and propose global fee params.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by sainoe** [comment]
Duplicate of #2456
