### ISSUE TITLE
Docker Hub release for Gaia v2.0.3

### ISSUE THREAD

**Issue by willclarktech** [cosmos/gaia#248]
## Summary

Please publish an updated image to Docker Hub.

## Problem Definition

I've been running Gaia via Docker Hub (currently using `v2.0.0`), but there's no image for `v2.0.3`.

## Proposal

Publish `v2.0.3` to Docker Hub and ideally automate this process for subsequent releases.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
cc @mircea-c

**Comment by mircea-c** [comment]
Looks like the automated process (located in the `.circleci` folder at the root of this repo) needs some updating since it is not taking into consideration the release tags. I'll push a fix shortly.

**Comment by willclarktech** [comment]
@mircea-c Thanks, looks like that solves the long-term issue. Is it possible to release v2.0.3 as a one-off though?

**Comment by willclarktech** [comment]
^ @alexanderbez

**Comment by mircea-c** [comment]
Hi @willclarktech! You can pull both v2.0.3 and v2.0.4 from the hub now.

**Comment by willclarktech** [comment]
Fantastic, thanks @mircea-c !

**Comment by romeo4934** [comment]
@mircea-c Hi Mircea, could we have others versions like v2.0.8 ?
https://hub.docker.com/r/tendermint/gaia/tags
Thank you!

**Comment by romeo4934** [comment]
@alexanderbez

**Comment by alexanderbez** [comment]
Hey @antoineherzog, unfortunately, I don't know too much about how this process works? I do know there is a CI job that is supposed to do this, I think?

**Comment by romeo4934** [comment]
Yes. Maybe the circleci is not properly configured? I am not an expert on this fied unfortunately :(
https://github.com/cosmos/gaia/blob/master/.circleci/config.yml

**Comment by romeo4934** [comment]
@alexanderbez

**Comment by tac0turtle** [comment]
seems like the username or password has changedhttps://app.circleci.com/pipelines/github/cosmos/gaia/1207/workflows/4165947d-20b5-4cf9-bea3-b0d955e988bd/jobs/11927

will ping someone about this

**Comment by romeo4934** [comment]
@marbar3778 Great! sounds good.

**Comment by tac0turtle** [comment]
https://github.com/cosmos/gaia/pull/357#pullrequestreview-393947927

we found the issue and fixed it. we will try to manually psuh 2.0.8 to docker hub for the time being

**Comment by romeo4934** [comment]
Wonderfull! 
Thank you so much :)

**Comment by romeo4934** [comment]
@marbar3778 Did you get a chance to upload the version 2.0.8 also?

**Comment by tac0turtle** [comment]
we have not done so yet. We are running into some issues with manually pushing it, will update when we do.

**Comment by romeo4934** [comment]
Thank you!

**Comment by romeo4934** [comment]
Do you have any ETA to push 2.0.8 on dockerhub?

**Comment by tac0turtle** [comment]
@alessio is the man with the docker hub credintals. He is the best to ask. There is the off chance that a minor release is made soon as well.

**Comment by alessio** [comment]
@antoineherzog https://hub.docker.com/layers/tendermint/gaia/v2.0.8/images/sha256-76c50c6b197e9f8278c0a99a9853b262b724d3fe8a101d47b700e472ac5ff226?context=repo

**Comment by romeo4934** [comment]
Thank you Alessio!!!

**Comment by KrzysztofHajdamowicz** [comment]
@alessio Can you automate pushing image to hub? 2.0.11 is current stable and it isn't in the hub :(

**Comment by tac0turtle** [comment]
I don't have permission on that org. @alessio would be the correct person to ask

**Comment by tac0turtle** [comment]
we will be migrating the gaia docker images to a new docker org. Once we have the release from the sdk (0.37.14) I will update this repo and the new location will house the image.
