### ISSUE TITLE
halt-height not checked & respected by sync thread post restart as 1st thing (sync new blocks across the border) in v9

### ISSUE THREAD

**Issue by jun0tpyrc** [cosmos/gaia#2482]
## Summary of Bug

- set --halt-height in commandline & app.toml
- without the halt-height being removed, the node still sync bypassing the halt-height after restart to new blocks instead of checking that it shouldn't finalize and store new block post that value , from logs both `sync new block thread` and `check halt-height & exit thread` is working , whatever faster will do it work => so after few restart (each moving a few blocks) the node  finally reaching the consensus-breaking block 
- we set halt-height before the last mainnet upgrade , it's still broken like https://github.com/cosmos/gaia/issues/2476

(from exp, we expect post restart there being a hardstop for sync thread - `should refuse to ingest new block >= halt-height`)

## Version

v9.0.1, v9.1.0

## Steps to Reproduce

same as above
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Thanks for opening the issue.

I was not able to reproduce the issue where the `halt-height` is not respected. I will try creating scenarios to cause the specified behaviour. Would you mind sharing information about your setup (OS, config file, tools you use (k8s, ansible, shell scripts only))?

Are you experiencing any issues with `v10`?

**Comment by MSalopek** [comment]
@jun0tpyrc Hey, I'm checking up on this issue.

Did you face any further issues?

Gaia will be updating to `v11` very soon, and this issue is about `v9`.

**Comment by mmulji-ic** [comment]
Hi @jun0tpyrc closing this issue as stale, please reopen if you have similar issues. 
Currently testnet is on `v13` will move to `v14` next week.
