### ISSUE TITLE
make install does not support forwards compatibility of golang versions

### ISSUE THREAD

**Issue by damiannolan** [cosmos/gaia#2487]
## Summary

Running `make install` performs strict equality on Go version by using the [`check_version`](https://github.com/cosmos/gaia/blob/v9.1.0/Makefile#L98) target.

This would be better suited to use greater than or equal to. 

For example, checking out `v9.1.0` and running `make install` with Go >1.18 fails. This is unexpected behaviour.

## Version

I've noticed this is applicable to the following, but could be more?

- `main` (mandates Go 1.20)
- `v9.1.0` (mandates Go 1.18)

## Steps to Reproduce

1. Install a version of Go greater than 1.18
2. Checkout `v9.1.0`
3. Run `make install`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by glnro** [comment]
If you run gaia built with 1.18 and 1.19 for example you can app hash. This is why there's a hard requirement to stick to one version...there have just been other pressing updates and making sure all validators building from the source used a different  but consistent go version was deemed an extra risk.

**Comment by faddat** [comment]
Validators are reporting app hashes on 1.18 too.

1.18 is deprecated.

**Comment by faddat** [comment]
For now, please do not use versions greater than 1.18 -- I think it was a mistake to use a deprecated language runtime, but that is what v9.1.0 uses. 

In the future, this PR will handle things nicely:

* https://github.com/cosmos/gaia/pull/2490

**Comment by damiannolan** [comment]
I guess the [Go 1.19 release notes](https://go.dev/doc/go1.19) don't provide any guarantees.
> We expect almost all Go programs to continue to compile and run as before.

It does seem quite odd tho, was there RCA done or did anyone manage to track down the source of indeterminism?

**Comment by damiannolan** [comment]
Btw, feel free to close this issue if its out of scope, but it would be nice to not have to rely on specific Go versions for builds

**Comment by faddat** [comment]
@damiannolan - fyi, we'll always want to have a full validator set on the same version of the go runtime. 

go 1.18 is deprecated so we probably shouldn't use it, but I think v10 fixes this.  

My recommendation is like:

Use the latest go and at least one feature in it.  That way, the software requires the latest go.

**Comment by mpoke** [comment]
Gaia v10 will use go 1.20. Closing this issue as removing the check in the Makefile may result in a apphash mismatch.

**Comment by mmulji** [comment]
@mmulji-ic ping test!
