### ISSUE TITLE
genutil and globalfee init order

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#2489]
## Summary of Bug

In genutils module, there is [`DeliverGenTxs`](https://github.com/cosmos/cosmos-sdk/blob/HEAD/x/genutil/gentx.go#L88) which is called in [`initGenesis`](https://github.com/cosmos/cosmos-sdk/blob/HEAD/x/genutil/genesis.go#L19), `DeliverGenTxs` calls `DeliverTx` which will call the antehandler involved in deliverTx check. 

initGenesis -> DeliverGenTxs -> deliverTx -> antehandler

In the next gaia release, global fee will does fee check also in DeliverTx. Which means in DeliverGenTxs call stack, the globalfee antehandler will be called, global fee module should be inited this moment.

Solution 1: 
init globalfee before genutil module in [`initBlock`](https://github.com/cosmos/gaia/blob/2fd6f6d200176e5fe5d630653e7a6a19baa4bfbe/app/modules.go#L264). 

Disadvantage: if the chain is inited with non-zero globalfee, calling gentx need to be paid, which might cause trouble.

Solution 2:

when getting globalfee Params for fee checks, we check only get the params if they exist, otherwise, return empty params.  
this means `gentx` will go through fee check with min-gas-price 0uatom, bypass-msg=[], and BypassMinFeeMsgTypes = 0
see this [fix](https://github.com/cosmos/gaia/blob/a0cd727f68cbfa7be0a80502f14e5af2dc7d005d/x/globalfee/ante/fee.go#L242).

the fix is to make sure to [check if key exists](https://github.com/cosmos/gaia/blob/a0cd727f68cbfa7be0a80502f14e5af2dc7d005d/x/globalfee/ante/fee.go#L189) before `get` it  to avoid panic

Disadvantage: works, but this put gentx at a different fee check condition, which is empty fees.

Solution 3:

Put gentx as bypass-msg which means it is free. 
concerns: will the gentx exceed bypass allowed max gas ? bypass can be always proposed to be changed.

Solution 4: 
only does globalfee fee antehandler in checkTx.

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
I think solution 2 is the way to go.
