### ISSUE TITLE
Add command to show seed phrase

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/gaia#25]

**Comment by rigelrozanski** [comment]
what do you mean by seed phrase? as in mnemonic phase your private which you generate with `gaiacli keys new`?

**Comment by rigelrozanski** [comment]
@adrianbrink ?

**Comment by zramsay** [comment]
i think he meant a way to get the seed phrase from keyName + password, but I don't think we should do this

**Comment by adrianbrink** [comment]
@rigelrozanski The idea is to be able to recover the seedphrase in case you didn't write it down during the key generation. 

It's massively useful for users, that didn't back up the seedphrase initially. I know they should have, but realistically most won't, because they think they'll never have value on it. 

Once they have some value, they will want to back it up. Currently the process involves generating a new key and then moving the funds. It would be much easier to just show the seedphrase again for an existing key.

**Comment by adrianbrink** [comment]
@zramsay Why shouldn't we do this?

**Comment by zramsay** [comment]
>  that didn't back up the seedphrase initially

yeah, we shouldn't be encouraging bad security/backup practices with features in our code, when the existing workaround simply involves generating a new key and sending funds...

**Comment by rigelrozanski** [comment]
@adrianbrink I actually k i n d a o f disagree? Ledger doesn't allow you to retrieve your seed phrase... I guess this is different because you still have the seed file so somebody could steal your funds anyway if your privkey was hot on your computer anyway?

**Comment by adrianbrink** [comment]
Yes, but the ledger enforces that you have it written down and even then I think it would be nice to be able to get it afterwards.

I love this feature in Jaxx, since it only enforces the cost of security

**Comment by zramsay** [comment]
if a user wants this feature, they can open an issue in SDK repo
