### ISSUE TITLE
Discrepancy between v10 release branch and main

### ISSUE THREAD

**Issue by shaspitz** [cosmos/gaia#2505]
# Problem

https://github.com/cosmos/gaia/pull/2352 was recently merged to main, with changes related to the min-fee module, as well as boilerplate for a "v10 release". It turns out that gaia v10 will not include these changes to the min-fee module. See #2497 for context. 

# Closing criteria

Main is cleaned up with upgrade boilerplate for both v10 and v11

# Problem details

https://github.com/cosmos/gaia/pull/2502 was inspired by code from https://github.com/cosmos/gaia/pull/2352, and merged into the v10 release branch directly, without any corresponding PR to main. We need to update main to have boilerplate for both v10 and v11 with minfee changes

**Comment by yaruwangway** [comment]
hi, @smarshall-spitzbart , "https://github.com/cosmos/gaia/pull/2502 was inspired by code from https://github.com/cosmos/gaia/pull/2352," means 2502 was checkout out from the first commit of 2352 ?
