### ISSUE TITLE
Proto builder

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2506]
Numerous chains using SDK45 are having some issues with building protocol buffers files.

I have a solution for this here:

* #2462 

Here are the issues that it addresses:

* The proto build is dockerized so it works on windows and Mac and Linux
* Proto builder has been updated to use the latest buf and go
* Proto builder will now demand fully qualified domains which makes it easier over time to use

**Comment by mpoke** [comment]
Closing as the next release of Gaia will upgrade SDK to 0.47
