### ISSUE TITLE
gaiad version reports githash instead of tag name for v9.0.3 and v9.1.0

### ISSUE THREAD

**Issue by alexpGH** [cosmos/gaia#2529]
## Summary of Bug

gaiad version reports githash instead of tag name for v9.0.3 and v9.1.0

## Steps to Reproduce
git clone -b v9.1.0 https://github.com/cosmos/gaia
cd gaia
make install
gaiad version
-> HEAD-321d15a574def0f338ceacc5c060159ebba95edc
expected: v9.1.0
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Thanks for opening the issue.

This is the culprit:
https://github.com/cosmos/gaia/blob/main/Makefile#L7C1-L13

```makefile
# Makefile
ifeq (,$(VERSION))
  VERSION := $(shell git describe --exact-match 2>/dev/null)
  # if VERSION is empty, then populate it with branch's name and raw commit hash
  ifeq (,$(VERSION))
    VERSION := $(BRANCH)-$(COMMIT)
  endif
endif
```

Tags for `v9.0.3` and `v9.1.0` were `lightweight` tags, so when you do `git describe --exact-match` there's no exact match.

The tags were probably created using Github UI which [always creates `lightweight`](https://github.com/orgs/community/discussions/4924) tags (as opposed to `annotated` tags when you use the CLi `git -s -a v10.0.0 -m 'v10.0.0'`).

We're updating our release procedure as we speak. These changes will be included in the documentation.
