### ISSUE TITLE
Refactor App Wiring for SDK v0.47 & IBC v7

### ISSUE THREAD

**Issue by glnro** [cosmos/gaia#2533]
# Problem
Upgrade the application trunk to compile and run with SDK v0.47 and IBC v7.  

Disabled components/tests:
- E2E tests
- Global Fee module
- Migration Tests
- ICS

# Closing criteria

The upgraded minimalist version of Gaia compiles, produces bocks and passes the remaining tests.

**Comment by mpoke** [comment]
Fixed by https://github.com/cosmos/gaia/pull/2541
