### ISSUE TITLE
Add a command to Gaia to retrieve all consumer chain keys for a specific consumer chain

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#2555]
## Summary

Add a command for getting all consumer keys for a consumer chain.

## Problem Definition

I want to be able to add a consumer chain support for my monitoring bot, and I’ll need to query for consumer keys on all validators, and it’s more correct to query all of it at once with one query instead of querying it for each validator separately

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by freak12techno** [comment]
As a suggester of the feature in the first place, here's my usecase.

I am writing a tool to track validators' uptime on cosmos-sdk chains. For that, I need two things
1) a validator info
2) a signing info for this validator

Without RS it's quite easy, as I can just query SigningInfos and Validators, and for each validator I can find its signing info by taking its consensus address and finding the SigningInfos entry with the same consensus address.
With RS and without key assignment it's pretty much the same (but I need to query Validators from provider chain and SigningInfos from consumer chains).
With RS and key assignments it's getting more fun. Let's say, a validator issues an assign-consensus-key transaction. Then, if I do it with the algorithm above, when I query validators list, this validator will have its own consensus pubkey returned, and I won't be able to map it to consumer chain's signing info, as it uses a different pubkey.
The correct way would be to query 1) Validators, from a provider chain, 2) SigningInfos, from a consumer chain, and 3) assigned keys for this consumer chain from a provider chain.
Then I can do the following:
- assume ConsensusKey is the validator's consensus key
- if validator has assigned consensus key for a consumer chain, assume ConsensusKey as this assigned consensus key
- find SigningInfo with consensus address equal to the ConsensusKey
- calculate missed blocks counter

Problem is, imagine there are 175 validators. To calculate missed blocks for all active validators, I need to do the following queries as of now:
- 1 query to a validators list to get all validators
- 1 query to a signing info list to get all signing infos (unfortunately on cosmoshub there's a bug so I need to do 175 requests, but that's discussed here: https://github.com/cosmos/gaia/issues/1734, and it's not related to this topic, and generally it's working with 1 request on all other chains I've tested)
- 175 requests per each validator to get an assigned consensus key

This might be 1) slow and 2) unreliable, and it'd be nice to have a possibility to query for all assigned consensus key for a consumer chain, so I'll need to do 3 queries in total to calculate the missed blocks counter for all validators on a consumer chain.
Also this kinda resembles the N+1 problems from the databases: https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping

I am pretty sure other maintainers of bots tracking the validators' uptime will face it, so I think this will be useful.

I'm mostly interested in the API to return all the consensus keys on a specific consumer chain, however having a command to do it from CLI shouldn't be that difficult to make I assume.

**Comment by glnro** [comment]
Wouldn't this make sense to define the cobra command in [interchain-security](https://github.com/cosmos/interchain-security) and then import into gaia?

**Comment by freak12techno** [comment]
Actually it seems like the keeper method is already in place: https://github.com/cosmos/interchain-security/blob/e8868556cadfa95a6b0786bd75d7a42debabc57a/x/ccv/provider/keeper/key_assignment.go#L62. I guess what's needed is only 1) add a query handler and 2) add a CLI command.

If it's that simple I can try implementing this on my own, is that good?

@glnro 
> Wouldn't this make sense to define the cobra command in [interchain-security](https://github.com/cosmos/interchain-security) and then import into gaia?

Seems so

**Comment by mmulji-ic** [comment]
> Wouldn't this make sense to define the cobra command in [interchain-security](https://github.com/cosmos/interchain-security) and then import into gaia?

This is to track when it actually lands in Gaia. cc @freak12techno 

Will create an ICS issue linked to this.

**Comment by mpoke** [comment]
This issue is blocked for now as the work will be done on the interchain-security repo.
