### ISSUE TITLE
Correct broken Discord links on Governance docs

### ISSUE THREAD

**Issue by syedc5** [cosmos/gaia#2556]
## Summary of Bug

Hub docs link to a deprecated Discord invite link. 

Please replace "https://discord.gg/W8trcGV" with "https://discord.com/invite/cosmosnetwork"

There are 3x instances on current docs:
https://github.com/search?q=repo%3Acosmos%2Fgaia%20https%3A%2F%2Fdiscord.gg%2FW8trcGV&type=code

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Thanks @syed-Interchain for the issue!
