### ISSUE TITLE
I added cosmosation years ago I could login to over 4 billion dollars and now I can't get in because I staked it for a year and when they sent me the seed phrase I had an issue with my phone charging. If they could just please send me the information again it would be fine. I'm Daniel Walker and I'm the one who staked all the cosmos coin and implanted a withdraw method for cosmosation. I consider it a bug and please help me fix, thank you.

### ISSUE THREAD

**Issue by vehicles4real** [cosmos/gaia#2575]
## Steps to Reproduce

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Hi @vehicles4real thanks for raising this issue. The procedure is to visit the [security.md](https://github.com/cosmos/gaia/blob/main/SECURITY.md) and report a vulnerability using Github's vulnerability reporting mechanism. Our security people will take a look at that straightaway.
