### ISSUE TITLE
Update Validator Set Number on Validator Doc

### ISSUE THREAD

**Issue by Zoltan118** [cosmos/gaia#2581]
# Problem

Cosmos Hub validator set has been increased from 175 to 180 via [Prop797](https://www.mintscan.io/cosmos/proposals/797)— the info on the [Validator page](https://hub.cosmos.network/main/validators/overview.html) is outdated.

# Closing criteria

Please update the page with the correct validator set number.

**Comment by mmulji-ic** [comment]
Hello @Zoltan118 , thanks for filing. 

Please see the issue https://github.com/cosmos/gaia/issues/2569 that reflects changes to both Gaia docs and ICS docs. If there are changes that are missing, please let us know.
