### ISSUE TITLE
Binary "gaiacli" should become "gaia"

### ISSUE THREAD

**Issue by ghost** [cosmos/gaia#260]
## Current Status

* giaad => the gaia daemon
* gaiacli => the gaia cli

## Expected

Usual naming, without(!) the "cli" suffix:

* gaiad => the gaia daemon
* gaia => the gaia-cli

**Comment by alexanderbez** [comment]
I'm not opposed to this. My only concern it's been this way for as long as I can remember so it might cause some UX confusion and tooling to break. I would like to get other opinions before moving forward with something like this.

/cc @hschoenburg @jackzampolin @marbar3778 @fedekunze

**Comment by ghost** [comment]
> My only concern it's been this way for as long as I can remember so it might cause some UX confusion and tooling to break.

An alias which prints additionally a deprecation-warning could do it (3 or 6 months time-frame).

**Comment by jackzampolin** [comment]
@lazaridiscom the `*cli` (sometimes (`*ctl`) naming convention is used in a large number of projects, and I see no reason to confuse users by renaming our binaries.

**Comment by ghost** [comment]
"-cli" suffix in project names, yes, but not on the binary (example: "angular-cli" binary: "ng", https://angular.io/cli)

This is a bit too basic to even discuss, you should lookup yourself for the rationales.

**Comment by ghost** [comment]
a more general issue: https://github.com/tendermint/tendermint/issues/4339 (I could not identify a technical top-level project, so filed it there)

**Comment by shahankhatch** [comment]
The binary is now named `gaiad`.
