### ISSUE TITLE
Handshake Transaction in IBC Demo

### ISSUE THREAD

**Issue by migueldingli1997** [cosmos/gaia#263]
IBC demo in  `ibc-alpha` branch still uses the `handshake` transactions which were removed from the latest versions of the Cosmos SDK. Thus, the demo currently does not work.

**Comment by cwgoes** [comment]
Aye, apologies. This is blocked on https://github.com/cosmos/gaia/issues/201 & you can track progress there.

**Comment by jackzampolin** [comment]
Closing this issue. If you would like more information on the handshake and future IBC CLI client work please see the relayer -> https://github.com/cosmos/relayer
