### ISSUE TITLE
Cannot start a chain using one validator holding 2/3+ of the voting power

### ISSUE THREAD

**Issue by sainoe** [cosmos/gaia#2631]
# Problem

There is a weird behaviour when running a chain with two validator nodes holding 96% and 4% of the voting power.
It appears that the chain doesn't start when running only its big validator, which holds more than 2/3 of the voting power.
The Gaiad is idle and the  logs show the following:
```
INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
INF No addresses to dial. Falling back to seeds module=pex
```

# Problem details

[Script that replicates the issue](https://gist.github.com/sainoe/a5169858b8c03dd01f98ed1f67100e85) using the Gaia v10.0.0 binary.

**Comment by sainoe** [comment]
Fixed by changing  `fast_sync = false` in `config.toml`.
Credit: @MSalopek

**Comment by MSalopek** [comment]
Also credit to @dasanchez who discovered this in the testnet.
