### ISSUE TITLE
e2e doesn't work on apple silicon

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#2645]
## Summary

The e2e tests don't run on apple silicon. 

## Type

I don't know what type of technical debt this is. 

## Impact

Slower software development

## Proposed Solution

Adopt a newer hermes docker image, I made them work on x86 and arm equally well:

* https://github.com/informalsystems/hermes/pull/3305
* https://github.com/cosmos/gaia/pull/2644

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Strange, because most people check those on apple silicon.

Have you tried running `make docker-build-debug` before `make test-e2e`?
