### ISSUE TITLE
Hermes docker builder isn't run in E2E tests 

### ISSUE THREAD

**Issue by sainoe** [cosmos/gaia#2659]
## Summary

#2644 updated the [Hermes builder](https://github.com/cosmos/gaia/blob/main/tests/e2e/docker/hermes.Dockerfile) to version 1.5.1, however the [E2E tests setup](https://github.com/cosmos/gaia/blob/main/tests/e2e/e2e_setup_test.go) wasn't updated accordingly. 

## Proposed Solution

- Ensure the E2E tests run the Hermes builder's image
 see [hermes.Dockerfile](https://github.com/cosmos/gaia/blob/main/tests/e2e/docker/hermes.Dockerfile)

- Update the E2E tests to pass using  the Hermes builder's version

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Just a note, `v1.6.0` is out:
https://github.com/informalsystems/hermes/releases/tag/v1.6.0

**Comment by sainoe** [comment]
Closed by #2841.
