### ISSUE TITLE
packet-forward-middleware not working as expected

### ISSUE THREAD

**Issue by devon-chain** [cosmos/gaia#2669]
## Summary of Bug

When I forward ibc transfer tx to osmosis via cosmoshub, if the amount is greater than the maximum value of int64, the estimated will fail, this problem exists in both mainnet and testnet

Before the v4.0.6 of packet-forward-middleware, if ibc transfer amount was greater than the maximum value of int64, the conversion would overflow, causing the [code](https://github.com/strangelove-ventures/packet-forward-middleware/blob/ac89f66ccba85d6bf3a142d01bb57f0f05d6d659/router/keeper/keeper.go#L307C12-L307C17) to panic, and tx would fail

Related issues: 
[gaia #2553](https://github.com/cosmos/gaia/pull/2553)
[packet-forward-middleware #78](https://github.com/strangelove-ventures/packet-forward-middleware/pull/78)

## Version

gaia: v10.0.2(Latest)
gaia: v11.0.0(Pre-release)

## Steps to Reproduce

Send ibc transfer tx to chainA(Any chain with which cosmoshub has created an ibc channel), receiver is cosmoshub, amount must be greater than maximum value of int64, and fill tx memo with [forward data](https://github.com/strangelove-ventures/packet-forward-middleware/tree/v4.0.5#minimal-example---chain-forward-a-b-c) (for example, forward to osmosis/evmos/kava)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by jtieri** [comment]
This issue should have been addressed in [v4.0.6](https://github.com/strangelove-ventures/packet-forward-middleware/releases/tag/v4.0.6) of the packet forward middleware, it looks like Gaia is still using [v4.0.5](https://github.com/cosmos/gaia/blob/581ef19342d174c06f8245a2d899a7ae7b811519/go.mod#L22). I suspect that an upgrade to the patched version is all that is necessary to rectify the issue.

**Comment by mpoke** [comment]
@devon-chain Thanks for opening the issue. I opened a PR to bump the PFM version https://github.com/cosmos/gaia/pull/2677. Thanks @jtieri.
