### ISSUE TITLE
UX & anti-spam questions surrounding IBC token transfers

### ISSUE THREAD

**Issue by cwgoes** [cosmos/gaia#269]
Migrated from https://github.com/cosmos/ics/issues/336 since this is a Gaia question.

I do not believe the anti-spam model (post ADR 4 - https://github.com/cosmos/cosmos-sdk/issues/5519) of permissionless token transfers is substantially different than the anti-spam model of "pay gas costs to make new accounts with tiny balances", modulo picking appropriate gas costs, and it seems to be the same as Ethereum (where anyone can create worthless tokens, again paying gas costs).

I also think that IBC token transfers do not change the anti-spam model for fee payments, though for a different reason - proposers can always include zero-fee transactions anyways, which is no different than including a transaction with a worthless token as fee payment. If we introduce an *in-consensus* minimum fee this would no longer be true.

Separately, it may be helpful for Gaia to maintain some sort of canonical name registry that maps user-friendly denomination names ("BTC", "ETH") to appropriate internal names which reference specific IBC port & channel identifiers. My general inclination would be to punt this problem to client-side applications (e.g. wallets just importing a list from a curated JSON file a la https://github.com/MetaMask/eth-contract-metadata) for the time being, but other options are possible (though they require implementation work).

**Comment by cwgoes** [comment]
https://github.com/cosmos/ics/issues/232 also needs to be considered with respect to this question.

**Comment by alexanderbez** [comment]
How would a global/consensus min fee impact these discussions, because we were planning on implementing such a feature?

ref: https://github.com/cosmos/cosmos-sdk/issues/4527

**Comment by cwgoes** [comment]
> How would a global/consensus min fee impact these discussions, because we were planning on implementing such a feature?
> 
> ref: [cosmos/cosmos-sdk#4527](https://github.com/cosmos/cosmos-sdk/issues/4527)

It would mean that a fee token whitelist *would* make a difference, and exchange rates would somehow need to be tracked if multiple tokens were allowed for fee payments.

**Comment by okwme** [comment]
Closing this issue in light of ongoing conversation about whitelisting tokens wrt 1559 in other places and in threads previously linked earlier in this issue.
