### ISSUE TITLE
Gaia panic

### ISSUE THREAD

**Issue by ronigk8io** [cosmos/gaia#2693]
## Summary of Bug
Trying to set up a fresh new testnet node following [tutorial](https://github.com/cosmos/testnets/blob/master/public/join-public-testnet-cv.sh), but gaiad start panic
It is similar to this closed [issue](https://github.com/cosmos/gaia/issues/936) which didn't help me.

I have tried to sync with statesync as well as fastsync.
I have tried it a few times with some configuration changes of app.toml and config.toml, but git no good news yet.

Have tried also launching gaiad without cosmovovisor with this [tutorial](https://github.com/cosmos/testnets/blob/master/public/join-public-testnet.sh)

## Version

cosmovisor v1.3.0
gaiad v11.0.0
ubuntu 22.04
2 vCPU, 8GBRAM

## Steps to Reproduce
Run the scripts from the tutorials with bash.
Set STATE_SYNC=true or false in a different trials.

## Logs
In short (more logs down below):
 --  new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
 --  We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}

Trying to get block or status:
 -- <MY_DOMAIN>:1317/status
 ----- gets:  code 12  |  message "Not Implemented"  |  details []
 -- <MY_DOMAIN>:1317/blocks/latest
 ---- gets:   block_id  |  hash ""  |  parts |  total 0  |  hash ""  |  block null
Here I did not change anything in configuration except enabling API (port 1317) in app.toml

More logs for cosmovisor:
Aug 14 13:29:01 ip-10-0-0-74 gaiad[37295]: 1:29PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
Aug 14 13:29:01 ip-10-0-0-74 gaiad[37295]: 1:29PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
Aug 14 13:29:02 ip-10-0-0-74 gaiad[37295]: 1:29PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:29:02 ip-10-0-0-74 gaiad[37295]: 1:29PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:29:31 ip-10-0-0-74 gaiad[37295]: 1:29PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
Aug 14 13:29:31 ip-10-0-0-74 gaiad[37295]: 1:29PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
Aug 14 13:29:32 ip-10-0-0-74 gaiad[37295]: 1:29PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:29:32 ip-10-0-0-74 gaiad[37295]: 1:29PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:29:32 ip-10-0-0-74 gaiad[37295]: 1:29PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:29:32 ip-10-0-0-74 gaiad[37295]: 1:29PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:29:32 ip-10-0-0-74 gaiad[37295]: 1:29PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:30:02 ip-10-0-0-74 gaiad[37295]: 1:30PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
Aug 14 13:30:02 ip-10-0-0-74 gaiad[37295]: 1:30PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
Aug 14 13:30:03 ip-10-0-0-74 gaiad[37295]: 1:30PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:30:04 ip-10-0-0-74 gaiad[37295]: 1:30PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:30:04 ip-10-0-0-74 gaiad[37295]: 1:30PM INF new bucket is full, expiring new book=/home/ubuntu/.gaia/config/addrbook.json module=p2p
Aug 14 13:30:32 ip-10-0-0-74 gaiad[37295]: 1:30PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
Aug 14 13:30:32 ip-10-0-0-74 gaiad[37295]: 1:30PM INF Saving AddrBook to file book=/home/ubuntu/.gaia/config/addrbook.json module=p2p size=1021
Aug 14 13:31:05 ip-10-0-0-74 gaiad[37295]: 1:31PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
Aug 14 13:35:19 ip-10-0-0-74 gaiad[37295]: 1:32PM INF Saving AddrBook to file book=/home/ubuntu/.gaia/config/addrbook.json module=p2p size=1021
Aug 14 13:35:21 ip-10-0-0-74 gaiad[37295]: 1:31PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
Aug 14 13:36:49 ip-10-0-0-74 gaiad[37295]: 1:33PM ERR Connection failed @ sendRoutine conn={"Logger":{}} err="pong timeout" module=p2p peer={"id":"b1f24b5b4e93a69b34effb80058567e1d2c4a332","ip":"65.108.79.246","port":26661}
Aug 14 13:44:42 ip-10-0-0-74 gaiad[37295]: 1:37PM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"b1f24b5b4e93a69b34effb80058567e1d2c4a332","ip":"65.108.79.246","port":26661}

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Hi @ronigk8io , thanks for reporting the issue. 
The version that your using, v11, won't be operational until the following proposal is live: https://www.mintscan.io/cosmos/proposals/804

If your syncing from mainnet you will need to use v10. You can sync from the current testnet, which is one v11. See the following link for further instructions on the setup: https://github.com/cosmos/testnets/tree/master/public

**Comment by ronigk8io** [comment]
Hi @mmulji-ic, thank you for your response.
As described, I do launch a v11 testnet instance.
Also I did use the same suggested link, which from I took "join-public-testnet-cv.sh" to install.
Then I tried to set statesync to be set to true of false.
Between trials, I just remove ".gaia" dir.

$ gaiad version --long
name: gaia
server_name: gaiad
version: v11.0.0
commit: 541a8d86af28231c767d6db52eb88ba9496ad0c4
build_tags: netgo,ledger
go: go version go1.20.6 linux/amd64
build_deps: .......
cosmos_sdk_version: v0.45.16-ics

**Comment by ronigk8io** [comment]
Hi @mmulji-ic,

I noticed that this issue has been moved to "In progress" a few days ago. I was just wondering if there are any updates or if there's any further information you might need from my end to help resolve this.

Thank you for your time and assistance!

**Comment by f-squirrel** [comment]
I am experiencing the same issue with testnet.
Is there any solution or workaround?

**Comment by mmulji-ic** [comment]
Hi @f-squirrel @ronigk8io we checked with Hypha (who run the testnet) and there didn't seem to be a problem on that side. In the meantime, the testnet has moved to v12, maybe v13. Can you check with this setup and let me know if you experience the same issues?

**Comment by mmulji-ic** [comment]
Hi @f-squirrel @ronigk8io closing now, because the testnet has moved on and there was no further feedback on this issue. Testnet is currently at v13 and will move to v14 next week. If you do find some issues, please ping again, happy to take a look.
