### ISSUE TITLE
make install issue

### ISSUE THREAD

**Issue by bilbonlehobbit** [cosmos/gaia#270]
hello ,
i try to do make install but i've an issue , i think i'm doing something wrong or forget something but don't know what 
if someone could help me to resolve ?? THANK'S :)
Go : 1.13.6
Os : Ubuntu 18.04

rm -rf snapcraft-local.yaml build/
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=2.0.5 -X github.com/cosmos/cosmos-sdk/version.Commit=ffb24de1d697c8d37e3e91282b6039c3c7b3da16 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiad
go: downloading github.com/cosmos/cosmos-sdk v0.37.6
go: downloading github.com/tendermint/tendermint v0.32.9
go: downloading golang.org/x/text v0.3.2
build github.com/cosmos/gaia/cmd/gaiad: cannot load github.com/cosmos/cosmos-sdk/baseapp: github.com/cosmos/cosmos-sdk@v0.37.6: read tcp 172.20.10.3:40684->172.217.22.81:443: read: connection timed out
Makefile:90: recipe for target 'install' failed
make: *** [install] Error 1

so each time it says :
read: connection timed out
or
build github.com/cosmos/gaia/cmd/gaiad: cannot load github.com/cosmos/cosmos-sdk/baseapp: github.com/cosmos/cosmos-sdk@v0.37.6: read tcp 172.20.10.3:34468->216.58.211.113:443: read: connection reset by peer

thank's for your help

**Comment by tac0turtle** [comment]
can you `go get ./...` then try make install again

**Comment by bilbonlehobbit** [comment]
i've tried this but got the same :

home@home:/opt/gaia/gaia$ go  get ./...
go: downloading github.com/cosmos/cosmos-sdk v0.37.6
go: downloading github.com/tendermint/tendermint v0.32.9
go: downloading github.com/stretchr/testify v1.4.0
go: extracting github.com/stretchr/testify v1.4.0
go: downloading github.com/snikch/goodman v0.0.0-20171125024755-10e37e294daa
go: downloading github.com/tendermint/go-amino v0.15.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/etcd-io/bbolt v1.3.3
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/stumble/gorocksdb v0.0.3
go: downloading github.com/jmhodges/levigo v1.0.0
go: downloading golang.org/x/text v0.3.2
go: extracting github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/inconshreveable/mousetrap v1.0.0
go: extracting github.com/etcd-io/bbolt v1.3.3
go: extracting github.com/davecgh/go-spew v1.1.1
go: extracting github.com/jmhodges/levigo v1.0.0
go: extracting github.com/tendermint/go-amino v0.15.1
go: extracting github.com/snikch/goodman v0.0.0-20171125024755-10e37e294daa
go: extracting github.com/stumble/gorocksdb v0.0.3
go: finding github.com/snikch/goodman v0.0.0-20171125024755-10e37e294daa
go: finding github.com/stretchr/testify v1.4.0
go: finding github.com/tendermint/go-amino v0.15.1
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/pmezard/go-difflib v1.0.0
build github.com/cosmos/gaia/cmd/gaiacli: cannot load github.com/cosmos/cosmos-sdk/baseapp: github.com/cosmos/cosmos-sdk@v0.37.6: read tcp 172.20.10.3:58642->172.217.194.141:443: read: connection reset by peer

**Comment by bilbonlehobbit** [comment]
hello 
i solved :)
thank's
