### ISSUE TITLE
Backporting creating an index on validators' delegations to Cosmos Hub

### ISSUE THREAD

**Issue by freak12techno** [cosmos/gaia#2726]
## Summary of Bug

Currently, when querying a validator's delegations, either if it's a validator who has not that much delegators or if you query delegations and asking to return the total count of the delegators, such query on Cosmos Hub can be really slow as there's no index on validator's delegations, so the fullnode iterates all over ALL delegations to find the ones belonging to this validator.
I've filed an issue on that on cosmos-sdk: https://github.com/cosmos/cosmos-sdk/issues/15162, it is already fixed, but it might take a long time before Eden lands on Cosmos Hub.

Do you think it's possible to backport it to Gaia so this would get resolved?

As of my understanding, it's quite severe as, from my experience, querying for a delegations of a validator who has only 1 delegator on my node can take around 5 minutes and would make the node go out of sync for a few minutes. And these kinds of queries are done a lot by other applications, namely by restake.app. Basically, if you list your node on chain-registry as a public node, it'll get crashed periodically by such queries. As I can see, other node maintainers usually disable this endpoint on a reverse proxy level to avoid the node getting out of sync by these queries. That's why I consider this as quite a severe thing that is better to be fixed as soon as possible.

See the issue on cosmos-sdk I mentioned above for more details.

## Version

latest Gaia, 12.0.0

## Steps to Reproduce

- Run a node
- Do a query towards your node like this: `gaiad q staking delegations-to cosmosvaloper1xqz9pemz5e5zycaa89kys5aw6m8rhgsvw4328e --count-total` 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Hi @freak12techno thanks for filing. Will take a look at the SDK fix and see if it is possible to backport as is. Theres an aversion to running custom SDK's in Gaia, but maybe we can have a release thats available to validators that really need it.

**Comment by freak12techno** [comment]
@mmulji-ic just clarifying, it's mostly not validators who are suffering from this, but the public node owners, or whoever has their RPC node exposed to the outside world. If you look at the nodes listed under https://cosmos.directory/cosmoshub/nodes, most of them have the endpoint that returns validator's delegators returning 404, as this query can bring a node down for a while (that's also the reason my public node is not listed on cosmos.directory as of now).

**Comment by mmulji-ic** [comment]
@freak12techno checking to see if this will be in SDK 47, not just Eden, in which we'll have to patch our SDK release. In which case it'll 🤞 go into the Gaia 15 release in the new year.

Update from Julien: won't be in 47, but in 50, so will need to cherry pick and see if the merge issues raised can be fixed.

**Comment by freak12techno** [comment]
@mmulji-ic so, just to clarify: can we say for sure if it can be included in Gaia v15 or not? or it's not clear yet?

**Comment by mmulji-ic** [comment]
Gaia v15 should be SDK47, so won't be including this fix without an SDK fork.

**Comment by freak12techno** [comment]
@mmulji-ic a few questions to get this straight:
1) do I get it right that the fix wasn't backported to 0.47.something of cosmos-sdk and is only present in cosmos-sdk v0.50.x?
2) if it was backported, can we base v15 release on the 0.47 patch version that includes the fix?
3) if it wasn't, do you think it'll be possible to cherry-pick it to v15 release somehow?

asking because this issue is quite serious specifically on cosmoshub (I guess because of the large delegators amount) at least for me (and I assume others as well, because if you look at the most of the cosmos.directory's cosmoshub nodes, they all have the endpoint for getting validators' delegators blocked or returning 404, because it halts the node for some time under specific conditions I've mentioned in the original issue), as every time somebody does such a query towards my node, it gets out of sync for a few minutes, so at least for me it would be extra lovely to have this fix on mainnet as soon as possible

**Comment by mmulji-ic** [comment]
Hi @freak12techno ,

i) Thats correct it was just to sdk v0.50.x, I didn't find it in any of the previous releases.
ii) Yes we could, but that needs internal discussion. Generally the preference is not to use forks in official releases. We could patch the SDK and make it available for people that want to use it. If the fix is in an official SDK release, then will endeavour to use it asap.
iii) Again, this would be a custom SDK release just for validators that wanted to use the binary.

**Comment by mmulji-ic** [comment]
Hi @freak12techno we decided not to go ahead with this feature, as we're working hard on getting a SDK 47 release out in Jan. Also, some of the work for a SDK 50 release is also already done, therefore from a priority/resource perspective we want to focus on the mainline releases, so that we're up to date with the SDK as much as possible and can avoid situations like this in the future.

**Comment by freak12techno** [comment]
@mmulji-ic got it. Do we have an estimation on when to expect SDK 50 on Gaia?

**Comment by mmulji-ic** [comment]
@freak12techno it'll be Q2 at the earliest.
