### ISSUE TITLE
Failing to build on make install

### ISSUE THREAD

**Issue by sebastiaoamaro** [cosmos/gaia#2729]
## Summary of Bug
Hi everyone, I am trying to build the latest version of gaia (12.0.0) following the steps on [1], however, I get this error.
go: module github.com/cometbft/cometbft: not a known dependency
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.AppName=gaiad -X github.com/cosmos/cosmos-sdk/version.Version=v12.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=6f8067d76ce30996f83645862153ccfaf5f13dd1 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/cometbft/cometbft/version.TMCoreSemVer= -w -s' -trimpath  ./...

## Version
gaia 12.0.0, Ubuntu 22.04, go version 1.20.5

## Steps to Reproduce

Run steps on [1].
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

https://github.com/cosmos/gaia/releases/tag/v12.0.0

**Comment by sebastiaoamaro** [comment]
Fixed with go get -d, however now I have no binary in either the main folder or in the build folder.

**Comment by mmulji-ic** [comment]
Hello @sebastiaoamaro ,

The message ..
`go: module github.com/cometbft/cometbft: not a known dependency` is something thats new and also in the latest version, but it does not stop the binary from being generated.

Typically the `make install` puts the gaiad binary in the same directory as all other golang generated binaries. 
Try `which gaiad` in your terminal to see where the binary is stored.

On my mac, its something like:
`/Users/<username>/go/bin/gaiad`

The directory `/Users/<username>/go/bin/` should also be in your path, if it is then you will be able to run `gaiad` from anywhere. Let me know if that helps.

**Comment by mmulji-ic** [comment]
Hi @sebastiaoamaro any luck in finding your gaiad binary?
