### ISSUE TITLE
Can't connect to Ledger device

### ISSUE THREAD

**Issue by kremalicious** [cosmos/gaia#2756]
Essentially following [this tutorial](https://hub.cosmos.network/main/resources/ledger.html#gaia-cli-ledger-nano), trying to reference a key from an initialized Ledger Nano X with `gaiad keys add` but when doing so I get:

```bash
Error: failed to generate ledger key: failed to retrieve device: ledger nano S: hidapi: failed to open device
```

Note that error says "ledger nano s" despite using Nano X. But also tried with a Nano S and getting same error message. Can use the devices without issues in browser wallets like Keplr or MetaMask.

## Version

```bash
gaiad version --long
name: gaia
server_name: gaiad
version: v13.0.0
commit: 04ea8da5a1257a855e307ed61d245a2af2719757
build_tags: netgo,ledger
go: go version go1.20.8 darwin/arm64
...
```

Cosmos app on Ledger is `v2.34.12`.

I'm on macOS 14.0, Apple Silicon. Getting same issue with `gaiad v12.0.0`.

## Steps to Reproduce

```bash
git clone git@github.com:cosmos/gaia.git
cd gaia && git checkout v13.0.0
make install

# while Ledger is unlocked and Cosmos app is opened:
gaiad keys add ledger1 --ledger
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Thank you for reporting the issue!

The latest stabile release running on chain is [v12](https://github.com/cosmos/gaia/releases/tag/v12.0.0).

~~Did you have any luck with v12 by any chance or does the issue persist?~~


EDIT:
Confirming that it does work with v12 for me.

It did not work for me when I downloaded the binary from the [release page](https://github.com/cosmos/gaia/releases/download/v13.0.0/gaiad-v13.0.0-darwin-arm64).

However, it did work when I reproduced your steps (although I built it using go1.21):
```shell
git clone git@github.com:cosmos/gaia.git
cd gaia && git checkout v13.0.0
make install

# while Ledger is unlocked and Cosmos app is opened:
gaiad keys add ledger1 --ledger
```

**Comment by kremalicious** [comment]
thanks for the info! Are you on macOS/arm64 too? Thought so that something with my local system might be at fault. Actually had to downgrade go cause this package complained. When I try to do `make install` with that:

```bash
❯ go version
go version go1.21.1 darwin/arm64

❯ make install
go: module github.com/cometbft/cometbft: not a known dependency
ERROR: Go version 1.20 is required for v12.0.0 of Gaia.
exit 1
make: *** [check_version] Error 1
```

And the same for v13:

```bash
❯ make install  
go: module github.com/cometbft/cometbft: not a known dependency
ERROR: Go version 1.20 is required for v13.0.0 of Gaia.
exit 1
make: *** [check_version] Error 1
```

But even if I simply overwrite the `REQUIRE_GO_VERSION` in the Makefile, still get the same connection issue at the end.

System detects the Nano X correctly:

```bash
❯ system_profiler SPUSBDataType
USB:

    USB 3.1 Bus:

      Host Controller Driver: AppleT8112USBXHCI

        Nano X:

          Product ID: 0x4011
          Vendor ID: 0x2c97
          Version: 2.01
          Serial Number: 0001
          Speed: Up to 12 Mb/s
          Manufacturer: Ledger
          Location ID: 0x00100000 / 2
          Current Available (mA): 500
          Current Required (mA): 100
          Extra Operating Current (mA): 0

    USB 3.1 Bus:

      Host Controller Driver: AppleT8112USBXHCI
```

**Comment by MSalopek** [comment]
I am running on an M1 chip.

If you are testing out different builds try changing this line in the [makefile](https://github.com/cosmos/gaia/blob/main/Makefile#L24)
```makefile
REQUIRE_GO_VERSION = 1.21
```

I think you've already done that.

I connected to my Nano S-Plus, so I'm not sure how comparable are our results.


Have you upgraded the firmware on your ledger?

EDIT:
Got my hands on a Nano-X, was working fine with built from source
```bash
➜  ~ gaiad version --long
name: gaia
server_name: gaiad
version: v13.0.0
commit: 04ea8da5a1257a855e307ed61d245a2af2719757
build_tags: netgo,ledger
go: go version go1.21.1 darwin/arm64
```

EDIT 2:
Any change you could try this out on a different machine?

**Comment by glnro** [comment]
I actually encountered a similar issue. Downloaded the `gaiad-v12.0.0-darwin-arm64` binary and ran `gaiad keys add account-2 --index 0 --account 2 --ledger` which returned `support for ledger devices is not available in this executable`.

This was run on a new Mac m2 air. I went ahead and downloaded go 1.20, built gaiad from source, and was able to execute the command with no problem. Seems it might be related to [this issue](https://github.com/tendermint/images/issues/70).

**Comment by kremalicious** [comment]
thanks everyone for the tips but just no luck for me. Tried on another (Intel) Mac and get same error. Then spun up a fresh Ubuntu VM (with go 1.21 through snap) but getting exact same error. With Nano X and Nano S (they are mirrors of each other, initialized with same seed), with bot devices at their latest firmware and latest Cosmos app `v2.34.12` installed. Tried with a bunch of `index` & `account` combinations. Also switched cables just in case. But always the same `hidapi: failed to open device`

So not sure what would be different in my setup. I can access the Ledger devices just fine from pretty much every other tool, including Keplr. Just gaiad/Cosmos app is not working for me.

Remaining thing I can think of is something with the devices themselves, both being Ledger's first generation devices, or with the derivation path. I see this for the only Cosmos account on it within Ledger Live:

```
"index": 0,
"freshAddressPath": "44'/118'/0'/0/0",
```

So pretty much all expected with the default 118 coin type and 0 for account & index, leaving me puzzled as to what would be the issue here.

Feel free to close this as it seems to be not reproducible for everyone else, but sadly I have to give up now. I simply wanted to create another Cosmos account on the device beside another empty one. As Ledger Live disallows this, Keplr does not support this, the only way would be to use gaiad to do that.

**Comment by MSalopek** [comment]
I'm sorry about the troubles you are experiencing. Let us know if you somehow manage to get it working at a later point in time.

> Feel free to close this as it seems to be not reproducible for everyone else, but sadly I have to give up now. I simply wanted to create another Cosmos account on the device beside another empty one. As Ledger Live disallows this, Keplr does not support this, the only way would be to use gaiad to do that.

I vaguely remember that you can use Ledger Live to make another account from the same seed phrase using a different derivation path you can set yourself, but I may just be misremembering or thinking about some other wallet.

**Comment by ftheirs** [comment]
Hey guys! There are new versions from ledger-cosmos-go, ledger-go and hid
[Ledger-cosmos-go](https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.13.2): v0.13.2
[Ledger-go](https://github.com/Zondax/ledger-go/releases/tag/v0.14.3): v0.14.3
[hid](https://github.com/Zondax/hid/releases/tag/v0.9.2): v0.9.2

In case that you need some backward compatibility (without Textual mode), you should go for the [v0.12.x](https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.12.4) version from ledger-cosmos-go

I wasn't able to reproduce this issue on my machine but I got some confirmation that the latest version solves the issue. Can you confirm this please @kremalicious ?

**Comment by mmulji-ic** [comment]
Hi @ftheirs we've [merged in](https://github.com/cosmos/gaia/commit/b11af5a4c2a5ec1556fdd079992e4fd039882d30) support for [v0.12.x](https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.12.4) so hopefully that support is coming to a release in the next month or so. Will close when this version is released.

**Comment by mpoke** [comment]
Fixed in https://github.com/cosmos/gaia/releases/tag/v13.0.2
