### ISSUE TITLE
One address should not be able to self-bond to two pubkeys

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#28]
Should throw an error from CLI and from TX for bonding with an already used sender address

**Comment by zmanian** [comment]
It's no intuitively obvious to me why this is an error?

**Comment by rigelrozanski** [comment]
Aha - just changed the name to maybe make it a bit more clear. The intention of this was for self bonding of validator nodes. If you want to be in control of two validator nodes (which should really be a rate occurrence) you simply would have to send coins to a second account under your control and bond them from there. Because it's thought to be a rare phenomina to represent two validators, we assume that each validator sender address is only married to a single validator PubKey which is nice because now when you are unbonding as a validator you don't need to specify the validator pubkey, it is simply determined from the sender address. 

As a delegator you are obviously permitted to bond to multiple validators... does this clear up this issue?

**Comment by zmanian** [comment]
Yep. Much clearer

**Comment by naruemont** [comment]
thanks for the update. just would like to be clear as i am still very new.
so, if we have one address which hold the token and want to bond to many validators. we have to transfer to other address before bond to a new validator. right?

i am running 3 local nodes to test concept. I bonded 22 fermions to second nodes and 33 fermions to third nodes but when I query validators, all 55 tokens were bonded to only second nodes (using command 'curl localhost:46657/validators'). testing unbond all 55 tokens works fine without any problem but causing me to check this issue. in this case, should i create a new address, transfer some fermion and bond to third node instead?

**Comment by rigelrozanski** [comment]
@naruemont You would only need to do what you describe if you want to be the Owner of multiple validators, which in a functioning hub will hopefully be a rare occurrence. If you wish to delegate to  to other validators only a single address is needed. Delegation functionality should be coming out this week. 

The example you described in your local test net is an example of this bug. The fact that all fermions ended up at the second node is a bug - really once this bug is corrected, you should have received an error when you attempted to bond to the third node from the address you had already used from the second node. The correct way to proceed is as you have described, send to another address, and then use that new address to bond to a third node

**Comment by rigelrozanski** [comment]
Okay after a tiny bit of deliberation - for the efficiency of being able write records we made the judgement that one address SHOULD be able to bond to multiple validator as well as delegate from the same address - this prevents overhead requirement to store by validator.
