### ISSUE TITLE
Not clear if Authz execute command still works on Gaiad

### ISSUE THREAD

**Issue by marius987654** [cosmos/gaia#2830]
## Summary of Bug
I am trying to execute via authz a delegate and a redelegate transaction from a single sign on behalf of a multisig. I get error message for either.

gaiad tx authz exec testredelegation-unsigned.json --from [delegation key] --fees 1000uatom --gas 400000
Error: post failed: Post "http://localhost:26657/": dial tcp [::1]:26657: connect: connection refused

cat testredelegation-unsigned.json 
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgBeginRedelegate","delegator_address":"cosmos1rppu6rwukvggp3zd5dkpq8ewn70duryxjfmp43","validator_src_address":"cosmosvaloper1up3slj4nr5y23gxkvqn8h5ra9mv0pj2vrh0djk","validator_dst_address":"cosmosvaloper1qmr8acxu0d9ytase8v9mza6k96y479getstqn2","amount":{"denom":"uatom","amount":"20000"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uatom","amount":"10000"}],"gas_limit":"400000","payer":"","granter":""}},"signatures":[]}
[11:58](https://interchainfoundation.slack.com/archives/C04QN3PDPQV/p1700567893448209)

gaiad tx authz exec testdelegation-unsigned.json --from [delegation key] --fees 1000uatom --gas 400000
Error: post failed: Post "http://localhost:26657/": dial tcp [::1]:26657: connect: connection refused

cat testdelegation-unsigned.json 
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgDelegate","delegator_address":"cosmos1rppu6rwukvggp3zd5dkpq8ewn70duryxjfmp43","validator_address":"cosmosvaloper1up3slj4nr5y23gxkvqn8h5ra9mv0pj2vrh0djk","amount":{"denom":"uatom","amount":"100000"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uatom","amount":"10000"}],"gas_limit":"400000","payer":"","granter":""}},"signatures":[]}
mariusbudu@Mariuss-MacBook-Pro test-redelegate %

## Version
Gaiad v13.0.2
go version go1.20.10 darwin/amd64
I use a MacBook Pro with Sonoma 14.1.1

## Steps to Reproduce
Please see above

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by greg-szabo** [comment]
Based on the error message, gaiad might either not read the client.toml file that contains the node to connect to or the file is not set up.

In any case, you can try adding the `--node` parameter with a valid RPC endpoint

**Comment by marius987654** [comment]
Thank you, Greg. This fixed it.
