### ISSUE TITLE
[Question] What is happening in Mainnet?

### ISSUE THREAD

**Issue by fmira21** [cosmos/gaia#2833]
Hi guys!
Today I am observing a strange activity in Mainnet: the number of transactions in blocks increased dramatically, and the vast majority of transactions are just self-transfers of 0.000001 ATOM.

Check it out:
https://atomscan.com/blocks/18096673

Is this activity expected?

**Comment by mmulji-ic** [comment]
Hi @fmira21 it was related to this post on the forum
https://forum.cosmos.network/t/proposal-856-voting-funding-the-first-inscription-coss-on-cosmos/12317

The COSS activity was not expected, as we didn't have it before, but it was not an attack, though it did stress a number of validator nodes out. There seems to be some plan to repeat the exercise, so I expect it to happen again sometime in the future.
