### ISSUE TITLE
tests/e2e: writeFile unnecessrily leaks a file yet os.WriteFile already handles its functionality

### ISSUE THREAD

**Issue by odeke-em** [cosmos/gaia#2834]
## Summary of Bug

Noticed in our audits that this code https://github.com/cosmos/gaia/blob/4ab68854cfdbc592ed0cbaea48f4654fb89d2924/tests/e2e/io.go#L37-L44

That code invokes `_, err := os.Create` but doesn't capture the file nor close it. That is all unnecessary becasue `os.WriteFile` handles all that logic https://pkg.go.dev/os#Create

It should be done
```diff
diff --git a/tests/e2e/io.go b/tests/e2e/io.go
index 40b316bec..81160d4aa 100644
--- a/tests/e2e/io.go
+++ b/tests/e2e/io.go
@@ -35,10 +35,5 @@ func copyFile(src, dst string) (int64, error) { //nolint:unparam
 
 // writeFile write a byte slice into a file path
 func writeFile(path string, body []byte) error {
-	_, err := os.Create(path)
-	if err != nil {
-		return err
-	}
-
 	return os.WriteFile(path, body, 0o600)
 }
```

## Version
4ab68854cfdbc592ed0cbaea48f4654fb89d2924

/cc @mpoke @elias-orijtech
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Thanks @odeke-em will apply the change.
