### ISSUE TITLE
MsgTransfer is missing public_key in signer_infos.

### ISSUE THREAD

**Issue by DAICers** [cosmos/gaia#2843]
## Summary of Bug

Transaction C50FD27745011D5AFC5679BDB79D66C3001205ABD09BA8DCF168763DFDD16C13 in block 17685584 appears to not have a public key attached to it in signer_infos: https://www.mintscan.io/cosmos/tx/C50FD27745011D5AFC5679BDB79D66C3001205ABD09BA8DCF168763DFDD16C13?height=17685584

Except from mintscan but if you query an archive node you will find the same
`{
    "auth_info": {
        "signer_infos": [
            {
                "public_key": NULL,
                "mode_info": {
                    "single": {}
                },
                "sequence": "1291"
            }
        ]
    }
}`

Same happened recently on the new dydx-mainnet-1 in a successful MsgSend
https://www.mintscan.io/dydx/tx/3DFAEE653B7A6EEA086818109D7B1174E14C35ECF8EA81529675CE5C83107A3C

## Version

v13.0.0 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
@DAICers Thanks for opening an issue. According to the [SignerInfo definition in SDK](https://github.com/cosmos/cosmos-sdk/blob/0af2f4da004cbea6414a8bad56e8bdcd45badf1e/proto/cosmos/tx/v1beta1/tx.proto#L116), the public key is optional, i.e., 
```go
message SignerInfo {
  // public_key is the public key of the signer. It is optional for accounts
  // that already exist in state. If unset, the verifier can use the required \
  // signer address for this position and lookup the public key.
  google.protobuf.Any public_key = 1;
```
As a result, I will close this as a non-issue.
