### ISSUE TITLE
Timeline for archival Snapshot Update for Cosmos 4 

### ISSUE THREAD

**Issue by mayank-daga** [cosmos/gaia#2860]
## Summary of Bug

Need to know when archival Snapshot Update for Cosmos 4 will be done i am still seeing 5th December 2023 in https://quicksync.io/networks/cosmos.html 

## Version
gaiad v14.1.0

**Comment by mpoke** [comment]
@mayank-daga The latest snapshot for Cosmos 4 is from Dec 19. As a result, I'll close this issue as solved.
