### ISSUE TITLE
EPIC: Test Gaia with CometMock

### ISSUE THREAD

**Issue by p-offtermatt** [cosmos/gaia#2866]
## Problem

We want to use CometMock with the Gaia e2e tests to run them faster and lay the foundations to run *more* tests.

## Closing criteria

In the Gaia e2e tests, it is possible to spin up a local testnet that uses CometMock instead of CometBFT.

**Prerequisite:** The Gaia e2e framework should undergo a general refactor and cleanup,
which itself doesn't integrate CometMock, but which should already keep in mind this will be done later.
This issue tracks the general Gaia e2e refactor:
https://github.com/cosmos/gaia/issues/2406

## Task list
The rough tasks to do are:

```[tasklist]
- [ ] Modify startup scripts from Gaia
- [ ] Connect Gaia CLI to CometMock to submit TXs and Queries
```

These can be made separate issues, but for now I think they are both relatively minor and interconnected, so I will leave them as tasks.

**Comment by mpoke** [comment]
@p-offtermatt Could you please add a reason why we don't want to do this and close the issue?

**Comment by p-offtermatt** [comment]
It turns out that instead of using CometMock, for the use cases we considered it is more reasonable to use an in-memory testing framework like ibctesting, which completely gets rid of the need for a consensus engine.

For testing the internal logic, this approach is much faster, and easier to maintain. If we are worried about the CLI itself, we should test that separately, and not mix that too much with testing the internal logic.

For this reason, it was decided we would close this issue for now and shift the focus away from integrating CometMock.
