### ISSUE TITLE
Failed start node

### ISSUE THREAD

**Issue by zZoMROT** [cosmos/gaia#293]
## Summary of Bug

My gaiad began to die after starting (`gaiad start`) with error 
for v2.0.0: `module=privval err="accept tcp [::]:26657: i/o timeout"`
<img width="924" alt="Снимок экрана 2020-02-17 в 17 50 28" src="https://user-images.githubusercontent.com/3616087/74921862-683f1b00-53df-11ea-939c-392d1a1384ce.png">
for v2.0.5,2.0.6: `module=privval err="endpoint connection timed out"`
<img width="902" alt="Снимок экрана 2020-02-17 в 18 56 25" src="https://user-images.githubusercontent.com/3616087/74921872-6aa17500-53df-11ea-993c-f9e9f8d0e7d2.png">

Up to some point, the node worked correctly, I didn’t change anything in the configuration or installation.
Gaiad configuration is default, no another process running at port 26657, no filters, no firewalls, all ports (26656,26657,1317) are expose and available (I checked it with netcat utility additionally).
Please tell me what could happen and what is wrong?

## Version
2.0.0
2.0.5
2.0.6

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
are you using an external signer?

**Comment by zZoMROT** [comment]
> are you using an external signer?

nope

**Comment by tac0turtle** [comment]
Are you still experiencing this issue on 2.0.8?

**Comment by HankFit247** [comment]
Was ready to start my next step, then encountered the following after a reboot.
Ubuntu 20.04 LTS

$ gaiad start
ERROR: While parsing config: (169, 10): unescaped control character U+000A

$ gaiad version --long
ERROR: While parsing config: (169, 10): unescaped control character U+000A

$ gaiacli version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.13
commit: bc93dcc040570c71fad288ba5eeebe4033a5c5d8
build_tags: netgo,ledger
go: go version go1.15.2 linux/amd64
