### ISSUE TITLE
Unable to use  REST Server  after upgrading to v15

### ISSUE THREAD

**Issue by 45988611** [cosmos/gaia#2951]
curl http://127.0.0.1:1317/blocks/latest

{"code":12,"message":"Not Implemented","details":[]}

**Comment by MSalopek** [comment]
Thank you for pointing it out.

The endpoint has moved to `<addr:port>/cosmos/base/tendermint/v1beta1/blocks/latest` when using cosmos-sdk v0.47.

Please try using `curl 127.0.0.1:1317/cosmos/base/tendermint/v1beta1/blocks/latest` - this endpoint will return a slightly different result.

If you require the old behavior switch to using the cometBFT api (default port `26658`)
`curl localhost:26658/block`

**Comment by mmulji-ic** [comment]
Hi @45988611 does this address your concern?

**Comment by MSalopek** [comment]
Closing as completed since the answer is given in this comment:
* https://github.com/cosmos/gaia/issues/2951#issuecomment-1953977875
