### ISSUE TITLE
Wrong command to move to latest branch .Its given "git checkout v15.0.0" but it should be "git checkout v15.0.0-rc1"

### ISSUE THREAD

**Issue by coderasha** [cosmos/gaia#2953]
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Hey, thanks for your concern!

Gaia v15 has not been yet released and it is in release candidate phase.

Please do not attempt to run v15.0.0-rc1 on the mainnet.

For testnet use please consult the [testnets repo](https://github.com/cosmos/testnets/blob/master/replicated-security/provider/README.md) which has the appropriate instructions.
