### ISSUE TITLE
gaiad cannot start

### ISSUE THREAD

**Issue by atoken-ops** [cosmos/gaia#297]
[2020-02-25|23:30:01.379] starting ABCI with Tendermint module=main
panic: version 868343 was already saved to different hash 03C0DA0BF4D2DDF2614B14E5AFE00FA66BF49C68EED3B41D4E60D07B04317452 (existing hash 7CAFDDC9D7C13A22AAA468D107B1946723E6BEA477B68B3A5DBBB653FE5A0E51)

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc000c77c80, 0x11af7a4, 0x6, 0x20, 0x20)
/usr/local/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/store/iavl/store.go:108 +0x1b6
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0xd3ff7, 0xc000a371a0, 0x8010104, 0x0, 0xffffffffffffffff, 0xc00101d0f8)
/usr/local/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/store/rootmulti/store.go:528 +0x165
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000016600, 0x0, 0x0, 0x0, 0x0)
/usr/local/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/store/rootmulti/store.go:203 +0x68
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc000156360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/baseapp/baseapp.go:1020 +0x1ad
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000c6a960, 0x0, 0x0, 0x0)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/abci/client/local_client.go:215 +0xcf
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc000ebafb0, 0x0, 0x0, 0x7d)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/proxy/app_conn.go:81 +0x33
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc0001537a0, 0xa, 0x0, 0xc00286bc30, 0x6, 0xc00286bc50, 0xb, 0xd3ff7, 0x3c329, 0xc000f3f1e0, ...)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/state/execution.go:205 +0x224
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0001537a0, 0xa, 0x0, 0xc00286bc30, 0x6, 0xc00286bc50, 0xb, 0xd3ff7, 0x3c329, 0xc000f3f1e0, ...)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/state/execution.go:159 +0x625
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc00101f0c0, 0xa, 0x0, 0xc00286bc30, 0x6, 0xc00286bc50, 0xb, 0xd3ff6, 0x3c328, 0xc001777f00, ...)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/consensus/replay.go:463 +0x233
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0018670c0, 0xa, 0x0, 0xc00286bc30, 0x6, 0xc00286bc50, 0xb, 0xd3ff6, 0x3c328, 0xc001777f00, ...)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/consensus/replay.go:387 +0xdf3
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00101f0c0, 0x15947c0, 0xc000153340, 0x80, 0x1022720)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/consensus/replay.go:269 +0x485
github.com/tendermint/tendermint/node.doHandshake(0x1593d40, 0xc0000c0270, 0xa, 0x0, 0xc00286bc30, 0x6, 0xc00286bc50, 0xb, 0xd3ff6, 0x3c328, ...)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/node/node.go:275 +0x199
github.com/tendermint/tendermint/node.NewNode(0xc00047ef00, 0x157c0c0, 0xc000aa8320, 0xc000ae6800, 0x15627e0, 0xc000e49e40, 0xc000ae6a70, 0x13ab578, 0xc000ae6a80, 0x1581dc0, ...)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/node/node.go:582 +0x334
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000139540, 0x13abd98, 0x1d, 0x0, 0x0)
/usr/local/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/server/start.go:152 +0x4c1
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000132280, 0xc0001399a0, 0x0, 0x2, 0x0, 0x0)
/usr/local/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/server/start.go:65 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000132280, 0xc000139960, 0x2, 0x2, 0xc000132280, 0xc000139960)
/usr/local/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c8c80, 0x11d3a84, 0xc000879ea0, 0x59de52)
/usr/local/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
/usr/local/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000c8c80, 0x13ac1b8, 0x11b9152, 0x10)
/usr/local/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.7/libs/cli/setup.go:89 +0x3c
main.main()
/tmp/gaia/cmd/gaiad/main.go:68 +0x875

V2.0.3

**Comment by tac0turtle** [comment]
it looks like you somehow got conflicting app hashes. If you have a snapshot of the data dir id recommend starting from there and syncing again

**Comment by tac0turtle** [comment]
going to close this issue, if you are still having the issue, please reopen
