### ISSUE TITLE
[docs] Search is Broken

### ISSUE THREAD

**Issue by salmad3** [cosmos/gaia#2975]
## Summary of Bug

Algolia search not working for [hub.cosmos.network](https://hub.cosmos.network/)

## Steps to Reproduce

No results 
<img width="561" alt="image" src="https://github.com/cosmos/gaia/assets/25497083/a2dc2a8d-68a1-4fb8-ad89-74e2b5f1bd20">

Perhaps site needs to be re-crawled.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mmulji-ic** [comment]
Thanks @salmad3 , we'll try and get the indexes updated.

**Comment by MSalopek** [comment]
Removed algolia search in https://github.com/cosmos/gaia/pull/3392.

Docs now use local search.

It's a bit uglier but a lot more convenient from a management perspective.
