### ISSUE TITLE
Broken link to migration for most recent release

### ISSUE THREAD

**Issue by rootulp** [cosmos/gaia#2985]
There is a broken link on the most recent release: https://github.com/cosmos/gaia/releases/tag/v14.1.0

> The migration instructions can be found here:
> https://hub.cosmos.network/main/migration/cosmoshub-4-v14-upgrade.html

Takes me to

<img width="1490" alt="Screenshot 2024-03-06 at 2 24 39 PM" src="https://github.com/cosmos/gaia/assets/3699047/8d5729c8-7d99-4a5d-a2db-ddb9f5d21f39">

**Comment by mpoke** [comment]
Thanks @rootulp. Fixed it https://github.com/cosmos/gaia/releases/tag/v14.1.0
