### ISSUE TITLE
After update to v15.1.0, node does not work, no logs

### ISSUE THREAD

**Issue by fmira21** [cosmos/gaia#3013]
Hi guys!
Updated my nodes to 15.1.0 and cannot make them work.
They look like frozen, do not return any logs.
I applied a pruned snapshot for one of them, also no luck - same situation.

My setup is Dockerised.

Is there any workaround?

Thank you in advance!

**Comment by MichaelLLC** [comment]
I also have a problem running the cosmos node in a docker container.

**Comment by tyg03485** [comment]
So do i

**Comment by bb4L** [comment]
i had the same problem, waiting "resolved" it

running v15.1.0 in docker

**Comment by tyg03485** [comment]
Eventually works after waiting few hours..
I think it would have been very helpful if it could log at least a little bit..

related. https://github.com/cosmos/gaia/blob/release/v15.x/UPGRADING.md#upgrade-duration

**Comment by mpoke** [comment]
@jungrae-prestolabs Happy to hear the issue was solved.

**Comment by fmira21** [comment]
Yeah, just commenting after the completion.
All my nodes are back to operation now, but it took literally 6 hours for a snapshotted one.

**Comment by tyg03485** [comment]
Fyi. In our case, while upgrading v15.1.0, it used a lot of memory. If using k8s or containerized environments, you need to monitor the usage of resource well avoiding cpu throttling or OOM.
