### ISSUE TITLE
Atom Upgrade to v15.0.0 from v14.1.0 not working

### ISSUE THREAD

**Issue by mayank-daga** [cosmos/gaia#3017]
I am trying to upgrade my mainnet archival atom node from v14.1.0 to v15.0.0. 
I cloned the new git using below command :

1. git clone -b v15.0.0 <url>
2. Build the image : sudo docker build -t gaia:15.0.0 .
3. To create the .gaia folder inside ran below command:
 sudo docker run -it -p 26657:26657 -p 26656:26656 -v /<diskname>/node-atom/gaia/.gaia:/gaia/.gaia gaia:latest gaiad init tenatom --chain-id cosmoshub-4

Was getting one error here:

Error: unknown flag: --chain-id

But .gaia folder was created so moved my config and data folder inside the .gaia folder 

4. Check the image is created or not 
	sudo docker images

5. Updated peers list from   https://nodestake.top/cosmos and update them in the config.toml file under config folder.

6. updated addrbook.json from   https://nodestake.top/cosmos and update the same under config folder.

7. Updated the genesis.json from  https://nodestake.top/cosmos under config folder.(if chain id is changed than only required) 

Start the Node with start command and change the image with latest image
	
sudo docker run -d -it  -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /<diskname>/node-atom/v15.0.0/gaia/.gaia:/gaia/.gaia gaia:15.0.0 gaiad start --pruning nothing --home /gaia/.gaia

Container start and stays up for many hours without producing any logs

**Comment by mpoke** [comment]
> I am trying to upgrade my mainnet archival atom node from v14.1.0 to v15.0.0.

@mayank-daga Please note that [v15.0.0](https://github.com/cosmos/gaia/releases/tag/v15.0.0) is deprecated and you should use [v15.1.0](https://github.com/cosmos/gaia/releases/tag/v15.1.0) instead. Also, you should upgrade from [v14.2.0](https://github.com/cosmos/gaia/releases/tag/v14.2.0). For more details, please check out the [upgrading instructions](https://github.com/cosmos/gaia/blob/release/v15.1.x/UPGRADING.md.).

**Comment by mayank-daga** [comment]
Hi @mpoke thanks for the info i will try that also one more question do we need to download latest archive snapshot as my node was synced to latest?

**Comment by mayank-daga** [comment]
Hi @mpoke I upgraded to first v14.2.0 and then tried to upgrade to v15.1.0. I am getting the same issue

**Comment by MSalopek** [comment]
The upgrade is taking a long time, the software is performing a large upgrade.

The upgrade can take a long time, and unfortunately there's nothing in the log output (that's outside of cosmos-hub scope).

For me, upgrading a 1TB node (custom pruning) took almost 2 hours. If you're upgrading an archive it will take longer - please don't shut down the node an let it complete the upgrade. If you have heartbeats/healthchecks please turn them off.

-----------------

> To create the .gaia folder inside ran below command:
> sudo docker run -it -p 26657:26657 -p 26656:26656 -v //node-atom/gaia/.gaia:/gaia/.gaia gaia:latest gaiad init tenatom > --chain-id cosmoshub-4
> Was getting one error here:
>
> Error: unknown flag: --chain-id

Checked locally, there does not seem to be an issue with `chain-id` on either `gaiad v15.1.0` or `v14.2.0`.
I was able to run `gaiad init testing --home .gaiad-test --chain-id cosmoshub-4`

Were you able to resolve your issue?

**Comment by mayank-daga** [comment]
No @MSalopek I was not able to resolve the issue also the docker container was up till 2 days but still no logs was produced

**Comment by MSalopek** [comment]
Do you have any metrics or insight into the process? Can you check that the process is doing something and it hasn't died on startup?

**Comment by mayank-daga** [comment]
Hi @MSalopek and @mpoke node is up and running i guess it is taking too long but got started thanks
