### ISSUE TITLE
Need Updated Query for Atom Node v15.1.0

### ISSUE THREAD

**Issue by mayank-daga** [cosmos/gaia#3034]
Hi I am trying below curl query :
http://<server>/cosmos/tx/v1beta1/txs?messages.action=/cosmos.bank.v1beta1.MsgSend&message.sender=cosmos1kpnryd5zzcswkev4y92xxd4dvvhc6k7gtgejpr&page=1&limit=25

But it is not working earlier used to work with Atom Node v14.2.0
Currently, it is giving below error: 
{"code":3,"message":"must declare at least one event to search","details":[]}

What am i missing in query parameter?

Any help is highly appreciated

**Comment by MSalopek** [comment]
@mayank-daga Hi! Thanks for opening the issue.

You did not provide the "events" portion needed by the query:
`"<api>/cosmos/tx/v1beta1/txs?events=message.action='/cosmos.bank.v1beta1.MsgSend'&events=message.sender='cosmos1kpnryd5zzcswkev4y92xxd4dvvhc6k7gtgejpr'&page=1&limit=25"`

Notice that you need to provide `events=` for every event attribute you intend to use as filter:
* the query above filters by `message.action` and `message.sender`
* that means you need to use: `?events=message.action='/cosmos.bank.v1beta1.MsgSend'&events=message.sender='cosmos1kpnryd5zzcswkev4y92xxd4dvvhc6k7gtgejpr'`
* the filter values need to be properly escaped using `'` or `"`

**Comment by mayank-daga** [comment]
Hi @MSalopek I changed the query and added 'events='. It works for some addresses but for other addresses it is giving zero transactions(but there is send transactions avialable) or it is taking too long which results in Http Timeout issue 

For example:
http://<server>/cosmos/tx/v1beta1/txs?events=message.action=%27/cosmos.bank.v1beta1.MsgSend%27&events=message.sender=%27cosmos166tuwql86p0sr0nqjr4rq2vkeh87u266dwkm32%27&page=1&limit=25

Adrress: cosmos166tuwql86p0sr0nqjr4rq2vkeh87u266dwkm32 has send transactions but i am getting zero transactions

**Comment by MSalopek** [comment]
> or it is taking too long which results in Http Timeout issue

That could be due to the amount of data you're searching and it could depend on your node config.

>  I changed the query and added 'events='. It works for some addresses but for other addresses it is giving zero transactions(but there is send transactions avialable)

Be sure that your node has appropriate pruning settings (you have the data that you're interested in querying).

A pruned node will not have the events available, check on your archive node and possibly limit the query nby

**Comment by mayank-daga** [comment]
ok @MSalopek. Also one more api i am issues. Below is the api to get balance at a particular height:

http://node-url/cosmos/bank/v1beta1/balances/cosmos1th4k6hj64sdxx0g56ggv66j26huqpmc3y0x9t5?height=18530337
 
But it is giving the latest balance. I want balance till that height. Am I missing out anything in query?

**Comment by mayank-daga** [comment]
I found the change i need to do need to added x-cosmos-block-height: 18530337' in header

**Comment by MSalopek** [comment]
Closing as completed.

---------
Short recap:

Question about balances:
This will not work (`height` url param does not do anything - it never did)
`curl http://node-url/cosmos/bank/v1beta1/balances/cosmos1th4k6hj64sdxx0g56ggv66j26huqpmc3y0x9t5?height=18530337`

This will work:
`curl  -H "x-cosmos-block-height: 18530337" http://node-url/cosmos/bank/v1beta1/balances/cosmos1th4k6hj64sdxx0g56ggv66j26huqpmc3y0x9t5`


Questions about fetching message events are answered in the following comments:
* https://github.com/cosmos/gaia/issues/3034#issuecomment-2034320996
* https://github.com/cosmos/gaia/issues/3034#issuecomment-2027035019
