### ISSUE TITLE
Integrate Permissioned CosmWasm

### ISSUE THREAD

**Issue by reecepbcups** [cosmos/gaia#3050]
CosmosHub delegations have now signaled the addition of CosmWasm into the cosmoshub mainnet per https://www.mintscan.io/cosmos/proposals/895

gaiad q gov proposal 895

# notes
- On Upgrade handler, set to permissioned for upload, but permissionless instantiate? (maybe permissioned on both)
- Builds can no longer be done for windows

**Comment by MSalopek** [comment]
Closing as cosmwasm got merged to main in #3051 (targeting gaia v18).

Thanks you for your support in adding cosmwasm to gaia! 🚀
