### ISSUE TITLE
unknown query path for `gaiad query interchain-accounts controller params`

### ISSUE THREAD

**Issue by rootulp** [cosmos/gaia#3054]
## Context

I'm working on an interchaintest that creates interchain accounts from Celestia on Cosmos Hub. I was able to create the account in my test successfully but when I attempt to query the account, I hit an error. I was able to repro the error on a local devnet using `make start-localnet-ci`. I'm using `v15.1.0` in my test and locally. 

## Problem

In one tab:

```
make start-localnet-ci
```

In another tab:

```
$ gaiad query interchain-accounts controller params --home ~/.gaiad-liveness
Error: rpc error: code = Unknown desc = unknown query path: unknown request
Usage:
  gaiad query interchain-accounts controller params [flags]

Examples:
gaiad query interchain-accounts controller params
```

## Proposal

Investigate if the query commands under interchain accounts were registered correctly.

## Appendix

[Logs](https://pastebin.com/DEVDs311) from my test that motivated this issue. In my test, I want to query the interchain account that was just created so I'm trying to do:

```
gaiad query interchain-accounts controller interchain-account cosmos1dcl59vturqvzdcv90ya7q3t5e3966trz70kqxc connection-0 --chain-id gaia --home /var/cosmos-chain/gaia-2 --node http://gaia-val-0-TestICA:26657
```

**Comment by rootulp** [comment]
I don't see the `interchain_accounts.controller` registered

```
$ grpcurl -plaintext cosmos-grpc.polkachu.com:14990 list
cosmos.auth.v1beta1.Query
cosmos.authz.v1beta1.Query
cosmos.autocli.v1.Query
cosmos.bank.v1beta1.Query
cosmos.base.node.v1beta1.Service
cosmos.base.reflection.v1beta1.ReflectionService
cosmos.base.reflection.v2alpha1.ReflectionService
cosmos.base.tendermint.v1beta1.Service
cosmos.consensus.v1.Query
cosmos.distribution.v1beta1.Query
cosmos.evidence.v1beta1.Query
cosmos.feegrant.v1beta1.Query
cosmos.gov.v1.Query
cosmos.gov.v1beta1.Query
cosmos.mint.v1beta1.Query
cosmos.params.v1beta1.Query
cosmos.reflection.v1.ReflectionService
cosmos.slashing.v1beta1.Query
cosmos.staking.v1beta1.Query
cosmos.tx.v1beta1.Service
cosmos.upgrade.v1beta1.Query
gaia.globalfee.v1beta1.Query
grpc.reflection.v1alpha.ServerReflection
ibc.applications.interchain_accounts.host.v1.Query
ibc.applications.transfer.v1.Query
ibc.core.channel.v1.Query
ibc.core.client.v1.Query
ibc.core.connection.v1.Query
interchain_security.ccv.provider.v1.Query
packetforward.v1.Query
testpb.Query
```

**Comment by rootulp** [comment]
Host works

```
$ gaiad query interchain-accounts host params --home ~/.gaiad-liveness
allow_messages:
- '*'
host_enabled: true
```

but controller doesn't

```
$ gaiad query interchain-accounts controller params --home ~/.gaiad-liveness
Error: rpc error: code = Unknown desc = unknown query path: unknown request
Usage:
  gaiad query interchain-accounts controller params [flags]
```

**Comment by rootulp** [comment]
Okay I think I found the issue, on v15.1.0, the controller module isn't enabled https://github.com/cosmos/gaia/blob/1e7b5171ff1d6c8626aa4a0f049a10fefd69823e/app/keepers/keepers.go#L389

on main, the controller module is enabled

https://github.com/cosmos/gaia/blob/9aa34296715bbf43c2efc055a40337efea674a01/app/keepers/keepers.go#L426

when the controller module isn't enabled, the CLI command is added but we get confusing errors. See https://github.com/cosmos/ibc-go/issues/2978. So I think I can resolve by running `main` locally and a Docker image from `main` in my test.

**Comment by rootulp** [comment]
Confirmed, works on `main`:

```
$ gaiad query interchain-accounts controller params --home ~/.gaiad-liveness
controller_enabled: true
```

**Comment by MSalopek** [comment]
This feature will be enabled in the next gaia release.
It's scheduled for `gaiad v16.x`.
