### ISSUE TITLE
selecting cleveldb on build time

### ISSUE THREAD

**Issue by steevi** [cosmos/gaia#306]
## Summary of Bug

I'm trying to compile gaia with cleveldb support, and I cannot get it to start.

If I try to create a completely new chain using the provided commands below, I get the following error:
```
gaiacli keys add validator
Enter a passphrase to encrypt your key to disk:
Repeat the passphrase:
ERROR: couldn't create db: Unknown db_backend cleveldb, expected either fsdb or goleveldb or memdb
```

If i use an already existing `genesis.json`, I get the following error:
```
I[2020-03-04|11:27:56.760] starting ABCI with Tendermint                module=main
ERROR: couldn't create db: Unknown db_backend cleveldb, expected either memdb or goleveldb
```
## Version

release v2.0.5

## Steps to Reproduce

```
git clone https://github.com/cosmos/gaia.git
git checkout release/v2.0.5
WITH_CLEVELDB=yes make install



gaiad init --chain-id=testing testing
gaiacli keys add validator
gaiad add-genesis-account $(gaiacli keys show validator -a) 1000000000stake,1000000000validatortoken
gaiad gentx --name validator
gaiad collect-gentxs

nano ~/.gaiad/config/config.toml  # Change goleveldb to cleveldb db_backend = "cleveldb"

gaiad start
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by armorsun** [comment]
Met the same problem with gaia v4.0.0
