### ISSUE TITLE
Is make on master broken?

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#307]
## Summary of Bug
I just pulled master to my local branch and was unable to run make without an error:
```
golangci-lint run
cmd/gaiad/testnet.go:262:2: `cdc` can be `github.com/cosmos/cosmos-sdk/codec.JSONMarshaler` (interfacer)
	cdc *codec.Codec, mbm module.BasicManager, chainID string,
	^
make: *** [Makefile:169: lint] Error 1
```
I'm not sure if it's possible that my `golangci-lint` has local configurations that would break this but if that is the case then is it possible to write the make file in a way that overwrites them?

## Version

0.0.0-152-gfa691b7

## Steps to Reproduce

```sh
git checkout master
git pull
make
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
No master is not broken. Not sure why you're build is failing, but make sure you env is clean (e.g. `go.mod` isn't polluted). That being said, gaia is overdue for an update to SDK's latest `master`.
