### ISSUE TITLE
API /txs does not show failed transactions

### ISSUE THREAD

**Issue by congle-ibl** [cosmos/gaia#309]
Hi Team,

I'm running COSMOS fullnode with gaia v2.0.4. I'm trying to get transactions related to this address: 
```
cosmos1gzc54u4p67hh9r4m9vcml3ke9fc29tplsefy6k
```
But it only shows successful transactions. 

This address has 130 transactions (124 successful and 6 failed) on mintscan:
https://www.mintscan.io/account/cosmos1gzc54u4p67hh9r4m9vcml3ke9fc29tplsefy6k

Here are my requests:
http://my_local_IP:1317/txs?message.sender=cosmos1gzc54u4p67hh9r4m9vcml3ke9fc29tplsefy6k
http://my_local_IP:1317/txs?transfer.recipient=cosmos1gzc54u4p67hh9r4m9vcml3ke9fc29tplsefy6k

I checked all pages of these requests but not found any failed transactions.
Please help to give me some advice. Thank you so much for your time.

**Comment by alexanderbez** [comment]
It does show the failed tx(s). eg. https://api.cosmos.network/txs?tx.height=678820

**Comment by congle-ibl** [comment]
Hi @alexanderbez ,

Thank you so much for your quickly support.
Actually I mean my input param is an address and I want to query all of its history, so I will try to do this:
```
https://api.cosmos.network/txs?message.sender=cosmos1gzc54u4p67hh9r4m9vcml3ke9fc29tplsefy6k&tx.height=678820
```
OR
```
https://api.cosmos.network/txs?transfer.recipient=cosmos1gzc54u4p67hh9r4m9vcml3ke9fc29tplsefy6k&tx.height=678820
```

And I found nothing. I think because failed transaction does not contain logs and events, and raw_log is just an error message when we call this:
```
https://api.cosmos.network/txs?tx.height=678820
```

So if my input param is an address, what should I do to get its failed transactions?
Thank you so much.

**Comment by alexanderbez** [comment]
This is because your tx failed before any message was even processed. It failed at the AnteHandler. Thus the tx won't have any events and that's why you can't query for them by events.

**Comment by congle-ibl** [comment]
Is there anyway to query for them by another?

**Comment by alexanderbez** [comment]
Txs that don't pass the ante-handler don't have any events to emit, so hence there is nothing to query by. Your only safe bet is to query the block itself and get all the txs to see if any failed.

**Comment by congle-ibl** [comment]
It's clear to me. Thank you so much for your explanation.

**Comment by congle-ibl** [comment]
Please help me to clarify one more thing, I don't know how mintscan.io can show all transactions (including failed transactions) of each address.

**Comment by alexanderbez** [comment]
Easy. They can either query (or subscribe to) all-new block events or query for block txs directly. The response includes _all_ txs -- including failed.

You're querying for _specific_ txs by _events_ which _dont_ exist.

**Comment by congle-ibl** [comment]
Amazing. Would you please help to give me the way how to subscribe all-new block events? I'm trying to run tmkms to support for gaia node's socket but there is no data while a new block is coming. Is there any document for it or would you please help to give me an example source code to subscribe? Thank you in advance @alexanderbez

**Comment by alexanderbez** [comment]
It outlined in Tendermint's RPC docs => https://docs.tendermint.com/master/rpc/#/Websocket/subscribe

**Comment by congle-ibl** [comment]
I tried it out with option tm.event = 'NewBlock' but it did not work, I got an error message:
```
TypeError: NetworkError when attempting to fetch resource.
```

**Comment by congle-ibl** [comment]
I also tried to run with this url: `http://rpc.cosmos.network/subscribe?tm.event='NewBlock'` but I got this:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32601,
    "message": "Method not found"
  }
}
```
