### ISSUE TITLE
[question]: Unable to get the latest list of proposals through the restful interface

### ISSUE THREAD

**Issue by YuXiaoCoder** [cosmos/gaia#3098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I can't get the latest proposals through the interface /cosmos/gov/v1beta1/proposals

```bash
curl -X GET https://cosmos-api.polkachu.com/cosmos/gov/v1beta1/proposals | jq
```
![image](https://github.com/cosmos/gaia/assets/26297513/cede1060-22a8-47d4-9966-e3cbfacdedb0)

But there's up-to-date information on the proposal on [mintscan](https://www.mintscan.io/cosmos/proposals)
![image](https://github.com/cosmos/gaia/assets/26297513/eae4099e-f0e8-49b8-bd23-cf079497c895)

### Gaia Version

v15.2.0

### How to reproduce?

Just request it directly, if it's known that it's not available this way, is there another way you can tell me about?

**Comment by MSalopek** [comment]
Thank you for opening the issue.

Try this `curl -X GET https://cosmos-api.polkachu.com/cosmos/gov/v1/proposals\?pagination.reverse\=true`

There were some changes in cosmos-sdk v0.47.x - `gov/v1/proposals` is not the same as `gov/v1beta/proposals`

Docs reference: https://docs.cosmos.network/api#tag/Query/operation/GovV1Proposal

**Comment by YuXiaoCoder** [comment]
Thanks, the problem has been solved, the reason was that I was not aware of the paging feature
