### ISSUE TITLE
support "unknown command" for tx and query commands

### ISSUE THREAD

**Issue by colin-axner** [cosmos/gaia#310]
## Summary of Bug
Misuse of `gaiacli tx` and `gaiacli query` provide uninformative error reports as first reported in the [sdk](https://github.com/cosmos/cosmos-sdk/issues/4284)

## Version
v2.0.6

## Steps to Reproduce
`gaiacli tx distr --from blabla`
`ERROR: unknown flag: --from`
*because distr should be distribution

This can be fixed by adding 
```
DisableFlagParsing:         true,
SuggestionsMinimumDistance: 2,
RunE:                       client.ValidateCmd,
```
to each command, alternatively I'm still tracking this [pr](https://github.com/spf13/cobra/pull/842) which should fix some of these issues natively in cobra.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
ahh found another issue with `ValidateCmd`, [this](https://github.com/cosmos/cosmos-sdk/blob/116b6cfc1d957ab7a6649bc070a3e5112d49fb79/client/cmd.go#L19) will catch the flag names from being added to suggested args, but it won't catch the flag arg from being added to suggested args, for example in the following:
```
gaiacli tx distribution --chain-id cosmoshub-3
ERROR: unknown command "cosmoshub-3" for "distribution"
```
I'd add a `skipNext` bool and if it is a flag under the condition arg[0] == "-" then set skipNext to true. At the beginning of the loop add a if skipNext { skipNext = false } and make the help if a elseif

edit: this doesn't work if the user does --flag=flagVal

**Comment by alexanderbez** [comment]
Nice catch! Shouldn't this issue exist under the SDK?

**Comment by colin-axner** [comment]
The first part I believe would be changed [here](https://github.com/cosmos/gaia/blob/fa691b711e05d89f9e51658257f504c09b26917d/cmd/gaiacli/main.go#L91) and under tx cmd. The second comment should exist under the sdk, but I posted it here since I had just opened up a related issue
