### ISSUE TITLE
Jailed validator

### ISSUE THREAD

**Issue by Seel555** [cosmos/gaia#3121]
Hello, validator received jailed status but running command gaiad tx slashing unjail returns Error: illegal base64 data at input byte 24

**Comment by mpoke** [comment]
Hi @Seel555. What version of gaiad are you using?

**Comment by MSalopek** [comment]
Thank you for opening the issue!

Please give us more information about the exact cmd you are trying to execute and the gaiad version in question.

**Comment by Seel555** [comment]
Hello, thank you for your replies, issue been fixed the reason is broken key.

**Comment by MSalopek** [comment]
Thank you for clarifying.

Closing as it is resolved
