### ISSUE TITLE
[feature request]: gaia container image is outdated since 2 years

### ISSUE THREAD

**Issue by onur-ozkan** [cosmos/gaia#3124]
gaia container image is outdated since 2 years (see https://github.com/orgs/cosmos/packages?repo_name=gaia). Reason for this is that the `docker-push` pipeline never runs at the moment, which I assume is due to an incorrect branch check at here: https://github.com/cosmos/gaia/blob/3462c51d6874a82dbd7fe6b295d804e1ffe5caa5/.github/workflows/docker-push.yml#L6

**Comment by MSalopek** [comment]
Thank you for opening the issue.

The gaia container image is not used by any of our internal processes or pipelines.

If you find it useful we can allocate resources to cleaning up the published docker images and publishing images consistently for every major release.

Could you please describe how you would like to use the docker image and what processes would it improve for you?

**Comment by onur-ozkan** [comment]
> If you find it useful we can allocate resources to cleaning up the published docker images and publishing images consistently for every major release.

I would use free/shared CI runner from Github and dockerhub as a container registry which would be perfectly fine for providing gaia image.

> Could you please describe how you would like to use the docker image and what processes would it improve for you?

I am currently using Atom testnets in my integration tests. However, I have decided to migrate these tests to use local testnets for stability (so my balances won't run out and tests results will be consistent). To do this, I had to build my own gaia image as there no image provided by Cosmos. This is not ideal because I want my integration tests to always use the latest gaia version but there is no sane way to do this from outside of upstream repository. If there was an official image provided by Cosmos, I could simply do something like `cosmos/gaia:latest` while running my container and my tests would automatically use the latest gaia release without needing any workaround.

**Comment by MSalopek** [comment]
Thank you for walking me though your usecase.

I think we can allocate some capacity to getting this done and have it as part of the release process.

Until we handle it,  there are dockerfiles you can use:
* https://github.com/cosmos/gaia/blob/main/Dockerfile
* https://github.com/cosmos/gaia/blob/main/e2e.Dockerfile

**Comment by reecepbcups** [comment]
Our team maintains the latest tagged images of the hub here: https://github.com/strangelove-ventures/heighliner/pkgs/container/heighliner%2Fgaia :) `ghcr.io/strangelove-ventures/heighliner/gaia:v17.2.0`

We also have iavl patches for SDK v45 queries, useful for archival nodes

**Comment by MSalopek** [comment]
Thank you @Reecepbcups!

@onur-ozkan You can use the images above until we clean up the release process.

We will be packaging the docker workflow updates and publishing with some release testing changes.

Closing as this is solved, more updates will be coming later.

Please tag me if you need further assistance and I will reopen the issue.

**Comment by MSalopek** [comment]
Re-opening for tracking ongoing work.
@fastfadingviolets
