### ISSUE TITLE
How to search transactions by recipient

### ISSUE THREAD

**Issue by abyssal0** [cosmos/gaia#314]
/txs?message.action=send&message.sender=adress
can search transactions by sender
But I want to search transactions by recipient. How can I do?

**Comment by alexanderbez** [comment]
Each module documents all the events it may emit. I recommend reviewing [this](https://docs.cosmos.network/master/core/events.html) for a better understanding.

**Comment by abyssal0** [comment]
each module documents its events under spec/xx_events.md.
I didn't find the above document
