### ISSUE TITLE
Delegator TxCancelUnbond or TxCancelRebond

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#32]
If you are in the process of unbonding you should be able to restore your bond to the original validator. You would potentially lose validation reward for the period in which you were unbonding (unless you were rebonding). 

If you cancel an unbond, and are now rebonded you should be slashable even for the period you were unbonding from the validator (?)

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/577
