### ISSUE TITLE
[Bug]: Unbond validator is not working on v19.0.0-rc

### ISSUE THREAD

**Issue by arifintahu** [cosmos/gaia#3245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!
I tried `gaiad tx staking unbond-validator --from validator1` on v19.0.0-rc0 theta testnet and then I got 
```
Error: hrp does not match bech32 prefix: expected 'cosmos' got 'cosmosvaloper': internal logic error
```
![image](https://github.com/user-attachments/assets/015ba7b4-c1b1-4af9-8fb2-3b594387024e)

After following the corresponding code, it seems the error come from cosmos sdk v0.50.8-lsm https://github.com/cosmos/cosmos-sdk/blob/62baa29ab9e3f190b148fc9e2e8e884da452a8e9/x/staking/client/cli/tx.go#L338 
valAddrCodec.BytesToString cannot process valoper

### Gaia Version

v19.0.0-rc0 to v19.0.0-rc3

### How to reproduce?

1. create validator on theta testnet
2. unbond validator `gaiad tx staking unbond-validator --from validator1`

**Comment by MSalopek** [comment]
Thanks for opening the issue.

The text and the image you showed do not match. The text states you are executing an unbond Tx, while the image shows that you have a signing step.

How did you generate the Tx?

We're checking it out.

**Comment by arifintahu** [comment]
I tried two methods directly signing unbond validator and signing using tx sign, but the result is the same
1. gaiad tx staking unbond-validator --from validator1
2. gaiad tx staking unbond-validator --from validator1 --generate-only > msg.json | gaiad tx sign msg.json --from validator1

**Comment by MSalopek** [comment]
Thanks for the additional context!

We are looking into it.

**Comment by MSalopek** [comment]
The bug has been triaged and the fix will be ready soon. The fix will be a part of the upcoming cosmos-sdk-lsm release and the next gaia release candidate.

Thank you @arifintahu

**Comment by MSalopek** [comment]
Fixed in:
https://github.com/cosmos/gaia/pull/3249

Targeting v19.0.0-rc0. The changes will be in the mainnet v19.0.0 release.

Thanks once again!

**Comment by arifintahu** [comment]
Great, glad to hear that!
