### ISSUE TITLE
[Bug]: chain (mainnet) stuck after upgrade to 19.1.0

### ISSUE THREAD

**Issue by tmeinlschmidt** [cosmos/gaia#3286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgraded to 19.1.0 (used Dockerfile provided in the repo) and after restart chain is stuck with
````
3:07PM INF packet sent dst_channel=channel-0 dst_port=consumer module=x/ibc/channel sequence=2059900 src_channel=channel-568 src_port=provider
3:07PM INF packet sent dst_channel=channel-146 dst_port=consumer module=x/ibc/channel sequence=1738960 src_channel=channel-635 src_port=provider
````

and I only see more disk consuption, rosetta nor any other service is not started (from /data/config/app.toml)

### Gaia Version

19.1.0

**Comment by MSalopek** [comment]
Hi! Thanks for opening an issue.

How big is your node instance in TB?

The app is likely performing the upgrade. If you have a large node, it will take some time because the database is getting migrated.

**Comment by tmeinlschmidt** [comment]
Hey, almost 16TB. Okay, will wait. Thanks!

**Comment by MSalopek** [comment]
It might take quite a while, the entire database is being migrated.

Please let us know if there are any issues, we'll keep the issue open.

**Comment by tmeinlschmidt** [comment]
looks like migrated, took almost 1.5 hours. Ports are up except rosetta, even it's specified in app.toml, something changed?
````
[rosetta]

# Enable defines if the Rosetta API server should be enabled.
enable = true

# Address defines the Rosetta API server to listen on.
address = "127.0.0.1:8545"

# Network defines the name of the blockchain that will be returned by Rosetta.
blockchain = "cosmos"

# Network defines the name of the network that will be returned by Rosetta.
network = "mainnet"
````

**Comment by tmeinlschmidt** [comment]
So, I had to run separate `gaiad rosetta` to enable rosetta then, even it has the configuration entry in app.toml. Is that expected? It did work in 18.1.0

**Comment by MSalopek** [comment]
> So, I had to run separate `gaiad rosetta` to enable rosetta then, even it has the configuration entry in app.toml. Is that expected? It did work in 18.1.0

Judging by the docs, it's no longer supported in the same way:
* https://docs.cosmos.network/v0.50/build/migrations/upgrading#rosetta
* https://docs.cosmos.network/main/user/run-node/rosetta#standalone

Additionally, the config option from `app.toml` is not available if you do `gaiad init <moniker>`, you probably have it left over from your old config.

**Comment by MSalopek** [comment]
Closing as completed. If you run into more issues, please open another issue and we'll address it.

Thanks!
