### ISSUE TITLE
How to run gaia node with socket

### ISSUE THREAD

**Issue by congle-ibl** [cosmos/gaia#329]
Hi all,

I'm trying to run gaia node v2.0.6 to hope that socket will work and I can subscribe new data from gaia node's socket.

I tried to run gaia node with this command:
```
gaiad start --home <data_folder> --address tcp://127.0.0.1:26658
```
Or:
```
gaiad start --home <data_folder> --proxy_app tcp://127.0.0.1:26658
```
Or:
```
gaiad start --home <data_folder> --priv_validator_laddr tcp://127.0.0.1:26658
```

But I got the same error message:
```
I[2020-03-20|19:10:55.313] starting ABCI with Tendermint                module=main 
E[2020-03-20|19:10:59.068] SignerClient::GetPubKey                      module=privval err="endpoint connection timed out"
ERROR: could not retrieve public key from private validator
```

I don't know how to run gaia node with socket. Please help to give me some advice. Thank you in advance.

**Comment by cryptnotiq** [comment]
hey @congle-ibl just trying to better understand your situation. Did you generate a new public/private key pair prior to running the node?

**Comment by tac0turtle** [comment]
@congle-ibl  are you trying to run your gaia node with the kms on a socket?

**Comment by glnro** [comment]
Hi @congle-ibl, thanks for posting your issue! We've been behind on many reviews and apologize for such. Would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team

**Comment by uhvyuhs77** [comment]
I[2020-03-20|19:10:55.3gaiad start --home <data_folder> --address tcp://127.0.0.1:26658
