### ISSUE TITLE
[General question]: Getting [panic]: Could not open exclusive.lock  issue after upgrade to v19.1.0

### ISSUE THREAD

**Issue by mayank-daga** [cosmos/gaia#3296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrade to v19.1.0, I am getting following logs:

panic: Could not open exclusive.lock

goroutine 1 [running]:
github.com/CosmWasm/wasmd/x/wasm/keeper.NewKeeper({_, _}, {_, _}, {_, _}, {_, _}, {0x4f79be8, 0xc00270cf80}, ...)
  github.com/CosmWasm/wasmd@v0.51.0/x/wasm/keeper/keeper_cgo.go:72 +0xe4d
github.com/cosmos/gaia/v19/app/keepers.NewAppKeeper({_, _}, _, _, _, _, _, _, {0x7ffc98566f61, 0xb}, ...)
  github.com/cosmos/gaia/v19/app/keepers/keepers.go:476 +0x50f0
github.com/cosmos/gaia/v19/app.NewGaiaApp({0x4f797f8, 0xc001d59180}, {0x4f91020, 0xc0019ac030}, {0x0, 0x0}, 0x1, 0xc04d766210, {0x7ffc98566f61, 0xb}, ...)
  github.com/cosmos/gaia/v19/app/app.go:181 +0x72b
github.com/cosmos/gaia/v19/cmd/gaiad/cmd.appCreator.newApp({}, {0x4f797f8, 0xc001d59180}, {0x4f91020, 0xc0019ac030}, {0x0, 0x0}, {0x4f30960, 0xc001f84fc0})
  github.com/cosmos/gaia/v19/cmd/gaiad/cmd/root.go:372 +0xa45
github.com/cosmos/cosmos-sdk/server.startApp(0xc00178ef40, 0xc0013c3d50, {0x4838bd0, 0x0, 0x0, 0x0, 0x4838be0})
  github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:618 +0x223
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x4f96ed8, 0xc001e682a0}, 0x0, {0x0, 0x0}, {0x4fbb108, ...}, ...}, ...)
  github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:224 +0x159
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
  github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:198 +0x63
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc00178ef40, 0xc002591a20)
  github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:570 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc001964308, {0xc001a11b00?, 0x2?, 0x6?})
  github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:197 +0x212
github.com/spf13/cobra.(*Command).execute(0xc001964308, {0xc001a11a40, 0x6, 0x6})
  github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00180cf08)
  github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
  github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
  github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc00180cf08, {0x0, 0x0}, {0xc0012eeff0, 0x13})
  github.com/cosmos/cosmos-sdk@v0.50.9/server/cmd/execute.go:34 +0x187
main.main()
  github.com/cosmos/gaia/v19/cmd/gaiad/main.go:15 +0x2a

### Gaia Version

v19.1.0

**Comment by MSalopek** [comment]
Thanks for opening the issue.

Check that you have the `wasm` directory present in your node's root directory and that you don't have a `wasm/wasm` directory.

Also, take note that only 1 node at a time is accessing the directory.

EDIT:
Are participating in the cosmos hub discords? Issues like these might get an immediate response from validators who have already solved similar issues.

**Comment by mayank-daga** [comment]
reoslved
