### ISSUE TITLE
[Docs]: Joining Testnet page is missing information for releases >= v17

### ISSUE THREAD

**Issue by rootulp** [cosmos/gaia#3297]
## Context

I want to join Cosmos Hub testnet.

## Problem

I think [Joining Testnet](https://hub.cosmos.network/v19.1.0/hub-tutorials/join-testnet) page is outdated because it doesn't contain information about the v19 upgrade. The most recent blocks on Cosmos Hub testnet use binary version v19.1.0. See [mintscan](https://www.mintscan.io/cosmos-testnet/parameters/)

![Screenshot 2024-08-27 at 10 35 58 AM](https://github.com/user-attachments/assets/9ef0733f-7389-4002-bcc3-ec7ca00ca01a)

## Proposal

Update the docs

**Comment by MSalopek** [comment]
Thank you for opening the issue!

Please use this link:
* https://github.com/cosmos/testnets/tree/master/release

We will update the docs accordingly.
