### ISSUE TITLE
sync was stoped

### ISSUE THREAD

**Issue by prettyCoders** [cosmos/gaia#33]
![image](https://user-images.githubusercontent.com/36216120/58774851-1c043e80-85f6-11e9-9681-dce2f39e1d7c.png)

**Comment by alexanderbez** [comment]
@prettyCoders please provide the binary version you're using?

**Comment by prettyCoders** [comment]
0.34.4 or 0.34.5,I do not remenber it ,I upgraded newest

**Comment by alexanderbez** [comment]
@prettyCoders you need to run the latest version v0.34.7. Can you try that?

**Comment by prettyCoders** [comment]
Yes  of course,thanks 

发自我的iPhone

------------------ Original ------------------

**Comment by crossle** [comment]
use the lastest v0.35.0 got the error
```
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected C90B86E6C15CF3EB7C0B5BE414BE354C37A8CC2A22354C23DFDA043DE24EE457, got 056A9CA652FC5DD667A19362081216A57A70F87A256FD62B3131673BCDBD969B
```

**Comment by alexanderbez** [comment]
@crossle you cannot use v0.35.x. That version is not compatible with the mainnet. Please review the README 😄
