### ISSUE TITLE
cosmos-sdk/MsgMultiSend

### ISSUE THREAD

**Issue by abyssal0** [cosmos/gaia#331]
A transfer was received today of 'cosmos-sdk/MsgMultiSend' type. What is the difference between 'cosmos-sdk/MsgSend'.
Can I safely hold this asset?

**Comment by alexanderbez** [comment]
A `MsgMultiSend` is multiple `MsgSend`. It allows you to avoid sending multiple `MsgSend` txs, where instead you construct multiple inputs & outputs in a single message.
