### ISSUE TITLE
[Bug]: Node is creating multiple temp directories on command executions

### ISSUE THREAD

**Issue by harish551** [cosmos/gaia#3348]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

In latest versions of code while we are using a temp dir for queries or any kind of command executions 
node is trying to create a temp directory but these are not removing after executing folders still exists on temp folder

https://github.com/cosmos/gaia/blob/main/cmd/gaiad/cmd/root.go#L437

```
var tempDir = func() string {
	dir, err := os.MkdirTemp("", ".gaia")
	if err != nil {
		dir = gaia.DefaultNodeHome
	}
	defer os.RemoveAll(dir)

	return dir
}
```

This function will remove node home if there is problem with creating temp directory
it happened to me multiple times when the server's disk is full (it will completely erase node home)

### Gaia Version

v19.0.0, v20.0.0

### How to reproduce?

check tmp folder after executing some queries 
you will find lot of .gaia-temp** folders

**Comment by MSalopek** [comment]
Thank you for reporting this.

This was confirmed as an issue and will be scheduled for fixing.

If this is posing issues for your current setup, you can modify the init procedure in your root.go - the change does not affect node state.

**Comment by harish551** [comment]
Okay thank you

I've already worked on this fix for omniflixhub

https://github.com/OmniFlix/omniflixhub/pull/190
