### ISSUE TITLE
Internal server error on some gaia API calls

### ISSUE THREAD

**Issue by feri42** [cosmos/gaia#335]
## Summary of Bug

Calling the Gaia-Lite for Cosmos API calls:
```
POST /staking/delegators/{delegatorAddr}/delegations
POST /staking/delegators/{delegatorAddr}/unbonding_delegations
POST /staking/delegators/{delegatorAddr}/redelegations
```
with `simulate=true` or with the query paramter `generate_only=true` returns a Internal Server Error with the following response body:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "runtime error: invalid memory address or nil pointer dereference"
  }
}
```

## Version

Gaiacli and gaiad version is 2.0.7

## Steps to Reproduce

Unpack the attached `body.json` file and run:
```
curl -X POST -H "Content-Type: application/json" https://<gaiad>/staking/delegators/cosmos1j4heycy25ersvld236f3ckpn9avjjt4p3tmg23/delegations -d @body.json
```

[body.json.gz](https://github.com/cosmos/gaia/files/4377001/body.json.gz)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
Thanks for the details report @feri42 I'm moving this issue over to the SDK https://github.com/cosmos/cosmos-sdk/issues/5869

**Comment by okwme** [comment]
Hi @feri42 looks like @jgimeno has identified a problem with your original transaction that was causing the error:
https://github.com/cosmos/cosmos-sdk/issues/5869#issuecomment-607342642

**Comment by feri42** [comment]
Yes, thank you @okwme . The issue has been resolved for me. This one can be closed and re-classified as not-a-bug. It is a documentation issue.
