### ISSUE TITLE
[Docs]: validators/validators-faq returns a 404

### ISSUE THREAD

**Issue by odeke-em** [cosmos/gaia#3382]
### Summary

Reported originally at https://github.com/cosmos/cosmos-sdk/issues/22158

### Summary

If I navigate to the page about validators setup at https://hub.cosmos.network/main/validators/validator-setup.html, trying to click on the FAQ at https://hub.cosmos.network/validators/validator-faq#how-can-validators-protect-themselves-from-denial-of-service-attacks results in a 404

**Comment by MSalopek** [comment]
How are you getting that link, could you provide a screenshot showing what you're seeing?

This is the correct link.
https://hub.cosmos.network/main/validators/validator-faq#how-can-validators-protect-themselves-from-denial-of-service-attacks

I can see it whenever I hover over the section title.

There may have been some cache invalidation issues. The site seems to have been fully rebuilt now.

EDIT:
Nevermind, I managed to reproduce.
Fix: https://github.com/cosmos/gaia/pull/3391
