### ISSUE TITLE
Account and Node addresses should be prefixed differently

### ISSUE THREAD

**Issue by zmanian** [cosmos/gaia#34]
Cosmos uses ed25519 public keys at identifiers for both accounts and nodes in gaia.

Keys and addresses should have a prefixes to different different types of objects.

Interactions with the CLI should check the address/pubkey prefix before executing actions like send to only account and bond only to nodes.

**Comment by rigelrozanski** [comment]
Does this apply to the SDK? `gaia tx send` is a sdk function, are you hoping that this would be implemented there too?

**Comment by zmanian** [comment]
Closing favor of https://github.com/cosmos/cosmos-sdk/issues/263
