### ISSUE TITLE
Unknown db_backend leveldb, expected either fsdb or goleveldb or memdb

### ISSUE THREAD

**Issue by alpe** [cosmos/gaia#341]
## Summary of Bug
Invalid DB default for new testnet:

```sh
I[2020-03-31|11:07:18.008] starting ABCI with Tendermint                module=main
panic: Unknown db_backend leveldb, expected either fsdb or goleveldb or memdb

goroutine 1 [running]:
github.com/tendermint/tm-db.NewDB(0x4d65c79, 0xa, 0xc000f3e010, 0x7, 0xc0001bccc0, 0x37, 0x4b6ec60, 0x0)
	/Users/alex/workspace/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/db.go:67 +0x39f
github.com/tendermint/tendermint/node.DefaultDBProvider(0xc000efc6e0, 0xc000efc6e0, 0x0, 0x0, 0x0)
```

Problem:
`config.toml` contains: `db_backend = "leveldb"` instead of `db_backend = "goleveldb"`

## Version

`v2.0.7` with hash `2eaf341`

## Steps to Reproduce

* `gaiad testnet --v=1 -o= ~/my-testnet`
* `gaiad start --home ~/my-testnet/node0/gaiad`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
This doesn't belong in Gaia. If you're using a config.toml from a previous network, you have to update that config value as Tendermint changed its allowed DB backends. If your node is brand new, then Tendermint should set the correct default value.

**Comment by alpe** [comment]
It was a brand new node created with the `gaiad testnet -v=1 -o= ~/my-testnet` command.

**Comment by alexanderbez** [comment]
That cannot be.

```
❯ $ gaiad version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.7
commit: 2eaf34171e7dc97c18c76b117ffc5455d3cd1ec3
build_tags: netgo,ledger
go: go version go1.14 darwin/amd64
```

```
❯ $ gaiad init foo --home /tmp/foo
```

```
❯ $ cat /tmp/foo/config/config.toml | grep 'db_backend
db_backend = "goleveldb"
```

As you can see, on a fresh install and fresh init, Tendermint generates the correct default value.

**Comment by alpe** [comment]
This is not the problem I was reporting. `gaiad init` worked as you had pointed out and I got the same results on every step.
Instead of `gaiad init` I was reporting an issue with `gaiad testnet`.
```sh
> gaiad testnet --v=1 -o=/tmp/bar
```
```sh
> cat /tmp/bar/node0/gaiad/config/config.toml | grep 'db_backend'

db_backend = "leveldb"
```

**Comment by alexanderbez** [comment]
I've never used that command directly before. You may launch a local testnet via `make clean install localnet-start` which under the hood uses `gaiad testnet`.
