### ISSUE TITLE
[question] cosmos testnet upgrade issues - migrating from theta to provider testnet

### ISSUE THREAD

**Issue by saravadeanil** [cosmos/gaia#3434]
## Problem

I am facing below issues on my cosmos-testnet node while migrating from `theta-testnet-001` -> `provider (ics-testnet-provider)`

```
1:55PM INF error from light block request from primary, removing... error="client provided bad signed header: invalid signed header: header belongs to another chain \"provider\", not \"theta-testnet-001\"" height=8787650 module=light primary=http{https://rpc.provider-sentry-01.ics-testnet.polypore.xyz}

1:55PM ERR error on light block request from witness, removing... error="client provided bad signed header: invalid signed header: header belongs to another chain \"provider\", not \"theta-testnet-001\"" module=light primary=http{https://rpc.provider-sentry-02.ics-testnet.polypore.xyz}

Error: failed to start state sync: failed to set up light client state provider: light block not found
```

I am following this documents:- https://github.com/cosmos/testnets/blob/master/interchain-security/provider/README.md

How should I resolve it?

**Comment by MSalopek** [comment]
Thanks for opening the issue and sorry for the trouble.

What do you mean by migrating? You should be syncing to the `provider` network via statesync or node snapshot.

I don't see a mention of addrbook. Please use the `provider` network `addrbook.json`.

**Comment by saravadeanil** [comment]
Hi @MSalopek Thanks for writing back.

Actually, I updated the following values by referring this document. [THIS](https://github.com/cosmos/testnets/blob/master/interchain-security/provider/README.md#endpoints)

- client.toml

```
    chain-id = "provider"

```
- config.toml
```
[statesync]
    rpc_servers = "https://rpc.provider-state-sync-01.ics-testnet.polypore.xyz:443,https://rpc.provider-state-sync-02.ics-testnet.polypore.xyz:443"
    trust_height = 9464974
    trust_hash = "D9EF41F56787141DBF2A7243988EAB14DE53897AA6D9A6EA1A403C60A7B40C41"
[p2p]
    seeds = "08ec17e86dac67b9da70deb20177655495a55407@provider-seed-01.ics-testnet.polypore.xyz:26656,4ea6e56300a2f37b90e58de5ee27d1c9065cf871@provider-seed-02.ics-testnet.polypore.xyz:26656"
```

And I am running my node with version [v21.0.1](https://github.com/cosmos/gaia/releases/tag/v21.0.1)

Can you help me understand what values should I be using?

**Comment by MSalopek** [comment]
I can try to help.

Is this a new node or are you trying to re-use an existing node?

The client config is not important. It's only used for the CLI interactions (sending `gaiad q ...` and `gaiad tx ...`).

EDIT:
You can use this (it has instructions) to setup your node from snapshot to avoid some of these onboarding issues.
https://polkachu.com/testnets/cosmos/snapshots

**Comment by saravadeanil** [comment]
@MSalopek Thanks for your help. I was able to sync the node by referring to below files.

- https://www.polkachu.com/testnets/cosmos/peers
- https://www.polkachu.com/testnets/cosmos/snapshots
- https://www.polkachu.com/testnets/cosmos/addrbooks
- https://github.com/cosmos/testnets/raw/master/interchain-security/provider/provider-genesis.json

**Comment by saravadeanil** [comment]
I appreciate your help 🙏  🎉 

We can close the issue for now @MSalopek

**Comment by MSalopek** [comment]
Glad it worked!

Closing. Please open another issue if you run into further issues.
