### ISSUE TITLE
FTBFS: update against cosmos-sdk v0.34.4-0.20200409184808-709d96a6f4c4

### ISSUE THREAD

**Issue by alessio** [cosmos/gaia#352]
`gaia` FTBFS when compiled against `github.com/cosmos/cosmos-sdk` rev v0.34.4-0.20200409184808-709d96a6f4c4 - related to https://github.com/cosmos/cosmos-sdk/pull/5966 

An excerpt of the build log follows:

```
alessio@bangalter:~/work/gaia$ make install
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=0.0.0-172-g2bff973 -X github.com/cosmos/cosmos-sdk/version.Commit=2bff973c92f3529f942f790ec44e83c65f83fc4e -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' -trimpath ./cmd/gaiad
# github.com/cosmos/gaia/app
app/app.go:271:40: not enough arguments in call to auth.NewAnteHandler
	have ("github.com/cosmos/cosmos-sdk/x/auth/keeper".AccountKeeper, "github.com/cosmos/cosmos-sdk/x/supply/keeper".Keeper, func("github.com/cosmos/cosmos-sdk/store/types".GasMeter, []byte, crypto.PubKey, "github.com/cosmos/cosmos-sdk/x/auth/types".Params) error)
	want ("github.com/cosmos/cosmos-sdk/x/auth/keeper".AccountKeeper, "github.com/cosmos/cosmos-sdk/x/auth/types".SupplyKeeper, "github.com/cosmos/cosmos-sdk/x/ibc/keeper".Keeper, func("github.com/cosmos/cosmos-sdk/store/types".GasMeter, []byte, crypto.PubKey, "github.com/cosmos/cosmos-sdk/x/auth/types".Params) error)
Makefile:94: recipe for target 'install' failed
make: *** [install] Error 2
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alessio** [comment]
@jackzampolin can you provide a justification when you close an issue please? Thanks!

**Comment by alessio** [comment]
Reopening as this still stands. We shall close it when it's resolved.

**Comment by tac0turtle** [comment]
If we update to master of the sdk this should not be present 

@alessio have you tested with master lately?

**Comment by alessio** [comment]
> WTF is FTBFS?

Fail To Build From Source

> @alessio have you tested with master lately?

This can be closed once `ibc-alpha` is merged in

**Comment by alessio** [comment]
> Can we just close this issue? ibc-alpha will have the latest SDK head commit.

Yep, `ibc-alpha` is ready. Let's close it. Thanks!
