### ISSUE TITLE
Gas fee issue during unbond

### ISSUE THREAD

**Issue by dev-lc** [cosmos/gaia#356]
## Summary of Bug

I wanna to get back the tokens I had delegated to some validator. But I got the error

## Version

gaiacli version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.3
commit: 2f6783e298f25ff4e12cb84549777053ab88749a
build_tags: netgo,ledger
go: go version go1.13.5 linux/amd64

## Steps to Reproduce

$ gaiacli query account cosmos1g*

address: *
coins:

denom: uatom
amount: "225425"
pubkey: *
accountnumber: *
sequence: *
$ gaiacli query staking delegations cosmos1g*

delegation:
delegator_address: cosmos1g*
validator_address: cosmosvaloper1kn3wugetjuy4zetlq6wadchfhvu3x740ae6z6x
shares: "154189589.000000000000000000"
balance: "154189589"
$ gaiacli tx staking unbond cosmosvaloper1kn3wugetjuy4zetlq6wadchfhvu3x740ae6z6x 154189589stake --from at01 --gas-adjustment 1.5 --gas 20589 --gas-prices 0.05uatom
{"chain_id":"cosmoshub-3","account_number":"","sequence":"","fee":{"amount":[{"denom":"uatom","amount":"1030"}],"gas":"20589"},"msgs":[{"type":"cosmos-sdk/MsgUndelegate","value":{"delegator_address":"cosmos1g*","validator_address":"cosmosvaloper1kn3wugetjuy4zetlq6wadchfhvu3x740ae6z6x","amount":{"denom":"stake","amount":"154189589"}}}],"memo":""}

confirm transaction before signing and broadcasting [y/N]: y
Password to sign with 'at01':
height: 0
txhash: *
code: 12
data: ""
rawlog: '{"codespace":"sdk","code":12,"message":"out of gas in location: WriteFlat;
gasWanted: 20589, gasUsed: 22437"}'
logs: []
info: ""
gaswanted: 0
gasused: 0
codespace: ""
tx: null
timestamp: ""
events: []

$ gaiacli tx staking unbond cosmosvaloper1kn3wugetjuy4zetlq6wadchfhvu3x740ae6z6x 154189589stake --from at01 --gas auto
gas estimate: 13586
{"chain_id":"cosmoshub-3","account_number":"","sequence":"","fee":{"amount":[],"gas":"13586"},"msgs":[{"type":"cosmos-sdk/MsgUndelegate","value":{"delegator_address":"cosmos1g*","validator_address":"cosmosvaloper1kn3wugetjuy4zetlq6wadchfhvu3x740ae6z6x","amount":{"denom":"stake","amount":"154189589"}}}],"memo":""}

confirm transaction before signing and broadcasting [y/N]: y
Password to sign with 'at01':
height: 0
txhash: *
code: 14
data: ""
rawlog: '{"codespace":"sdk","code":14,"message":"insufficient fees; got: "" required:
"340uatom""}'
logs: []
info: ""
gaswanted: 0
gasused: 0
codespace: ""
tx: null
timestamp: ""
events: []

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dev-lc** [comment]
I found out how to solve this:
It's necessary to add **--fees** flag:
`$ gaiacli tx staking unbond cosmosvaloper1kn3wugetjuy4zetlq6wadchfhvu3x740ae6z6x 154189589stake --from at01 --gas auto --fees 750uatom
gas estimate: 29704
{"chain_id":"cosmoshub-3","account_number":"*","sequence":"*","fee":{"amount":[{"denom":"uatom","amount":"750"}],"gas":"29704"},"msgs":[{"type":"cosmos-sdk/MsgUndelegate","value":{"delegator_address":"cosmos1*","validator_address":"cosmosvaloper1kn3wugetjuy4zetlq6wadchfhvu3x740ae6z6x","amount":{"denom":"stake","amount":"154189589"}}}],"memo":""}

confirm transaction before signing and broadcasting [y/N]: y
Password to sign with 'at01':
height: 0
txhash: *
code: 0
data: ""
rawlog: '[{"msg_index":0,"success":true,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"begin_unbonding"}]}]}]'
logs:
- msgindex: 0
  success: true
  log: ""
  events:
  - type: message
    attributes:
    - key: action
      value: begin_unbonding
info: ""
gaswanted: 0
gasused: 0
codespace: ""
tx: null
timestamp: ""
events: []`


**But it's not straightforward. There is no explicit explanation** in documentation as well as in the _Example_ section of --help flag:
`gaiacli tx staking unbond --help
Unbond an amount of bonded shares from a validator.

Example:
$ gaiacli tx staking unbond cosmosvaloper1gghjut3ccd8ay0zduzj64hwre2fxs9ldmqhffj 100stake --from mykey

Usage:
  gaiacli tx staking unbond [validator-addr] [amount] [flags]

Flags:
  -a, --account-number uint     The account number of the signing account (offline mode only)
  -b, --broadcast-mode string   Transaction broadcasting mode (sync|async|block) (default "sync")
      --dry-run                 ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it
      --fees string             Fees to pay along with transaction; eg: 10uatom
      --from string             Name or address of private key with which to sign
      --gas string              gas limit to set per-transaction; set to "auto" to calculate required gas automatically (default 200000) (default "200000")
      --gas-adjustment float    adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
      --gas-prices string       Gas prices to determine the transaction fee (e.g. 10uatom)`

**Comment by alexanderbez** [comment]
Hey @dev-lc, what exactly is the issue? Your first `tx staking unbond` failed because you didn't provide enough gas. Your second one failed because you didn't provide enough fees _to the node your broadcasted the tx to_. 

What exactly are you stating is the issue and what proposal do you have in mind? Note, `--fees` is not required. It all depends on the node your broadcast the tx to.

**Comment by dev-lc** [comment]
Thank you for your reply. I understood you. 
I also had asked this question in the Riot chat. And no one gave any suggestion in this situation. Thus, it's not fully comprehensive of how to handle such cases. 
Perhaps my proposal is to add more examples with descriptions to the --help section of gaiacli.

**Comment by tac0turtle** [comment]
hey @dev-lc the riot is not used anymore, I would suggest joining the discord, here is a link: https://discord.gg/YHyUWbX

Maybe more examples in the docs is needed.

**Comment by tac0turtle** [comment]
closing due to staleness
