### ISSUE TITLE
Release Binaries

### ISSUE THREAD

**Issue by zmanian** [cosmos/gaia#36]
We should release binaries when we tag versions so users don't need the go toolchain.

@melekes suggests using https://goreleaser.com/

**Comment by zmanian** [comment]
@Greg-Szabo How do you feel about goreleaser?

**Comment by melekes** [comment]
https://gist.github.com/melekes/4ffdc7551b3efab58c836c8e4462d969

**Comment by adrianbrink** [comment]
Let's follow the Tor process as explained by Zaki during the retreat.

**Comment by zramsay** [comment]
jenkins FTW (coming soon)

**Comment by zramsay** [comment]
will be handled in SDK repo
