### ISSUE TITLE
Unknown image

### ISSUE THREAD

**Issue by wimel** [cosmos/gaia#364]
## Summary of Bug
On [Docs/translations](https://github.com/cosmos/gaia/tree/master/docs/translations) there seems to be a picture of a validator from Castlenode

## Steps to Reproduce
Trying to translate the docu from [gaia](https://github.com/cosmos/gaia) I found an image that I don't think should be there, or yes I don't know 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
yes you are correct we do need to remove this. would you like to open a pr with this removal

**Comment by wimel** [comment]
> yes you are correct we do need to remove this. would you like to open a pr with this removal

Yes sure!! currently I'm translating some docs to ES_es, so I can do it, thanks

**Comment by wimel** [comment]
ok thanks @marbar3778, fixed in [PR#368](https://github.com/cosmos/gaia/pull/368)
