### ISSUE TITLE
Missed version 

### ISSUE THREAD

**Issue by wimel** [cosmos/gaia#365]
## Summary

The commit for the version used in [documentation](https://github.com/cosmos/gaia/blob/master/docs/README.md#version) doesn't appear

## Problem Definition

I think to create new issues or features is also useful to have the version of doc used. 
The benefit will be to be able to exclude problems if they are using an older version.
I think there is no disadvantage in adding the latest commit

## Proposal
Add the latest commit on docs, I think the latest commit is [7eb955a805f9031a4ff3a39c1212a2fcdc6e39aa](https://github.com/cosmos/gaia/commit/7eb955a805f9031a4ff3a39c1212a2fcdc6e39aa)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
@fadeev do you think this is possible?

**Comment by fadeev** [comment]
Yes, I think I can add a version number to the website. So, if the docs were built from `master`, it will show `master` in the footer, or somewhere. We can remove "This documentation is built from the following commit" from the readme, because version will be added dynamically.

**Comment by tac0turtle** [comment]
we use to have the commit near the footer, it seems the commit may be better than having it say master. 

Do docs get deployed every time something is merged to master even if it doesn't touch docs?

**Comment by fadeev** [comment]
For commit hash we would have to modify deploy script, but otherwise should be doable. Yes, for every push to master.
