### ISSUE TITLE
Change the max validators on docs

### ISSUE THREAD

**Issue by wimel** [cosmos/gaia#367]
## Summary

On the documentation to [upgrade to Validator node](https://github.com/cosmos/gaia/blob/master/docs/gaia-tutorials/join-mainnet.md#upgrade-to-validator-node) appear `100` validators, but with the recent upgrade we have `125` validators.

## Problem Definition
We need this feature because is the correct number of validators.

## Proposal
On [Upgrade to validator Node](https://github.com/cosmos/gaia/blob/master/docs/gaia-tutorials/join-mainnet.md#upgrade-to-validator-node) change the value of `100` validators to `125` validators.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
This says that it's 125, not 120.  I'd thought it was 125, as well.  Is it 125 or 120?

:)

https://blog.cosmos.network/cosmos-development-update-july-2019-8df2ade5ba0a

Happy to make the change when clear on the number of validators.

**Comment by wimel** [comment]
> This says that it's 125, not 120. I'd thought it was 125, as well. Is it 125 or 120?
> 
> :)
> 
> https://blog.cosmos.network/cosmos-development-update-july-2019-8df2ade5ba0a
> 
> Happy to make the change when clear on the number of validators.

Yes, the correct number is `125`, you can check this on any block explorer like [Bigdipper](https://cosmos.bigdipper.live/validators?sort=votingPower&dir=-1) or [Mintscan](https://www.mintscan.io/validators) _(for example)_ under `Active validators` 

On the link you shared describes the change from _(older)_ `100` validators to `125` validators that is the new value from max validators.
This value it was modified on [proposal 10](https://cosmos.bigdipper.live/proposals/10).

_Thank you for reporting my mistake!_
