### ISSUE TITLE
rpc block_by_hash is not working

### ISSUE THREAD

**Issue by mesment** [cosmos/gaia#373]
## Summary of Bug

rpc block_by_hash is not working

## Version
git tag v2.0.8 

cimmit hash:  e6f3efff002f74741b05233fe1f05aa893611d53
gaiad version
2.0.8
gaiacli version
2.0.8

## Steps to Reproduce
use curl to get a blockinfo by block hash

for example:
input:
curl http://127.0.0.1:26657/block_by_hash?hash=0x86A9E030CD719A2CE174EDBA484621201D9BC8AE27B850874A12BEE99C9AAB8B

response:
 404 page not found
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
`block_by_hash/` isn't an RPC route, not sure where you read that.
