### ISSUE TITLE
evidenceParams.MaxAgeNumBlocks must be greater than 0. Got 0

### ISSUE THREAD

**Issue by luoxiandong** [cosmos/gaia#376]
versison
`name: gaia
server_name: gaiad
client_name: gaiacli
version: 0.0.0-181-g20a071c
commit: 20a071cf84b965d0892c5a216b32c44963a83173
build_tags: netgo,ledger
go: go version go1.14.2 linux/amd64`

commond follows:
`download gaia and make install`
`gaiad init abc`
`curl https://raw.githubusercontent.com/cosmos/launch/master/genesis.json > $HOME/.gaiad/config/genesis.json`
`gaiad start`

display errors:
ERROR: Error reading GenesisDoc at /root/.gaiad/config/genesis.json: evidenceParams.MaxAgeNumBlocks must be greater than 0. Got 0

what happens?

**Comment by alexanderbez** [comment]
Cosmos hub mainnet works with Gaia v2.0.x
