### ISSUE TITLE
Transfer through Rest Server

### ISSUE THREAD

**Issue by gblue1223** [cosmos/gaia#377]
## Summary of Bug
I’m trying to send a coin through the gaiacli rest server
But the signatures is null and the transfer doesn’t make.
Should I implement the signature even for gaiacli?
I asked this a week ago in Cosmos Forum but no answer.

sent
```
{
   "base_req":{
      "from":"xxx",
      "password":"xxx",
      "memo":"Test",
      "chain_id":"pcoin-chain",
      "account_number":"0",
      "sequence":"2",
      "gas":"100",
      "gas_adjustment":"1.2",
      "fees":[
         {
            "denom":"mpcn",
            "amount":"1"
         }
      ],
      "simulate":false
   },
   "amount":[
      {
         "denom":"mpcn",
         "amount":"1"
      }
   ]
}
```
recv
```
{
   "type":"cosmos-sdk/StdTx",
   "value":{
      "msg":[
         {
            "type":"cosmos-sdk/MsgSend",
            "value":{
               "from_address":"xxx",
               "to_address":"xxx",
               "amount":[
                  {
                     "denom":"mpcn",
                     "amount":"1"
                  }
               ]
            }
         }
      ],
      "fee":{
         "amount":[
            {
               "denom":"mpcn",
               "amount":"1"
            }
         ],
         "gas":"100"
      },
      "signatures":null,
      "memo":"Test"
   }
}
```
## Version
2.0.8

## Steps to Reproduce
curl -X POST http://localhost:1317/bank/accounts/xxx/transfers \
    -d '{   "base_req": {     "from": "xxx",    "memo": "Test",     "chain_id": "pcoin-chain",     "account_number": "0",     "sequence": "2",     "gas": "100",     "gas_adjustment": "1.2",     "fees": [       {         "denom": "mpcn",         "amount": "101"       }     ],     "simulate": false   },   "amount": [     {       "denom": "mpcn",       "amount": "1"     }   ] }'

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
You cannot sign via the REST service for security reasons. You must:

1. Generate the tx (e.g. `/bank/accounts/xxx/transfers`
2. Sign **offline**
3. Broadcast (i.e. `/txs/broadcast`)
