### ISSUE TITLE
Easier Mainnet Nodes

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#378]
*Goal*:  Reduce setting up a mainnet node to the fewest number of steps possible without breaking any existing practices

*Context*:

https://twitter.com/gadikian/status/1254828427728674817?s=20

This week I put up a server at hetzner.de to run a decentralized VPN node, because hetzner has cheap unlimited bandwidth and the connection is really excellent.  I was left with a ton of excess storage, RAM, and CPU capacity.  

I decided that I'd run nodes for all of the chains that I was interested in running nodes for, and got an opportunity to compare the setup process between blockchain ecosystems.  

For Cosmos, what I found was that the default path of "I just want to run a mainnet node" was a bit tougher than it should be and the docs/links are possibly a little dated.  Some of the seeds referenced on the launch repo are no longer up, for example. 

So once I'm done typing up this issue, I'm going to make a PR that attempts to solve this by: 

* provide a file called `seeds`
* provide the user with some bash in the "quick start" process that ensures that they do not need to move the seeds into config.toml manually
* Putting exact directions in the quick start, which result in a functioning node when followed exactly and do not require much interpretation, editing of config files, or thought to get a fully functioning mainnet node

**Comment by faddat** [comment]
Ideally, we would have a hundred seeds, I think.  I've been to the block explorers linked to in the docs, and also wasn't able to get a "list of sentries" more or less.  

I was able to get ten like:

curl -X GET "http://localhost:26657/net_info" -H "accept: application/json"

ba3bacc714817218562f743178228f23678b2873@5.83.160.108:26656
1e63e84945837b026f596ed8ae68708783d04ad4@51.75.145.123:26656
d2d452e7c9c43fa5ef017552688de60a5c0053ee@34.245.217.163:26656
dd36969b56c740bb40bb8badd4d4c6facc35dc24@206.189.115.41
a0aca8fb801c69653a290bd44872e8457f8b0982@47.99.180.54
27f8dd3bdbecbef7192291083706c156e523d8e0@3.122.248.21
aee0df1a660f301d456a0c2f805b372f7341e8ec@63.35.230.143:26656
7d1f660b361d6286715c098a3a171e554e9642bb@34.254.205.37
fa105c2291ac4aa452552fa4835266300a8209e1@88.198.41.62
bd410d4564f7e0dd9a0eb16a64c337a059e11b80@47.103.35.130

....except I did just realize that putting them right into config.toml wouldn't be the right path.  I'm going to use a file called `seeds` that's inserted into config.toml with a little bash that we provide to the user.

**Comment by faddat** [comment]
So I:

https://github.com/faddat/gaia/tree/patch-1

I prefer the repo the way I made it look; think it gives the user more information about what Gaia actually **is**.  The image didn't give me much info or help define Gaia.  Might be interesting to replace it with an image that shows Gaia working as a hub with zones.  

I think that it's better to give full directions on Readme.md that result in the desired outcome for 90% of users: a running full node on Mac/Linux. 

The bash probably still needs improvement, or maybe the whole handling of seed insertion needs improvement.

**Comment by tac0turtle** [comment]
We have been having some discussions on how to better this experience. I will start working on some of them soon. In the meantime would you like to open a pr with your changes and we can review them if you'd like. I gave it a quick look over and it does look better

**Comment by faddat** [comment]
I'll put the PR in now
