### ISSUE TITLE
gaiacli status: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by novy4** [cosmos/gaia#380]
## Summary of Bug
When I run gaiacli status on a ubuntu server I get this error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x87df65]

goroutine 1 [running]:
github.com/spf13/viper.pflagValue.HasChanged(0x0, 0xc0000a3650)
	github.com/spf13/viper@v1.6.3/flags.go:41 +0x5
github.com/spf13/viper.(*Viper).find(0xc0000ca900, 0x122a307, 0xf, 0x1, 0x0, 0x0)
	github.com/spf13/viper@v1.6.3/viper.go:1075 +0x13ab
github.com/spf13/viper.(*Viper).Get(0xc0000ca900, 0x122a307, 0xf, 0x0, 0x0)
	github.com/spf13/viper@v1.6.3/viper.go:728 +0x81
github.com/spf13/viper.(*Viper).GetString(0xc0000ca900, 0x122a307, 0xf, 0xc000c55000, 0x13)
	github.com/spf13/viper@v1.6.3/viper.go:793 +0x3f
github.com/spf13/viper.GetString(...)
	github.com/spf13/viper@v1.6.3/viper.go:791
github.com/cosmos/cosmos-sdk/client/context.NewCLIContextWithInputAndFrom(0x15a6c40, 0xc0000ba000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20200423152229-f1fdde5d1b18/client/context/context.go:64 +0xe8
github.com/cosmos/cosmos-sdk/client/context.NewCLIContextWithFrom(...)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20200423152229-f1fdde5d1b18/client/context/context.go:137
github.com/cosmos/cosmos-sdk/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20200423152229-f1fdde5d1b18/client/context/context.go:142 +0xc3
github.com/cosmos/cosmos-sdk/client/rpc.printNodeStatus(0xc000c862c0, 0x20d9f58, 0x0, 0x0, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.34.4-0.20200423152229-f1fdde5d1b18/client/rpc/status.go:47 +0x7e
github.com/spf13/cobra.(*Command).execute(0xc000c862c0, 0x20d9f58, 0x0, 0x0, 0xc000c862c0, 0x20d9f58)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c86000, 0x8ad300, 0xc000c86000, 0x121e9f3)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000c86000, 0x142ad78, 0x2, 0xc000c55040)
	github.com/tendermint/tendermint@v0.33.4/libs/cli/setup.go:89 +0x3c
main.main()
	github.com/cosmos/gaia/cmd/gaiacli/main.go:84 +0x583

## Version
gaiacli version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 0.0.0-180-g50be36d
commit: 50be36de941b9410a4b06ec9ce4288b1529c4bd4
build_tags: netgo,ledger
go: go version go1.14 linux/amd64

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

go version
go version go1.14 linux/amd64

## Steps to Reproduce

gaiacli status

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Already fixed on SDK `master` and Gaia has been updated to use the latest commit 👍
