### ISSUE TITLE
Fix v2 module path to comply with Go module versioning rules

### ISSUE THREAD

**Issue by leoluk** [cosmos/gaia#389]
The module path in go.mod should be `github.com/cosmos/gaia/v2`. Right now, it's not possible to depend on the v2 tags:

```
$ go get github.com/cosmos/gaia/v2@v2.0.9
go get github.com/cosmos/gaia/v2@v2.0.9: github.com/cosmos/gaia@v2.0.9: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

Similar to https://github.com/cosmos/gaia/issues/232

**Comment by alexanderbez** [comment]
Thanks for pointing this out! Indeed we have to update the packages in Gaia to be semver compatible.

**Comment by shahankhatch** [comment]
v3.0.0 is about to be released under semver policy.

**Comment by tac0turtle** [comment]
Not sure this is solved. This is specific to go mod not semvar.

**Comment by leoluk** [comment]
The import path wasn't changed in #456, so it doesn't seem to be solved.

It needs to be `github.com/cosmos/gaia/v3`.

**Comment by shahankhatch** [comment]
Please see `main` which will be used to tag v3.0.0 v soon.

**Comment by shahankhatch** [comment]
https://github.com/cosmos/gaia/blob/16b31b0193c622039d35d22137d6b7cdcf304c06/go.mod#L1

**Comment by tac0turtle** [comment]
Oh interesting, my bad missed that.
