### ISSUE TITLE
Stable tagging for docker images

### ISSUE THREAD

**Issue by sabau** [cosmos/gaia#4]
**Proposal** 
We may want to introduce stable tagging for our docker images once we get stable enough, to ease clients developer with updates if they choose to receive them:
- Every breaking change means major version update
- minor add features or fixes
- patch increase are mainly bigfix

Something similar to:
![StableTagging](https://user-images.githubusercontent.com/1656471/57980713-0526ef00-7a2f-11e9-8808-34660e5b415f.gif)

### Current Situation
**Given**
we push a tag as new version i.e. `0.34.3`
**Then**
We push its exact tag on Docker Hub as `tendermint/gaia:0.34.4` and nothing else

### Desired Outcome
**Given**
we push a tag as new version i.e. `0.34.3`
**Then**
1. We push its exact tag on Docker Hub as `tendermint/gaia:0.34.4`
2. We update or add its minor tag reference `tendermint/gaia:0.34` to the latest available for this minor
3. We update or add its major tag reference `tendermint/gaia:0` to the latest available for this major

We don't need to check if the tags already exists for step `2` and `3` as if they exists they will be overridden, otherwise created.

Ideally this new tagging system should occur (it can be beneficial only) when we are mature enough to stop adding breaking changes inside minor / patches versions, so the image can be used by clients without the need for them to change their implementations at all, at most they can add interfaces to new features in some minor release - we probably need team agreement here, this is my typical view of projects

**Comment by alexanderbez** [comment]
What is the exact proposal here @sabau? To finally move to a version 1 release of Gaia? Otherwise, how is this different than what we're currently doing?

**Comment by sabau** [comment]
Nice question @alexanderbez I'll try to write it more explicitely & write in spec oriented way the description

Currently we tag only `:0.34.4` the idea is to let the developers of clients choose `:0.34` or simply `:0` tags where:
- `:0.34.4` is a specific patch, 
- `:0.34` can be updated and have bugfixes or some new features and update in it
- `:0` will have all new features and bugfixes of this major version, but no breaking changes (and that's why I was thinking is too early now, we still introduce breaking changes from time to time)

In a similar manner as you describe packages by allowing wildcards in the version descriptor, this (as far as I'm aware) is the way to allow the same idea in dockers

**Comment by sabau** [comment]
Ideally I would move to version `1` once we are stable enough to not introduce breaking changes for a big while, until version `2`

**Comment by alexanderbez** [comment]
Hmmmm, maybe this makes sense for the SDK, but I expect gaia to continuously have breaking changes through means of governance proposals that signal desired changes in the state machine.

**Comment by sabau** [comment]
Shouldn't we reflect those with major releases?
Agree, also on the SDK this will make sense, but on the other side, the SDK repo will still produce any docker image?

**Comment by alexanderbez** [comment]
They can be major changes yeah. There will be/is no docker image on the SDK 👍
