### ISSUE TITLE
App Hash changes every block

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#41]
For some unknown reason, the app hash changes every block.

I've pinned it down to the LoadBonds call in gaia's tickFn: https://github.com/cosmos/gaia/blob/master/cmd/gaia/main.go#L41

Turns out calling Get on the prefixedStore with the right prefix causes the tree hash to change. 

I think it has to do with using a MemKVCache, where we cache items even if they weren't found, and thus later commit them, ie. https://github.com/cosmos/cosmos-sdk/blob/master/state/kvcache.go#L36

There's too many layers of stores and caches for me to really know what's going on though :(

**Comment by ethanfrey** [comment]
Haha... this used to work as set(nil) would cause a delete. Now it write nil? (Refactor of iavl).
I thought that @cloudhead wanted to make this case panic? That would have caught the error sooner...

Anyway, I will write a test and fix it.

**Comment by cloudhead** [comment]
Doing a `Set(k, nil)` currently panic, is that what you mean?

**Comment by ethanfrey** [comment]
Does it? Just saw that I don't call that directly, but if I did, it would panic, right?

**Comment by ethanfrey** [comment]
Reproduced this with a test, when you read real data back. Working on a fix `cosmos-sdk:bugfix/stable-app-hash`

**Comment by ethanfrey** [comment]
Proposed fix: https://github.com/cosmos/cosmos-sdk/pull/271

**Comment by adrianbrink** [comment]
@rigelrozanski Is this fixed?

**Comment by rigelrozanski** [comment]
yes in feature/delegation
