### ISSUE TITLE
Gaia master should not be updated to Cosmos-SDK master

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/gaia#425]
## Summary

Gaia represents the software used by the Cosmos Hub. Its master branch should not look at the master branch of the Cosmos-SDK as this is unstable software. The reason this is being done is when we moved Gaia out of the Cosmos-SDK we removed the cmd's from the Cosmos-SDK, so we used Gaia as part of the SDK testing suite. We have now brought the cmd's back to the SDK and do not have a need for Gaia to look at master. 

## Problem Definition

Gaia master branch is looking at the latest Cosmos-SDK master branch. 

## Proposal

Gaia is pinned to a release of the Cosmos-SDK (0.37.x), it's master branch gets minor updates and can be used on testnets for early-stage testing before being deployed to the hub. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I approve of this. Very easy to do this. Have the latest 2.x.x release of Gaia now be `main`.

**Comment by tac0turtle** [comment]
will let this sit for a couple of days before I make the changes

**Comment by webmaster128** [comment]
When this is implemented (which makes perfect sense as far as I can see), where would a version of gaia be maintained that contains the latest updates to Cosmos SDK master? Would someone work on this at all? We'd need somthing like a gaia nightly to start testing stargate clients (https://github.com/CosmWasm/cosmjs/issues/242).

Thank you!

**Comment by tac0turtle** [comment]
> When this is implemented (which makes perfect sense as far as I can see), where would a version of gaia be maintained that contains the latest updates to Cosmos SDK master? Would someone work on this at all? We'd need somthing like a gaia nightly to start testing stargate clients ([CosmWasm/cosmjs#242](https://github.com/CosmWasm/cosmjs/issues/242)).
> 
> Thank you!

could [simd & simcli](https://github.com/cosmos/cosmos-sdk/tree/master/simapp/cmd) be used from the sdk. WE would just need to add a make target for installing instead of building.

**Comment by webmaster128** [comment]
> could [simd & simcli](https://github.com/cosmos/cosmos-sdk/tree/master/simapp/cmd) be used from the sdk. WE would just need to add a make target for installing instead of building.

Yes, I think that would do the trick. Would it be possible to dockerize simd/simcli like https://hub.docker.com/r/tendermint/gaia (I can build and upload locally if needed)? It would need to run as a testing chain on dev machines and CIs without a Go build environment.

**Comment by tac0turtle** [comment]
> Yes, I think that would do the trick. Would it be possible to dockerize simd/simcli like [hub.docker.com/r/tendermint/gaia](https://hub.docker.com/r/tendermint/gaia) (I can build and upload locally if needed)? It would need to run as a testing chain on dev machines and CIs without a Go build environment.

yes, ill take care of that in the coming days.

**Comment by alessio** [comment]
I agree with this. This burden is becoming unbearable

**Comment by jgimeno** [comment]
This is music to my ears! I totally agree!

**Comment by tac0turtle** [comment]
default branch is now main and has been reverted to latest release. I will begin migrating things from master that need to be here
