### ISSUE TITLE
Stop syncing blocks occasionally

### ISSUE THREAD

**Issue by atoken-ops** [cosmos/gaia#426]
This often happens。how fix？

2020/06/22 07:27:01 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 5ms
2020/06/22 07:27:01 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 10ms
2020/06/22 07:27:01 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 20ms
2020/06/22 07:27:01 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 40ms
2020/06/22 07:27:01 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 80ms
2020/06/22 07:27:01 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 160ms
2020/06/22 07:27:02 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 320ms
2020/06/22 07:27:02 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 640ms
2020/06/22 07:27:03 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 1s
2020/06/22 07:27:04 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 1s
2020/06/22 07:27:05 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 1s
E[2020-06-22|07:27:05.891] Failed to save AddrBook to file              module=p2p book=/opt/cosmos/config/addrbook.json file=/opt/cosmos/config/
addrbook.json err="open /opt/cosmos/config/write-file-atomic-03947057347640974596: too many open files"
2020/06/22 07:27:06 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 1s
2020/06/22 07:27:07 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 1s
2020/06/22 07:27:08 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 5ms
2020/06/22 07:27:08 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 10ms
2020/06/22 07:27:08 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 20ms
2020/06/22 07:27:08 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 40ms
2020/06/22 07:27:08 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 80ms
2020/06/22 07:27:08 http: Accept error: accept tcp [::]:26657: accept4: too many open files; retrying in 160ms

**Comment by tac0turtle** [comment]
it seems you need to bump the amount of open files allowed on your machine. you can do this by running `ulimit -n 4096`

**Comment by atoken-ops** [comment]
already 65535

**Comment by tac0turtle** [comment]
how many peers do you have? did you adjust the default setting?

**Comment by atoken-ops** [comment]
how get that?
start with

gaiad --home /opt/cosmos/ start

**Comment by okwme** [comment]
i'm getting this error a lot. it's been increasing until now it comes instantly when i start gaiad trying to sync.

my peer list is as follows:
```
seeds = "bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656, 366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656, cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656, d72b3011ed46d783e369fdf8ae2055b9$
```

**Comment by okwme** [comment]
hmm, i had a larger number than `ulimit -n 4096` prior to this, but changing it to `ulimit -n 4096` seems to have worked
