### ISSUE TITLE
require mod missing in cosmos-sdk

### ISSUE THREAD

**Issue by viyang** [cosmos/gaia#43]
## Summary of Bug

make build failure due to missing require in go.mod
github.com/cosmos/cosmos-sdk v0.28.2-0.20190606154315-d6cb24e849a3

verified in cosmos-sdk, is has no tag v0.28.2

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks @viyang. v0.28.2 isn't a version. We currently specify the SDK version used in Gaia by a direct hash (until we're ready for the next major upgrade). The go module system automatically populates v0.28.2.
