### ISSUE TITLE
Validator Lags Behind Network

### ISSUE THREAD

**Issue by pink-flamingo** [cosmos/gaia#444]
## Summary of Bug

I have a validator nodes deployed behind 3 sentry nodes, as described here: https://forum.cosmos.network/t/sentry-node-architecture-overview/454
When I try to upgrade it from Gaia v2.0.3 to Gaia v2.0.8 or above I'm experiencing sync issues that prevent it from signing blocks. Sync works but it's delayed by about 10 seconds, so the validator can never sign the most recent block. When the validator is reverted to Gaia v2.0.3 sync works perfectly again.

## Version

I tried with both v2.0.8 and v2.0.11

## Steps to Reproduce

Setup a validator as described in https://forum.cosmos.network/t/sentry-node-architecture-overview/454 and try to sign blocks.
It doesn't reproduce on Testnet.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
are there any issues that surface when logging for errors?

**Comment by tac0turtle** [comment]
ref https://github.com/tendermint/tendermint/issues/3767. this possible may overlap with this issue

**Comment by pink-flamingo** [comment]
There's not much to log: the validator seems to be syncing correctly but when I look in another Cosmos node I see that the blocks that the validator is seeing are behind the other node.

**Comment by ebuchman** [comment]
Believe this may be due to https://github.com/tendermint/tendermint/issues/5112#issuecomment-661704414 cc @melekes

**Comment by tac0turtle** [comment]
@pink-flamingo are you using a remote signer?

**Comment by pink-flamingo** [comment]
Yes I am.

**Comment by tac0turtle** [comment]
There will be a release coming out shortly that will fix this issue. thank you for being patient.

**Comment by tac0turtle** [comment]
please try: https://github.com/cosmos/gaia/releases/tag/v2.0.12, this will contain the fix

**Comment by pink-flamingo** [comment]
@marbar3778 it looks like both v2.0.12 and v2.0.11 point to the same commit d00db033d861c4f59e07038e61bcaf39274ff6da

**Comment by tac0turtle** [comment]
there was a minor issue in the release process. I will need to release 2.0.13 to fix it.

**Comment by pink-flamingo** [comment]
I upgraded to Gaia v2.0.13 and the issue still happens. The fix didn't work.

**Comment by tac0turtle** [comment]
hmm then you are experiencing a different issue then what we observed. Could you provide more information.

**Comment by pink-flamingo** [comment]
I'm running a validator with a remote signer. The validator is using Gaia v2.0.3.
When I upgrade the validator to Gaia v2.0.8 or above while keeping the ~/.gaiad directory the same I can't sync the validator, it keeps lagging behind.
When I revert to v2.0.3 everything works well again, still using the same ~/.gaiad directory.

**Comment by pink-flamingo** [comment]
@marbar3778 is there any more info I can provide that would help? Thanks!

**Comment by pink-flamingo** [comment]
@marbar3778 hi, what can we do to promote this?

**Comment by pink-flamingo** [comment]
@melekes once https://github.com/tendermint/tendermint/issues/5550 is solved can a new version of Gaia be tagged that contains that fix? Thanks

**Comment by tessr** [comment]
Hey @pink-flamingo - sorry for all the silence here. We are about to cut a few new releases to fix the issue you noticed was related (#5550). Those releases should go out tomorrow, and we'll see about getting Gaia updated as well.

**Comment by pink-flamingo** [comment]
Hey @tessr - any update on releasing a version of Gaia with the fix?

**Comment by pink-flamingo** [comment]
Hey @tessr , sorry to bother you.
Do you know when would this fix be released? Thanks again!

**Comment by tessr** [comment]
Hey @pink-flamingo, no problem. Let me talk to the folks who actually work on Gaia about this - my hunch is that we should make you a tag on Gaia with an updated Tendermint and SDK version, and then you can try it out and confirm that it actually fixes the problem you're seeing. We'll have an update for you later today.

**Comment by tac0turtle** [comment]
@pink-flamingo we released https://github.com/cosmos/gaia/releases/tag/v2.0.14 with the updated Tendermint changes. Could you test your configuration with this release and let us know if it's fixed.

**Comment by pink-flamingo** [comment]
I tested it and it looks like it's working well! Thanks for your help!
