### ISSUE TITLE
Doc files went missing during branch migration

### ISSUE THREAD

**Issue by lovincyrus** [cosmos/gaia#446]
Doc files (e.g. `docs/.vuepress`, etc) went missing 🕵🏻‍♂️ during the migration from `master` → `main` https://github.com/cosmos/gaia/pull/443

`master`
![image](https://user-images.githubusercontent.com/1021101/88446580-15c7b780-cde0-11ea-90de-c439dcf350f0.png)

`main`
![image](https://user-images.githubusercontent.com/1021101/88446596-43146580-cde0-11ea-84b4-a432b9a01a53.png)

Related to https://github.com/cosmos/cosmos-sdk/pull/6846, so we can add a Stargate banner in the docs.

**Comment by shahankhatch** [comment]
Looks to have copied into `main` at some point.
