### ISSUE TITLE
Run gaiad as a full node sync error

### ISSUE THREAD

**Issue by viyang** [cosmos/gaia#45]
## Summary of Bug
I run a gaiad connect to main net. but sync failed at height 1.

the output :

I[2019-06-14|11:04:21.276] Starting ABCI with Tendermint                module=main 
E[2019-06-14|11:04:22.895] Connection failed @ recvRoutine (reading byte) module=p2p peer=3028c6ee9be21f0d34be3e97a59b093e15ec0658@91.205.173.168:26656 conn=MConn{91.205.173.168:26656} err=EOF
E[2019-06-14|11:04:22.896] Stopping peer for error                      module=p2p peer="Peer{MConn{91.205.173.168:26656} 3028c6ee9be21f0d34be3e97a59b093e15ec0658 out}" err=EOF
E[2019-06-14|11:04:53.618] Connection failed @ recvRoutine (reading byte) module=p2p peer=6be0856f6365559fdc2e9e97a07d609f754632b0@35.238.158.173:26656 conn=MConn{35.238.158.173:26656} err=EOF
E[2019-06-14|11:04:53.618] Stopping peer for error                      module=p2p peer="Peer{MConn{35.238.158.173:26656} 6be0856f6365559fdc2e9e97a07d609f754632b0 out}" err=EOF
E[2019-06-14|11:05:22.895] Dialing failed                               module=pex addr=2e7c678aaad8602d3bacea26a68d180bd28892a4@[2a05:d014:60:7301:4c44:7c2c:1443:e6e4]:26656 err="dial tcp [2a05:d014:60:7301:4c44:7c2c:1443:e6e4]:26656: connect: cannot assign requested address" attempts=0
E[2019-06-14|11:05:22.936] Dialing failed                               module=pex addr=3c063f06119fc00e72a4493810014e0dab231d6f@49.247.215.16:44996 err="dial tcp 49.247.215.16:44996: connect: connection refused" attempts=0
E[2019-06-14|11:05:23.162] Dialing failed                               module=pex addr=2d9021d3b6b2fccd5be83c06a4f9339658f975ac@144.76.101.254:26656 err="dial tcp 144.76.101.254:26656: connect: connection refused" attempts=0
E[2019-06-14|11:05:23.175] Dialing failed                               module=pex addr=89d7049746ce2ea0b12a229b10666da011f4f371@95.179.164.203:26656 err="dial tcp 95.179.164.203:26656: connect: no route to host" attempts=0
E[2019-06-14|11:05:23.895] Dialing failed                               module=pex addr=ef3e5c18177c43239be9e7dc4102f5b16dc927c8@47.90.29.31:26656 err="dial tcp 47.90.29.31:26656: i/o timeout" attempts=0
E[2019-06-14|11:05:23.895] Dialing failed                               module=pex addr=f784d560445808dc9ec221d2b6a0df5830d21e26@153.156.40.19:54286 err="dial tcp 153.156.40.19:54286: i/o timeout" attempts=0
E[2019-06-14|11:05:23.895] Dialing failed                               module=pex addr=ac2d24deab592fb1a92b2d041c03c6ead2e913e6@118.243.115.211:60928 err="dial tcp 118.243.115.211:60928: i/o timeout" attempts=0
E[2019-06-14|11:05:23.895] Dialing failed                               module=pex addr=8922d8e8c87ee6d4745de5685ccf766819d299af@35.246.242.230:26656 err="dial tcp 35.246.242.230:26656: i/o timeout" attempts=0
E[2019-06-14|11:05:23.895] Dialing failed                               module=pex addr=4b8038151c550ca85f202207774541d141249755@85.255.11.49:26656 err="dial tcp 85.255.11.49:26656: i/o timeout" attempts=0
E[2019-06-14|11:05:23.895] Dialing failed                               module=pex addr=00523c0e62d3134126ebcec686306da3f64eb95a@54.165.75.6:26252 err="dial tcp 54.165.75.6:26252: i/o timeout" attempts=0
E[2019-06-14|11:05:52.895] Dialing failed                               module=pex addr=4b8e925115ece77169bbfbaa5f41bae7df33ad6e@[2a05:d014:60:7301:b541:3611:1ed2:47fd]:26656 err="dial tcp [2a05:d014:60:7301:b541:3611:1ed2:47fd]:26656: connect: cannot assign requested address" attempts=0
E[2019-06-14|11:05:53.122] Dialing failed                               module=pex addr=717a165ee4e6c29b0d14bd85e1231f6b52587864@77.87.108.21:26656 err="dial tcp 77.87.108.21:26656: connect: connection refused" attempts=0
E[2019-06-14|11:05:53.546] Connection failed @ recvRoutine (reading byte) module=p2p peer=3d5f2927b095c1da6021a2f25179cc72de255638@52.56.253.229:26656 conn=MConn{52.56.253.229:26656} err=EOF
E[2019-06-14|11:05:53.546] Stopping peer for error                      module=p2p peer="Peer{MConn{52.56.253.229:26656} 3d5f2927b095c1da6021a2f25179cc72de255638 out}" err=EOF
E[2019-06-14|11:05:53.895] Dialing failed                               module=pex addr=1f2234181968fb4b934c4a7bb432776bdd7fdd8e@46.183.115.231:26656 err="dial tcp 46.183.115.231:26656: i/o timeout" attempts=0
E[2019-06-14|11:05:53.895] Dialing failed                               module=pex addr=010cf5e960953f3d181c4eb0f1c2d8f03f804c3a@151.236.217.169:26656 err="dial tcp 151.236.217.169:26656: i/o timeout" attempts=0
E[2019-06-14|11:05:53.895] Dialing failed                               module=pex addr=3451916af0d569896b55452e23c0a231fa07afe8@47.52.234.156:35288 err="dial tcp 47.52.234.156:35288: i/o timeout" attempts=0
E[2019-06-14|11:05:53.895] Dialing failed                               module=pex addr=ae615ed08997756e786a1c0e4e2b30a2438e0e47@35.161.235.185:9328 err="dial tcp 35.161.235.185:9328: i/o timeout" attempts=0
E[2019-06-14|11:05:53.895] Dialing failed                               module=pex addr=7b3bf28f5a1626696b5362d4642bdeac961d97ad@98.15.8.61:54116 err="dial tcp 98.15.8.61:54116: i/o timeout" attempts=0
E[2019-06-14|11:05:53.895] Dialing failed                               module=pex addr=ca27ca169e8908f2aaa4d9c47f0bc43bedc78f45@54.209.128.157:26656 err="dial tcp 54.209.128.157:26656: i/o timeout" attempts=0
I[2019-06-14|11:05:54.552] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[2019-06-14|11:05:56.510] Committed state                              module=state height=1 txs=0 appHash=3987F88CD400DC5B4679A708220D44F045FD077DB6E323D315486CF238892E41
panic: Failed to process committed block (2:6874A607AABF97B8D0627ADDF4B7501CCE74ECAB82E44A6C4F39A4562D75601B): Wrong Block.Header.AppHash.  Expected 3987F88CD400DC5B4679A708220D44F045FD077DB6E323D315486CF238892E41, got 056A9CA652FC5DD667A19362081216A57A70F87A256FD62B3131673BCDBD969B

## Version

gaiad version
0.0.0-30-g8fd398c

seeds in config.toml
seeds = "3e16af0cead27979e1fc3dac57d03df3c7a77acc@3.87.179.235:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,2626942148fd39830cb7a3acccb235fab0332d86@173.212.199.36:26656,3028c6ee9be21f0d34be3e97a59b093e15ec0658@91.205.173.168:26656,89e4b72625c0a13d6f62e3cd9d40bfc444cbfa77@34.65.6.52:26656,6be0856f6365559fdc2e9e97a07d609f754632b0@cosmos-cosmoshub-2-seed.nodes.polychainlabs.com:26656"

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Hello @viyang. The README provides a disclaimer that this repo is not to be used on mainnet. Mainnet is currently running [v0.34.7](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.34.7). Please install and use that.

**Comment by viyang** [comment]
Thank you very much!
