### ISSUE TITLE
How to synchronize only new blocks instead of all historical blocks

### ISSUE THREAD

**Issue by zhangtao940419** [cosmos/gaia#452]
How to synchronize only new blocks instead of all historical blocks

**Comment by zhangtao940419** [comment]
It's too slow to synchronize all historical blocks. In fact, I only need the latest block records,
Is this option available in the configuration file?

**Comment by tac0turtle** [comment]
This is not possible at this time. There are services that provide you with a dB so you don't have to sync yourself. Chainlayer.io is one. 

In the next hub upgrade a sync protocol will be made available that will do this exact thing. 

Will close this issue for now
