### ISSUE TITLE
Build fails on FreeBSD

### ISSUE THREAD

**Issue by mdyring** [cosmos/gaia#46]
make all:

[INFO]  Replacing existing vendor dependencies
?       github.com/cosmos/gaia/cmd/gaia [no test files]
# github.com/cosmos/gaia/vendor/github.com/ethanfrey/ledger
vendor/github.com/ethanfrey/ledger/device.go:27:15: undefined: hid.Devices
*** Error code 2

**Comment by adrianbrink** [comment]
@ethanfrey What is the dependency on the hid for? It seems that it is going to cause all sorts of issues.

**Comment by ethanfrey** [comment]
This is needed for the nano Ledger support, which was a requirement for launch.

It supports Darwin, Linux, and osx. We only officially support Linux and osx. 

If you want to add FreeBSD support, it may be possible, please take a look at https://github.com/ethanfrey/hid

It's needed for the client now, will be embedded in tendermint soon, so I think it is worth the effort to make this work, rather than remove it.

**Comment by ethanfrey** [comment]
You can also talk with @wrl if there is another approach than using hid. I took his advice on how to call into the Ledger.

**Comment by wrl** [comment]
I have not looked at low-level device access on FreeBSD in some time. If Ledger support on FreeBSD is a requirement for launch, I can investigate (I have a spare FreeBSD machine I can research on). If this is not critical for launch, we should disable the ledger dependency on platforms where we don't support it.

**Comment by adrianbrink** [comment]
@wrl Let's go with that approach. So then at least everyone can still build it :-)

**Comment by mdyring** [comment]
HIDAPI (which I believe the Go HID code is based on) supports Linux, Darwin, FreeBSD and Windows: https://github.com/signal11/hidapi

Maybe some inspiration can be borrowed from there? 

Not sure how much work it is, but I think it would be a shame for gaia not support FreeBSD since people then probably just flock to Linux and a few Windows installs.

**Comment by mdyring** [comment]
Or a quickfix to just get it to build on FreeBSD would be great, as I'd like to deploy a testnet validator on this OS. :-)

**Comment by nickray** [comment]
Also running into this trying to create a statically linked binary on Linux.

**Comment by mdyring** [comment]
Seems to work now with gaia v0.5.0:

```
go get github.com/cosmos/gaia
cd $GOPATH/src/github.com/cosmos/gaia
git checkout -qf v0.5.0
make get_vendor_deps
make install
```

results in working binary. Yay.

Thanks @ethanfrey - I imagine it was some magic in the HID department.

**Comment by adrianbrink** [comment]
Removal :-)

**Comment by mdyring** [comment]
Ah, the magic of removal.. ;-)
