### ISSUE TITLE
Questions; how can I see swagger doc for gaia? & how can I sign transaction through json rpc?

### ISSUE THREAD

**Issue by johndoe0x** [cosmos/gaia#468]
Hello guys.
I have couple of questions about gaia. 

1. How can I build docs through swagger? 
I couldn't find way generate json rpc docs. 

2. How can I sign transaction through json rpc?
in [cosmos doc](https://cosmos.network/rpc/v0.38.3) , I could see only transaction broadcasting. 

If someone help about these would be appreciated.

**Comment by tac0turtle** [comment]
you will have to sign the transaction in cli and broadcast it. The json-roc swagger is not provided to be viewed on a running node, but https://docs.tendermint.com/master/rpc/ is the main resource for it. 

In cli you could do, gaiad tx sign 
```
Sign a transaction created with the --generate-only flag.
It will read a transaction from [file], sign it, and print its JSON encoding.

If the --signature-only flag is set, it will output the signature parts only.

The --offline flag makes sure that the client will not reach out to full node.
As a result, the account and sequence number queries will not be performed and
it is required to set such parameters manually. Note, invalid values will cause
the transaction to fail.

The --multisig=<multisig_key> flag generates a signature on behalf of a multisig account
key. It implies --signature-only. Full multisig signed transactions may eventually
be generated via the 'multisign' command.

Usage:
  gaiad tx sign [file] [flags]
  
```

if you have more questions feel free to ping in discord
