### ISSUE TITLE
Move gaiadebug functionality to gaiacli

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/gaia#47]
@jackzampolin commented on [Mon Apr 15 2019](https://github.com/cosmos/cosmos-sdk/issues/4119)

It would be nice for developers to have the `gaiadebug` functionality on the `gaiacli` executable.

---

@alexanderbez commented on [Mon Apr 15 2019](https://github.com/cosmos/cosmos-sdk/issues/4119#issuecomment-483325123)

Maybe we can mount the functionality under `gaiacli debug`. We should look through the current binary/implementation and see what we want to pull out of there. Then we can have an exact set of acceptance criteria/actionable items for this issue 😄 

---

@marbar3778 commented on [Mon Jun 17 2019](https://github.com/cosmos/cosmos-sdk/issues/4119#issuecomment-502723958)

Can we close this issue, or move it to cosmos/gaia? @jackzampolin @alexanderbez 

---

@alexanderbez commented on [Tue Jun 18 2019](https://github.com/cosmos/cosmos-sdk/issues/4119#issuecomment-503074170)

Yes. Moving to the gaia repo.

**Comment by tac0turtle** [comment]
this has been compelted
