### ISSUE TITLE
gaiacli: Is it possible to provide logging configuration?

### ISSUE THREAD

**Issue by jaydp17** [cosmos/gaia#474]
The rest server logs every single incoming request, which is great, but a little overwhelming.

1. Is there a way to only output error or warn logs?
2. Also, is it possible to output the logs in json?

**Comment by alexanderbez** [comment]
> Is there a way to only output error or warn logs?

The (legacy) API uses the same logger as the state-machine/application. Thus you can tune the level and modules logged via the `--log_level` config. There used to be a CLI flag for this too, but it seems to have been removed. Regardless, you can set this in `config.toml` for now.

> Also, is it possible to output the logs in json?

AFAIK, Tendermint's logger doesn't allow configurable structured logging (shame). Correct me if I'm wrong @marbar3778

**Comment by jaydp17** [comment]
Thanks @alexanderbez for the blazing fast response.
I tried setting the following in `~/.gaiacli/config/config.toml`
```toml
log_level = "*:error"
```

But it doesn't seem to work.

**Comment by zmanian** [comment]
most of the logging we are seeing in Gaia is coming from Tendermint and not the SDK.

**Comment by alexanderbez** [comment]
Yes, this is true. I've opened https://github.com/tendermint/tendermint/issues/5912 to try and remove many of the superfluous logs. This will probably happen over time before the next release.
