### ISSUE TITLE
Problems： replace github.com/cosmos/cosmos-sdk => /path/to/clone/cosmos-sdk to go.mod

### ISSUE THREAD

**Issue by ying2025** [cosmos/gaia#49]
ubuntu:~/gospace/src/github.com/cosmos/gaia$ make clean build
go: parsing /path/to/clone/cosmos-sdk/go.mod: open /path/to/clone/cosmos-sdk/go.mod: no such file or directory
go: error loading module requirements
rm -rf snapcraft-local.yaml build/
--> Ensure dependencies have not been modified
go: parsing /path/to/clone/cosmos-sdk/go.mod: open /path/to/clone/cosmos-sdk/go.mod: no such file or directory
go: error loading module requirements
Makefile:106: recipe for target 'go.sum' failed
make: *** [go.sum] Error 1
My cosmos-sdk path is : $HOME/gospace/src/github.com/cosmos/cosmos-sdk

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/59756070-9ce05d00-92bb-11e9-84f8-cbd605985c3e.png)
rm -rf snapcraft-local.yaml build/
--> Ensure dependencies have not been modified
go: errors parsing go.mod:
/home/zhr/gospace/src/github.com/cosmos/gaia/go.mod:8: usage: require module/path v1.2.3
Makefile:106: recipe for target 'go.sum' failed
make: *** [go.sum] Error 1

**Comment by tac0turtle** [comment]
1. uncomment the commented github.com/cosmos/cosmos-sdk....
2. Move the underlined "github.com/cosmos/cosmos-sdk => " to the bottom of the go.mod file. you can see below. 

replace github.com/cosmos/cosmos-sdk => ../<path_to_sdk_locally>

Let me know if the issue persists

**Comment by ying2025** [comment]
When I use "replace github.com/cosmos/cosmos-sdk => ../<path_to_sdk_locally>", it happend following problem.
make clean build
go list -m github.com/cosmos/cosmos-sdk: module "github.com/cosmos/cosmos-sdk" is not a known dependency
rm -rf snapcraft-local.yaml build/
go build -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=0.0.0-31-g7d68770 -X github.com/cosmos/cosmos-sdk/version.Commit=7d68770d30cfd818281570fb82c13f18af27d67e -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' -o build/gaiad ./cmd/gaiad
build github.com/cosmos/gaia/cmd/gaiad: cannot load github.com/cosmos/cosmos-sdk/baseapp: import lookup disabled by -mod=readonly
Makefile:75: recipe for target 'build' failed
make: *** [build] Error 1

It has another problem.

**Comment by ying2025** [comment]
@marbar3778 
When I run  go install  -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=0.34.7 -X github.com/cosmos/cosmos-sdk/version.Commit=7d68770d30cfd818281570fb82c13f18af27d67e -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiad
It happend following problem.
go: finding github.com/cosmos/cosmos-sdk/codec latest
go: finding github.com/cosmos/cosmos-sdk/server/config latest
go: finding github.com/cosmos/cosmos-sdk/store latest
go: finding github.com/cosmos/cosmos-sdk/x/auth latest
go: finding github.com/cosmos/cosmos-sdk/server latest
go: finding github.com/cosmos/cosmos-sdk/x/auth/genaccounts latest
go: finding github.com/cosmos/cosmos-sdk/x/genutil/client/cli latest
go: finding github.com/cosmos/cosmos-sdk/x/auth/genaccounts/client/cli latest
go: finding github.com/cosmos/cosmos-sdk/client/keys latest
go: finding github.com/cosmos/cosmos-sdk/client latest
go: finding github.com/cosmos/cosmos-sdk/x/auth/genaccounts/client latest
go: finding github.com/cosmos/cosmos-sdk/x latest
go: finding github.com/cosmos latest
go: finding github.com latest
go: finding github.com/cosmos/cosmos-sdk/x/slashing latest
go: finding github.com/cosmos/cosmos-sdk/types latest
go: finding github.com/cosmos/cosmos-sdk/version latest
go: finding github.com/cosmos/cosmos-sdk/x/genutil latest
go: finding github.com/cosmos/cosmos-sdk/x/staking latest
go: finding github.com/cosmos/cosmos-sdk/x/mint latest
go: finding github.com/cosmos/cosmos-sdk/x/params latest
go: finding github.com/cosmos/cosmos-sdk/x/params/client latest
go: finding github.com/cosmos/cosmos-sdk/types/module latest
go: finding github.com/cosmos/cosmos-sdk/x/crisis latest
go: finding github.com/cosmos/cosmos-sdk/x/distribution latest
go: finding github.com/cosmos/cosmos-sdk/x/gov latest
go: finding github.com/cosmos/cosmos-sdk/x/bank latest
go: finding github.com/cosmos/cosmos-sdk/x/distribution/client latest
go: finding github.com/cosmos/cosmos-sdk/x/genutil/client latest
go: finding github.com/cosmos/cosmos-sdk/baseapp latest
build github.com/cosmos/gaia/cmd/gaiad: cannot load github.com/cosmos/cosmos-sdk/baseapp: cannot find module providing package github.com/cosmos/cosmos-sdk/baseapp

**Comment by ying2025** [comment]
But the cosmos-sdk/baseapp does exist

**Comment by ying2025** [comment]
@marbar3778  Maybe gaia and cosmos-sdk use different tendermint, gaia and cosmos-sdk how to use same package ?

**Comment by tac0turtle** [comment]
What is your absolute path to your local version of the sdk?

Can you post a copy of your go.mod here?

**Comment by ying2025** [comment]
Ok, wait a minute

**Comment by ying2025** [comment]
/home/zhr/gospace/src/github.com/cosmos/cosmos-sdk

**Comment by ying2025** [comment]
module github.com/cosmos/gaia

go 1.12

require (
	github.com/btcsuite/btcd v0.0.0-20190523000118-16327141da8c // indirect
	github.com/cosmos/cosmos-sdk v0.28.2-0.20190615141739-ac2e765607a6
	github.com/cosmos/go-bip39 v0.0.0-20180819234021-555e2067c45d // indirect
	github.com/google/gofuzz v1.0.0 // indirect
	github.com/gorilla/mux v1.7.2 // indirect
	github.com/magiconair/properties v1.8.1 // indirect
	github.com/mattn/go-isatty v0.0.8 // indirect
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/otiai10/copy v1.0.1
	github.com/otiai10/curr v0.0.0-20190513014714-f5a3d24e5776 // indirect
	github.com/pelletier/go-toml v1.4.0 // indirect
	github.com/pkg/errors v0.8.1
	github.com/prometheus/common v0.4.1 // indirect
	github.com/prometheus/procfs v0.0.0-20190523193104-a7aeb8df3389 // indirect
	github.com/rakyll/statik v0.1.6 // indirect
	github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a // indirect
	github.com/snikch/goodman v0.0.0-20171125024755-10e37e294daa
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cobra v0.0.4
	github.com/spf13/viper v1.4.0
	github.com/stretchr/testify v1.3.0
	github.com/syndtr/goleveldb v1.0.0 // indirect
	github.com/tendermint/go-amino v0.15.0
	github.com/tendermint/tendermint v0.31.5
	golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f // indirect
	golang.org/x/sys v0.0.0-20190527104216-9cd6430ef91e // indirect
	golang.org/x/text v0.3.2 // indirect
	google.golang.org/appengine v1.4.0 // indirect
	google.golang.org/genproto v0.0.0-20190522204451-c2c4e71fbf69 // indirect
)

replace golang.org/x/crypto => github.com/tendermint/crypto v0.0.0-20180820045704-3764759f34a5

**Comment by tac0turtle** [comment]
with this go.mod file, I am able to install everything correctly. where did you place you replace for the cosmos-sdk

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/59839220-e34cbf00-9382-11e9-91cc-10ae005c46a3.png)

**Comment by tac0turtle** [comment]
yes, so at the bottom of the go.mod that you sent, did you add a replace statement to use your version of the sdk? or are you just trying to get it run first then do that?

**Comment by ying2025** [comment]
@marbar3778  My cosmos-sdk git checkout v0.34.7, it cannt pass make install

**Comment by ying2025** [comment]
module github.com/cosmos/gaia

go 1.12

require (
	github.com/btcsuite/btcd v0.0.0-20190523000118-16327141da8c // indirect
	//github.com/cosmos/cosmos-sdk v0.28.2-0.20190615141739-ac2e765607a6
	github.com/cosmos/go-bip39 v0.0.0-20180819234021-555e2067c45d // indirect
	github.com/google/gofuzz v1.0.0 // indirect
	github.com/gorilla/mux v1.7.2 // indirect
	github.com/magiconair/properties v1.8.1 // indirect
	github.com/mattn/go-isatty v0.0.8 // indirect
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/otiai10/copy v1.0.1
	github.com/otiai10/curr v0.0.0-20190513014714-f5a3d24e5776 // indirect
	github.com/pelletier/go-toml v1.4.0 // indirect
	github.com/pkg/errors v0.8.1
	github.com/prometheus/common v0.4.1 // indirect
	github.com/prometheus/procfs v0.0.0-20190523193104-a7aeb8df3389 // indirect
	github.com/rakyll/statik v0.1.6 // indirect
	github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a // indirect
	github.com/snikch/goodman v0.0.0-20171125024755-10e37e294daa
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cobra v0.0.4
	github.com/spf13/viper v1.4.0
	github.com/stretchr/testify v1.3.0
	github.com/syndtr/goleveldb v1.0.0 // indirect
	github.com/tendermint/go-amino v0.15.0
	github.com/tendermint/tendermint v0.31.5
	golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f // indirect
	golang.org/x/sys v0.0.0-20190527104216-9cd6430ef91e // indirect
	golang.org/x/text v0.3.2 // indirect
	google.golang.org/appengine v1.4.0 // indirect
	google.golang.org/genproto v0.0.0-20190522204451-c2c4e71fbf69 // indirect
)

replace golang.org/x/crypto => github.com/tendermint/crypto v0.0.0-20180820045704-3764759f34a5

replace github.com/cosmos/cosmos-sdk => ../<path_to_sdk_locally>

**Comment by ying2025** [comment]
Just now, I redownload the code that override my previous modifications "replace github.com/cosmos/cosmos-sdk => ../<path_to_sdk_locally>" in the go.mod, so I add it again

**Comment by tac0turtle** [comment]
<path_to_sdk_locally> for you would be ../cosmos-sdk i believe. I put that there because i didnt know your path, like a fill in the blank

**Comment by ying2025** [comment]
My cosmos-sdk path ?

**Comment by tac0turtle** [comment]
the path from this folder to your version of cosmos-sdk. so for me if wanted to use a local version of the sdk I would put `replace github.com/cosmos/cosmos-sdk => ../cosmos-sdk` then make install

**Comment by ying2025** [comment]
~/gospace/src/github.com/cosmos/gaia$ make install
go list -m: not using modules
--> Ensure dependencies have not been modified
all modules verified
go install  -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=0.0.0-31-g7d68770 -X github.com/cosmos/cosmos-sdk/version.Commit=7d68770d30cfd818281570fb82c13f18af27d67e -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiad
go: finding github.com/cosmos/cosmos-sdk/x/genutil latest
go: finding github.com/cosmos/cosmos-sdk/x/auth/genaccounts latest
go: finding github.com/cosmos/cosmos-sdk/x/genutil/client/cli latest
go: finding github.com/cosmos/cosmos-sdk/x/auth/genaccounts/client/cli latest
go: finding github.com/cosmos/cosmos-sdk/types/module latest
go: finding github.com/cosmos/cosmos-sdk/x/params/client latest
go: finding github.com/cosmos/cosmos-sdk/x latest
go: finding github.com/cosmos/cosmos-sdk/x/auth latest
go: finding github.com/cosmos/cosmos-sdk/x/genutil/client latest
go: finding github.com/cosmos/cosmos-sdk/x/params latest
go: finding github.com/cosmos/cosmos-sdk/types latest
go: finding github.com/cosmos/cosmos-sdk/x/auth/genaccounts/client latest
go: finding github.com/cosmos latest
go: finding github.com latest
build github.com/cosmos/gaia/cmd/gaiad: cannot load github.com/cosmos/cosmos-sdk/types/module: cannot find module providing package github.com/cosmos/cosmos-sdk/types/module
Makefile:90: recipe for target 'install' failed
make: *** [install] Error 1
It still has the problem, My cosmos-sdk also has a problem when I make install. 
~/gospace/src/github.com/cosmos/cosmos-sdk$ make install
bash contrib/install-golangci-lint.sh /home/zhr/gospace/bin v1.15.0 ac897cadc180bf0c1a4bf27776c410debad27205b22856b861d41d39d06509cf
scripts/Makefile:51: recipe for target '/home/zhr/gospace/bin/golangci-lint' failed
make: *** [/home/zhr/gospace/bin/golangci-lint] Error 1

**Comment by tac0turtle** [comment]
oooohhhh, on your cosmos-sdk you are using 0.34.7 but gaia repo is linked to master branch of comsos-sdk. So you have to go to the cosmos-sdk checkout and pull master

**Comment by ying2025** [comment]
But when I checkout to master , it cannt install the dependency packages when I make build, only if I use go mod vendor.

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/59840889-e1382f80-9385-11e9-9a9a-90082a30625b.png)

**Comment by ying2025** [comment]
If I go mod vendor, I am worry that gaia cannt get these package

**Comment by tac0turtle** [comment]
okay so it built correctly, so now if you go to gaia, it should install correctly. Also is there a reason you are using local sdk version instead of just the version that is in the go.mod file in gaia?

**Comment by ying2025** [comment]
what's your mean ?

**Comment by sabau** [comment]
Hi, does you have the `env GO111MODULE=on` flag set?

**Comment by ying2025** [comment]
yes

**Comment by ying2025** [comment]
There are a lot of package donnt download in cosmos-sdk just by make build
![image](https://user-images.githubusercontent.com/28092539/59841630-50625380-9387-11e9-8a5c-00b01bb6c61c.png)

**Comment by alessio** [comment]
@ying2025 what version of gaia do you want to build? If you want to build any of the stable releases, you should just *not* use the `github.com/cosmos/gaia` repo. Old stable releases of gaia live within the `github.com/cosmos/cosmos-sdk` main repo. The version of gaia that lives here is unreleased and build against `github.com/cosmos/cosmos-sdk` master branch

We are very happy to help you, though we need to understand better what you are trying to do.

**Comment by ying2025** [comment]
I want to mainly use cosmos-sdk, if change cosmos-sdk, the gaia can know it.

**Comment by ying2025** [comment]
And  I want to use the lastest cosmos-sdk.

**Comment by alessio** [comment]
> And cosmos-sdk I want to use the lastest edition.

There are presently two latest versions, a stable one `0.35.0` and a development one, which is `master`. Which do you want to build on top of?

**Comment by ying2025** [comment]
0.35.0

**Comment by alessio** [comment]
Good, so you don't use `github.com/cosmos/gaia` at all. Everything you need is in `github.com/cosmos/cosmos-sdk`. I advise you to just clone the `cosmos-sdk` repo, you will find gaia under the `cmd/gaia` directory of the `cosmos-sdk` repository.

**Comment by ying2025** [comment]
I cannt checkout v0.35 in master branch

**Comment by ying2025** [comment]
@alessio I also need to set up my own testnet, so the gaia should be needed.

**Comment by sabau** [comment]
By running those commands in sequence, you got some errors?

```
git https://github.com/cosmos/cosmos-sdk.git
git checkout v0.35.0
```
For your situation, tag v0.35.0, `gaia` was still included in the SDK. In master, you can't see it anymore because we decided to decouple it in a different repository

**Comment by ying2025** [comment]
ok, I already checkout v0.35.0, but when i make install or make build, it occur following problem
~/gospace/src/github.com/cosmos-sdk$ make install
bash contrib/install-golangci-lint.sh /home/zhr/gospace/bin v1.15.0 ac897cadc180bf0c1a4bf27776c410debad27205b22856b861d41d39d06509cf
scripts/Makefile:51: recipe for target '/home/zhr/gospace/bin/golangci-lint' failed
make: *** [/home/zhr/gospace/bin/golangci-lint] Error 1
When I run gaiad version, why its version is 0.0.0-31-g7d68770
~/gospace/src/github.com/cosmos-sdk/cmd/gaia$ gaiad version
0.0.0-31-g7d68770

**Comment by sabau** [comment]
This may help:
```
make tools
```

**Comment by ying2025** [comment]
make tools
go install -mod=readonly ./cmd/gosum/
bash contrib/install-golangci-lint.sh /home/zhr/gospace/bin v1.15.0 ac897cadc180bf0c1a4bf27776c410debad27205b22856b861d41d39d06509cf
scripts/Makefile:51: recipe for target '/home/zhr/gospace/bin/golangci-lint' failed
make: *** [/home/zhr/gospace/bin/golangci-lint] Error 1

**Comment by alessio** [comment]
@ying2025 please let's move this discussion here: https://github.com/cosmos/cosmos-sdk/issues/4596

**Comment by alessio** [comment]
Closing this for now, this has nothing to do with the gaia repo.

**Comment by ying2025** [comment]
ok, thank you very much
