### ISSUE TITLE
panic: StoreBlockHeight (3924407) > StateBlockHeight + 1 (1)

### ISSUE THREAD

**Issue by liangping** [cosmos/gaia#493]
## Summary of Bug

```
Nov 28 13:30:33 vultr gaiad[153438]: panic: StoreBlockHeight (3924407) > StateBlockHeight + 1 (1)
Nov 28 13:30:33 vultr gaiad[153438]: goroutine 1 [running]:
Nov 28 13:30:33 vultr gaiad[153438]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc020946748, 0xb, 0x0, 0x0, 0x0, 0xc000f3bd80, 0x19, 0x3be1b7, 0x0, 0x0, ...)
Nov 28 13:30:33 vultr gaiad[153438]: #011github.com/tendermint/tendermint@v0.34.0-rc6/consensus/replay.go:382 +0x162b
Nov 28 13:30:33 vultr gaiad[153438]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc020946748, 0x1fd6b20, 0xc0004bc000, 0xc0000dc570, 0x203000)
Nov 28 13:30:33 vultr gaiad[153438]: #011github.com/tendermint/tendermint@v0.34.0-rc6/consensus/replay.go:268 +0x4d8
Nov 28 13:30:33 vultr gaiad[153438]: github.com/tendermint/tendermint/node.doHandshake(0x1fd2cc0, 0xc000464470, 0xb, 0x0, 0x0, 0x0, 0xc000f3bd80, 0x19, 0x3be1b7, 0x0, ...)
Nov 28 13:30:33 vultr gaiad[153438]: #011github.com/tendermint/tendermint@v0.34.0-rc6/node/node.go:277 +0x1d8
Nov 28 13:30:33 vultr gaiad[153438]: github.com/tendermint/tendermint/node.NewNode(0xc000d36b40, 0x1fb47c0, 0xc00042ad20, 0xc00049ad00, 0x1f814a0, 0xc0002e85c0, 0xc00049ad70, 0x1dcacc0, 0xc00049ae60, 0x1fbdc40, ...)
Nov 28 13:30:33 vultr gaiad[153438]: #011github.com/tendermint/tendermint@v0.34.0-rc6/node/node.go:685 +0x1da5
Nov 28 13:30:33 vultr gaiad[153438]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000e1e380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1fbd800, 0xc000d20610, ...)
Nov 28 13:30:33 vultr gaiad[153438]: #011github.com/cosmos/cosmos-sdk@v0.40.0-rc3/server/start.go:235 +0x5d7
Nov 28 13:30:33 vultr gaiad[153438]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000d68000, 0xc000e15a00, 0x0, 0x1, 0x0, 0x0)
Nov 28 13:30:33 vultr gaiad[153438]: #011github.com/cosmos/cosmos-sdk@v0.40.0-rc3/server/start.go:117 +0x154
Nov 28 13:30:33 vultr gaiad[153438]: github.com/spf13/cobra.(*Command).execute(0xc000d68000, 0xc000e159f0, 0x1, 0x1, 0xc000d68000, 0xc000e159f0)
```

CHAIN_ID=cosmoshub-test-stargate-d
GENESIS_URL=https://storage.googleapis.com/stargate-genesis/genesis.json
SERVER_BIN=gaiad
START_CMD="${SERVER_BIN} start --x-crisis-skip-assert-invariants"
SEEDS=9811c237b8674c755d51346de08f5d0e7c76d843@34.66.219.254:26656
 

## Version

```
# gaiad version
cosmoshub-test-stargate
root@vultr:~# gaiad version --long
name: gaia
server_name: gaiad
version: cosmoshub-test-stargate
commit: 204fe7e42f4a4d9558641d26c7f269e88338f904
build_tags: netgo,ledger
go: go version go1.15.3 linux/amd64
```

## Steps to Reproduce
```
gaiad start --x-crisis-skip-assert-invariants 
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
This panic seems to be coming from Tendermint. @liangping can you provide more info? There isn't enough for us to go off of here. What genesis file are you using? How many validators?

**Comment by greg-szabo** [comment]
I received this error at startup after my sentry node ran out of memory. (stargate-c testnet) Edit: maybe stargate-d? Whatever we ran this week.

To reproduce, create a fresh node with 4GB of RAM, run gaiad and wait for the network to come online. Some time there (sorry can't remember the timeline, but I think the network had to be running) your node will run out of memory and gaiad panics. (According to Zaki, the first startup takes around 16GB of RAM. I'm not sure about subsequent startups, but my prod sentry nodes run on 4GB of RAM.)

Subsequent starts of your node will produce that error. Possibly the database gets corrupted when the node runs out of memory.

The workaround was to raise the available RAM to 16GB and reset the database. Starting up the node didn't resolve into an out-of-memory panic at that point and the subsequent StoreBlockHeight error didn't appear either.

I would request to clarify system requirements for sentry/validator nodes and explicitly state in the documentation that first run of a node requires 16GB of RAM. (Alternatively, lower that requirement, but I'm not sure what exactly eats the RAM. Zaki knows better.)

It would also be nice to possibly run a few tests for subsequent runs so the documentation can be clarified for RAM requirements for ongoing nodes. The jump from 4GB to 16GB for a sentry node is more ok, for the first run and less ok for continuous use. (It can get expensive quickly with multiple sentry nodes.)

Edit2: to explicitly answer bez's questions: this was the stargate-d testnet with 125 validators (some controlled by Zaki). I believe the genesis file is this one https://storage.googleapis.com/stargate-genesis/genesis.json .

**Comment by liangping** [comment]
@greg-szabo I am running on 8G RAM server

**Comment by alexanderbez** [comment]
Wow, 16gb of ram requirement? What is making it require so much memory @greg-szabo? Is it loading the genesis state into memory? Any chance you can run the node with profiling on?

**Comment by zmanian** [comment]
These are similar requirements to what we have seen with the Terra startup after an upgrade.
