### ISSUE TITLE
install  cmd  to /usr/local/bin/xxx, It should be much better！

### ISSUE THREAD

**Issue by shepf** [cosmos/gaia#495]
install  cmd  to /usr/local/bin/xxx, It should be much better！

```
root@VM-0-2-ubuntu:/home/shepf/gaia# make install
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=2.0.13 -X github.com/cosmos/cosmos-sdk/version.Commit=bc93dcc040570c71fad288ba5eeebe4033a5c5d8 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiad
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=2.0.13 -X github.com/cosmos/cosmos-sdk/version.Commit=bc93dcc040570c71fad288ba5eeebe4033a5c5d8 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiacli
root@VM-0-2-ubuntu:/home/shepf/gaia# 
root@VM-0-2-ubuntu:/home/shepf/gaia# gaiad init taigu_test
gaiad: command not found
root@VM-0-2-ubuntu:/home/shepf/gaia# find / -name gaiad
/root/go/bin/gaiad
/home/shepf/gaia/cmd/gaiad
/home/shepf/gaia/networks/remote/ansible/roles/set-debug/files/sysconfig/gaiad
```

**Comment by tac0turtle** [comment]
do you have your `gobin` set? this seems like your environment is not setup correctly

**Comment by faddat** [comment]
I think he is right.  Gopath stuff gets so unweildy to deal with, and not everyone will have it set correctly.  

The way he is suggesting, at least it'll end up on $PATH reliably.

**Comment by shepf** [comment]
> do you have your `gobin` set? this seems like your environment is not setup correctly

yes,but i think, install cmd to /usr/local/bin/xxx, It should be much better！ many well-known open source projects are like this. 
it will be silky when used in this way.

**Comment by okwme** [comment]
I think we shouldn't make this decision on behalf of users but we should provide better documentation about the options they have for configuring it themselves.

**Comment by glnro** [comment]
Will be updating documentation to address limited support for go installation as part of #1092
