### ISSUE TITLE
CLI sign with `--amino` produces invalid "mode" field

### ISSUE THREAD

**Issue by greg-szabo** [cosmos/gaia#499]
## Summary of Bug
The `gaiad tx sign --amino` command generates a signed transaction that can be sent over the stargate `/txs` RPC endpoint. Except for one thing:
```
...
    ],
    "memo": "send_tx_to_validator",
    "timeout_height": "0"
  },
  "mode": "block|sync|async"
}
```
The `mode` field returns all options instead of choosing a default. 

The stargate RPC `/txs` endpoint correctly rejects it with:
```
{
  "error": "unsupported return type block|sync|async; supported types: sync, async, block"
}
```

Since this will most probably affect command-line users, it is a safe bet to set the `mode` to `block` as default. That would allow the struct to be successfully submitted. (Tested it.)

## Version
```
name: gaia
server_name: gaiad
version: cosmoshub-test-stargate-2
commit: 94c77126db850e01ade7535c6286ed2a7c3fb9f6
build_tags: netgo,ledger
go: go version go1.15.6 linux/amd64
```

## Steps to Reproduce
CLI commands I ran (you might need different keys or use the DockerHub image (informaldev/gaiad)[https://hub.docker.com/repository/docker/informaldev/gaiad]):
```
gaiad tx bank send cosmos1cww3sjp5lc4jglur6ghspszycmdx29q3kvhfce cosmos1e27k6gp3qjc9dzva793m9a77epjk8q6y0gu4em 1uatom --keyring-backend test --chain-id dockerchain --gas-prices 200000.0uatom --memo "send_tx_to_validator" --generate-only > unsigned.json
gaiad tx sign unsigned.json --keyring-backend test --chain-id dockerchain --from c0 --offline --account-number 0 --sequence 0
```

The output of the second command will show the issue. The result can be almost successfully pasted into a `POST /txs` request.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
in the new versions of the sdk the flag is `--sign-mode amino-json`

**Comment by greg-szabo** [comment]
The issue is still present in gaiad v6.0.0 (cosmos SDK 0.44.3)

The issue is not with the sign mode of the key used.

From `gaiad tx sign help`:
```
      --amino                    Generate Amino encoded JSON suitable for submiting to the txs REST endpoint
```

To reproduce:
Step 1: (create a send transaction, this is fine)
`gaiad tx bank send cosmos1qhzcyutu233pmsw75q908j6dt6z4c5ekg3cqkn cosmos1e27k6gp3qjc9dzva793m9a77epjk8q6y0gu4em 1uatom --keyring-backend test --chain-id dockerchain --gas-prices 200000.0uatom --note "send_tx_to_validator" --generate-only`

Result of step 1:
```
{
  "body": {
    "messages": [
      {
        "@type": "/cosmos.bank.v1beta1.MsgSend",
        "from_address": "cosmos1qhzcyutu233pmsw75q908j6dt6z4c5ekg3cqkn",
        "to_address": "cosmos1e27k6gp3qjc9dzva793m9a77epjk8q6y0gu4em",
        "amount": [
          {
            "denom": "uatom",
            "amount": "1"
          }
        ]
      }
    ],
    "memo": "send_tx_to_validator",
    "timeout_height": "0",
    "extension_options": [],
    "non_critical_extension_options": []
  },
  "auth_info": {
    "signer_infos": [],
    "fee": {
      "amount": [
        {
          "denom": "uatom",
          "amount": "40000000000"
        }
      ],
      "gas_limit": "200000",
      "payer": "",
      "granter": ""
    }
  },
  "signatures": []
}
```
(so far so good)

Step 2: (Sign the transaction and output a JSON that can directly be submitted to the `/txs` endpoint. This is not the regular output of the `tx sign` command. The `--amino` parameter makes sure of that.)
`gaiad tx sign unsigned.json --keyring-backend test --chain-id dockerchain --from k1 --offline --account-number 0 --sequence 0 --amino`

Result of the command:
```
{
  "tx": {
    "msg": [
      {
        "type": "cosmos-sdk/MsgSend",
        "value": {
          "from_address": "cosmos1qhzcyutu233pmsw75q908j6dt6z4c5ekg3cqkn",
          "to_address": "cosmos1e27k6gp3qjc9dzva793m9a77epjk8q6y0gu4em",
          "amount": [
            {
              "denom": "uatom",
              "amount": "1"
            }
          ]
        }
      }
    ],
    "fee": {
      "amount": [
        {
          "denom": "uatom",
          "amount": "40000000000"
        }
      ],
      "gas": "200000"
    },
    "signatures": [],
    "memo": "send_tx_to_validator",
    "timeout_height": "0"
  },
  "mode": "block|sync|async"
}
```

See the the value of `mode` is invalid. This is added by the `--amino` parameter.

**Comment by greg-szabo** [comment]
The issue is still present in gaiad v7.0.1. I was able to create the below transaction with the invalid mode field:
```
{
  "tx": {
    "msg": [
      {
        "type": "cosmos-sdk/MsgSend",
        "value": {
          "from_address": "cosmos1atwc6zs27hu7w2wlqeq2c2d4dumtclwckknmkw",
          "to_address": "cosmos14lultfckehtszvzw4ehu0apvsr77afvyhgqhwh",
          "amount": [
            {
              "denom": "uatom",
              "amount": "10"
            }
          ]
        }
      }
    ],
    "fee": {
      "amount": [
        {
          "denom": "uatom",
          "amount": "1"
        }
      ],
      "gas": "200000"
    },
    "signatures": [],
    "memo": "",
    "timeout_height": "0"
  },
  "mode": "block|sync|async"
}
```
