### ISSUE TITLE
Home dir not passed to gaia for state export

### ISSUE THREAD

**Issue by alpe** [cosmos/gaia#501]
## Summary of Bug
Cross posting the issue here as it affects gaia as well:
* Original issue and description https://github.com/cosmos/cosmos-sdk/issues/8150

## Version
Not sure which is the current development branch. Assuming `jack/gaiav3.0` (`5652138`)
https://github.com/cosmos/gaia/blob/jack/gaiav3.0/cmd/gaiad/cmd/root.go#L205-L211

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by shahankhatch** [comment]
Stargate upgrade just took place and the export seemed to proceed fine.
