### ISSUE TITLE
Gaia changelog is out of date

### ISSUE THREAD

**Issue by tessr** [cosmos/gaia#504]
The changelog on master goes up to 0.2.13, but the latest Gaia release is 0.2.14. (I think the diff is probably minor, tbh.)

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
(Maybe also a good time to introduce a CHANGELOG_PENDING?)

**Comment by tac0turtle** [comment]
I think the unreleased section is better. In the cosmos-sdk an unreleased section is used and makes for easier changes.
