### ISSUE TITLE
Set memory limit

### ISSUE THREAD

**Issue by atomlab** [cosmos/gaia#508]
## Summary

- `gaiad` uses 25GB of RAM
- 50 req/sec RPC calls   
- some times out of memory happens. OOM Killer comes.

## Problem Definition

I can't control memory usage by `gaiad`. After few hours it use about 25GB RAM. 

## Proposal

Use some thing like `--cache SIZE`   or another options to limit memory usage.

**Comment by shahankhatch** [comment]
Unfortunately, this is currently out of scope for gaia. The challenge is that there are many components coming from the sdk and tendermint, and the possibility of using different storage mechanisms.
