### ISSUE TITLE
(Minor) Runtime error when unbonding before bonding.

### ISSUE THREAD

**Issue by svaishnavy** [cosmos/gaia#52]
Steps to reproduce:
1. Bond with 10 fermion and unbond.
2. Stopped gaia process
3. Restarted gaia process
4. Bond again

I am getting this error: 
ERROR: CheckTx: (1): runtime error: invalid memory address or nil pointer dereference

Query returns 10 fermions available.

I am running gaia in macbook pro

**Comment by svaishnavy** [comment]
Sorry, I was issuing a wrong command to bond. In fact, I was trying to unbond. I'll close the issue.

**Comment by melekes** [comment]
> runtime error: invalid memory address or nil pointer dereference

is that all you're getting? is there no trace?

**Comment by adrianbrink** [comment]
@svaishnavy Can you post the output of the terminal for the error.

**Comment by zramsay** [comment]
this was reported (and fixed IIRC) elsewhere. at any rate, it should be fixed once gaia has migrated to SDK repo
