### ISSUE TITLE
Update documentation for stargate

### ISSUE THREAD

**Issue by fedekunze** [cosmos/gaia#533]
## Summary of Bug

The documentation is outdated and needs to be updated to the latest SDK changes from Stargate, specially the delegation guide, Tutorial, Resources and Validator sections

- [ ] `gaiad config` command has been deprecated
- [ ] update offline signing
- [x] update governance (proposal types, governance working group, etc)

Feel free to add more items to the list above

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
I think these have all been updated thanks to @glnro @nooomski @yaruwangway @uditvira @dcwalk 🙏
