### ISSUE TITLE
No pre-built binaries for gaiacli? 

### ISSUE THREAD

**Issue by jadechip** [cosmos/gaia#538]
## Summary of Bug

For the latest release, I see pre-built binaries for gaiad are now included, but I cannot find anything for gaiacli.
Is it advised to instead build it from source? 

## Version

v3.0.0

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by shahankhatch** [comment]
The gaiacli commands have been rolled into gaiad, so the gaiad binary should be sufficient.

https://github.com/cosmos/gaia/issues/531#issuecomment-757689844

**Comment by jadechip** [comment]
@shahankhatch thanks for the clarification!

**Comment by lcgogo** [comment]
@shahankhatch How can I start rest-server?

I used to start rest-server by
/usr/bin/gaiacli rest-server --trust-node=true --node tcp://${ATOMIP}:26657 --laddr tcp://0.0.0.0:1317

but no rest-server options in gaiad 3.0.0

**Comment by shahankhatch** [comment]
@lcgogo In the document linked here:
https://github.com/cosmos/cosmos-sdk/blob/master/docs/migrations/chain-upgrade-guide-040.md#upgrade-procedure

Finding the word "rest-server" shows it a bit further down, and it appears that the `rest-server` option has been moved into the `app.toml` configuration file.

**Comment by lcgogo** [comment]
> @lcgogo In the document linked here:
> https://github.com/cosmos/cosmos-sdk/blob/master/docs/migrations/chain-upgrade-guide-040.md#upgrade-procedure
> 
> Finding the word "rest-server" shows it a bit further down, and it appears that the `rest-server` option has been moved into the `app.toml` configuration file.

Many thanks!
