### ISSUE TITLE
3.0.0 build error

### ISSUE THREAD

**Issue by lcgogo** [cosmos/gaia#539]
## Summary of Bug

3.0.0 build error

## Version

git checkout v3.0.0

go: downloading github.com/mimoo/StrobeGo v0.0.0-20181016162300-f8f6d4d2b643
go: downloading github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
go: downloading github.com/gtank/ristretto255 v0.1.2
# github.com/zondax/hid
In file included from /go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:22:
/usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
    1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
      |  ^~~~~~~

## Steps to Reproduce

make install

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by smithy9901** [comment]
Faced with the same problem
Dockerfile v3.0.0 not working

**Comment by shahankhatch** [comment]
Closing since v3.0.0 is no longer current. Please open another issue if you have the same problem with v4.0.x.
