### ISSUE TITLE
deploy single node local testnet

### ISSUE THREAD

**Issue by xihucuyu888** [cosmos/gaia#542]
## Summary of Bug

![image](https://user-images.githubusercontent.com/41260909/104444178-64f1e680-55d2-11eb-8bf5-438929253826.png)

Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
Usage:
  gaiad start [flags]

## Version

3.0.0

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
This error usually appears when you may have skipped a step. In the past when I have run into the error I rerun the script or cmds and if it persists then I am doing something wrong in the process. Can you try again to see if it works.

**Comment by xihucuyu888** [comment]
i have solved
