### ISSUE TITLE
local node rest api returns no sequence

### ISSUE THREAD

**Issue by xihucuyu888** [cosmos/gaia#546]
i start a local node and enable the API server
but i can't get sequence of an account

```
curl  http://127.0.0.1:1317/auth/accounts/cosmos1880dqz6x8h0r2pxwy7nupypdrs07vk2md9322n | jq

{
    "height": "667",
    "result": {
        "type": "cosmos-sdk/BaseAccount",
        "value": {
            "address": "cosmos1880dqz6x8h0r2pxwy7nupypdrs07vk2md9322n",
            "account_number": "10"
        }
    }
}
```

using gaiad query can get sequence

```
 gaiad query account cosmos10h44ukvzk6yjqsfne4ypemxulqtnu0de3zhzgm
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "0"
address: cosmos10h44ukvzk6yjqsfne4ypemxulqtnu0de3zhzgm
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: A9yaIJHbdhcoRPr7FNEIoD5IsW7TKTd27EgRoSY4/l7t
sequence: "6"
```

## Version

v3.0.0

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by xihucuyu888** [comment]
ok, i found that new account doesn't return sequence 0,
accounts that having txs would return sequence...

**Comment by yaruwangway** [comment]
Hi @xihucuyu888, thanks for posting your issue! We've been behind on many reviews and apologize for such. Would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.

Thanks for your help,
Cosmos Hub Team
