### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by maef2018** [cosmos/gaia#558]
Reference deployment document：
https://hub.cosmos.network/main/gaia-tutorials/installation.html
https://hub.cosmos.network/main/gaia-tutorials/join-mainnet.html
https://github.com/cosmos/mainnet
version ：V3.0.1

I compiled only the gaiad file, but not the gaiacli file.
I started the gaiad program and reported the following error：
root@5577f3292089:~# gaiad start
11:35AM INF starting ABCI with Tendermint
Error: error reading GenesisDoc at /root/.gaia/config/genesis.json: evidence.MaxAgeNumBlocks must be greater than 0. Got 0

Among them, /root/.gaia/config/genesis.json comes from https://raw.githubusercontent.com/cosmos/launch/master/genesis.json

**Comment by shahankhatch** [comment]
Hi @maef2018 If I understand correctly, I believe you're trying to join the cosmos mainnet, often called `Cosmos Hub`, using Gaia v3.0.1. Thanks for using the latest release; however, the Cosmos Hub is not yet running Gaia v3. There's currently an impending governance proposal to upgrade the Cosmos Hub to Gaia v3. If you want to join the Cosmos Hub mainnet, please use the latest Gaia v2 release, [v2.0.14](https://github.com/cosmos/gaia/releases/tag/v2.0.14).

**Comment by maef2018** [comment]
hi,@shahankhatch, I followed the compilation version v2.0.14 you mentioned above and succeeded, but the following connections obtained from https://github.com/cosmos/mainnet are not available, and the node I built cannot synchronize to the block data:

3e16af0cead27979e1fc3dac57d03df3c7a77acc@3.87.179.235:26656
ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656
2626942148fd39830cb7a3acccb235fab0332d86@173.212.199.36:26656
3028c6ee9be21f0d34be3e97a59b093e15ec0658@91.205.173.168:26656
89e4b72625c0a13d6f62e3cd9d40bfc444cbfa77@34.65.6.52:26656
6be0856f6365559fdc2e9e97a07d609f754632b0@cosmos-cosmoshub-2-seed.nodes.polychainlabs.com:26656


E[2021-01-25|11:46:47.974] Error dialing seed                           module=p2p err="dial tcp 3.87.179.235:26656: i/o timeout" seed=3e16af0cead27979e1fc3dac57d03df3c7a77acc@3.87.179.235:26656

**Comment by maef2018** [comment]
success, Thank you!
