### ISSUE TITLE
Whitelisting Delegators

### ISSUE THREAD

**Issue by crainbf** [cosmos/gaia#56]
In my view, it is of critical importance that validators can choose who delegates to them. This could be accomplished by validators whitelisting addresses of delegators and those only being able to delegate if they are on the whitelist. 

There are various use cases that become possible with this feature:

- Let's say a group of AIB employees want to run a validator together, but they don't want the responsibility of validating with atoms from third parties they do not know. This makes it possible.
- Let's say a validator wants delegators to sign a terms of service. This could include things such as place of arbitration in case a validator gets slashed. I'm almost certain that lawyers will insist that this is of critical importance. With a whitelist, a validator can ask delegators to cryptographically sign the agreement on its website, then whitelist that address and accept their delegation.
- In some jurisdiction, validators may be forced to KYC their delegators. With whitelisting this becomes possible. 

With a whitelist, we give validators a lot of flexibility. This will dramatically increase the diversity both in type of organization and geographic distribution of validators.

Of course, it is perfectly legitimate for a validator to accept any delegators, without accompanying legal terms or other restrictions. Those validators can just ignore the whitelisting feature.

**Comment by ethanfrey** [comment]
I talked with Brian for like 5 minutes on this and agree completely, it is a minor addition to the protocol that adds enormous amount of control to the validators for any sort of SLA or other sign-up procedure they want to implement independently off-chain. And probably a requirement for any large company running a validator (and needing a sign-off from their legal department)

**Comment by adrianbrink** [comment]
I am against establishing a whitelist. The game-ability consequences are right now to hard to judge. I think this can be an interesting feature to revisit 6 months after launch, when we have the time to think about all the implications that it presents, but it should not be something that we launch with.

**Comment by zmanian** [comment]
Implementing white listing in the protocol signals that validators are fiduciaries. Another signal would be marketing yourself as a validator.

But lets say you just build a validator. Clearly publicize your security setup and anonymous people decide to delegate. Are you a fiduciary?

In some zones/hubs running all validators as fiduciaries may make sense. Ideally, I'd like this to be decided post launch via a protocol upgrade rather than backed in.

**Comment by crainbf** [comment]
I disagree that this implies validators are fiduciaries. It simply says: Validators should have control over how they run their operation. If we don't allow this, we restrict to an extreme extent what kind of organization a validator can be. I am fairly certain that many organizations will not be able to run validators from a legal perspective without this feature.

There are many different scenarios why you would want that. It can simply be that a bunch of friends want to run a validator together and don't want the burden of validating for third parties. This is really something that should be possible. A whitelist allows this while keeping the burden of the chain minimal. 

I think we will dramatically reduce the diversity of validators without this feature. And I strongly suspect that in many jurisdictions, nobody will run a validator without the ability to whitelist. 

We will be looking into the regulatory implications of running a validator. We may make a proposal to the foundation to fund proper research into this. But I think we should at least start thinking about how we could do this soon. (Assuming it's not a trivial thing to implement)

**Comment by ethanfrey** [comment]
If it is turned off by default, and just an opt-in feature, I don't see how it can hurt. Maybe only expose it in some "advanced" section in the UI for people who ask, if you don't want this to be common. But I think this is important if you want people to place real-world reputation behind their validator.

Implementing shouldn't be hard. Just add a whitelist field to the CandidateBond and check it when delegating to someone. We can limit it to maximum, say, 40 addresses to prevent potentially unbounded size and computations. 

I could add it in a few hours to Rigel's design for gaia, and I'm sure it would take him about the same time. (maybe a couple more hours if we want to do extensive testing of it)

**Comment by rigelrozanski** [comment]
very simple to implement it - we just need to decide if we want too - doesn't need to be limited either we can add it to the store - so we never need to iterate over the list

**Comment by adrianbrink** [comment]
As I argued in the [economics talk](https://www.youtube.com/watch?v=ew7tL0rG6vM) I think this is a feature that should be decided on by governance. It is not critical for the MVP and launching the hub. If >2/3 of validators after launch agree on this, we can simply implement it.

I completely support @zmanian stance on this.

**Comment by crainbf** [comment]
Look at it like this: 
If we have this feature at the beginning, anyone can run a validator whether you want to use this or not. Validators who don't want this, have no disadvantage at all. 
If we don't have this feature, some may decide that they can't run a validator at all. 

Afterward, there can be a governance vote to turn it off if people want that. However, then both sides can participate in that. It's a much fairer way.

Having this feature strictly gives people more options. If we want to take away choice from people, we should have extremely strong reasons for that and so far I don't feel such reasons have been given. 

@adrianbrink Can you please explain why you think this feature would cause a problem?

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/572
