### ISSUE TITLE
Bump Cosmos-SDK to v0.41

### ISSUE THREAD

**Issue by Jelena647** [cosmos/gaia#566]
Note that it's currently listed as Milestone v0.40.2 since v0.41 contains lots of other planned work but since the changes from #568 are breaking v0.40.2 will need to be v0.41 and what was previously v0.41 will be v0.42 -  https://github.com/cosmos/cosmos-sdk/milestone/37 - should be updated in the SDK milestones @ clevinson @aaronc

**Comment by aaronc** [comment]
Thanks @Jelena647. The SDK release team has not yet made this decision regarding versioning. I know others have proposed it but we currently aren't thinking in this direction. We will share our thoughts in a public channel.
