### ISSUE TITLE
Gov Proposal - IBC transfers

### ISSUE THREAD

**Issue by Jelena647** [cosmos/gaia#567]
Stargate has full support for IBC transfers, but they are disabled by default. They need to be enabled by a parameter change proposal. 

Here is an initial draft of that proposal: https://github.com/cosmos/governance/pull/14

Are there any milestones, risk assessments, or other criteria folks would like to see before this proposal goes living?

**Comment by shahankhatch** [comment]
The IBC parameter change was submitted and voted Yes. IBC is now active.
