### ISSUE TITLE
CI: Fix contract_tests 

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/gaia#57]
## Summary of Bug

The `contract_tests` CI target is currently broken. As such, it's currently disabled.

The `contract_tests` CI target executes `make setup-contract-tests-data`:

```shell
setup-contract-tests-data:
	echo 'Prepare data for the contract tests'
	rm -rf /tmp/contract_tests ; \
	mkdir /tmp/contract_tests ; \
	cp "${GOPATH}/pkg/mod/${SDK_PACK}/client/lcd/swagger-ui/swagger.yaml" /tmp/contract_tests/swagger.yaml ; \
	./build/gaiad init --home /tmp/contract_tests/.gaiad --chain-id lcd contract-tests ; \
	tar -xzf lcd_test/testdata/state.tar.gz -C /tmp/contract_tests/
```

The `tar -xzf lcd_test/testdata/state.tar.gz -C /tmp/contract_tests/` command is completely overriding the `.gaiad` directory which is wrong.

I'm not sure where `state.tar.gz` comes from or how it's configured, but we should not be dumping static configuration here.

Example with this pipeline enabled: https://circleci.com/gh/cosmos/gaia/2543. In this case, Tendermint's configuration structure has changed and the correct configuration was replaced by whatever was in `state.tar.gz` which was old/deprecated.

## Version

0432ac5

/cc @alessio @sabau 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by sabau** [comment]
That's good! the goal of this test was to catch this kind of things. 

> The tar -xzf lcd_test/testdata/state.tar.gz -C /tmp/contract_tests/ command is completely overriding the .gaiad directory which is wrong.

Luckily that command does not override everything, only files that match their path:
in `/tmp/contract_tests/.gaiad/config/`:
- addrbook.json
- config.toml
- genesis.json
- gentx
- node_key.json
- priv_validator_key.json

If you try to launch locally the untar command you will see what's inside, some accounts in gaiacli and a validator with his private key in gaiad + a genesis

By changing the config.toml inside the state.tar.gz works, I ran a diff between the two configurations and the only meaningful difference is:
```
< db_backend = "goleveldb" # new version
---
> # Database backend: leveldb | memdb | cleveldb
> db_backend = "leveldb" # old version
```

The reason why the `config.toml` is here is to speed up the tests by reducing the timeouts, if you prefer we can achieve this with a few `sed` commands and keep generated `config.toml`
```
< timeout_propose = "3s"
< timeout_propose_delta = "500ms"
< timeout_prevote = "1s"
< timeout_prevote_delta = "500ms"
< timeout_precommit = "1s"
< timeout_precommit_delta = "500ms"
< timeout_commit = "5s"
---
> timeout_propose = "200ms"
> timeout_propose_delta = "200ms"
> timeout_prevote = "500ms"
> timeout_prevote_delta = "100ms"
> timeout_precommit = "200s"
> timeout_precommit_delta = "200ms"
> timeout_commit = "500ms"
```

**Comment by sabau** [comment]
Just made a PR for that, I just removed the config.toml from the targz and added few sed to achieve the speedup, the tests itself seems happy again: https://circleci.com/gh/cosmos/gaia/2637
