### ISSUE TITLE
New Stargate Proposal

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#571]
Due to the issues raise in #568 , the Stargate [proposal 35](https://www.mintscan.io/cosmos/proposals/35) to launch on Jan 28 is being overruled. A new [proposal 36](https://www.mintscan.io/cosmos/proposals/36) is up to advocate for cancelling the proposal 35. ATOM holders should vote on 36 to signal support for cancelling proposal 35.

A new proposal should go up soon once all issues from #568 are addressed. This new proposal is being drafted [here](https://github.com/cosmos/governance/pull/13).

It should contain the new gaia codehash once all issues from #568 are complete.   

- [ ] Prepare governance proposal
- [ ] Code Hash
- [ ] Block height/time
- [ ] Get signoffs for proposal

Note the upgrade from cosmoshub-2 -> cosmoshub-3 took 5 gov proposals to get it right ;)

**Comment by zmanian** [comment]
WIP PR
https://github.com/cosmos/governance/pull/13

**Comment by zmanian** [comment]
Closed by  Prop 37 https://www.mintscan.io/cosmos/proposals/37
