### ISSUE TITLE
GetTxsEventRequest Tx and TxResponse ordering

### ISSUE THREAD

**Issue by williamberman** [cosmos/gaia#574]
## Summary

This isn't really a feature request. This is more of a question for clarification. We want to verify that the `tx.GetTxsEventRequest` rpc endpoint returns corresponding `TxResponse`s and `Tx`s at the same index.

The rationale for this is that we index transaction data and require information present in both the `TxResponse` and the `Tx`. See the following code snippet for more details.

```
package main
import (
	"context"
	"fmt"
	"github.com/cosmos/cosmos-sdk/types/query"
	"github.com/cosmos/cosmos-sdk/types/tx"
	"google.golang.org/grpc"
)
func main() {
	grpcURL := ""
	height := 1000
	var currentKey []byte
	cosmosTxFetchLimit := uint64(100)
	grpcConn, err := grpc.Dial(
		grpcURL,
		grpc.WithInsecure(),
	)
	if err != nil { panic(err) }
	client := tx.NewServiceClient(grpcConn)
	request := &tx.GetTxsEventRequest{
		Events: []string{fmt.Sprintf("tx.height=%d", height)},
		Pagination: &query.PageRequest{
			Key:   currentKey,
			Limit: cosmosTxFetchLimit,
		},
	}
	response, err := client.GetTxsEvent(context.Background(), request)
	for index, txResponse := range response.TxResponses {
		tx := response.Txs[index] // <- Does this tx coorespond to txResponse because they're at the same index?

                 // At this location, we require the following information
		tx.Body.Memo
		tx.Body.Messages
		tx.GetSigners()
		txResponse.Logs
		txResponse.Code
		txResponse.Height
		txResponse.TxHash
	}
}

```

## Problem Definition

This is a rather performance sensitive part of our indexer. The alternative of issuing additional queries by transaction hash likely does not fit in our performance constraints.

## Proposal

If this is not the current way that the endpoint works, we would like to request that it should return it as such. If that's not feasible, further discussion would be appreciated :)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
Yes the tx and its response should match up at the same index. Do you have a case where it doesn't? cc @clevinson and @tessr, ultimately this issue will belong in tendermint or the SDK

There are some event related issued being collected in https://github.com/tendermint/tendermint/issues/5963 but I'm not sure if that's relevant here.

**Comment by williamberman** [comment]
Yep I assumed that they would match up at the same index. I just couldn't find docs that confirmed it and wanted to double check because it's a very important part of our code base that relies on this being correct. 

@jackzampolin had pointed us towards this issue https://github.com/tendermint/tendermint/issues/5133 in tendermint that indicated we weren't able to rely on them matching up at the same index. 

We're ok with either way as of now with a strong preference towards them matching. Let me know which interpretation we should go with :)

**Comment by ebuchman** [comment]
I believe https://github.com/tendermint/tendermint/issues/5133 is unrelated. @clevinson / @aaronc can you confirm we have tests for this and update docs accordingly plz ?

**Comment by alexanderbez** [comment]
So It's been some time since I've looked at SDK internals, but doing some digging, I see that this is handled by  [`txServer#GetTxsEvent`](https://github.com/cosmos/cosmos-sdk/blob/v0.41.0/x/auth/tx/service.go#L51) and that _does_ seem to _confirm_ your reasoning -- the index do line up.


```go
	for i, tx := range result.Txs {
		txResp := txResultToTxResponse(&tx.TxResult)
		txResp.Height = tx.Height
		txResp.TxHash = tx.Hash.String()
		txRespList[i] = txResp

		var protoTx txtypes.Tx
		if err := cdc.UnmarshalBinaryBare(tx.Tx, &protoTx); err != nil {
			return nil, err
		}
		txsList[i] = &protoTx
	}
```

**Comment by williamberman** [comment]
Ok, great. I'm going to take this as confirmation that we can use the index. Thank you and feel free to close this if you don't need to leave this open for anything else :)
