### ISSUE TITLE
KMS Signing support for relayer txs

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#577]
As discussed in this [Stargate issue](https://github.com/cosmos/gaia/issues/568#issuecomment-767258515) and elsewhere, IBC messages in Stargate cannot be signed yet by Ledgers.

We should add hardware support for IBC message signing through the [TMKMS](https://github.com/iqlusioninc/tmkms/). @zmanian @tony-iqlusion are there issues for this?

**Comment by tony-iqlusion** [comment]
It should certainly be doable via a YubiHSM2.

How are you foreseeing an IBC relayer interacting with TMKMS? Would you like for TMKMS to expose a gRPC service?

**Comment by zmanian** [comment]
My mental model is similar to the oracle architecture maybe.

**Comment by ebuchman** [comment]
Yeh I think a gRPC makes sense, is that what the oracle uses ?

I guess there would also be the option for the rust relayer of running in process but that seems special case.

Any thoughts here @ancazamfir

**Comment by tony-iqlusion** [comment]
@ebuchman the current transaction signer uses a JSON/HTTP webhook (which makes outgoing requests).

At the time we implemented it we needed Amino support, so it was easier to get started with Amino JSON.

However, now we have `tendermint-proto`, `cosmos-sdk-proto`, and `cosmos-tx`, so we can start working on defining a gRPC service.

**Comment by nooomski** [comment]
Is this still relevant or can we close this? @ebuchman Not too familiar with IBC status on this. Thanks

**Comment by romac** [comment]
There's no support for TMKMS in Hermes at the moment, so we can maybe keep this issue open to discuss relayer integration with TMKMS?

**Comment by tony-iqlusion** [comment]
Would be good to discuss this after we have initial gRPC support

**Comment by ebuchman** [comment]
I think the original issue may still stand but it prob doesn't need to be in this repo. @charleenfei @jackzampolin do you know if relayer txs can be signed by hardware yet ? should we move this issue somewhere to track it? I believe all relayers are currently just using text file private keys and that might be fine for now but as relayer balances increase this may become higher priority - cc @adizere @greg-szabo

**Comment by mmulji-ic** [comment]
AFAIK This issue is no longer relevant, we'll close, please reopen if incorrect.
