### ISSUE TITLE
Documentation and Services for Navigating the Cosmos Network

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#578]
Once Stargate is live and chains start connecting, users and services will be faced with the problem of navigating the new interchain world.

When chains connect, their identifiers are just deterministic strings, and contain no branding information, metrics, or meta data. There is also plenty of pertinent off-chain data like market cap, application specific UIs, where to find tokens, etc.

We need to ensure there are explorers and funnels to support users discovering and navigating through the interchain.

This includes services like CoinMarketCap, DefiPulse, Map of Zones, etc.

Ultimately we need to be answering the questions, **"Where do users go to find out about what's happening in the interchain and get started participating?".**

Some existing CoinMarketCap style offerings:
- https://cosmos-cap.com/#/
- https://messari.io/screener/cosmos-ecosystem-FCB5C9E8

There is also https://mapofzones.com, built during Game of Zones, but likely needing updates and maintenance for the Stargate mainnet.

I believe @nylira, @nassdonald, and team also have some stuff cooking!

There is also currently the [cosmos-registrar](https://github.com/cosmos/cosmos-registrar) tool to scrape data from chains and store it in this [registry](https://github.com/cosmos/registry) repository. Ultimately we expect a registry like this to [move onto the chain itself](https://github.com/cosmos/gaia/projects/6#card-53521941).

One note is that there are some issues currently querying the total liquid supply of chains, which needs to get fixed:  https://github.com/cosmos/cosmos-sdk/issues/7774

We should check in with other block explorer teams where they're at and what support they might need. Likely a lot of them  should organize around using Stargate battle ready CosmJS.

**Comment by ebuchman** [comment]
@nylira can we also get a short summary/update here on the state and timeline of the Cosmos website revamp?

**Comment by nassdonald** [comment]
Some wonderful points raised here, plenty to think about. One thing to consider is who are we talking about when we say “users”? I believe the spectrum is rather broad and we need to consider all the various touchpoints different audiences are likely to encounter. For instance, a developer “user” building a wallet is very different to an end user of a wallet - both require funnels across our websites.

Would love to discuss this in greater depth if you have the time to join our weekly website strategy meetings or even our weekly content-focused call with @hxrts, where we focus on user flows, content strategy, copywriting and so on.
Regarding the state of the Cosmos Network website revamp, we’re not far off from starting development, but still ironing out some content and flows based on feedback. However, we’ve had to shift gears in light of the recent marketing push for Prop #34, and direct our focus to the Cosmos Hub website (initially separate from the Cosmos Network website). Happy to share the progress so far via DM – Telegram or Slack?

We’re aiming to have the Cosmos Hub website live in time for the Stargate upgrade on Cosmos Hub – mid-late Feb.

**Comment by ebuchman** [comment]
Awesome thanks Nass! Fully agree re user groups, there are a lot, and the B9 work should help us better delineate them and target different groups with different content and services. Would love to join some of those calls, or maybe better yet see some of their output written up as issues or docs in this repo :D

**Comment by nassdonald** [comment]
For sure! We've been working a little bit in a silo for lack of somewhere appropriate to document our process, so if this repo is the place to do it (without adding to the noise), I'm happy to add any relevant meeting minutes. Just let me know where you feel this content is best surfaced.

Regarding B9, I'd very much like to work closer with them, considering that they have been auditing old and out-of-date wireframes. 🙈  Coordination is essential here if we're to action any of their feedback, and I've only had one introductory call with them to date.

**Comment by nooomski** [comment]
Going over some old issues that we'd like to close. Would like to chime in and update with current activities:

- [Mintscan](https://mintscan.io) is offering most of the explorer needs expressed by @ebuchman 
- [MapOfZones](https://mapofzones.com) has been upgraded 
- Chain Registry has been moved to [this repo](https://github.com/cosmos/chain-registry) and is in progress. We aim to standardise chain metadata and IBC metadata (and maybe asset lists?) and move to an automated solution once we've gotten input on the standards & figured out governance & incentive structure.

In my view, I think [Atlas](http://atlas.cosmos.network/) is a great starting point to consider placing the aggregated data around chain discoverability. But for now, would suggest we continue this discussion in the chain registry repo. Closing this for now. Feel free to re-open if anyone feels this was closed too soon.
