### ISSUE TITLE
Allow Validators to Set Cap on Amount of Atoms to be Delegated

### ISSUE THREAD

**Issue by crainbf** [cosmos/gaia#58]
I think it would be good if the protocol can support validators capping the amount of atoms that can be delegated to them. This way a validator can limit how much of the atom supply is delegated to them and thus voluntarily help us get a more decentralized network. 

e.g. Validator A may have 1m atoms self-bonded (~0.4% of supply). They set a cap of 5m atoms that can be bonded to them. When the cap is reached, further transactions to delegate to them fail. If that isn't there, a validator may not want to have a huge percentage of atoms being delegated to them, but not have a tool to prevent it either.

This would also allow social consensus to emerge to support more decentralization. e.g. the community could start exerting pressure on validators that don't have a cap to set one. It could become a sign of a 'responsible validator' if they have reasonable caps.

**Comment by rigelrozanski** [comment]
Why not just up your commission rate until you kick off the right amount of delegation instead?

**Comment by zramsay** [comment]
closing as obsolete. re-open in SDK repo if applicable
