### ISSUE TITLE
Document running multi-node test with replacement validator keys

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#589]
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
@yaruwangway can this be closed?

**Comment by yaruwangway** [comment]
> @yaruwangway can this be closed?

we can close this!

**Comment by yaruwangway** [comment]
[document shows how to replace validator keys](https://github.com/cosmos/vega-test/tree/master/local-testnet)
