### ISSUE TITLE
Discord link on readme.md is broken

### ISSUE THREAD

**Issue by giovannirco** [cosmos/gaia#595]
## Summary of Bug
Discord link is broken, new link I got from Discord Server is https://discord.gg/vcExX9T

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Jelena647** [comment]
thank you I've made a [PR](https://github.com/cosmos/gaia/pull/596) to merge the updated link!
