### ISSUE TITLE
Precision Integer VS use of external library for decimal management 

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#6]
General discussion. 

We need to use decimal information for a few key factors within the staking module, namely commission rate, as well as bonded token exchange rate. If banker decimal rounding is not used, we will have consistency problems, So I guess we can either build in this functionality where necessary, or incorporate another decimal library (see link) into the staking module. 

https://github.com/shopspring/decimal 

What are others preferences? @mappum @ebuchman @ethanfrey

**Comment by adrianbrink** [comment]
I'm in favour of using the library by writing a wrapper around the library itself. 

Two reasons:
1. We shouldn't re-implement everything. If we were to write this ourselves, we would essentially take that code, reimplement the same functionality and then have another package that we need to maintain. 
2. It's easy to test the correctness of the external dependency. We can write super detailed test cases that make us certain that the implementation is correct.

Side points:
* if we want a different API I think it is better to write a wrapper around the existing library
* if we need higher performance I think we should also write a wrapper around the existing library to have the potential of replacing the underlying implementation with a rust library

**Comment by rigelrozanski** [comment]
Hmm Interesting, I'm still processing why wrapping other libraries (even within tendermint) is a common technique that we have been using. I understand that if the library does not have the full functionality, or some basic pre-/post-processing steps need to be taken as to why you would wrap another library, but what if the library already has full functionality and we don't need to limit any of the methods? I suppose it is nice to be able to use the newly wrapped functions with unit testing. Not totally positive this is needed her, but I think I'm leaning towards using this decimal library too... I guess in the weeds I'll spec it out a bit more whether it makes sense to wrap it. @adrianbrink Let me know if you have any other thoughts as to why we should wrap it, definitely intrigued by this approach and it seems to be used although throughout our repos

**Comment by ethanfrey** [comment]
My two sense. I agree with Rigel that wrapping libraries doesn't always make sense. I think using a library is a good idea. I want the decimal format to have functions/methods for basic math. And nice json and go wire encodings. Other than that, I am open to whatever you find. On Aug 26, 2017 20:28, Rigel <notifications@github.com> wrote:Hmm Interesting, I'm still processing why wrapping other libraries (even within tendermint) is a common technique that we have been using. I understand that if the library does not have the full functionality, or some basic pre-/post-processing steps need to be taken as to why you would wrap another library, but what if the library already has full functionality and we don't need to limit any of the methods? I suppose it is nice to be able to use the newly wrapped functions with unit testing. Not totally positive this is needed her, but I think I'm leaning towards using this decimal library too... I guess in the weeds I'll spec it out a bit more whether it makes sense to wrap it. @adrianbrink Let me know if you have any other thoughts as to why we should wrap it, definitely intrigued by this approach and it seems to be used although throughout our repos

**Comment by adrianbrink** [comment]
Two reasons for wrapping:
1. We want a different and maybe cleaner API.
2. We want the ability to swap the implementation in the future.

Point to is relevant in this case, because the library states that it opted for API clarity over performance. Math libraries quickly become bottlenecks in financial applications (trading bot on the chain). That's why I would wrap it, so that we can implement the math in Rust or C and swap the implementation.

**Comment by ethanfrey** [comment]
The biggest performance killers we have in cpu cycles areVerifying public key signatures at 200 microseconds eachAnd computing the hashes for the Merkle tree. IO for the saving of the merkle tree is also significant even with ssds.On Aug 26, 2017 9:45 PM, Adrian Brink <notifications@github.com> wrote:Two reasons for wrapping:
We want a different and maybe cleaner API.We want the ability to swap the implementation in the future.
Point to is relevant in this case, because the library states that it opted for API clarity over performance. Math libraries quickly become bottlenecks in financial applications (trading bot on the chain). That's why I would wrap it, so that we can implement the math in Rust or C and swap the implementation.

**Comment by rigelrozanski** [comment]
The ability to easily swap out the library seems positive. Like it, esp if we eventually choose to reimplement math library. cool thanks.

**Comment by rigelrozanski** [comment]
@adrianbrink turns out we definitely need to wrap anyways to use exposed variables in the struct for go-wire... Also @ethanfrey we will need to update coins to use this repo too, will PR this to cosmos-sdk when I migrate the staking module there

**Comment by jaekwon** [comment]
BTW, whenever we import libraries, we need to check for their license (Apache2.0 is OK, GPL is not, unlicensed is not).  We will also need to audit everything we import, so don't import anything substantial without approval.

**Comment by rigelrozanski** [comment]
here MIT license which is less restrictive than Apache2.0 and therefor compatible... More on this... based on stack convo with Jae, I'm leaning towards only using this library for display purposes not for calculation logic... will rework back to int64 with a minimum denomination (something probably between bitcoin and eth aka between 10^-8 and 10^-18)

**Comment by rigelrozanski** [comment]
*** while also still using bank rounding

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/573
