### ISSUE TITLE
How to upgrade to gaia v4.0.0?

### ISSUE THREAD

**Issue by JohnsonCaii** [cosmos/gaia#601]
I'm running an old gaia version.
```
$ gaiad version
2.0.13
```

I would like to know how to upgrade to the latest version(v4.0.0)

Is there any migration doc like [cosmoshub-2](https://github.com/cosmos/gaia/blob/main/docs/migration/cosmoshub-2.md) saying?

---

I've tried the v4.0.0 version starting from scratch, after the successfully `make install` I got the error
```
$ gaiad start
...
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

From [stargate-launch](https://github.com/cosmos/stargate-launch) I get the avaiable validator node now is `6ae55f60f0951247985ccd52773312aa89413d1c@34.71.170.158:26656`.

I also tried this with command
```
$ gaiad start --p2p.persistent_peers "6ae55f60f0951247985ccd52773312aa89413d1c@34.71.170.158:26656"
...
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

Please help!

**Comment by tac0turtle** [comment]
Gaia 4.0 is not on the hub currently. There will be a migration on the 18th of February. At this time a new genesis will be provided for use.
