### ISSUE TITLE
Gaia v4.0.0 rest endpoint /slashing/validators/{validatorPubKey}/signing_info does not work

### ISSUE THREAD

**Issue by JoeKash** [cosmos/gaia#623]
## Summary of Bug
Sending requests to `/slashing/validators/{validatorPubKey}/signing_info` always returns error no signing info found -
`{"error":"3E899BA36A93C7370347BD5FE85909F2ECD93F8C: no validator signing info found"}`
 
## Version
v4.0.0

## Steps to Reproduce
curl 34.71.170.158:1317/slashing/validators/cosmosvalconspub1zcjduepqxd3zalq0z9qun2ygsyd2l7y4uvqxx43aprfqw807wdnm7zd8fa5qng8ncw/signing_info 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
@JoeKash is this still present?

Ill close the issue for now, but feel free to comment in it or ping marbar in discord
