### ISSUE TITLE
Gaia v4.0.0 v1beta api no easy way to find validator sigining info

### ISSUE THREAD

**Issue by JoeKash** [cosmos/gaia#624]
## Summary of Bug
There is an encoding mismatch between the value returned from `/cosmos/staking/v1beta1/validators` and they validator identifier expected to use when querying `/cosmos/slashing/v1beta1/signing_infos/{cons_address}` as the cons_address is never returned

to find a validator signing info we need to know it's cons_address (cosmosvalcons) but when we ask for the validator info we only get the public key (and even that not in an address format -
```json
{ 
"operator_address": "cosmosvaloper1lmxn3tumhp6cpmv4epq4ha9r9hv0jrv9n8hhky", 
"consensus_pubkey": { 
    "@type": "/cosmos.crypto.ed25519.PubKey", 
    "key": "F9mcgQ4JP/twt0wRzF8JZXH75LOCOkb0Njn1Cart1Yo=" 
}, 
"jailed": false, 
"status": "BOND_STATUS_BONDED", 
...
}
```

So it is not trivial to query the node for signing info

There are probably other places in the API where similar issues are happening.
It should be checked that the API will always return data in the same format / encoding it expects it to be queried later

## Version
v4.0.0

## Steps to Reproduce
`curl 34.71.170.158:1317/cosmos/staking/v1beta1/validators`
and see you don't have any way to get the cosmosvalcons address

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
Hey, this issue should be created in the sdk. Im not sure if it has changed but yea agree its weird that its done this way.

**Comment by liangping** [comment]
@JoeKash You have to convert `consensus_pubkey` { 
    "@type": "/cosmos.crypto.ed25519.PubKey", 
    "key": "F9mcgQ4JP/twt0wRzF8JZXH75LOCOkb0Njn1Cart1Yo=" 
} and consensus "osmovalcons1pwtm90tzdq9hx0ylk7j2xzdm6s8nuac0erdwws"  to hex.

**Comment by ilcatos** [comment]
Hi @JoeKash !  Did you find a solution about  con address in the query's: /cosmos/slashing/v1beta1/signing_infos/{cons_address} ?
