### ISSUE TITLE
Validator parameter set

### ISSUE THREAD

**Issue by gamarin2** [cosmos/gaia#63]
As per discussion on slack:

- Validator Name - INPUT/UI
- Validator Website - INPUT/UI
- Validator Description - INPUT/UI
- Amount of atoms self-bonded - INPUT/UI
- Amount of atoms delegated to them - UI
- Commission rate - INPUT/UI
- How long they have been validator - UI

**Comment by gamarin2** [comment]
* Minimum self-bond amount (if validator falls under it, he and his delegators will unbond)

**Comment by adrianbrink** [comment]
* Amount of atoms self-bonded shouldn't be an input but should just depend on the actual self-bonded atoms.

**Comment by gamarin2** [comment]
When you set your Minimum self-bond, you should be able to self-bond with the same transaction so that you don't get immediately unbonded.

**Comment by rigelrozanski** [comment]
@gamarin2 `minimum self bond` is set ONCE when you declare candidacy - at this same moment you also set the amount of initial bond to declare candidacy with - @adrianbrink is correct you can increase (or unbond) from your self bond at any moment

**Comment by gamarin2** [comment]
@rigelrozanski 

> minimum self bond is set ONCE when you declare candidacy - at this same moment you also set the amount of initial bond to declare candidacy with

Is exactly what I meant.

**Comment by mappum** [comment]
>Minimum self-bond amount (if validator falls under it, he and his delegators will unbond)

Just clarifying: when we talked about this before, we figured that the delegators wouldn't unbond automatically from this condition since we don't have an index to iterate over all the delegators for a certain validator. So would this mean you want the UI to automatically detect when the minimum self bond is too low and trigger unbonding?

**Comment by mappum** [comment]
Also, at the retreat, we discussed (can't remember who was there) removing the candidacy declaration from the UI and leaving it only as a CLI tool, since validators know how to use a command-line anyway.

**Comment by gamarin2** [comment]
> Just clarifying: when we talked about this before, we figured that the delegators wouldn't unbond automatically from this condition since we don't have an index to iterate over all the delegators for a certain validator. So would this mean you want the UI to automatically detect when the minimum self bond is too low and trigger unbonding?

**Comment by rigelrozanski** [comment]
@mappum 
> Just clarifying: when we talked about this before, we figured that the delegators wouldn't unbond automatically from this condition since we don't have an index to iterate over all the delegators for a certain validator. So would this mean you want the UI to automatically detect when the minimum self bond is too low and trigger unbonding?

No, the entire validator with delegators unbond together to a liquid pool where each delegator must send in a transaction to move the already unbonded tokens from the pool to their own wallet. If the validator becomes active again, anyone who has not yet unbonded from this pool will automatically be bonded with this validator once again (more relevant for liveliness kicks) 

> Also, at the retreat, we discussed (can't remember who was there) removing the candidacy declaration from the UI and leaving it only as a CLI tool, since validators know how to use a command-line anyway.

Sure, no opinion, that sounds reasonable.

**Comment by gamarin2** [comment]
Shouldn't we add:

- Consensus PubKey - Input
- Governance PubKey - Input

?

**Comment by rigelrozanski** [comment]
oh yeah this list wasn't complete - checkout the spec for what I currently have included in there... consensus pubkey is in there.

I'm wondering if it does make sense to have a seperate governance pubkey. @gamarin2 has this been established in your conversations with others? I might be okay to just use the consensus pubkey ... would they normally have different levels of security aka. consensus super lockdown, but maybe a validator may cary there governance key with them?? thoughts?

**Comment by gamarin2** [comment]
Yeah we had this discussion many time, @ethanfrey proposed it originally if I remember correctly.

To me it makes sense because consensus PubKey frequently and automatically signs blocks. You don't touch it, you restrict access and you make sure it's secure. OTOH governance key is used manually to send votes. Validator operator will probably designate someone to vote on their behalf, like an employee. Or they may carry it with them to make sure they always vote on every proposal. 

I mean it's definitely two different level of security, so it makes sense to differentiate.

**Comment by rigelrozanski** [comment]
Okay will make a note to add this to the spec.
