### ISSUE TITLE
Validator Legal Issues

### ISSUE THREAD

**Issue by repj1** [cosmos/gaia#64]
We had a short discussion on Riot about validators ideally being public facing organizations (registering a website announcing intent). 

This has opened a few questions in about legal implications around validating. 

Namely, by acting as a public facing organization are there legal ramifications for Validators if good-faith errors are made early on in the validating process?

For example: A good intentioned Validator has issues resulting in a burned stake for stakers. Is that 'the risk of doing business', or is there now a legal liability for the validator, and an opening for stakers to file suit? 

Brian touches on this [here](https://github.com/cosmos/gaia/issues/56) somewhat, stating that stakers may be expected to sign a ToS which names a place of arbitration -- these are heavy implications.

There will I'm sure be anonymous validators, but really they'd potentially be obstructing simply for the purpose of avoiding legal responsibility (rather than privacy which could be obtained by using a passthrough and VPN) and therefore a target in their jurisdiction.

We may need some sort of guide or guidance-- possibly from the cosmos legal to set a standard. 

Thoughts?

**Comment by jackson-jackson** [comment]
I don't understand the rationale for burning stake if a validator is DDOSd. How much stake is burned? What if a validator gets hit with an unstoppable DDOS?

**Comment by zmanian** [comment]
Failing to propose/vote results in the loss of rewards to stakeholders and eventually automatically triggers unbonding.

Stake isn't burned due to DDOS.

**Comment by jackson-jackson** [comment]
Ok, that makes much more sense.

**Comment by repj1** [comment]
The example may be misplaced but the concern stands. If a validator mistake results in burned stake, etc. I'll edit the OP.

**Comment by zmanian** [comment]
Things that could result in stake burning.

1. Insider attacks.
2. Compromise of the validator systems
3. Accidentally activating a backup validator and having them both online at the same time.

**Comment by jackson-jackson** [comment]
A company must act to the best of their ability to maintain the function of their business. If their business is operating a validator and they're hit with an attack that cannot be defended, then they are absolutely not liable. If however, they repeatedly make costly errors, and negligence can be demonstrated, then there are definitely legal ramifications. None of this is very complicated though, and good legal counsel and a qualified team would mitigate the concern.

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/570
