### ISSUE TITLE
Cannot initialize full node using Gaia v4.0.2, hangs at ABCI Replay Blocks

### ISSUE THREAD

**Issue by armorsun** [cosmos/gaia#647]
## Summary of Bug

After execute the command: `gaiad start`

The process hangs with the following output:

```
10:21AM INF starting ABCI with Tendermint
10:21AM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
10:21AM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
10:21AM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
10:21AM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
10:21AM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
10:21AM INF Starting EventBus service impl={"Logger":{}} module=events
10:21AM INF Starting PubSub service impl={"Logger":{}} module=pubsub
10:21AM INF Starting IndexerService service impl={"Logger":{}} module=txindex
10:21AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
10:21AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
```

## Version

```
gaiad version --long
name: gaia
server_name: gaiad
version: 4.0.2
commit: 6d46572f3273423ad9562cf249a86ecc8206e207
build_tags: netgo ledger,
go: go version go1.15.8 linux/amd64
```

## Steps to Reproduce

Get the latest genesis.json from https://raw.githubusercontent.com/cosmos/mainnet/master/genesis.cosmoshub-4.json.gz

Modified the seeds in config.toml with:
```
seeds = "89e4b72625c0a13d6f62e3cd9d40bfc444cbfa77@34.65.6.52:26656"
```
I found the seed nodes on https://github.com/cosmos/mainnet

`gaiad init [my_moniker]`
`gaiad start`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by matyushkins** [comment]
+1 similar situation

**Comment by tac0turtle** [comment]
Can you please retry now. I believe at the time you opened the issue the chain hadn't started yet.

**Comment by Daniel1984** [comment]
same here, just now

**Comment by jun0tpyrc** [comment]
it takes ~5 hours without `--x-crisis-skip-assert-invariants` , ~1hour with `--x-crisis-skip-assert-invariants` to start , don't forget adding p2p.persistent_peers/seed before starting , because you would need to start over if you forgot that ....

**Comment by gituser** [comment]
Seems it's working, you just have to wait.

Put this into your `.gaia/config/config.toml` in the relevant section:

```
# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
seeds = "ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656,bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,585794737e6b318957088e645e17c0669f3b11fc@54.160.123.34:26656,df57f70cd3a104dcbd14d1aac9eb260c99a620e0@121.78.247.247:26656,11dfe200894f38e411beca77928e9dd118e66813@94.130.98.157:26656,5b4ed476e01c49b23851258d867cc0cfc0c10e58@206.189.4.227:26656,654f47a762c8f9257aef4a44c1fb5014916d8b20@99.79.60.15:26656,366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656,547bfac343b9b4bd54ce9cb891c4bca3db2a0922@157.230.116.241:26656,d6318b3bd51a5e2b8ed08f2e520d50289ed32bf1@52.79.43.100:26656,1bfda3d59e70290a3dada9bb809dd954371850d3@54.180.225.240:26656,6ee94c2093505e8790442c054e6e1e0211d36583@44.239.140.195:26656,ec779a2741da6dd2ccdaa6dfc0bebb10e595dfa4@50.18.113.67:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,047f723806ee702b211e7227f89eacd829aabd86@52.9.212.125:26656,b0e746acb6fbed7a0311fe21cfb2ee94581ca3bc@51.79.21.187:26656,82772547c4575c18dfe6e75aafe521cf7d4dc8de@142.93.157.186:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656"
# Comma separated list of nodes to keep persistent connections to
persistent_peers = "ee27245d88c632a556cf72cc7f3587380c09b469@45.79.249.253:26656,bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,585794737e6b318957088e645e17c0669f3b11fc@54.160.123.34:26656,df57f70cd3a104dcbd14d1aac9eb260c99a620e0@121.78.247.247:26656,11dfe200894f38e411beca77928e9dd118e66813@94.130.98.157:26656,5b4ed476e01c49b23851258d867cc0cfc0c10e58@206.189.4.227:26656,654f47a762c8f9257aef4a44c1fb5014916d8b20@99.79.60.15:26656,366ac852255c3ac8de17e11ae9ec814b8c68bddb@51.15.94.196:26656,547bfac343b9b4bd54ce9cb891c4bca3db2a0922@157.230.116.241:26656,d6318b3bd51a5e2b8ed08f2e520d50289ed32bf1@52.79.43.100:26656,1bfda3d59e70290a3dada9bb809dd954371850d3@54.180.225.240:26656,6ee94c2093505e8790442c054e6e1e0211d36583@44.239.140.195:26656,ec779a2741da6dd2ccdaa6dfc0bebb10e595dfa4@50.18.113.67:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,047f723806ee702b211e7227f89eacd829aabd86@52.9.212.125:26656,b0e746acb6fbed7a0311fe21cfb2ee94581ca3bc@51.79.21.187:26656,82772547c4575c18dfe6e75aafe521cf7d4dc8de@142.93.157.186:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656"
```

Then start gaia with:

```
./gaiad start --x-crisis-skip-assert-invariants
```

and wait for around 1 hour at least

**Comment by tac0turtle** [comment]
what is the amount of ram you have on the server?

**Comment by jun0tpyrc** [comment]
> what is the amount of ram you have on the server?

it doesn't take much for non-validator , on a 8gb machine it seems take ~1 gb consistently

**Comment by tac0turtle** [comment]
At this time there isn't anything we can do. The sdk needs to modify how it ingests the genesis file. You could try to circumnavigate this long start time by state syncing. This depends on nodes in the network taking snapshots of current state

**Comment by gituser** [comment]
@marbar3778 would be good to print some info regarding the waiting interval and that there is no need to panic.

**Comment by tac0turtle** [comment]
> @marbar3778 would be good to print some info regarding the waiting interval and that there is no need to panic.

Will open an issue in the sdk.

**Comment by shahankhatch** [comment]
Closing as it's not a bug per se, and Marko's got it covered on the sdk side.

**Comment by zhangsj** [comment]
gaiad --home /opt/cosmos/ start --x-crisis-skip-assert-invariants
12:36PM INF starting ABCI with Tendermint
12:36PM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
12:36PM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting EventBus service impl={"Logger":{}} module=events
12:36PM INF Starting PubSub service impl={"Logger":{}} module=pubsub
12:36PM INF Starting IndexerService service impl={"Logger":{}} module=txindex
12:36PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
12:36PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
1:35PM INF created new capability module=ibc name=ports/transfer
1:35PM INF port binded module=x/ibc/port port=transfer
1:35PM INF claimed capability capability=1 module=transfer name=ports/transfer
1:35PM INF Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=consensus
1:35PM INF Version info block=11 p2p=8 software=
1:35PM INF This node is not a validator addr=2A67C51FBDCC102B41EE82308358086CA599842D module=consensus pubKey=R+vEt2YdRwpt87mA5+snbHcbNIzJ/YaoaCwB6ym6ppI=
1:35PM INF P2P Node ID ID=d1b3d9fd15481ed35454b52c6dc01bb50acc0a6f file=/opt/cosmos/config/node_key.json module=p2p
1:35PM INF Adding persistent peers addrs=[] module=p2p
1:35PM INF Adding unconditional peer ids ids=[] module=p2p
1:35PM INF Add our address to book addr={"id":"d1b3d9fd15481ed35454b52c6dc01bb50acc0a6f","ip":"0.0.0.0","port":26656} book=/opt/cosmos/config/addrbook.json module=p2p
1:35PM INF Starting Node service impl={"Logger":{}}
1:35PM INF Starting P2P Switch service impl={"Logger":{}} module=p2p
1:35PM INF Starting PEX service impl={"Logger":{},"Switch":{"Logger":{}}} module=pex
1:35PM INF Starting RPC HTTP server on 127.0.0.1:26657 module=rpc-server
1:35PM INF Starting AddrBook service book=/opt/cosmos/config/addrbook.json impl={"Logger":{}} module=p2p
1:35PM INF Starting Mempool service impl={"Logger":{},"Switch":{"Logger":{}}} module=mempool
1:35PM INF Starting BlockchainReactor service impl={"Logger":{},"Switch":{"Logger":{}}} module=blockchain
1:35PM INF Starting BlockPool service impl={"Logger":{}} module=blockchain
1:35PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
1:35PM INF No addresses to dial. Falling back to seeds module=pex
1:35PM INF Starting Consensus service impl={"Logger":{},"Metrics":{"BlockIntervalSeconds":{},"BlockParts":{},"BlockSizeBytes":{},"ByzantineValidators":{},"ByzantineValidatorsPower":{},"CommittedHeight":{},"FastSyncing":{},"Height":{},"MissingValidators":{},"MissingValidatorsPower":{},"NumTxs":{},"Rounds":{},"StateSyncing":{},"TotalTxs":{},"ValidatorLastSignedHeight":{},"ValidatorMissedBlocks":{},"ValidatorPower":{},"Validators":{},"ValidatorsPower":{}},"Switch":{"Logger":{}}} module=consensus
1:35PM INF Reactor module=consensus waitSync=true
1:35PM INF Starting Evidence service impl={"Logger":{},"Switch":{"Logger":{}}} module=evidence
1:35PM INF Starting StateSync service impl={"Logger":{},"Switch":{"Logger":{}}} module=statesync
1:35PM INF Saving AddrBook to file book=/opt/cosmos/config/addrbook.json module=p2p size=0
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/server/config.GetConfig(0xc00107b8c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/cosmos/cosmos-sdk@v0.41.3/server/config/config.go:197 +0xc19
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000fd9560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2069e00, 0xc000f54530, ...)
github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:264 +0x66f
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000fe2500, 0xc001058e10, 0x0, 0x3, 0x0, 0x0)
github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:120 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000fe2500, 0xc001066380, 0x3, 0x4, 0xc000fe2500, 0xc001066380)
github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e93400, 0x0, 0x0, 0xc000f485b0)
github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e93400, 0xc000f485b0, 0xb, 0x207c8c0, 0xc000f54530)
github.com/cosmos/cosmos-sdk@v0.41.3/server/cmd/execute.go:36 +0x265
main.main()
github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x45

**Comment by gituser** [comment]
@zhangsj 

Try doing this:

```
gaiad --home=/opt/cosmos unsafe-reset-all
```

and also copy new genesis.json into the `/opt/cosmos/config`:
```
wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz 
gzip -d genesis.cosmoshub-4.json.gz 
mv genesis.cosmoshub-4.json /opt/cosmos/config/genesis.json
```

Follow this migration doc - https://github.com/cosmos/gaia/blob/main/docs/migration/cosmoshub-3.md it should work for you.

**Comment by zebpay-peswani** [comment]
@gituser I did the same but when I start node it stuck at 

```
12:16PM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
12:16PM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:16PM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:16PM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:16PM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:16PM INF Starting EventBus service impl={"Logger":{}} module=events
12:16PM INF Starting PubSub service impl={"Logger":{}} module=pubsub
12:16PM INF Starting IndexerService service impl={"Logger":{}} module=txindex
12:16PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
12:16PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0

```
Do you know how much time it takes to sync?

**Comment by gituser** [comment]
@zebpay-peswani 

if you ran with `--x-crisis-skip-assert-invariants` like `gaiad --home /opt/cosmos/ start --x-crisis-skip-assert-invariants` it should take approximately 30-90 minutes. Just wait it will progress after some time.

**Comment by zebpay-peswani** [comment]
yes I started with `gaiad start --home=/blockchain/.gaiad --x-crisis-skip-assert-invariants`. I'll let you know in 2-3 hours how it goes.

**Comment by zebpay-peswani** [comment]
this is what I get 

```
1:39PM INF Starting RPC HTTP server on 127.0.0.1:26657 module=rpc-server
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/server/config.GetConfig(0xc000e1e120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/config/config.go:197 +0xc19
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000cf7840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20816c0, 0xc000c9dac0, ...)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:264 +0x66f
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000cfe780, 0xc000cf79c0, 0x0, 0x2, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:120 +0x1c8
github.com/spf13/cobra.(*Command).execute(0xc000cfe780, 0xc000cf79a0, 0x2, 0x2, 0xc000cfe780, 0xc000cf79a0)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c35680, 0x0, 0x0, 0xc000ca96e0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000c35680, 0xc000ca96e0, 0x12, 0x20941e0, 0xc000c9dac0)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/cmd/execute.go:36 +0x265
main.main()
	github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x45
```

**Comment by gituser** [comment]
@zebpay-peswani 

try doing all steps from scratch with empty cosmos data directory following this guide - https://github.com/cosmos/gaia/blob/main/docs/gaia-tutorials/join-mainnet.md
