### ISSUE TITLE
cosmoshub-4 panic 

### ISSUE THREAD

**Issue by ChainCoderX** [cosmos/gaia#648]
gaiad start --rpc.laddr tcp://0.0.0.0:26657  --home   ./cosmos-mainnet-data    --x-crisis-skip-assert-invariants     

6:33PM INF Starting Evidence service impl={"Logger":{},"Switch":{"Logger":{}}} module=evidence
6:33PM INF Starting StateSync service impl={"Logger":{},"Switch":{"Logger":{}}} module=statesync
6:33PM INF Starting PEX service impl={"Logger":{},"Switch":{"Logger":{}}} module=pex
6:33PM INF Starting AddrBook service book=cosmos-mainnet-data/config/addrbook.json impl={"Logger":{}} module=p2p
6:33PM INF Starting Mempool service impl={"Logger":{},"Switch":{"Logger":{}}} module=mempool
6:33PM INF Saving AddrBook to file book=cosmos-mainnet-data/config/addrbook.json module=p2p size=0
6:33PM INF Starting RPC HTTP server on [::]:26657 module=rpc-server
6:33PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
6:33PM INF No addresses to dial. Falling back to seeds module=pex
6:33PM INF Dialing peer address={"id":"27f8dd3bdbecbef7192291083706c156e523d8e0","ip":"3.122.248.21","port":26656} module=p2p
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/server/config.GetConfig(0xc000f818c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.41.2/server/config/config.go:197 +0xc19
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000eef360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x206bcc0, 0xc000e37dd0, ...)
        github.com/cosmos/cosmos-sdk@v0.41.2/server/start.go:264 +0x66f
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000ee6500, 0xc000e50c30, 0x0, 0x5, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.41.2/server/start.go:120 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000ee6500, 0xc000e50be0, 0x5, 0x5, 0xc000ee6500, 0xc000e50be0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000411400, 0x0, 0x0, 0xc000e48fc0)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000411400, 0xc000e48fc0, 0x12, 0x207e7e0, 0xc000e37dd0)
        github.com/cosmos/cosmos-sdk@v0.41.2/server/cmd/execute.go:36 +0x265
main.main()
        github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x45

**Comment by shahankhatch** [comment]
What version is this running?

**Comment by gituser** [comment]
most likely you are using old configuration with newer gaia

you need to remove old config files or specify different empty `--home`

**Comment by congle-ibl** [comment]
Same issue. I'm running latest version v4.0.3. Here is my error log, please help to take a look:
```
1|start-cosmos-mainnet  | 4:31AM INF starting ABCI with Tendermint
1|start-cosmos-mainnet  | 4:31AM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
1|start-cosmos-mainnet  | 4:31AM INF Starting EventBus service impl={"Logger":{}} module=events
1|start-cosmos-mainnet  | 4:31AM INF Starting PubSub service impl={"Logger":{}} module=pubsub
1|start-cosmos-mainnet  | 4:31AM INF Starting IndexerService service impl={"Logger":{}} module=txindex
1|start-cosmos-mainnet  | 4:31AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
1|start-cosmos-mainnet  | 4:31AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=5200791
1|start-cosmos-mainnet  | 5:14AM INF created new capability module=ibc name=ports/transfer
1|start-cosmos-mainnet  | 5:14AM INF port binded module=x/ibc/port port=transfer
1|start-cosmos-mainnet  | 5:14AM INF claimed capability capability=1 module=transfer name=ports/transfer
1|start-cosmos-mainnet  | panic: 
1|start-cosmos-mainnet  | StoreBlockHeight (5200791) > StateBlockHeight + 1 (1)
1|start-cosmos-mainnet  | goroutine 
1|start-cosmos-mainnet  | 1 [running]:
1|start-cosmos-mainnet  | github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc01af98420, 0xb, 0x0, 0x0, 0x0, 0xc00050fa80, 0xb, 0x4f5b97, 0x0, 0x0, ...)
1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/consensus/replay.go:382 +0x172b
1|start-cosmos-mainnet  | github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01af98420, 0x20927a0, 0xc0000a40d0, 0xc000cb1910, 0x1)
1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/consensus/replay.go:268 +0x478
1|start-cosmos-mainnet  | github.com/tendermint/tendermint/node.doHandshake(0x208e620, 0xc001182430, 0xb, 0x0, 0x0, 0x0, 0xc00050fa80, 0xb, 0x4f5b97, 0x0, ...)
1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/node/node.go:277 +0x1d8
1|start-cosmos-mainnet  | github.com/tendermint/tendermint/node.NewNode(0xc000ec4f00, 0x206fe00, 0xc00039b0e0, 0xc0004e1560, 0x203ace0, 0xc000d43640, 0xc0004e15d0, 0x1e74f30, 0xc0004e16c0, 0x2079700, ...)
1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/node/node.go:685 +0x1e05
1|start-cosmos-mainnet  | github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f92620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20816c0, 0xc000e7fd10, ...)
1|start-cosmos-mainnet  | 	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:244 +0x565
1|start-cosmos-mainnet  | github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000ee4000, 0xc000fb6ae0, 0x0, 0x3, 0x0, 0x0)
1|start-cosmos-mainnet  | 	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:120 +0x1c8
1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).execute(0xc000ee4000, 0xc000fb6a80, 0x3, 0x3, 0xc000ee4000, 0xc000fb6a80)
1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).ExecuteC(0xc000e68f00, 0x0, 0x0, 0xc000e97660)
1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go
1|start-cosmos-mainnet  | :960 +0x375
1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).Execute(...)
1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go:897
1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).ExecuteContext(...)
1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go:890
1|start-cosmos-mainnet  | github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e68f00, 0xc000e97660, 0x12, 0x20941e0, 0xc000e7fd10)
1|start-cosmos-mainnet  | 	github.com/cosmos/cosmos-sdk@v0.41.3/server/cmd/execute.go:36 +0x265
1|start-cosmos-mainnet  | main.main()
1|start-cosmos-mainnet  | 	github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x45
```

**Comment by JohnsonCaii** [comment]
> Same issue. I'm running latest version v4.0.3. Here is my error log, please help to take a look:
> 
> ```
> 1|start-cosmos-mainnet  | 4:31AM INF starting ABCI with Tendermint
> 1|start-cosmos-mainnet  | 4:31AM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
> 1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
> 1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
> 1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
> 1|start-cosmos-mainnet  | 4:31AM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
> 1|start-cosmos-mainnet  | 4:31AM INF Starting EventBus service impl={"Logger":{}} module=events
> 1|start-cosmos-mainnet  | 4:31AM INF Starting PubSub service impl={"Logger":{}} module=pubsub
> 1|start-cosmos-mainnet  | 4:31AM INF Starting IndexerService service impl={"Logger":{}} module=txindex
> 1|start-cosmos-mainnet  | 4:31AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
> 1|start-cosmos-mainnet  | 4:31AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=5200791
> 1|start-cosmos-mainnet  | 5:14AM INF created new capability module=ibc name=ports/transfer
> 1|start-cosmos-mainnet  | 5:14AM INF port binded module=x/ibc/port port=transfer
> 1|start-cosmos-mainnet  | 5:14AM INF claimed capability capability=1 module=transfer name=ports/transfer
> 1|start-cosmos-mainnet  | panic: 
> 1|start-cosmos-mainnet  | StoreBlockHeight (5200791) > StateBlockHeight + 1 (1)
> 1|start-cosmos-mainnet  | goroutine 
> 1|start-cosmos-mainnet  | 1 [running]:
> 1|start-cosmos-mainnet  | github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc01af98420, 0xb, 0x0, 0x0, 0x0, 0xc00050fa80, 0xb, 0x4f5b97, 0x0, 0x0, ...)
> 1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/consensus/replay.go:382 +0x172b
> 1|start-cosmos-mainnet  | github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01af98420, 0x20927a0, 0xc0000a40d0, 0xc000cb1910, 0x1)
> 1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/consensus/replay.go:268 +0x478
> 1|start-cosmos-mainnet  | github.com/tendermint/tendermint/node.doHandshake(0x208e620, 0xc001182430, 0xb, 0x0, 0x0, 0x0, 0xc00050fa80, 0xb, 0x4f5b97, 0x0, ...)
> 1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/node/node.go:277 +0x1d8
> 1|start-cosmos-mainnet  | github.com/tendermint/tendermint/node.NewNode(0xc000ec4f00, 0x206fe00, 0xc00039b0e0, 0xc0004e1560, 0x203ace0, 0xc000d43640, 0xc0004e15d0, 0x1e74f30, 0xc0004e16c0, 0x2079700, ...)
> 1|start-cosmos-mainnet  | 	github.com/tendermint/tendermint@v0.34.7/node/node.go:685 +0x1e05
> 1|start-cosmos-mainnet  | github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f92620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20816c0, 0xc000e7fd10, ...)
> 1|start-cosmos-mainnet  | 	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:244 +0x565
> 1|start-cosmos-mainnet  | github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000ee4000, 0xc000fb6ae0, 0x0, 0x3, 0x0, 0x0)
> 1|start-cosmos-mainnet  | 	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:120 +0x1c8
> 1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).execute(0xc000ee4000, 0xc000fb6a80, 0x3, 0x3, 0xc000ee4000, 0xc000fb6a80)
> 1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
> 1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).ExecuteC(0xc000e68f00, 0x0, 0x0, 0xc000e97660)
> 1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go
> 1|start-cosmos-mainnet  | :960 +0x375
> 1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).Execute(...)
> 1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go:897
> 1|start-cosmos-mainnet  | github.com/spf13/cobra.(*Command).ExecuteContext(...)
> 1|start-cosmos-mainnet  | 	github.com/spf13/cobra@v1.1.3/command.go:890
> 1|start-cosmos-mainnet  | github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e68f00, 0xc000e97660, 0x12, 0x20941e0, 0xc000e7fd10)
> 1|start-cosmos-mainnet  | 	github.com/cosmos/cosmos-sdk@v0.41.3/server/cmd/execute.go:36 +0x265
> 1|start-cosmos-mainnet  | main.main()
> 1|start-cosmos-mainnet  | 	github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x45
> ```

How did you catch-up on the blockchain height to 5200791? I thought you need to sync the whole network from scratch, why so fast?

**Comment by shahankhatch** [comment]
Hey @congle-ibl It looks like your migration above was set to start one block higher than what was decided (on social consensus). I think the block height to resume the chain on was '90 (above shows '91).
