### ISSUE TITLE
Start cosmoshub-4 from a scratch? Can't use previous data of cosmoshub-3?

### ISSUE THREAD

**Issue by congle-ibl** [cosmos/gaia#653]
Hi all,

I'm upgrade my node following this guide:
https://github.com/cosmos/gaia/blob/main/docs/migration/cosmoshub-3.md

But I found that, after backing up old data of cosmoshub-3, it wasn't used for running cosmoshub-4.
So I have to sync data for cosmoshub-4 from a scratch. Is it right?

Please help to take a look and confirm. Thanks a lot.

**Comment by JohnsonCaii** [comment]
Same issues, seems not many people out there running an atom node? Is there a public node?

**Comment by matyushkins** [comment]
As we noticed, the new network is starting from scratch. it retained only balances and delegations. So this is the norm. All the old story has been dropped. And it seems like somewhere they wrote that the new network starts from scratch.

**Comment by shahankhatch** [comment]
To access the old sate, start an instance of v2.0.15 with your old data/configs/keys but leave the peer and seed list empty. This way you can start the old node and can query it without trying to dial/sync. 

What @matyushkins describes above is correct.
