### ISSUE TITLE
hub-4 full node can not start

### ISSUE THREAD

**Issue by zhangsj** [cosmos/gaia#655]
https://github.com/cosmos/gaia/blob/main/docs/migration/cosmoshub-3.md
upgrade the full node ,no running.

gaiad --home /opt/cosmos/ start --x-crisis-skip-assert-invariants
12:36PM INF starting ABCI with Tendermint
12:36PM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
12:36PM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
12:36PM INF Starting EventBus service impl={"Logger":{}} module=events
12:36PM INF Starting PubSub service impl={"Logger":{}} module=pubsub
12:36PM INF Starting IndexerService service impl={"Logger":{}} module=txindex
12:36PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
12:36PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
1:35PM INF created new capability module=ibc name=ports/transfer
1:35PM INF port binded module=x/ibc/port port=transfer
1:35PM INF claimed capability capability=1 module=transfer name=ports/transfer
1:35PM INF Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=consensus
1:35PM INF Version info block=11 p2p=8 software=
1:35PM INF This node is not a validator addr=2A67C51FBDCC102B41EE82308358086CA599842D module=consensus pubKey=R+vEt2YdRwpt87mA5+snbHcbNIzJ/YaoaCwB6ym6ppI=
1:35PM INF P2P Node ID ID=d1b3d9fd15481ed35454b52c6dc01bb50acc0a6f file=/opt/cosmos/config/node_key.json module=p2p
1:35PM INF Adding persistent peers addrs=[] module=p2p
1:35PM INF Adding unconditional peer ids ids=[] module=p2p
1:35PM INF Add our address to book addr={"id":"d1b3d9fd15481ed35454b52c6dc01bb50acc0a6f","ip":"0.0.0.0","port":26656} book=/opt/cosmos/config/addrbook.json module=p2p
1:35PM INF Starting Node service impl={"Logger":{}}
1:35PM INF Starting P2P Switch service impl={"Logger":{}} module=p2p
1:35PM INF Starting PEX service impl={"Logger":{},"Switch":{"Logger":{}}} module=pex
1:35PM INF Starting RPC HTTP server on 127.0.0.1:26657 module=rpc-server
1:35PM INF Starting AddrBook service book=/opt/cosmos/config/addrbook.json impl={"Logger":{}} module=p2p
1:35PM INF Starting Mempool service impl={"Logger":{},"Switch":{"Logger":{}}} module=mempool
1:35PM INF Starting BlockchainReactor service impl={"Logger":{},"Switch":{"Logger":{}}} module=blockchain
1:35PM INF Starting BlockPool service impl={"Logger":{}} module=blockchain
1:35PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
1:35PM INF No addresses to dial. Falling back to seeds module=pex
1:35PM INF Starting Consensus service impl={"Logger":{},"Metrics":{"BlockIntervalSeconds":{},"BlockParts":{},"BlockSizeBytes":{},"ByzantineValidators":{},"ByzantineValidatorsPower":{},"CommittedHeight":{},"FastSyncing":{},"Height":{},"MissingValidators":{},"MissingValidatorsPower":{},"NumTxs":{},"Rounds":{},"StateSyncing":{},"TotalTxs":{},"ValidatorLastSignedHeight":{},"ValidatorMissedBlocks":{},"ValidatorPower":{},"Validators":{},"ValidatorsPower":{}},"Switch":{"Logger":{}}} module=consensus
1:35PM INF Reactor  module=consensus waitSync=true
1:35PM INF Starting Evidence service impl={"Logger":{},"Switch":{"Logger":{}}} module=evidence
1:35PM INF Starting StateSync service impl={"Logger":{},"Switch":{"Logger":{}}} module=statesync
1:35PM INF Saving AddrBook to file book=/opt/cosmos/config/addrbook.json module=p2p size=0
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/server/config.GetConfig(0xc00107b8c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/config/config.go:197 +0xc19
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000fd9560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2069e00, 0xc000f54530, ...)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:264 +0x66f
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000fe2500, 0xc001058e10, 0x0, 0x3, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:120 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000fe2500, 0xc001066380, 0x3, 0x4, 0xc000fe2500, 0xc001066380)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e93400, 0x0, 0x0, 0xc000f485b0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e93400, 0xc000f485b0, 0xb, 0x207c8c0, 0xc000f54530)
	github.com/cosmos/cosmos-sdk@v0.41.3/server/cmd/execute.go:36 +0x265
main.main()
	github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x45

**Comment by shahankhatch** [comment]
The error looks like a config issue. Are you reusing the previous config? The migration is intended to recreate the configs. Can you please include the steps you took?

**Comment by somebodyLi** [comment]
any process ???

**Comment by tac0turtle** [comment]
I think this is a issue with one our dependencies. I'm not sure which but there isnt a reason this should be happening. 

We should reopen and do some investigating as I have seen this error pop up quite a bit since the chain upgrade.
