### ISSUE TITLE
RFC Interchain Staking Light Paper

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#659]
## Summary
Create a RFC for Cross Chain Validation to track discussion that should result in an eventual ADR

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nylira** [comment]
I think this should be renamed Interchain Staking, at least for marketing purposes. Interchain is a very strong brand that Cosmos current owns. Cross-chain is super generic. And we also want to let ATOM stakers understand that this is a feature not just for validators, but for validators and delegators combined (i.e., stakers).
