### ISSUE TITLE
Increased difficulty to join validator set

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#66]
to reduce the frequency of kicking off validators - we can push how much more bonded token you need to have in order kick off the last validator... ideas:
 - 5% more bonded tokens than the last validator
 - need to have more bonded tokens then validator 98, 97, or 96 (etc.) 

Objections/ideas?

**Comment by adrianbrink** [comment]
I agree. Without this there might be a hot swamp of validators at the bottom of the list with someone leaving/joining all the time. 

Ideally we want to create a formula for how much more a new validator needs before being admitted but for now I think it's okay to just assume that he needs 5% more than the 100th validator.

**Comment by rigelrozanski** [comment]
HOT SWAMP of validators hahahahaha <3 <3 <3

**Comment by rigelrozanski** [comment]
Added to spec in `feature/provisions`

**Comment by rigelrozanski** [comment]
Discussed with @ebuchman, doesn't sound like this will be an issues so long as we don't change the validator set every block... I propose we change the validator set at the same increment which provide atom provisions which is once per hour (first block of each hour).

**Comment by zramsay** [comment]
closing given last comment. re-open in SDK repo if applicable
