### ISSUE TITLE
Log gaiad, cosmos-sdk, tm versions on startup

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#661]
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
this can be done via gaiad version --long. this is the recommended way for now. When the user installs the binary, the versions are logged as well.
