### ISSUE TITLE
[Feature] statesync rpc_servers

### ISSUE THREAD

**Issue by dualsystems** [cosmos/gaia#671]
## Summary
Current version tendermind includes support for state sync.

## Problem Definition
Long time for sync node.

## Proposal
Create a list of public rpc_servers with the enabled statesync option.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dualsystems** [comment]
Error: failed to start state sync: failed to set up light client state provider: at least 2 RPC servers are required, got 0

**Comment by faddat** [comment]
I like this suggestion and think that the only thing we might be able to do even better is bake seeds and RPCs into `gaiad`.

**Comment by tac0turtle** [comment]
This is being done as part of atlas.cosmos.network. You can follow the work here: https://github.com/cosmos/atlas/pull/63

**Comment by faddat** [comment]
@dualsystems Soon as my node is synced (we should look into sync times) I will put up a state sync RPC and share info here. 

It should be default behavior, because I am anticipating #704 and sync is really not fast at all, even on my 12 core / 128gb / raid 0 nvme machine.

**Comment by faddat** [comment]
I think this is completed here, and is safe to close. Also, it is now pretty easy to state sync. 

https://github.com/cosmos/gaia/pull/1027
