### ISSUE TITLE
Insta-run Docker image

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#675]
## Summary

Includes:

* Genesis
* Seeds

## Problem Definition

This reduces starting a node to:

```
docker run cosmos/gaia
```

## Proposal

Create a Dockerfile that contains genesis & seeds are present in CMD. 

May be more complex, because of init.  
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
This isn't possible for the initial release of a chain upgrade. Until the chain is upgraded we dont know that the genesis is. it would be easier to write a way to fetch the genesis on init. This would only work once there is a genesis as well tho. 

I have a demo of something like this, but never got around to completing it. I can look back at it in the coming days.

**Comment by faddat** [comment]
You are right.

I just ran into it while making the Dockerfile, came to note that in the repo, and saw your comment.

**Comment by faddat** [comment]
Closing this in favor of #678 #677 

This was unfortunately an unworkable stopgap solution without changes to init, which would see genesis.json and the only options are to overwrite or not.

**Comment by THEBOLCK79** [comment]
> 
> 
> ## Summary
> 
> Includes:
> 
> * Genesis
> * Seeds
> 
> 
> ## Problem Definition
> 
> This reduces starting a node to:
> 
> ```
> docker run cosmos/gaia
> ```
> 
> ## Proposal
> 
> Create a Dockerfile that contains genesis & seeds are present in CMD. 
> 
> May be more complex, because of init.  
> ____
> 
> #### For Admin Use
> 
> - [ ] Not duplicate issue
> - [ *] Appropriate labels applied
> - [* ] Appropriate contributors tagged
> - [ ] Contributor assigned/self-assigned
>
