### ISSUE TITLE
Embed Genesis

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#677]
## Summary

Go 1.16 has support for `embed` and gaia could carry mainnet genesis with her in the default build.  

## Problem Definition

* Chasing down the genesis.json file increases "time to fully operational node"

## Proposal

The cosmos SDK expects that genesis.json is always in the home directory.  We can modify the cosmos SDK to support embedded genesis.  When it does not find one, it falls back to looking in the home directory. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by shahankhatch** [comment]
While I support the notion of having mainnet genesis automatically available, I'm not in favour of the `embed` approach on this gaia repo for the following reasons:
- does not follow a practice of separating data from code
- gaia has releases with increasing frequency, but the genesis will be fairly static
- each platform binary generated from reproducible builds, even if the genesis is 20MB compressed, unnecessarily bloats the size of releases by 50% just to carry fairly-static data
- It's straightforward to include a command to download the genesis before startup or on build for mainnet that can achieve this, while maintaining the genesis file in a separate location outside of the code repo

**Comment by faddat** [comment]
So I am looking at it from more of a user perspective -- people currently have trouble getting their node going for the first time, mainly due to issues with seeds and genesis.

This said there are other ways to skin the cat, but Docker really did not look like one of them. The genesis, I'd imagine, will be entirely static, until a new network is launched, right?  

Thinking is to reduce the user-workload to simply downloading `gaiad`.

**Comment by shahankhatch** [comment]
Yes, the genesis will be static until the next upgrade. 

The idea you mentioned of using curl still appeals to me. wdyt of using that for seeds and genesis?

**Comment by faddat** [comment]
I did it once, and could do it again-- in fact, I just noticed that we're shipping compiled binaries now, means that the majority of this is a `cherry pick` away. 

https://github.com/galaxypi/galaxy/blob/master/install.sh

In that repository there's a mac flavored script and a linux-flavored script, but while writing this I realized there's a practical way to support both OSes from the same script without much difficulty.  Does the approach in that script work for you?

Thinking it may be best to remove the uninstaller lest someone delete their precious information.  

If that approach works, I can close these two issues and open up a `One-Liner Install` issue.

**Comment by andynog** [comment]
Agree with @shahankhatch, not a big fan of combining data and code, might lead into other problems. Not sure how embed in Go 1.16 is implemented but if it has to read the all the bytes in memory might not be feasible because the genesis uncompressed is getting larger and this would require a good amount of RAM, not sure exactly how the SDK process the genesis but I believe it might parse it so it is like processing chunks then having it separate would probably be better.

**Comment by faddat** [comment]
Alright, I think that these two issues can be closed, since it seems that we should keep from shipping state with Gaia.  

I'll make an issue for the one-liner install and adapt the Galaxy installer to Gaia's needs. 

I'll also take the embed seeds issue, and move it over to the SDK repo.

**Comment by faddat** [comment]
Discussion moved here:

https://github.com/cosmos/cosmos-sdk/issues/8720
