### ISSUE TITLE
Documenting parameters

### ISSUE THREAD

**Issue by nylira** [cosmos/gaia#68]
## Summary

Could we add a page to the documentation that shows all of the current parameters of the Cosmos Hub?

## Problem Definition

It's unclear to the community how long the unbonding period is, the exact percent slashed for validator double-signing, the amount slashed over time for validators that go offline, things like that. Can we document this? If it's in the docs it'll show up on https://hub.cosmos.network.

## Proposal

Document the relevant parameters of the Cosmos Hub that would otherwise require querying endpoints.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
The params themselves are already documented in the SDK (e.g. [here](https://github.com/cosmos/cosmos-sdk/blob/master/docs/spec/governance/06_params.md)). 

Now the actual specific parameters of the Hub are another story. I don't see the benefit of having these actual values documented as they're dynamic -- they can change live on-chain. This would require us to constantly keep an eye on this doc and keep it up to date (we already have trouble doing this).

All the parameters are queryable by a module's `/params` REST endpoint. IMHO, params should ideally be exposed on most, if not all, block explorers.
