### ISSUE TITLE
Inflation affected immediately from unbonding blocks

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#68]
idea from frey
exclude unbonding blocks from the inflation rate change algorithm

**Comment by adrianbrink** [comment]
What's the advantage?

**Comment by rigelrozanski** [comment]
faster response for inflation rate change (aka if you started unbonding - inflation should would change immediately...) think this makes sense

**Comment by rigelrozanski** [comment]
This will be included by default now that unbonding atoms do not collect rewards and the mechanism removes them from `GlobalState.BondedTokens` as soon as the unbond transaction begins
