### ISSUE TITLE
gaiad start  too slowly,It's not ready for two hours

### ISSUE THREAD

**Issue by Black52** [cosmos/gaia#692]
[root@block-centos gaia]# gaiad start --p2p.seeds bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656
11:16AM INF starting ABCI with Tendermint
11:16AM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
11:16AM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
11:16AM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
11:16AM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
11:16AM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
11:16AM INF Starting EventBus service impl={"Logger":{}} module=events
11:16AM INF Starting PubSub service impl={"Logger":{}} module=pubsub
11:16AM INF Starting IndexerService service impl={"Logger":{}} module=txindex
11:16AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
11:16AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0

**Comment by tac0turtle** [comment]
known issue please see: https://github.com/cosmos/gaia/issues/669.

We are working on a solution
