### ISSUE TITLE
Often out of sync, need to restart。And failed to start with supervisor

### ISSUE THREAD

**Issue by atoken-ops** [cosmos/gaia#697]
Often out of sync, need to restart
version 4.0.4
8c
16GB
1T SSD

with supervisor
error log:
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/simapp.init.0()
        github.com/cosmos/cosmos-sdk@v0.41.3/simapp/app.go:193 +0xe5
panic: $HOME is not defined

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/simapp.init.0()
        github.com/cosmos/cosmos-sdk@v0.41.3/simapp/app.go:193 +0xe5

**Comment by lukitsbrian** [comment]
I had the same issue with `systemd` and was able to fix it by defining my environment in my service file.

```
[Service]
Environment="HOME=/home"
``` 

The supervisor equivalent should be something like this - 

```
[program:gaiad]
environment=HOME=/home
```

**Comment by zhangsj** [comment]
> I had the same issue with `systemd` and was able to fix it by defining my environment in my service file.
> 
> ```
> [Service]
> Environment="HOME=/home"
> ```
> 
> The supervisor equivalent should be something like this -
> 
> ```
> [program:gaiad]
> environment=HOME=/home
> ```

tks

**Comment by faddat** [comment]
Are you querying your node frequently?

If you are querying your node frequently, what queries are you making?

Thank you!

**Comment by tac0turtle** [comment]
Closing due to staleness. if you still have issues, please feel free to ask in the discord.
