### ISSUE TITLE
docs: add note on migration 

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/gaia#699]
## Summary

Right now its unclear if someone should do the migration step or download the genesis. 

## Proposal

Add a note at the top of the file to redirect people to a different section for joining

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mmulji-ic** [comment]
@marbar3778 Is this still relevant? Require more details.
