### ISSUE TITLE
One-Liner install script

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#705]
## Summary

It would be nice to give users an instant way to get a node up and running directly on Readme.md without cluttering it up with a code snippet. 

## Problem Definition

Currently, setting up Gaia takes too many discrete steps and involves visiting numerous repositories for information.  

## Initial Proposal (scrapping)

Adapt the [Galaxy installer](https://github.com/galaxypi/galaxy/blob/master/install.sh) for use with Gaia.

- [ ] ~~Script should work on mac and windows~~

## 2nd Proposal

After looking this over, to be cross-platform, it seems to make the most sense to make a script that serves as a container's entrypoint, or start packaging Gaia for choco, brew, and apt, at a minimum.   

contrib/instagaia/instagaia.sh

```bash
#!/bin/sh
#give the node a random moniker
gaiad init instagaia$RANDOM
# Start the node with the default set of seeds
gaiad start --p2p.seeds bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656
```

contrib/instagaia/Dockerfile
```Dockerfile
FROM tendermint/gaia

USER gaia

COPY contrib/instagaia/instagaia.sh /gaia/instagaia.sh

RUN wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz && \
           gzip -d genesis.cosmoshub-4.json.gz && \
           mv genesis.cosmoshub-4.json ~/gaia/genesis.json


EXPOSE 46657
EXPOSE 46656
EXPOSE 1317

ENTRYPOINT ["/bin/sh", "/gaia/instagaia.sh"]
```

This will give us something that can go on Readme.md which will look like this:

```bash
docker run tendermint/instagaia
```

- [x] Runs on Windows, Mac and Linux

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
This is going to end up using Docker, unless anyone's got any objections to that.

**Comment by okwme** [comment]
is this work still relevant or redundant with latest docker images?

**Comment by okwme** [comment]
closing for lack of reply
