### ISSUE TITLE
Gaia update MaxValidatorSet to 125

### ISSUE THREAD

**Issue by ronaldstoner** [cosmos/gaia#707]
## Summary

Currently, Gaia uses the value of 100 for MaxValidatorSet (`gaiad query tendermint-validator-set` for example). Proposal 10 - https://www.mintscan.io/cosmos/proposals/10 - passed and increased the max set to 125 in July of 2019. 

## Problem Definition

Using the previous value of 100 causes a limited data view of the actual validator set of 125 when attempting validator troubleshooting commands such as `gaiad query tendermint-validator-set | grep "$(gaiad tendermint show-address)` which is referenced in validator setup documentation at https://hub.cosmos.network/main/validators/validator-setup.html.

It should be noted that setting the `--limit` flag to 125 does not have the desired effect. 

## Proposal

Change MaxValidatorSet to 125 and associated tests and code for validator set. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MarcelMWS** [comment]
it's a bit unfortunate, but you can try using the parameter --page 2 at the end of the command or set maxPerPage  = 125 in tendermint (~/go/src/github.com/tendermint/tendermint/rpc/core/env.go) and compile your gaia version

**Comment by tac0turtle** [comment]
this is done because of pagination, you can increase it via a cmd. 

```
❯ gaiad query tendermint-validator-set -h
Get the full tendermint validator set at given height

Usage:
  gaiad query tendermint-validator-set [height] [flags]
Flags:
  -h, --help                     help for tendermint-validator-set
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test) (default "os")
      --limit int                Query number of results returned per page (default 100)
  -n, --node string              Node to connect to (default "tcp://localhost:26657")
      --page int                 Query a specific page of paginated results (default 1)
```
