### ISSUE TITLE
error message refers to basecli/bascoin

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#71]
```
ERROR: `init` takes one argument, a basecoin account address. Generate one using `basecli keys new mykey`
```

**Comment by rigelrozanski** [comment]
Okay - yeah this is a larger issue of how we deal with errors for commands which are imported such as this basecli - thoughts? I wish we could pass in our own error messages to commands we wish to reuse

**Comment by rigelrozanski** [comment]
I almost think this one should wait until new SDK

**Comment by zramsay** [comment]
will be handled in SDK repo
