### ISSUE TITLE
how get version

### ISSUE THREAD

**Issue by atoken-ops** [cosmos/gaia#717]
4.0.5
gaiad version
Error: failed to parse log level (main:info,state:info,statesync:info,*:error): Unknown Level String: 'main:info,state:info,statesync:info,*:error', defaulting to NoLevel
Usage:
  gaiad version [flags]

Flags:
  -h, --help            help for version
      --long            Print long version information
  -o, --output string   Output format (text|json) (default "text")

Global Flags:
      --home string         directory for config and data (default "/root/.gaia")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors

**Comment by shahankhatch** [comment]
I believe you need to clear golang's cache. This worked for me: `go clean -r -cache -modcache`

**Comment by adizere** [comment]
Just wanted to highlight that despite `go clean -r -cache -modcache` the error persists.

> $ gaiad version
> Error: failed to parse log level (main:info,state:info,statesync:info,*:error): Unknown Level String: 'main:info,state:info,statesync:info,*:error', defaulting to NoLevel
> Usage:
>   gaiad version [flags]
> 
> Flags:
>   -h, --help            help for version
>       --long            Print long version information
>   -o, --output string   Output format (text|json) (default "text")
> 
> Global Flags:
>       --home string         directory for config and data (default "/Users/adi/.gaia")
>       --log_format string   The logging format (json|plain) (default "plain")
>       --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
>       --trace               print out full stack trace on errors

One workaround is to specify the log level explicitly.

> $ gaiad version --log_level info
> v4.1.0

**Comment by zmanian** [comment]
you need update your `config.toml` to use the line `log_level = info` instead of something like  `'main:info,state:info,statesync:info,*:error'`
