### ISSUE TITLE
panic while sync  on testnet

### ISSUE THREAD

**Issue by tpkeeper** [cosmos/gaia#718]
## Summary of Bug

INF executed block height=157566 module=state num_invalid_txs=0 num_valid_txs=0
panic: failed to write batch: open /Users/tpkeeper/.gaia/data/application.db/035086.ldb: too many open files

goroutine 133 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc0000ba0a0, 0x0, 0x0, 0x0, 0x0)
	/Users/tpkeeper/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.4/store/iavl/store.go:113 +0x1e9
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0x2677e, 0xc000eb5410, 0x0)
	/Users/tpkeeper/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.4/store/rootmulti/store.go:919 +0x16b
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0001ea640, 0x2677e, 0x0, 0xc0024e46e0, 0x59f111f13956c25b)
	/Users/tpkeeper/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.4/store/rootmulti/store.go:344 +0x6b
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00010fa00, 0x0, 0x0, 0x0, 0x0)
	/Users/tpkeeper/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.4/baseapp/abci.go:293 +0x29c
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000138fc0, 0x0, 0x0, 0x0)
	/Users/tpkeeper/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/abci/client/local_client.go:258 +0xab
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc000e3d160, 0x0, 0x0, 0xc0055e07e0)
	/Users/tpkeeper/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/proxy/app_conn.go:93 +0x33
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc0005db2d0, 0xb, 0x0, 0x0, 0x0, 0xc0000a7450, 0xe, 0x1, 0x2677e, 0xc0040697c0, ...)
	/Users/tpkeeper/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/state/execution.go:228 +0x23f
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0005db2d0, 0xb, 0x0, 0x0, 0x0, 0xc0000a7450, 0xe, 0x1, 0x2677e, 0xc0040697c0, ...)
	/Users/tpkeeper/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/state/execution.go:180 +0x725
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000564a80, 0x0)
	/Users/tpkeeper/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/blockchain/v0/reactor.go:398 +0xa53
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/Users/tpkeeper/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/blockchain/v0/reactor.go:110 +0x8c
## Version

gaiad: 4.0.5
os: mac os 11.2.2
## Steps to Reproduce

gaiad start
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tpkeeper** [comment]
because of  opening the fast sync mode?

**Comment by tpkeeper** [comment]
@zmanian

**Comment by tac0turtle** [comment]
you will need to restart your node and resync. Before doing this read https://hub.cosmos.network/main/validators/validator-setup.html#problem-2-my-gaiad-crashes-because-of-too-many-open-files. It will help fix your problem.
