### ISSUE TITLE
[Hub] Improve CLI UX for joining mainnet

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#719]
To join mainnet, users have to `init` then overwrite the new genesis with the mainnet genesis. But this means that users are exposed to cli options when running init that are confusing and unnecessary for joining mainnet, e.g., chain-id.

The instant gratification script does an excellent job of automating this, but requires adaptation if some options are necessary, e.g., specifying the home, and leads to a path where cli options will still be considered for the adaptation.

Let's consider adding a way to join a chain with a given genesis that avoids the cli options that aren't necessary.

**Comment by mmulji-ic** [comment]
Sync with Hypha

**Comment by okwme** [comment]
docs are clear about use of the flag and it's important for running local instances.
would require hard-coding chain-id which is a possibility but not a priority atm.
going to close for now
