### ISSUE TITLE
Is it go.mod version error?

### ISSUE THREAD

**Issue by HyoungsungKim** [cosmos/gaia#72]
## Summary of Bug

Can not find github.com/cosmos/cosmos-sdk v0.28.2-0.20190709192957-95f60ea120f0 version

## Version

gaia the newest version install

## Steps to Reproduce

my go version is 1.12.7 

`make install` in github.com/cosmos/gaia repository

![gaia-err-in-install](https://user-images.githubusercontent.com/25428581/61185657-bdbb8880-a696-11e9-8e74-69cf9c0aa725.png)

```
hskim@hskim-labPC:~/go/src/github.com/cosmos/gaia$ make install
go: finding github.com/cosmos/cosmos-sdk v0.28.2-0.20190709192957-95f60ea120f0
go: github.com/cosmos/cosmos-sdk@v0.28.2-0.20190709192957-95f60ea120f0: unknown revision 95f60ea120f0
go: error loading module requirements
--> Ensure dependencies have not been modified
go: finding github.com/cosmos/cosmos-sdk v0.28.2-0.20190709192957-95f60ea120f0
go: github.com/cosmos/cosmos-sdk@v0.28.2-0.20190709192957-95f60ea120f0: unknown revision 95f60ea120f0
go: error loading module requirements
Makefile:106: recipe for target 'go.sum' failed
make: *** [go.sum] Error 1
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Will be closed/fixed by https://github.com/cosmos/gaia/issues/72.
