### ISSUE TITLE
Sort out various directories

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#73]
there's a default `~/.cosmos-gaia-cli` for keys, then different ones for chains and such. the tool should be clearer about what goes where

**Comment by rigelrozanski** [comment]
What do you think of this structure:
```
~/.cosmos/keys
~/.cosmos/client
~/.cosmos/node
```
keys should probably be a separate directory because they should never be removed. If you were to create different instance of gaia/cosmos you would probably just do the same thing under `~/.cosmos2/` or something

**Comment by adrianbrink** [comment]
@rigelrozanski I like your proposed structure. Also how about a command to reset everything except the keys. :-)

**Comment by rigelrozanski** [comment]
Yeah keys should maybe be kept in a totally different directory than the cosmos directory... Currently the force-reset under client resets everything but keys

**Comment by zmanian** [comment]
How should setting `--home` after how this directory structure is mapped?

**Comment by rigelrozanski** [comment]
It should be set high level `~/.cosmos`

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/567
