### ISSUE TITLE
go: error loading module requirements

### ISSUE THREAD

**Issue by visepak** [cosmos/gaia#73]
Hi!
I try to build docker container by Dockerfile in repo
"sudo docker build . "
And have error
"The command '/bin/sh -c apk add --no-cache $PACKAGES &&     make tools &&     make install' returned a non-zero code: 2
"
[output.txt](https://github.com/cosmos/gaia/files/3393310/output.txt)

what is the problem?

**Comment by tac0turtle** [comment]
hey sorry for the delay in responding, are you still running into this isse?
