### ISSUE TITLE
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by anviar** [cosmos/gaia#733]
## Summary of Bug

11:16AM INF starting ABCI with Tendermint
11:16AM INF Starting multiAppConn service impl=multiAppConn module=proxy
11:16AM INF Starting localClient service connection=query impl=localClient module=abci-client
11:16AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
11:16AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
11:16AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
11:16AM INF Starting EventBus service impl=EventBus module=events
11:16AM INF Starting PubSub service impl=PubSub module=pubsub
11:16AM INF Starting IndexerService service impl=IndexerService module=txindex
11:16AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
11:16AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
11:16AM INF created new capability module=ibc name=ports/transfer
11:16AM INF port binded module=x/ibc/port port=transfer
11:16AM INF claimed capability capability=1 module=transfer name=ports/transfer
**Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain**

## Version

4.0.5

## Steps to Reproduce

download binary
https://github.com/cosmos/gaia/releases

next, by quickstart instractions from https://hub.cosmos.network/main/gaia-tutorials/join-mainnet.html

`gaiad init blablabla`

replace genesis
```
wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
gzip -d genesis.cosmoshub-4.json.gz
mv genesis.cosmoshub-4.json ~/.gaia/config/genesis.json
```
trying to start node

```
 gaiad start --p2p.seeds bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656 --x-crisis-skip-assert-invariants --log_level trace
 ```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
replace genesis

```
gaiad init -o blablabla
wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
gzip -d genesis.cosmoshub-4.json.gz
mv genesis.cosmoshub-4.json ~/.gaia/config/genesis.json
```

now please do:
```
cd ~/.gaia/config
ls -a -l
```


trying to start node

```
 gaiad start --p2p.seeds bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656 --x-crisis-skip-assert-invariants --log_level trace
```

Can you please put the result of the ls -a -l here?

**Comment by anviar** [comment]
`gaiad unsafe-reset-all`

that action resolved my issue. Thank you very much!
