### ISSUE TITLE
"gcc not installed for ledger support" upon trying to install Gaia

### ISSUE THREAD

**Issue by AbhinavMir** [cosmos/gaia#737]
Upon running

```
git clone https://github.com/cosmos/gaia
cd gaia && make install
```

I am met with the following error

"Makefile:43: *** gcc not installed for ledger support, please install or set LEDGER_ENABLED=false.  Stop. "

### System Specs:
Ubuntu 20.04.2 LTS on WSL2

**Comment by tac0turtle** [comment]
install gcc. `apt install gcc` you can also run with out ledger support

**Comment by AbhinavMir** [comment]
Thank you, my bad.
