### ISSUE TITLE
Define an encoding for transactions

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/gaia#74]
Let's specify the transaction encoding/format, so that `gaia` is able to receive an already signed transaction as a file or byte array.

This would mean that we don't have to specify all the transaction parameters in the cli but could use the ui/client to build, sign and submit it.

**Comment by zramsay** [comment]
should be implicit in the design. re-open in SDK repo if applicable

**Comment by rigelrozanski** [comment]
Yeah basically AFAICT we need to abandon ship on how we are using "go-bash" to run these tests.
The whole thing needs to be restructured to probably just call the cobra commands directly just opened up a blocking issue for this see #2706

**Comment by fedekunze** [comment]
@rigelrozanski @jackzampolin #2706 is tagged as `pre1.0` but this issue is `prelaunch`

**Comment by rigelrozanski** [comment]
these two issues are independant - I think that this issue should maybe be grouped as a part of a prelaunch checklist. This is something we're going to want to test _right_ before launch, I imagine that there are a few more things like this
