### ISSUE TITLE
Does Gaia currently have the function of a relayer?

### ISSUE THREAD

**Issue by cdkj** [cosmos/gaia#759]
I want to know whether gaia, serve as Cosmos hub, can be used as a hub for cross-chain transactions. I did not find relevant function in the source code of gaia. It seems more like a cosmos application template. 

I am very grateful for the development of **relayer**, which helped me a lot in cross-chain experiments. But relayer seems to be a program rather than a blockchain. I want to confirm whether gaia, as a blockchain, can play the role of relayer currently?

If this relayer part of the gaia source code is ignored by me, please forgive me for my negligence.

**Comment by shahankhatch** [comment]
Relayers are not part of Gaia, but Gaia can handle IBC messages for domains including cross-chain transactions. Module-specific discussions do take place around a Cosmos apps's (e.g., Gaia on the Hub) relationship with modules that depend on relayers.
