### ISSUE TITLE
Describe how to use edit-candidacy & add to the docs

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#76]

**Comment by zhiqiang-bianjie** [comment]
gaia client tx declare-candidacy --amount=1fermion --pubkey=55EAA075A2D61A981BF91BAE7A14F183ADFC9E561B52632EBAF96ECE136E2B8F --name=gaiav5 --moniker=bjtest5 。pubkey is your gaia node'pubkey.and name is your account's alias

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/569
