### ISSUE TITLE
gaiad doesn't work without explicitly setting a log level

### ISSUE THREAD

**Issue by tessr** [cosmos/gaia#767]
## Summary of Bug

The `gaiad` command doesn't work without explicitly setting a log level. 

## Version

v4.1.0

## Steps to Reproduce

Running any `gaiad` command fails if a log level is not specified.

```
$ gaiad version
Error: failed to parse log level (main:info,state:info,statesync:info,*:error): Unknown Level String: 'main:info,state:info,statesync:info,*:error', defaulting to NoLevel
Usage:
  gaiad version [flags]
```

vs

```
$ gaiad version --log_level info
v4.1.0
```

This may actually be an issue in the Cosmos SDK, not sure, but a quick search didn't turn up open issues in either repo.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AdityaSripal** [comment]
I ran into this same issue. After setting it once, subsequent calls to the same command work without the flag. My guess is the default is set to the string `main:info,state:info,statesync:info,*:error`

**Comment by adizere** [comment]
https://github.com/cosmos/gaia/issues/717#issuecomment-796874262

**Comment by mmulji-ic** [comment]
See #717 Update config.toml configuration
