### ISSUE TITLE
"gaia client tx delegate" should require `--amount`

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#77]

**Comment by zramsay** [comment]
`gaia client tx delegator-bond` requires `--delegator-address` otherwise it fails and doesn't say why

**Comment by zramsay** [comment]
we should use the `RequiredFlags` feature https://github.com/spf13/cobra/issues/206
but that would require refactoring a bit how the flags are initialized/handled in `modules/stake/commands/tx.go`

**Comment by rigelrozanski** [comment]
Great idea, thanks for the link

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/568
