### ISSUE TITLE
zondax/hid compilation_terminated

### ISSUE THREAD

**Issue by oggy95** [cosmos/gaia#78]
Hi!
I have such error while `make install` gaia:
/zondax/hid@v0.9.0/hid_enabled.go:22:23: fatal error: sys/poll.h: No such file or directory

go version go1.12.7 linux/amd64

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jleni** [comment]
Hi @oggy95, 
What specific linux distribution are you using?

**Comment by oggy95** [comment]
Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-154-generic x86_64)

**Comment by jleni** [comment]
mm... it sounds like you dont have `libc6-dev` installed..
Is that possible?

**Comment by jleni** [comment]
if you have enabled Ledger support, you will need gcc and related dependencies..

**Comment by oggy95** [comment]
i don't have 'libc6-dev'
thanks a lot, it's installed
