### ISSUE TITLE
Couldn't connect to any seeds

### ISSUE THREAD

**Issue by yzhou61** [cosmos/gaia#79]
## Summary of Bug

Trying to setup gaiad for the first time. Getting the following:
```
I[2019-07-18|21:11:47.715] Starting ABCI with Tendermint                module=main 
E[2019-07-18|21:11:48.218] Couldn't connect to any seeds                module=p2p 
E[2019-07-18|21:12:18.218] Couldn't connect to any seeds                module=p2p 
E[2019-07-18|21:12:48.218] Couldn't connect to any seeds                module=p2p 
E[2019-07-18|21:13:18.218] Couldn't connect to any seeds                module=p2p
```

## Version

`version: 0.0.0-43-gc1ae722`

## Steps to Reproduce

`gaiad start`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
This is typically normal behavior/log output. What are your seeds? Perhaps you can ask for others in other community forums if yours do not work 👍
