### ISSUE TITLE
multisign：couldn't verify signature: unable to verify single signer signature

### ISSUE THREAD

**Issue by JacksonRGB** [cosmos/gaia#796]
There was an error when I exec multisign.
I dont know how to fix it. 
Can someone help me? Many thanks

gaiad version v4.2.0

create tx
```gaiad tx bank send cosmos1pmpmwsc7z03c72ak80e8wc996nhmh9s8t8sn4v cosmoshub1f9nxjhy90e46ld9khpzrvlwr8fu77lzt0l0wwh 100uatom --generate-only > unsigned.json```

sign 1
```gaiad tx sign unsigned.json --multisig cosmos1pmpmwsc7z03c72ak80e8wc996nhmh9s8t8sn4v --from key1 --chain-id test > s1.json```

sign 2
```gaiad tx sign unsigned.json --multisig cosmos1pmpmwsc7z03c72ak80e8wc996nhmh9s8t8sn4v --from key2 --chain-id test > s2.json```

multisign  (report an error)
```gaiad tx multisign unsigned.json mk s1.json s2.json```

unsigned.json
```
{"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"cosmos1pmpmwsc7z03c72ak80e8wc996nhmh9s8t8sn4v","to_address":"cosmos1f9nxjhy90e46ld9khpzrvlwr8fu77lzt7p5nh5","amount":[{"denom":"uatom","amount":"100"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}
```

s1.json
```
{"signatures":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AnDuqhyDMNVu7rCtcG7rLHuafzQNoMK0P7IZaa1SQESi"},"data":{"single":{"mode":"SIGN_MODE_LEGACY_AMINO_JSON","signature":"OD7gzo69z+IuBu02u77S8H2//jxufXNJSCnTaxVaMZRwZ+LvEvgp1O0ziEMo7Wv0LY3/aTQsj30hnYzrogJwcg=="}},"sequence":"0"}]}
```

s2.json
```
{"signatures":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"Ar09QAYjAsb8cpqpCIUqgERm7YanioQ3Y5XZrYCqq3yM"},"data":{"single":{"mode":"SIGN_MODE_LEGACY_AMINO_JSON","signature":"F4XTFd+9kI8l6yQK2uAWTuKb7Uduhc1eN7Hfnt8mEEQQgjVXDNIwoXEscgCh1GEsCk6Dlkt7k40EedZowI6JIg=="}},"sequence":"0"}]}
```

keys 

- name: base
  type: local
  address: cosmos14t67fuey6ma8ml6zd8p2t2plvwzmptn4gw6guv
  pubkey: cosmospub1addwnpepqwygpdv3606a9x6tw9g2unfptejvj5n2mhgkkkzcfmsp3vnrq8vuy9xp7kj
  mnemonic: ""
  threshold: 0
  pubkeys: []
- name: key1
  type: local
  address: cosmos1ajmpm2jql9cyz2gqrdm9rvkd9hyfl3mr88mqke
  pubkey: cosmospub1addwnpepqfcwa2susvcd2mhwkzkhqmht93ae5le5pksv9dplkgvknt2jgpz2yw37ttr
  mnemonic: ""
  threshold: 0
  pubkeys: []
- name: key2
  type: local
  address: cosmos16fw4we0zh6srspjv7fu0vuqsllrqs05pjezr90
  pubkey: cosmospub1addwnpepq27n6sqxyvpvdlrjn25s3pf2spzxdmvx579ggdmrjhv6mq924d7gc4kggcl
  mnemonic: ""
  threshold: 0
  pubkeys: []
- name: mk
  type: multi
  address: cosmos1pmpmwsc7z03c72ak80e8wc996nhmh9s8t8sn4v
  pubkey: cosmospub1ytql0csgqgfzd666axrjzq4a84qqvgczcm789x4fpzzj4qzyvmkcdfu2ssmk89we4kq242mu3sfzd666axrjzqnsa64peqes64hwav9dwphwktrmnflngrdqc26rlvsedxk4yszy5g0nf7tp
  mnemonic: ""
  threshold: 0
  pubkeys: []

**Comment by zmanian** [comment]
I will make a note to improve this error message so leaving this open until we get a better error message.

If you add chain-id to the multisign command it will work.
`gaiad tx multisign unsigned.json mk s1.json s2.json --chain-id test`

**Comment by mmulji-ic** [comment]
@minchenzz @zmanian Is this issue still open?

**Comment by okwme** [comment]
instructions have been updated
