### ISSUE TITLE
Batch signing doesn't work with Ledger

### ISSUE THREAD

**Issue by greg-szabo** [cosmos/gaia#797]
## Summary of Bug
```
gaiad tx batch-signing --from key_on_ledger ...
```
When running batch signing, the first transaction gets signed by Ledger but then "nothing" happens: Ledger looks like it's waiting for the next transaction to sign, the command-line application doesn't print anything or do anything. If the application is stopped with CTRL-C, the Ledger ends up in a state where it can't sign additional transactions, even regular ones. Exiting the Ledger app and re-entering fixes Ledger and regular transactions can be signed.

## Version
gaiad v4.1.2

## Steps to Reproduce
1. Create a list of transactions to sign
2. Run gaiad tx batch-signing with a key residing on Ledger

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zmanian** [comment]
This is overwhelmingly likely to be an SDK issue.

**Comment by tac0turtle** [comment]
@greg-szabo could you open this issue in the sdk? Gaia can't make any changes to such an issue.
