### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by zhangsj** [cosmos/gaia#799]
version v4.2.0

4:42PM INF starting ABCI with Tendermint
4:42PM INF Starting multiAppConn service impl=multiAppConn module=proxy
4:42PM INF Starting localClient service connection=query impl=localClient module=abci-client
4:42PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
4:42PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
4:42PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
4:42PM INF Starting EventBus service impl=EventBus module=events
4:42PM INF Starting PubSub service impl=PubSub module=pubsub
4:42PM INF Starting IndexerService service impl=IndexerService module=txindex
4:42PM INF ABCI Handshake App Info hash="XB�v�y+\x1a��f��\x10D+�`r��xp���|�fM��" height=5600355 module=consensus protocol-version=0 software-version=
4:42PM INF ABCI Replay Blocks appHeight=5600355 module=consensus stateHeight=5600355 storeHeight=5600356
4:42PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 5842AA7683792B1A9ECE66AAD110442B8A6072F1CA7870C8C1B27CC2664D92CA, got E4B2A66ADB26C965F97694FA44BEF470E0CC78EBA916F306D0DC5989E66BE013
Usage:
  gaiad start [flags]

Flags:

**Comment by faddat** [comment]
I'd say to first, try a plain 

`gaiad unsafe-reset-all`  (making sure it won't wipe anything that you need)

and then start the node with the same flags.

Thanks!

**Comment by zhangsj** [comment]
Can't delete this wrong block alone?

**Comment by faddat** [comment]
I wouldn't recommend that approach

PS: If it fails again, could you please list out the flags and anything non-default in config.toml?

**Comment by zhangsj** [comment]
[config.txt](https://github.com/cosmos/gaia/files/6220971/config.txt)
