### ISSUE TITLE
No candidates returned for gaia client

### ISSUE THREAD

**Issue by faboweb** [cosmos/gaia#80]
`gaia client query candidates` returns `ERROR: No data returned for query`

I would expect that this returns at least all validators as I understood candidates to be a superset of the validators.
I would expect this to return [] instead of an error in the case of 'No data'.

**Comment by zramsay** [comment]
ya the error messages aren't the greatest. see https://github.com/cosmos/gaia/blob/feature/delegation/cmd/gaia/sh_tests/stake.sh#L188,it should work (the  test passes)

**Comment by zramsay** [comment]
actually, i get the same result for https://github.com/cosmos/gaia/blob/feature/delegation/cmd/gaia/sh_tests/stake.sh#L169

**Comment by faboweb** [comment]
![image](https://user-images.githubusercontent.com/5869273/33613885-18632ebc-d9d6-11e7-91f6-243ec9240f97.png)

**Comment by rigelrozanski** [comment]
@faboweb There is a known issue we're just leaving in here for a bit right now, which is that the genesis validators are not actually a part of the validator set as defined by the staking module.... when this is fixed there SHOULD be the genesis validators are height 0
https://github.com/cosmos/gaia/issues/17

**Comment by faboweb** [comment]
@rigelrozanski 
Hey! Is there progress on this issue?

**Comment by rigelrozanski** [comment]
Yeah well it works - but if there are no validator candidates it returns an error... is this not acceptable? The record which contains validator candidates is only available once candidates have been created... I think that's fair - not to mention in practice this shouldn't exist returns are in the following json, where data is the array of all validators: 
```
{
  "height": 9,
  "data": [
    {
      "type": "ed25519",
      "data": "2C0C39B1F54F718FB20F85DCC026E94FF1151433B8B61DC504C29572AF7956C5"
    }
  ]
}
```

**Comment by rigelrozanski** [comment]
It's kind of a hassle to do deal with the empty case right now as no generic init function for modules in old SDK - I'm going to pass on hacking this one in unless it's absolutely necessary in the short term - Let's leave this open and change the empty case to not be an error once there is a stable SDK... is that reasonable?

**Comment by zramsay** [comment]
obsolete / smooth error handling should be implicit in any design
