### ISSUE TITLE
Using gaiad CLI commands leaves dangling dbus-daemon processes

### ISSUE THREAD

**Issue by kirill-li** [cosmos/gaia#811]
## Summary of Bug

Using `gaiad` CLI commands  leaves dangling dbus-daemon processes
   

![image](https://user-images.githubusercontent.com/38109291/114392211-4348d100-9bba-11eb-9b64-a64620f84682.png)

## Version
4.2.1
## Steps to Reproduce

All the commands are leaving a dangling process. Even commands with incorrect arguments like `gaiad versoin` result in leaving a process.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @maldiva, would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team

**Comment by mmulji-ic** [comment]
Closing, if more information can be provided we can take a look.
