### ISSUE TITLE
Add CLI to enable stdout as default

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#818]
See https://github.com/cosmos/gaia/pull/800

This issue is really aiming to enable gaia-specific CLI options. Currently all CLI options are coming through underlying Cosmos SDK and Tendermint dependencies. We'll eventually need Gaia to have its own capabilities and configurations.

**Comment by alessio** [comment]
I believe that https://github.com/cosmos/cosmos-sdk/pull/8628 should fix this

**Comment by shahankhatch** [comment]
Closing this specific issue since it's been addressed in the SDK. Created new issue #847 re: gaia-specific CLI options
