### ISSUE TITLE
Add version into gaia-issued validator messages

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#819]
This feature will help to identify the version a validator is running on. This data will make new features possible, e.g., custom upgrade logic, security and hub analytics.

**Comment by okwme** [comment]
didn't this get added at the SDK or Tendermint level @marbar3778 ?

**Comment by tac0turtle** [comment]
this isn't really possible on the hub, since you don't know who is a validator and in many cases the validator is not exposed to the public network. A version feature was added, but you can only see it on public nodes

**Comment by okwme** [comment]
This input is available here: https://api.cosmos.network/node_info but like marko said it doesn't really solve for accessing actual validator nodes.
