### ISSUE TITLE
Consider adding DCO to repo

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#822]
Some resources:
https://github.com/probot/dco
https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md

**Comment by alain2sf** [comment]
FYI When working on the Linux Foundation EdgeX Foundry Project, I recall that DCO was added to the repositories:
[https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)

**Comment by faddat** [comment]
This would be an additional step for less-experienced developers to begin contributing and does not have a meaningful impact on security.

**Comment by okwme** [comment]
I tend to agree with @faddat here. Gonna close until another reason to open is brought up.
