### ISSUE TITLE
Search TXs request extremely slow if searching by `message.action`

### ISSUE THREAD

**Issue by JaTochNietDan** [cosmos/gaia#823]
## Summary of Bug

When you search `message.action` using the tx search endpoint, it is extremely slow and tends to lock up the entire API. When it finishes loading, other requests will load instantly at the same time. It seems like it blocks everything else from loading, while it is being loaded.

Check it out here from the Cosmos' team node:
https://api.cosmos.network/cosmos/tx/v1beta1/txs?events=message.action%3D%27send%27&orderBy=ORDER_BY_DESC&pagination.limit=10&pagination.offset=0

## Version
4.2.1

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
Hey @JaTochNietDan 
Thanks, performance on various queries is being worked on by the IBC team. There are some incoming changes to the IAVL trie that should speed things up significantly.
That URI is also out date, api.cosmos.network is the new URL and the swagger document can be found at https://cosmos.network/rpc
