### ISSUE TITLE
add `set -u` to top of bash scripts to catch unbound vars

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#83]
Currently doing so fails

**Comment by rigelrozanski** [comment]
sorry, what is `set -u` supposed to be doing?

**Comment by ebuchman** [comment]
It makes sure all variables are bound. 

For instance, if you do `rm -rf ~/$ABC` but you haven't set `$ABC` yet, the script will fail instead of deleting your home directory :)

**Comment by rigelrozanski** [comment]
oh amazing... wish I had known about that one before lol

**Comment by rigelrozanski** [comment]
resolved in develop -  Don't know what your problem is... added it in and played around and it makes everytime an undefined variable is called as expected
