### ISSUE TITLE
gaiad keys parse does not work, freezes when trying to use

### ISSUE THREAD

**Issue by stakezone** [cosmos/gaia#830]
## Summary of Bug

the command `gaiad keys parse` does not work. In versions before Stargate it was functional. This disrupts scripts and makes data processing difficult.

## Version

any stargate version

## Steps to Reproduce

`gaiad keys parse <any address>` results in freezed return.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @stakezone, would you mind confirming what version of gaia you have installed and whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team

**Comment by okwme** [comment]
hey @stakezone this is a known bug that has been fixed since ~v5.0.x. Please use the latest version of gaia for key parsing.
