### ISSUE TITLE
gaiad keys parse as endpoint for API

### ISSUE THREAD

**Issue by stakezone** [cosmos/gaia#831]
## Summary

Please add `gaiad keys parse` to API

## Problem Definition

When using the API, for many use cases it is required having the different key types, i.e. valoper, valcons in order to parse API requests.

## Proposal

Just extend the current API for the existing `gaiad keys parse` command. Note: as of time of writing the `gaiad keys parse` is broken.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
Bot closed this by accident. Opening again. @okwme can you give input perhaps?

**Comment by okwme** [comment]
recreating issue for Cosmos SDK and closing here
https://github.com/cosmos/cosmos-sdk/issues/11751
