### ISSUE TITLE
Peer node setup

### ISSUE THREAD

**Issue by blockchain-app12** [cosmos/gaia#833]
Hi,
Trying to connect private network with another node in cosmos gaia.
I am facing below error:
"starting ABCI with Tendermint                module=main 
Error dialing peer                           module=p2p err="dial tcp <ip>:26656: i/o timeout"
Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=node@ip:26656 elapsed=2m21.20442727s"
How to overcome this error?

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
(opinion) I think the network needs far more seeds and p2p needs a bit of an overhaul.

**Comment by faddat** [comment]
I'll use instagaia to host some seeds on Akash, and this should address the problem some.

**Comment by Andiami-Yusaka** [comment]
Same error on my side. I used gaiad V7 and synchronized 12965188 blocks; however, it stopped synching after that.
