### ISSUE TITLE
Identify and develop gaia-specific tests

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#846]
- [ ] run using `make test`
- [ ] test gaia-specific functionality
- [ ] help onboard users to testing gaia functionality
- [ ] help Cosmos module developers integrate into gaia repo
- [ ] separate test subsystem for Cosmos Hub-specific functionality
- [ ] help bridge modules from Cosmos ecosystem into Cosmos Hub ecosystem

**Comment by shahankhatch** [comment]
See #54 and https://github.com/cosmos/cosmos-sdk/pull/6711

**Comment by nooomski** [comment]
Bot closed by accident. @okwme, wdyt, another one for Milan perhaps?

**Comment by mmulji-ic** [comment]
Check #1253 .
