### ISSUE TITLE
The problem with the rank page

### ISSUE THREAD

**Issue by ghost** [cosmos/gaia#848]
https://gravitydex.io/app#/rank
![image](https://user-images.githubusercontent.com/56637396/117263248-c5938080-ae5a-11eb-93b9-8e2512c6139d.png)
after pressing the F5 key
![image](https://user-images.githubusercontent.com/56637396/117263350-db08aa80-ae5a-11eb-8def-52b628f59c63.png)

**Comment by shahankhatch** [comment]
Thanks for reporting this. It isn't a gaia issue, but tagging @alessio who is with Gravity Dex.

**Comment by alessio** [comment]
CC'ing @SenorMonito for visibility
