### ISSUE TITLE
Add protobuf string to /cosmos/tx/v1beta1/txs/{hash}

### ISSUE THREAD

**Issue by lhannest** [cosmos/gaia#851]
## Summary

Adding protobuf string to the json response of `/cosmos/tx/v1beta1/txs/{hash}`.

## Problem Definition

The API endpoint `/cosmos/tx/v1beta1/txs/{hash}` returns json, and to get the protobuf encoded string for the transaction this json needs to be parsed with `com.google.protobuf.util.JsonFormat`. This is inconvenient. I would be nice for the json response to contain that protobuf string, so that we can deserialize the transaction with the standard protobuf classes generated from `.proto` files and not have to use `JsonFormat`.

## Proposal

Add a "protobuf" key to the json response that holds the protobuf encoded string for that transaction:

```
{
   "tx" : {
      ...
   },
   "tx_response" : {
      ...
   },
   "protobuf" : "CqUBCpABChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEnAKLWNvc21vczFwdmhsNTVmN3M1NDd4ZWxuZjZyY2cycjIwNTYzOWpkczA2dnI0NxItY29zbW9zMWdoejM5aDB6a3VneHMzdHN0OG1mdnN5Mmc5OHhkYWFoODN4bDB0GhAKBXVhdG9tEgcyODQ1MTcyEhAyMzk4MzA4MDA2NzQzNTAyEmUKTgpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQNlN5uAg74176Chcf1JqT7IE28NghxeRGM3mLnYDCAVZRIECgIIfxITCg0KBXVhdG9tEgQxNzUwEPCiBBpA1h6nv9UpQbZNexA2EggEbTlKcFER73wAo0+DQZJuJh99DcVjyykBMxPdcS/uZODbvbvni976KHomyvccZjpi0g=="
}
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
Hey, this would be an issue for the cosmos-sdks. Could you open an issue [here](https://github.com/cosmos/cosmos-sdk/issues) and we will get to it in a timely manner
