### ISSUE TITLE
Add datetime of Declare-Candidacy to the candidate

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#86]
to represent how long this delegator has existed... exclusively for UI

**Comment by rigelrozanski** [comment]
Or more easy - maybe we just save the height and UI can guestimate the datetime... @faboweb @mappum @jolesbi ?? already need the height https://github.com/cosmos/gaia/issues/49

**Comment by faboweb** [comment]
How wrong can you be about the time, when guestimating?
I think it is OK to base this on the height. It would show relative time for all candidates.

**Comment by rigelrozanski** [comment]
Meh - on second thought that sounds a bit shady to guess... for all the quering of block headers... it may be worth just to store the datetime and the height...

**Comment by adrianbrink** [comment]
Can a validator add the date and time in the transaction? If so it would be spoofable by the validator. The date time should depend upon when a validator actually declared their candidacy.

**Comment by rigelrozanski** [comment]
No the date time needs to be calculated as the transaction is processed

**Comment by adrianbrink** [comment]
So this requires date time from the consensus right?

**Comment by rigelrozanski** [comment]
correct

**Comment by zramsay** [comment]
> exclusively for UI
shouldn't the UI and CLI stay in sync? e.g., #103

**Comment by zramsay** [comment]
obsolete? re-open in SDK if relevant

**Comment by faboweb** [comment]
Is this available in the new delegation module @rigelrozanski?
