### ISSUE TITLE
Release a Gaia 4.2.2

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#862]
- [ ] ARM support through SDK version bump, #803 
- [ ] https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.5
- [ ] Network creation tool from existing genesis, #860 (needs further testing and some fixes)
- [ ] cherrypick other updates, e.g., documentation
- [ ] changelog
- [ ] release

**Comment by faddat** [comment]
I reckon this is now safe to close.
