### ISSUE TITLE
Lock account in cosmos

### ISSUE THREAD

**Issue by blockchain-app12** [cosmos/gaia#874]
Hi everyone,
Is there any possibilities to lock funds in cosmos gaia?

**Comment by yaruwangway** [comment]
Hi @osiz-blockchainapp,
thanks for posting your issue! We've been behind on many reviews and apologize for such. 
For your question:
You can lock your tokens by using [vesting account](https://docs.cosmos.network/master/modules/auth/07_client.html).
Here are some CLI for how to interact with the vesting module:
https://docs.cosmos.network/master/modules/auth/07_client.html

We'll close this issue for now and if you have further questions, we can always re-open.
Thanks for your help,
Cosmos Hub Team

**Comment by tac0turtle** [comment]
closing this for now. If you have further questions, feel free to tag marbar in discord.
