### ISSUE TITLE
update import alias from types -> genutil types

### ISSUE THREAD

**Issue by colin-axner** [cosmos/gaia#875]
## Summary

It is SDK convention to alias external imports in a verbose way so it is easy to tell where the import comes from when used in code. This import [genutiltypes](https://github.com/cosmos/gaia/blob/930504209fc59bef3354a53c46c7e9e1e090a10d/app/migrate.go#L20) doesn't have an alias. This usage is odd in the code as `types.AppMap` implies the types of this repository, when in reality it is genutil types (not even sdk types)

This is likely an artifact of directly copying the file from x/genutil migrate.go. Just a nit but good for code hygiene 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nir1218** [comment]
I would like to handle this issue, please assign to me.

**Comment by colin-axner** [comment]
Files containing imports will be removed soon. Thanks anyways @nir1218!
