### ISSUE TITLE
peer to peer connection

### ISSUE THREAD

**Issue by blockchain-app12** [cosmos/gaia#876]
Hi everyone,
Running gaia private network. Already connected peer node with master node.
But i need to connect one peer node to another peer node. It results 'error'.
Is there any solution?

**Comment by okwme** [comment]
Hi thanks for your issue!
We're still missing info and context to be able to help you. Can you fill out the topic requested under the bug report issue?

> 
> ## Summary of Bug
> 
> Concisely describe the issue
> 
> ## Version
> 
> git commit hash, output of `gaiacli version`, output of `gaiad version
> 
> ## Steps to Reproduce
> 
> What commands in order should someone run to reproduce your problem
>

**Comment by okwme** [comment]
(also need to ACK our delay in reply. We're scaling up our support but in the meantime there is also resources on the commmunity devloper discord: https://discord.com/invite/cosmosnetwork

**Comment by tac0turtle** [comment]
> Hi everyone,
> Running gaia private network. Already connected peer node with master node.
> But i need to connect one peer node to another peer node. It results 'error'.
> Is there any solution?

hey, we would need more information and what the error is. I would recommend asking in discord, feel free to tag marker for a quick response
