### ISSUE TITLE
Update testnet command

### ISSUE THREAD

**Issue by colin-axner** [cosmos/gaia#879]
## Summary

apply [fix](https://github.com/cosmos/cosmos-sdk/pull/9497)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
should go in the hub/cosmoshub-4.6 branch

**Comment by brennhill** [comment]
Is this resolved?

**Comment by colin-axner** [comment]
No I don't think so. The [current code](https://github.com/cosmos/gaia/blob/main/cmd/gaiad/cmd/testnet.go#L288-#L292) doesn't match the diffs. I think this means the testnet command shouldn't work

cc @yaruwangway

**Comment by yaruwangway** [comment]
Hi @colin-axner, thank you for checking! I will include this change into the next Vega-rc2 release!
