### ISSUE TITLE
Disable unnecessary checks when updating only md files

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#887]
For example, see #878. The checks are unnecessary

**Comment by ghost** [comment]
Can see copy recive,for IT.
King regards.
MG

**Comment by brennhill** [comment]
Is this resolved?

**Comment by nooomski** [comment]
Bot closed by accident. Opening again. But not a priority right now.

**Comment by mmulji-ic** [comment]
Add labels to running tests.

**Comment by okwme** [comment]
https://stackoverflow.com/questions/62968897/is-it-possible-to-not-run-github-action-for-readme-updates
