### ISSUE TITLE
Update to 5.0.0 process crash

### ISSUE THREAD

**Issue by lcgogo** [cosmos/gaia#898]
## Summary of Bug

update from 4.2.1 to 5.0.0 met followed error and the gaia process crash

## Version

/ # gaiad version
v5.0.0

## Steps to Reproduce

/usr/bin/gaiad --home /data/atom start  --x-crisis-skip-assert-invariants

3:40AM INF starting ABCI with Tendermint
3:40AM INF Starting multiAppConn service impl=multiAppConn module=proxy
3:40AM INF Starting localClient service connection=query impl=localClient module=abci-client
3:40AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
3:40AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
3:40AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
3:40AM INF Starting EventBus service impl=EventBus module=events
3:40AM INF Starting PubSub service impl=PubSub module=pubsub
3:40AM INF Starting IndexerService service impl=IndexerService module=txindex
3:40AM INF ABCI Handshake App Info hash="\u007fχR\x0feY:<`l[1p�''ܶ�,@\x1a\x10�\x10w�n�\f\x04" height=6762565 module=consensus protocol-version=0 software-version=
3:40AM INF ABCI Replay Blocks appHeight=6762565 module=consensus stateHeight=6762565 storeHeight=6762566
3:40AM INF Replay last block using real app module=consensus
3:40AM INF minted coins from module account amount=4417640uatom from=mint module=x/bank
3:40AM INF client state updated client-id=07-tendermint-259 height=1-153031 module=x/ibc/client
3:40AM INF packet acknowledged module=x/ibc/channel packet="{13131 transfer channel-141 transfer channel-0 [123 34 97 109 111 117 110 116 34 58 34 49 50 53 49 50 51 49 48 48 34 44 34 100 101 110 111 109 34 58 34 117 97 116 111 109 34 44 34 114 101 99 101 105 118 101 114 34 58 34 111 115 109 111 49 115 113 55 110 54 121 114 120 101 117 112 101 53 119 109 52 57 113 101 99 52 53 119 113 112 51 110 51 115 100 118 50 97 100 118 50 103 109 34 44 34 115 101 110 100 101 114 34 58 34 99 111 115 109 111 115 49 115 113 55 110 54 121 114 120 101 117 112 101 53 119 109 52 57 113 101 99 52 53 119 113 112 51 110 51 115 100 118 50 52 107 108 54 55 102 34 125] 1-153173 0}"
3:40AM INF packet received module=x/ibc/channel packet="{10631 transfer channel-0 transfer channel-141 [123 34 97 109 111 117 110 116 34 58 34 50 51 54 49 52 53 53 57 54 34 44 34 100 101 110 111 109 34 58 34 116 114 97 110 115 102 101 114 47 99 104 97 110 110 101 108 45 48 47 117 97 116 111 109 34 44 34 114 101 99 101 105 118 101 114 34 58 34 99 111 115 109 111 115 49 106 121 109 97 118 97 110 119 104 112 55 99 48 100 97 100 107 104 57 120 56 55 53 108 120 104 102 99 104 48 55 52 106 103 53 104 121 110 34 44 34 115 101 110 100 101 114 34 58 34 111 115 109 111 49 106 121 109 97 118 97 110 119 104 112 55 99 48 100 97 100 107 104 57 120 56 55 53 108 120 104 102 99 104 48 55 52 54 110 56 56 106 112 34 125] 4-6762701 0}"
3:40AM INF acknowledged written module=x/ibc/channel packet="{10631 transfer channel-0 transfer channel-141 [123 34 97 109 111 117 110 116 34 58 34 50 51 54 49 52 53 53 57 54 34 44 34 100 101 110 111 109 34 58 34 116 114 97 110 115 102 101 114 47 99 104 97 110 110 101 108 45 48 47 117 97 116 111 109 34 44 34 114 101 99 101 105 118 101 114 34 58 34 99 111 115 109 111 115 49 106 121 109 97 118 97 110 119 104 112 55 99 48 100 97 100 107 104 57 120 56 55 53 108 120 104 102 99 104 48 55 52 106 103 53 104 121 110 34 44 34 115 101 110 100 101 114 34 58 34 111 115 109 111 49 106 121 109 97 118 97 110 119 104 112 55 99 48 100 97 100 107 104 57 120 56 55 53 108 120 104 102 99 104 48 55 52 54 110 56 56 106 112 34 125] 4-6762701 0}"
3:40AM INF packet sent module=x/ibc/channel packet="{13133 transfer channel-141 transfer channel-0 [123 34 97 109 111 117 110 116 34 58 34 54 53 49 48 48 48 48 48 48 34 44 34 100 101 110 111 109 34 58 34 117 97 116 111 109 34 44 34 114 101 99 101 105 118 101 114 34 58 34 111 115 109 111 49 115 53 112 99 57 51 52 116 97 119 51 48 114 114 113 48 115 118 53 99 119 104 100 121 100 109 99 51 113 51 118 57 115 118 104 52 106 104 34 44 34 115 101 110 100 101 114 34 58 34 99 111 115 109 111 115 49 115 53 112 99 57 51 52 116 97 119 51 48 114 114 113 48 115 118 53 99 119 104 100 121 100 109 99 51 113 51 118 57 99 104 121 57 121 57 34 125] 1-153189 0}"
3:40AM INF IBC fungible token transfer amount=651000000 module=x/ibc-transfer receiver=osmo1s5pc934taw30rrq0sv5cwhdydmc3q3v9svh4jh sender=cosmos1s5pc934taw30rrq0sv5cwhdydmc3q3v9chy9y9 token=uatom
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get(0x2199aa0, 0xc0030862a0, 0xc000522078, 0x2161f00, 0xc003087d80, 0x2161f80, 0xc003087df0, 0xc001145300, 0x9, 0x1f, ...)
	github.com/cosmos/cosmos-sdk@v0.42.6/x/params/types/subspace.go:109 +0x32a
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet(0x2199aa0, 0xc0030862a0, 0xc000522078, 0x2161f00, 0xc003087d80, 0x2161f80, 0xc003087df0, 0xc001145300, 0x9, 0x1f, ...)
	github.com/cosmos/cosmos-sdk@v0.42.6/x/params/types/subspace.go:222 +0x1a8
github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.GetParams(...)
	github.com/gravity-devs/liquidity@v1.2.9/x/liquidity/keeper/keeper.go:56
github.com/gravity-devs/liquidity/x/liquidity/keeper.Keeper.ExecutePoolBatches(0x219f520, 0xc0030862a0, 0x2161f00, 0xc003087dc0, 0x7f9eb97ed2a8, 0xc000c0a9a0, 0x2164a40, 0xc00057af30, 0x2144e40, 0xc0001b2840, ...)
	github.com/gravity-devs/liquidity@v1.2.9/x/liquidity/keeper/batch.go:84 +0x18f
github.com/gravity-devs/liquidity/x/liquidity.EndBlocker(0x2182ca0, 0xc000044040, 0x21994a0, 0xc00dc2b840, 0xb, 0x0, 0xc00db5a890, 0xb, 0x673046, 0x24b64e9b, ...)
	github.com/gravity-devs/liquidity@v1.2.9/x/liquidity/abci.go:24 +0x1b8
github.com/gravity-devs/liquidity/x/liquidity.AppModule.EndBlock(...)
	github.com/gravity-devs/liquidity@v1.2.9/x/liquidity/module.go:168
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(0xc0010431f0, 0x2182ca0, 0xc000044040, 0x21994a0, 0xc00dc2b840, 0xb, 0x0, 0xc00db5a890, 0xb, 0x673046, ...)
	github.com/cosmos/cosmos-sdk@v0.42.6/types/module/module.go:354 +0x227
github.com/cosmos/gaia/v5/app.(*GaiaApp).EndBlocker(...)
	github.com/cosmos/gaia/v5/app/app.go:479
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000529ba0, 0x673046, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.42.6/baseapp/abci.go:208 +0x314
github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000547c20, 0x673046, 0x0, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:282 +0xdb
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc000126450, 0x673046, 0x0, 0x14d, 0xc0204df4d0)
	github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:89 +0x42
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x21839e0, 0xc001154ae0, 0x218fb00, 0xc000126450, 0xc00000c780, 0x21996a0, 0xc002650520, 0x4f5b97, 0xc002e0ee40, 0x20, ...)
	github.com/tendermint/tendermint@v0.34.11/state/execution.go:327 +0x654
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00397d650, 0xb, 0x0, 0x0, 0x0, 0xc002655bb0, 0xb, 0x4f5b97, 0x673045, 0xc002e0ee40, ...)
	github.com/tendermint/tendermint@v0.34.11/state/execution.go:140 +0x165
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc0057ae1d8, 0xb, 0x0, 0x0, 0x0, 0xc002655bb0, 0xb, 0x4f5b97, 0x673045, 0xc002e0ee40, ...)
	github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:503 +0x292
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc003f581d8, 0xb, 0x0, 0x0, 0x0, 0xc002655bb0, 0xb, 0x4f5b97, 0x673045, 0xc002e0ee40, ...)
	github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:416 +0xdb8
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0057ae1d8, 0x219da40, 0xc000022000, 0x1, 0x1)
	github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x478
github.com/tendermint/tendermint/node.doHandshake(0x21996a0, 0xc002650520, 0xb, 0x0, 0x0, 0x0, 0xc002655bb0, 0xb, 0x4f5b97, 0x673045, ...)
	github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000eff400, 0x2179d60, 0xc002f00140, 0xc000524060, 0x2142aa0, 0xc0011d9480, 0xc000524180, 0x1f5e9a0, 0xc000524270, 0x21839e0, ...)
	github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x2085
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f68dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x218bfc0, 0xc000ef4310, ...)
	github.com/cosmos/cosmos-sdk@v0.42.6/server/start.go:244 +0x565
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f38000, 0xc000fc8ab0, 0x0, 0x3, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.42.6/server/start.go:120 +0x1ec
github.com/spf13/cobra.(*Command).execute(0xc000f38000, 0xc000f11d00, 0x3, 0x4, 0xc000f38000, 0xc000f11d00)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e66f00, 0x0, 0x0, 0xc000e81f98)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e66f00, 0xc000e81f98, 0x6, 0x219f520, 0xc000ef4310)
	github.com/cosmos/cosmos-sdk@v0.42.6/server/cmd/execute.go:36 +0x265
main.main()
	github.com/cosmos/gaia/v5/cmd/gaiad/main.go:16 +0x45

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melvjoshua** [comment]
I have this error too when update to 5.0.0

**Comment by yaruwangway** [comment]
Hi, is this after you submit a proposal to upgrade the chain from a certain height?

-  if yes, please make sure that this proposed height is given enough time to be processed and accepted (I proposed a height of the present height plus a few hundred, it worked fine). 
- the chain should stop itself at the proposed height, no need to manually stop. then you can upgrade to v5.0.0.
- please also make sure your data store directory is correct when starting the node again.

**Comment by lcgogo** [comment]
> Hi, is this after you submit a proposal to upgrade the chain from a certain height?
> 
>     * if yes, please make sure that this proposed height is given enough time to be processed and accepted (I proposed a height of the present height plus a few hundred, it worked fine).
> 
>     * the chain should stop itself at the proposed height, no need to manually stop. then you can upgrade to v5.0.0.
> 
>     * please also make sure your data store directory is correct when starting the node again.

No, I just stop the full synced gaia 4.2.1 process then start gaia 5.0.0 process with the same gaia startup options like below:
/usr/bin/gaiad --home /data/atom start --x-crisis-skip-assert-invariants

**Comment by tac0turtle** [comment]
5.0.0 can not be used yet, please wait for the upgrade date (tentatively july 12). For now down grade to 4.2.1

**Comment by yaruwangway** [comment]
> 5.0.0 can not be used yet, please wait for the upgrade date (tentatively july 12). For now down grade to 4.2.1

right! there is a test

> > Hi, is this after you submit a proposal to upgrade the chain from a certain height?
> > ```
> > * if yes, please make sure that this proposed height is given enough time to be processed and accepted (I proposed a height of the present height plus a few hundred, it worked fine).
> > 
> > * the chain should stop itself at the proposed height, no need to manually stop. then you can upgrade to v5.0.0.
> > 
> > * please also make sure your data store directory is correct when starting the node again.
> > ```
> 
> No, I just stop the full synced gaia 4.2.1 process then start gaia 5.0.0 process with the same gaia startup options like below:
> /usr/bin/gaiad --home /data/atom start --x-crisis-skip-assert-invariants

yes @marbar3778. 
You can only do a mock test now @lcgogo. ref: https://github.com/b-harvest/gravity-dex-upgrade-test

**Comment by lcgogo** [comment]
> > 5.0.0 can not be used yet, please wait for the upgrade date (tentatively july 12). For now down grade to 4.2.1
> 
> right! there is a test
> 
> > > Hi, is this after you submit a proposal to upgrade the chain from a certain height?
> > > ```
> > > * if yes, please make sure that this proposed height is given enough time to be processed and accepted (I proposed a height of the present height plus a few hundred, it worked fine).
> > > 
> > > * the chain should stop itself at the proposed height, no need to manually stop. then you can upgrade to v5.0.0.
> > > 
> > > * please also make sure your data store directory is correct when starting the node again.
> > > ```
> > 
> > 
> > No, I just stop the full synced gaia 4.2.1 process then start gaia 5.0.0 process with the same gaia startup options like below:
> > /usr/bin/gaiad --home /data/atom start --x-crisis-skip-assert-invariants
> 
> yes @marbar3778.
> You can only do a mock test now @lcgogo. ref: https://github.com/b-harvest/gravity-dex-upgrade-test

Many thanks. Will the mock test be the same process in mainnet at Jul 12th?
