### ISSUE TITLE
Docker for gaia 5.x.x

### ISSUE THREAD

**Issue by anhcao142** [cosmos/gaia#916]
Hi, the [tendermint/gaia](https://hub.docker.com/r/tendermint/gaia) docker hub seems to stop at version 4.2.1. Do we have any plan to continue adding new versions to the hub?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
looks like it was removed on purpose https://github.com/cosmos/gaia/pull/850. I am wondering why as well. @okwme could we bring it back? this is a major regression IMO

**Comment by ghost** [comment]
Please add Dockerfile for 5.x version?

**Comment by nooomski** [comment]
Closed by bot, opening again, should we also add a dockerfile for 6.x ? @okwme wdyt?

**Comment by tokamak-git** [comment]
@mmulji-ic could you please help me with updating a secret please? have updated the vault, `SLACK_WEBHOOK_URL`
thanks.

**Comment by tokamak-git** [comment]
@mmulji-ic getting following error, looks like my token does not have enough permissions to push to ghcr.

 ```
 #16 exporting to image
#16 pushing layers 0.3s done
#16 ERROR: server message: insufficient_scope: authorization failed

#20 [auth] cosmos/gaia:pull,push token for registry-1.docker.io
#20 DONE 0.0s

#21 [auth] cosmos/gaia:pull,push token for registry-1.docker.io
#21 DONE 0.0s
------
 > exporting to image:
------
error: failed to solve: server message: insufficient_scope: authorization failed
Error: buildx failed with: error: failed to solve: server message: insufficient_scope: authorization failed
```

**Comment by tokamak-git** [comment]
Blocked by need to create secret environment.
 
cc  @okwme @mmulji-ic
