### ISSUE TITLE
Loss of transactions in the local node block

### ISSUE THREAD

**Issue by JayYan726** [cosmos/gaia#918]
## Summary of Bug
The local node synchronizes the block normally, and the block height has reached the latest.
The node executes gaiad q tx <TXHASH>, the result is: tx {TXHASH} not found
It is normal to query transactions in the block explorer, and multiple similar situations have been found.
Abnormal block:
Height 6855446
TXHASH:
4BE164BD4A9A1280F7E4CB98DE7A7560EB18C40ACF66E66557ADC4D724FE4B89
07F1A4C85C7F18400CE31F2F2A899956C4905452FB03F16F27C35EDF69991B96

Height 6934624
TXHASH:
1CEA0C8A4A3081E739ACDD01DA7AC388B0D9ADCCE327694F9CA9D56F5CDD8E09
ED388BFD57AD5B6B8552DC9FE90C96C6090C3AC6BC10AB7B050A853F47101EEF

## Version

hash:43efea2ee78135fb0213e33208f245f571d5868b
release version: v5.0.2

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
all the transactions are accessible from block explorers and from our internal node. Can you describe the process of building your local node? Is it only some transactions that are missing? Is it all transactions? Are the block header hashes the same as those at the same height on block explorers?

**Comment by JayYan726** [comment]
The node was set up on the linux server as required, and only part of the block transaction was lost. The hash value of the block header is consistent with the block explorer

**Comment by web4ken** [comment]
> The node was set up on the linux server as required, and only part of the block transaction was lost. The hash value of the block header is consistent with the block explorer

Did you restart the node before it was fully synchronised?

**Comment by JayYan726** [comment]
I upgraded the node to v5.0.2

**Comment by web4ken** [comment]
There is a similar problem on the crypto.org chain

https://github.com/crypto-org-chain/chain-main/issues/604

**Comment by Jochy1873** [comment]
The other question is I have one contract for one leash is posivol transfer y need becaus. Ima maiking shiba swat  I need make bone and staking I'm pit a leash. Ether ion y and adicional ya he paga parte del leash please I'm star to the construction for the ecositem to shiba I'm star I need start to continue

**Comment by nooomski** [comment]
Bot closed this by accident. @JayYan726 let us know if you still need any help with this and we'll reopen.
