### ISSUE TITLE
Show commision config for candidates

### ISSUE THREAD

**Issue by faboweb** [cosmos/gaia#92]
Current Gaia output for candidates:
![image](https://user-images.githubusercontent.com/5869273/34105912-787c417e-e3f6-11e7-84b7-4130c584ee39.png)

Aligned on output for candidates:
https://github.com/cosmos/cosmos-ui/issues/35#issuecomment-348213985

There are still several properties of the candidates missing:
- since (will be done later)
- commissionRate
- commissionMax
- status: 'active' | 'bonding' | 'unbonding'
- slashRatio
- reDelegatingShares

Will those still be delivered? Could we get an ETA for those?

Pulling in @rigelrozanski @ebuchman

**Comment by rigelrozanski** [comment]
Um haha yeah these are being added as they are developed and tested. Commission related terms coming soon. Just finishing up implementing the crypto-economics piece for atom provisions. Next fees and commission... I'm not sure if we want to or not want to include placeholders, would that make the UI team easier? @faboweb

**Comment by adrianbrink** [comment]
I'd upvote placeholders.

**Comment by faboweb** [comment]
With properties being available on the returned json we could finish the implementation part in the UI early.

**Comment by faboweb** [comment]
Hiho, is there progress here?

**Comment by rigelrozanski** [comment]
Well I'm not going to implement placeholders unless you think it's of reasonable benefit, and you seemed to suggest that there isn't much benefit until the data is available... other thoughts? going to close this issue, can re-open if you think placeholders are of great benefit

Gaia-3 (`feature/provisions`) currently has `status` and `reDelegatingShares` implemented btw.

**Comment by faboweb** [comment]
Thx for the new data! Clarifying: Commission related stuff is generally not implemented yet?

**Comment by rigelrozanski** [comment]
not within develop but it's coming very soon, it's implemented but needs review
