### ISSUE TITLE
Move protoc-gen-buf-check-{breaking,lint} to protoc-gen-buf-{breaking,lint}

### ISSUE THREAD

**Issue by bufdev** [cosmos/gaia#920]
`protoc-gen-buf-check-{breaking,lint}` were deprecated in https://github.com/bufbuild/buf/releases/tag/v0.34.0. This was just a rename, the exact same functionality is available via `protoc-gen-buf-{breaking,lint}`.

All you need to do throughout the repository is:

- `s/protoc-gen-buf-check-breaking/protoc-gen-buf-breaking/`
- `s/protoc-gen-buf-check-lint/protoc-gen-buf-lint/`
- `s/--buf-check-breaking_out/--buf-breaking_out/`
- `s/--buf-check-lint_out/--buf-lint_out/`

And it should work, including for downloading/installing releases.

**Comment by tac0turtle** [comment]
this repo doesn't have any proto files, we will remove bug entirely. Thank you for opening the issue
