### ISSUE TITLE
State Sync Quickstart

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#926]
## Summary

In keeping with the logic of #704 , we should mitigate Gaia's fat where possible.  

I'm of the opinion that state sync is surely a way to do this, and I am volunteering a node with snapshots enabled for that.

For now, we are talking plain http on one of my sentries, but I can formalize this and get it rolling https with a caddy in front for rate limiting if we are happy with results.

Here's the endpoint in question:  

http://95.217.196.54:2101

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
I have the snapshot-interval in app.toml set to 1000.  

I think now I just need to wait for 2000 blocks to pass, will update this issue later tonight.  If it works, I will try and roll this out across every ibc enabled chain.

Right now, it is set to default pruning.  Any advice is appreciated. 

In the terminal of the M1 Macbook pro I'm trying to use state sync with, I get "discovering snapshots for 15s" messages.

**Comment by faddat** [comment]
It works now.  I will document it, and close this issue.  

This is dramatically more ergonomic than beginning from quicksync.io and reduces system requirements for validators back down to raspberry-pi level.

**Comment by tac0turtle** [comment]
in 0.35 of tendermint state sync is moving to the p2p layer. users wont need to get rpc endpoints anymore

**Comment by faddat** [comment]
Much excite!

**Comment by faddat** [comment]
#952 

So here's what I propose with this one, we set it to fail silently but run every time there's a pull request or merge. Right now, we don't get data on state sync. This GitHub action and script, used together, will give us the data that we need to improve state sync over time.

**Comment by faddat** [comment]
https://github.com/cosmos/gaia/pull/1027
