### ISSUE TITLE
Default inbound connections

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#927]
## Summary of Bug

We've currently got default inbound connections set to 40.  If we go to rpc.cosmos.network and get network info, we can find peers.  Most fail, and it is because not enough network connections are enabled inbound by default.  

## Version

5.0.2

## Steps to Reproduce

Try to connect to the network.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryan-u410** [comment]
Related: https://github.com/cosmos/cosmos-sdk/issues/9727

Been keeping an eye on updates regarding this issue so just linking the other open issue that I am aware of at the moment. Cheers.

**Comment by tac0turtle** [comment]
@faddat want to make a pr that bumps the defaulted amount to 60 or so similar to osmosis?

**Comment by mmulji-ic** [comment]
See for reference https://github.com/cosmos/gaia/pull/1160

**Comment by okwme** [comment]
Tendermint v0.35 has separated the peer list from the state sync so this shouldn't be an issue going forward.
Related was updates to defaults here: https://github.com/cosmos/cosmos-sdk/issues/9727
