### ISSUE TITLE
Division by zero in fraction module

### ISSUE THREAD

**Issue by petabytestorage** [cosmos/gaia#93]
```stack="goroutine 75 [running]:\nruntime/debug.Stack(0xc4204888a8, 0x485f000, 0x4fadff0)\n\t/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func1(0xc42007c680)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:508 +0x57\npanic(0x485f000, 0x4fadff0)\n\t/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283\ngithub.com/cosmos/gaia/modules/stake.Fraction.Simplify(0x0, 0x0, 0xc421ebca70, 0xc421ebc8f0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/modules/stake/fraction.go:90 +0xed\ngithub.com/cosmos/gaia/modules/stake.Fraction.Div(0x0, 0x0, 0x4f6cb20, 0xc421ebca20, 0x0, 0x0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/modules/stake/fraction.go:176 +0x7d\ngithub.com/cosmos/gaia/modules/stake.getInflation(0xc421ea82d0, 0x0, 0x0, 0xc421ebc915, 0x5, 0xc421ead520, 0x20, 0x20, 0x0, 0x0, ...)\n\t/Users/michael/go/src/github.com/cosmos/gaia/modules/stake/tick.go:60 +0x92\ngithub.com/cosmos/gaia/modules/stake.processProvisions(0x4f69c60, 0xc421e75860, 0xc421ea82d0, 0x0, 0x0, 0xc421ebc915, 0x5, 0xc421ead520, 0x20, 0x20, ...)\n\t/Users/michael/go/src/github.com/cosmos/gaia/modules/stake/tick.go:32 +0x70\ngithub.com/cosmos/gaia/modules/stake.Tick(0x4f6a2e0, 0xc421e71aa0, 0x4f69c60, 0xc421e75860, 0x5, 0x8, 0xc4209e8198, 0x4, 0x5)\n\t/Users/michael/go/src/github.com/cosmos/gaia/modules/stake/tick.go:22 +0x1e4\nmain.tickFn(0x4f6a2e0, 0xc421e71aa0, 0x4f699e0, 0xc421e73fe0, 0x0, 0x0, 0x0, 0x4f648a0, 0xc421eb70a0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/cmd/gaia/node.go:67 +0x108\ngithub.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk.TickerFunc.Tick(0x4ab43d0, 0x4f6a2e0, 0xc421e71aa0, 0x4f699e0, 0xc421e73fe0, 0x4f6a2e0, 0xc421e71aa0, 0x18, 0xc421eb7060, 0x6492bf0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/handler.go:44 +0x52\ngithub.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/app.(*BaseApp).EndBlock(0xc42051fe00, 0x5, 0x20, 0xc421d3e360, 0x0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/app/base.go:86 +0x258\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/abci/client.(*localClient).EndBlockSync(0xc420173860, 0x5, 0x4feb460, 0x0, 0x0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/abci/client/local_client.go:213 +0x6e\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc421650b90, 0x5, 0x14, 0x20, 0xc421d3e360)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x3d\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x4f590e0, 0xc421e757d0, 0x4f67ee0, 0xc421650b90, 0xc421e98a80, 0x4f648a0, 0xc420512980, 0x20, 0x30, 0xc421e757d0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/state/execution.go:100 +0x8c1\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/state.(*State).ValExecBlock(0xc4200905a0, 0x4f590e0, 0xc421e757d0, 0x4f67ee0, 0xc421650b90, 0xc421e98a80, 0x492ffa0, 0xc4200905a0, 0xc420489338)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/state/execution.go:29 +0xa8\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/state.(*State).ApplyBlock(0xc4200905a0, 0x4f590e0, 0xc421e757d0, 0x4f67ee0, 0xc421650b90, 0xc421e98a80, 0x1, 0xc421e83180, 0x14, 0x20, ...)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/state/execution.go:216 +0x73\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc42007c680, 0x5)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:1208 +0xb8b\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc42007c680, 0x5)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:1143 +0x536\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc42007c680, 0x0, 0x5)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:1095 +0x98\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc42007c680, 0x5, 0x0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:1122 +0x72f\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc42007c680, 0xc421e9ac80, 0x0, 0x0, 0xc420489b00, 0xc420489b20, 0x402cbc9)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:1431 +0xb74\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc42007c680, 0xc421e9ac80, 0x0, 0x0, 0x0, 0x0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:1325 +0x59\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc42007c680, 0x4848680, 0xc42000e3b0, 0x0, 0x0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:576 +0x589\ngithub.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc42007c680, 0x0)\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:534 +0x5cf\ncreated by github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/michael/go/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/consensus/state.go:248 +0x10d\n"```

**Comment by rigelrozanski** [comment]
This code is VERY much a work in progress and highly unstable - please do not review until the PR for `feature/provisions` is no-longer in WIP - fractions module is no longer a part of gaia repo and will be removed from `feature/provisions`
