### ISSUE TITLE
failed to execute message : insufficient fund

### ISSUE THREAD

**Issue by pss-datta** [cosmos/gaia#938]
## Summary of Bug
I have created test node for testing purpose and added 1000000stake to my-node my-chain as given in Installation document.
I can see in genesis.json its showing amount as account balance still its not showing in balance command.
When I check for balance from API/CLI command
Getting below error ; message index: 0: 0raindrops is smaller than 200000stake: insufficient funds

{
	"height": "904",
	"txhash": "FE576BBD05CA28C56B4487D0EC996A56A68A5475BC0AF562203F94E5693FD070",
	"codespace": "sdk",
	"code": 5,
	"data": "",
	"raw_log": "failed to execute message; message index: 0: 0stake is smaller than 100000stake: insufficient funds",
	"logs": [],
	"info": "",
	"gas_wanted": "200000",
	"gas_used": "42962",
	"tx": null,
	"timestamp": ""
}

GAIAD version =>4.2.1

## Steps to Reproduce

root@78be9b263ed2:~/.gaia/config# gaiad query bank balances cosmos1ef4e09fdh668fukcc42kpxnum47tuud9q84xx6
balances:
- amount: "0"
  denom: stake
pagination:
  next_key: null
  total: "0"
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
Hi, can you tell more info about how do you add  1000000stake to your account ?

**Comment by glnro** [comment]
Hi @DattaAdsule, would you mind confirming whether you're still experiencing this issue? We'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team

**Comment by yaruwangway** [comment]
closing now, please reopen it if you still experiencing this issue.
