### ISSUE TITLE
send atom using cli

### ISSUE THREAD

**Issue by whoistiger** [cosmos/gaia#958]
Follow the official documentation
<img width="471" alt="20210828100522" src="https://user-images.githubusercontent.com/46469762/131202981-0fe274f6-8491-4b7f-a360-5d0cba062034.png">

Error: unknown command "send" for "tx"

**Comment by chaishiqi** [comment]
the same problem occured, how is it going?

**Comment by yaruwangway** [comment]
Hi, thank you for opening this issue. The command should be `gaiad tx bank send [sender address] [receiver address] [tokens]`, we will update the documents.

**Comment by chaishiqi** [comment]
> Hi, thank you for opening this issue. The command should be `gaiad tx bank send [sender address] [receiver address] [tokens]`, we will update the documents.

Hi，I create the local_testnet environment with the genesis.json provided by the repo. How can  I know what the "sender address" is ?

**Comment by yaruwangway** [comment]
you mean vega-test repo ?

**Comment by yaruwangway** [comment]
can you send me the tutorial link that you are following ?

**Comment by chaishiqi** [comment]
> can you send me the tutorial link that you are following ?

yes,vega-test repo.
the link is [click](https://github.com/cosmos/vega-test/tree/master/local-testnet#init-the-chain). begin with init the chain"

**Comment by yaruwangway** [comment]
You can know the user's address by `gaiad keys show [key name]`, or `gaiad keys show [key name] -a`
If you follow vega-test local test tutorial, you should have a key called user, you can find out by `gaiad keys show user`, then you can query user's balance by `gaiad q bank balances [user's address]`

**Comment by yaruwangway** [comment]
If you do not want to check sender's address, you can also try `gaiad tx bank send [sender's key name] [to_address] [amount] [flags]`. 
for example, `gaiad tx bank send user cosmos199m6ewdzeshkae7ytv4qvehnx8jta9w9y2sq2k 1000uatom --chain-id test`

**Comment by chaishiqi** [comment]
> You can know the user's address by `gaiad keys show [key name]`, or `gaiad keys show [key name] -a` If you follow vega-test local test tutorial, you should have a key called user, you can find out by `gaiad keys show user`, then you can query user's balance by `gaiad q bank balances [user's address]`

thanks for your anwser, however it seems not worked?
![image](https://user-images.githubusercontent.com/15074168/145567180-a933b49c-e9e6-4d5f-ad54-d041bd6a6392.png)

**Comment by yaruwangway** [comment]
you probably do not have a key called user. You can query your keys by  `gaiad keys list`
if you do not have any keys, you can create a key by ` gaiad keys add <key name> [flags]`

**Comment by chaishiqi** [comment]
Got it! thx very much
