### ISSUE TITLE
Automatically download Genesis

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#959]
## Summary

Gaia should download Genesis automatically

## Problem Definition
Instead of worrying about whether or not we should put quick start instructions in the readme file, of course we should, what we should do is make launching Gaia absolutely as easy as possible, and this means that we do not force users to gather seeds, peers, Genesis. Instead, Gaia knows where her default Genesis is, and default can be overridden.

## Proposal

I built a tool for this but it is absolutely not stable enough for my liking and introduces too many dependencies:

GitHub.com/notional-labs/get

Get is in turn based on: GitHub.com/IPFS/ipget

I proposed that we do not use IPFS, except for the URL. We should reference an IPFS URL that way it's hard to take down. We can download for example, from the cloud flare IPFS gateway.  Did you know that osmosis  Genesis disappeared recently? Well it's because it had been downloaded too much.

So it might be easier to have people in the community simply host Genesis state, and some of them are already doing that:

https://GitHub.com/notional-labs/ipfsync

In that repository you will find a very easy to join IPFS cluster. In that cluster there is both the Gaia and Osmosis Genesis files, and soon, there will be quick sync stuff too.

* Use IPFS cloudflare gateway
* Download with http/s
* Verify genesis with sha256sum
* Now that both seeds and Genesis are in the binary, simply run `gaia start`.  It will handle init for you if It does not find information in the usual ~/.gaiad/

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
Closed by bot, opening again. @okwme might be a good one to bring up with Milan once he's onboarded. Wdyt?

**Comment by okwme** [comment]
prior issue where this general concept is discussed:
https://github.com/cosmos/gaia/issues/943

**Comment by okwme** [comment]
outcome of the issue in #943 was not to hardcode things like seednodes or genesis file:
