### ISSUE TITLE
Question about redundant setting of config values

### ISSUE THREAD

**Issue by rikonor** [cosmos/gaia#96]
Hi,

Was just curious why these values are explicitly set, even though they're just being set to the default values?

https://github.com/cosmos/gaia/blob/9c82ff236633e6a3e060bf574992be139a7a2947/cmd/gaiad/main.go#L38-L40

see [config.go#L23](https://github.com/cosmos/cosmos-sdk/blob/master/types/config.go#L23) for the current defaults.

**Comment by alexanderbez** [comment]
An application should set its own Bech32 prefixes through `config.Set*`. The reason why the config has those defaults already is so you can avoid having to do this (even though that's unadvisable).

**Comment by rikonor** [comment]
I see - so this is just setting a good example given that most applications will be setting their own prefixes? Thanks for the quick reply.
