### ISSUE TITLE
Interchain security light paper does not address baby chain inflation.

### ISSUE THREAD

**Issue by hxrts** [cosmos/gaia#961]
We can probably get away with something rough for v0, but with v1/v2 we should have a more robust model where the baby chain guarantees that the amount staked on the parent is larger than the cost of corruption through inflation. The cost of corruption can be very difficult to estimate, but in general we should use the cosmos staking/inflation relationship as a model for interchain security.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment]
@okwme @hxrts this was closed by a bot. Do we still need to reopen this one or was this already addressed?

**Comment by hxrts** [comment]
This is still an issue, but we can maybe leave it closed for now. It's not relevant for V1.
