### ISSUE TITLE
Gaiad sync issue

### ISSUE THREAD

**Issue by rocky2015aaa** [cosmos/gaia#965]
## Summary of Bug

I have two issues.

1. When I follow gaia tutorials, I get these kinds of errors several times but syncing works.
`9:18AM ERR dialing failed (attempts: 1): dial tcp 162.55.132.230:2010: connect: connection refused`
`9:18AM ERR dialing failed (attempts: 1): dial tcp 106.12.73.242:26656: i/o timeout`

2. According to quick start on document, At the `6910000` block height with panic, I need to change gaiad version.
I want to test it but for syncing I want to use quick sync.
https://cosmos.quicksync.io/
If I use quick sync, running v5.0.5 is enough? No need to run from v4.2.1 and change gaiad version?
## Version

`gaiad version` -> v4.2.1

## Steps to Reproduce

On macOS Big Sur v11.5.2

quick start
https://hub.cosmos.network/main/gaia-tutorials/join-mainnet.html#quickstart

quick sync
https://cosmos.quicksync.io/
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
> 1. When I follow gaia tutorials, I get these kinds of errors several times but syncing works.
>    `9:18AM ERR dialing failed (attempts: 1): dial tcp 162.55.132.230:2010: connect: connection refused`
>    `9:18AM ERR dialing failed (attempts: 1): dial tcp 106.12.73.242:26656: i/o timeout`

this is normal, if you wait a period of time they will pass and you will have a peer. Tendermint spits out a lot of noise, but they are benign 

> 2\. According to quick start on document, At the `6910000` block height with panic, I need to change gaiad version.
>     I want to test it but for syncing I want to use quick sync.
>     https://cosmos.quicksync.io/
>     If I use quick sync, running v5.0.5 is enough? No need to run from v4.2.1 and change gaiad version?

if you are using quick sync then you only need to use the latest binary since you already have all the old state.
