### ISSUE TITLE
support upgrade to tendermint 0.35

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#966]
## Summary
support key migration when upgrade to tendermint 0.35

## Problem Definition
 In Tendermint 0.35, the format of keys in the database are changed. Operators who are running nodes that started as 0.34 will need to [migrate the key](https://github.com/tendermint/tendermint/pull/6790) formats.

## Proposal
Gaia will migrate the key format through [pre-upgrade handler](https://github.com/cosmos/cosmos-sdk/issues/10047) in cosmovisor before execute the new binary. We could use cosmovisor with a flag `--pre-upgrade-hook` to run a script to migrate the key.

TODO:
- [ ] add key migration cli
- [ ] define the pre-upgrade handler and the script to run for migration
- [ ] tests

Ref:
https://github.com/cosmos/cosmos-sdk/issues/10047
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mmulji-ic** [comment]
v0.35 developed put on hold, in favour of v0.36.
