### ISSUE TITLE
Need more seed nodes, run by more validators

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#968]
## Summary of Bug
In order to solve

#965 
#873 

And likely others, the quickstart needs to change from listing persistent peers, to seeds.  Seeds should either be embedded in init.go ala Osmosis or provided in a clear and easy to find place.  

Using the info from quickstart, my gaia node currently has only 16 peers. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
I feel like the notion of seed nodes will eventually be phased out. Storing addresses and occasionally gossiping them to peers is a cheap operation and something that every node can and should do. 

The 0.35 release does include `BootstapPeers` which allows users to list an initial set of peers to be connected to (but not persistently). These nodes then should provide more peers if necessary. It is advisable to pick initial peers that take regular snapshots and/or have full block history as this will help a lot in syncing.

**Comment by faddat** [comment]
great stuff!

Can't wait for 0.35

PS:  I totally agree with what you said here.

**Comment by nooomski** [comment]
Closed by bot, opening again.

**Comment by okwme** [comment]
new updates to the docs shoudl cover information about getting seednodes: https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html
it links to quicksync addressbook: https://quicksync.io/addrbook.cosmos.json
as well as to chain registry: https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json
