### ISSUE TITLE
Remove Legacy Migration Code

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/gaia#969]
## Summary

There are two files that I believe are related to legacy migration paths/logic:

- `app/migrate.go`
- `app/pubkey_replacement.go`

These files relay on legacy SDK code that is marked deprecated and will be removed in future a release.

Not sure who the best person to ask is, but I wager we can just probably just remove these now.

/cc @yaruwangway @okwme 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
Since they're in the history, I think it makes sense to thin out by removing them from the current main branch.  Less to digest means more understanding for new readers.
