### ISSUE TITLE
Can`t start mainnet node

### ISSUE THREAD

**Issue by prettyCoders** [cosmos/gaia#97]
![image](https://user-images.githubusercontent.com/36216120/62919607-c8705700-bdd5-11e9-94d5-0f44e3dfca96.png)
![image](https://user-images.githubusercontent.com/36216120/62919627-d58d4600-bdd5-11e9-8fcb-0407a6691402.png)

**Comment by alexanderbez** [comment]
From the [launch repo](https://github.com/cosmos/launch):

```
The current SDK version of the Cosmos Hub mainnet: v0.34.6+
```

**Comment by prettyCoders** [comment]
means i should update my genesis.json?use https://raw.githubusercontent.com/cosmos/launch/master/genesis.json

**Comment by prettyCoders** [comment]
It not work,what should i do?

**Comment by alexanderbez** [comment]
It means for mainnet, you should use the genesis file posted in that repo with SDK/Gaia version v0.34.7
