### ISSUE TITLE
Clean up Gaia repo

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#977]
## Summary

Gaia is full of stale issues and out of date docs. Let's make it a better place to live.

## Proposal

* close stale issues
* solve real issues
* update all docs
* add governance to this repo
* add mainnet to this repo
* update docs build system
* add some flair

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
YES!

**Comment by dcwalk** [comment]
Where can we propose emoji flair for a specific area? 😂 

The existing ones from discord++:
⚛️
💫 - ecosystem
🤝 - ibc
🔭 - status
🔨 - cosmos sdk
🧰 - cosmos sdk modules
🍩 - hub (!!)

candidate Governance emoji?:
📜 🗳️ ⚖️ 🧭

**Comment by dcwalk** [comment]
I can take on closing out stale issues, addressing current ones, and updating parts of docs for gov- related topics! I've reviewed/tagged `docs` and `governance` issues in this repo. Post-gov repo merge I can transfer remaining issues from the governance repo and we'll have all documented gov issues in one place :sparkles:  I have ideas for refining gov docs once they land that I'm eager to take on as well.

Happy to join a doc / issue review call if needed!   

Is it okay to edit your top comment @okwme to add in tasks / checklist ? Or better to break out bite-sized issues and reference this top one? Still learning norms around github collaboration here :smile:

**Comment by dcwalk** [comment]
Udpate/Smaller issues from governance (docs) side:
- [x] add governance to this repo
- [x] Small gov docs cleanups / updates:
   - https://github.com/cosmos/gaia/issues/1042 (more details on params keys + json validator approach)
   - https://github.com/cosmos/gaia/issues/1035 
- [ ] Bigger (proposed) updates:
   - https://github.com/cosmos/gaia/issues/1055

**Comment by nooomski** [comment]
Closed by bot, opening again.
