### ISSUE TITLE
print out the path & config-file you are parsing during startup, please :)

### ISSUE THREAD

**Issue by atoz7** [cosmos/gaia#985]
## Summary of Bug

hello :)

gaiad scans for various config-file names all over the place, parses any file it finds and prints out an error, because a file which is clearly not in the dot-directory of gaiad is not valid -- which would be `~/.gaia`.

it took me some time and the tool `strace` to find out, that gaiad takes for example a totaly unrelated file which just happened to reside in my home-directory and is 
named `~/config.json`

[btw. yes, i have many other files in my home-directory ;]

proposed solution: if you insist in using config.* files from locations, which are not specific to gaiad ... for example: after finding an error in the config-file, just print out the path and filename you parsed.

but imho. it would be better to limit the search for config-files to the dot-directory of an application - and maybe `/etc/<application-name>`.

br
a

## Version

i tested it with several versions:

v5.0.5
v5.0.6
v6.0.0-rc1

## Steps to Reproduce

echo "{ some crap }" > ~/config.json
gaiad version

result
"Error: While parsing config: invalid character 's' looking for beginning of object key string"

and look at whats happening

strace gaiad version

[...]
newfstatat(AT_FDCWD, "\~/config.json", {st_mode=S_IFREG|0644, st_size=14, ...}, 0) = 0
openat(AT_FDCWD, "\~/config.json", O_RDONLY|O_CLOEXEC) = 7
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1016262200, u64=140287533051448}}) = -1 EPERM (Die Operation ist nicht erlaubt)
epoll_ctl(4, EPOLL_CTL_DEL, 7, 0xc000d5f8f4) = -1 EPERM (Die Operation ist nicht erlaubt)
fstat(7, {st_mode=S_IFREG|0644, st_size=14, ...}) = 0
read(7, "{ some crap }\n", 526)         = 14
read(7, "", 512)                        = 0
close(7)                                = 0
write(2, "Error: While parsing config: inv"..., 94Error: While parsing config: invalid character 's' looking for beginning of object key
[...]
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
Hi @alexanderbez , @okwme , shall we improve this in cosmos-sdk or gaia app ?

**Comment by alexanderbez** [comment]
I don't really see the issue here.

> gaiad scans for various config-file names all over the place, 

This is false. SDK-based applications look in a **single place** for ALL files, typically `$HOME/.<app>`. Here you have two primary directories: `config` and `data` and the `config` subdirectory is where the application looks for ALL of its configuration files.

**Comment by atoz7** [comment]
hello,

idk -- additionally: i really don't care --, but if you don't believe me: just look at the output of:
`strace gaiad version`

(on a "clean" system eg. without the presence of a ~/.gaia dot-directory :)

br,
a

**Comment by yaruwangway** [comment]
Hi @atoz7 , just to clarify
1. what is the `--home` you set for your gaia app ?
2. do you mean the `config.json` file in your gaia app home/config dir or in your `$HOME` ?
