### ISSUE TITLE
Master branch is broken - consequentially instructions to setup validator are not working

### ISSUE THREAD

**Issue by mdyring** [cosmos/gaia#99]
"go install ./cmd/gaia" results in:
```
github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/rpc/grpc
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:171: cannot use handler (type func("context".Context, interface {}) (interface {}, error)) as type grpc.UnaryHandler in argument to interceptor
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:189: cannot use handler (type func("context".Context, interface {}) (interface {}, error)) as type grpc.UnaryHandler in argument to interceptor
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:198: cannot use _BroadcastAPI_Ping_Handler (type func(interface {}, "context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/tendermint/tendermint/rpc/grpc/types.pb.go:202: cannot use _BroadcastAPI_BroadcastTx_Handler (type func(interface {}, "context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

make: *** [install] Error 2
```

**Comment by mdyring** [comment]
Doing more testing.. It seems v0.4.0 tag also fails now, so I suspect it is caused by a Go update:

_go version go1.8.3 linux/amd64_

**Comment by zramsay** [comment]
you might need `go1.9` minimum version

**Comment by mdyring** [comment]
Odd thing is that this was building & running fine just a few days ago on AWS (running AWS Linux instance).

Now that I have launched a new instance (passing same "gaia launch" script in user-data), it fails to build.

Would be great to get release binaries for gaia... Need to investigate more.

**Comment by adrianbrink** [comment]
Can you try with `go1.9.2`?

I think we lately upgraded to it.

**Comment by mdyring** [comment]
AFAIK 1.9.x is not supported out of the box on AWS Linux, Ubuntu or Debian. So I need to install gvm first right?

It seems to be a recurring problem that people are running the wrong Go version when building from source (in in this case, an existing setup breaking apparently).

Could you guys look into releasing binaries as well, like for Tendermint? That would also be better suited for production use anyway, which is where we are hopefully heading :-)

**Comment by mdyring** [comment]
Builds with 1.9.2 manually installed.

Can you guys work towards binary releases though? (ideally signed)

**Comment by mdyring** [comment]
I see there is already an issue for this: https://github.com/cosmos/gaia/issues/36
